---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 1.
--- DateTime: 2021/8/26 21:13
---

local CommonMessageBarItem = BaseClass("CommonMessageBarItem", UIBaseContainer)
local base = UIBaseContainer

-- 本项目没有英雄系统（UI.UIHero2 不存在），英雄头像分支整体停用。
-- 船舱等模块只用纯文本提示（UIUtil.ShowTips(msg)），走不到这些分支。
-- 日后接入英雄系统时，恢复这里的 require 并解开下方 heroHead 相关代码即可。
local msgTxt_path = "doTween/Text"
local playerHead_path = "doTween/UIPlayerHead"
local playerHeadIcon_path = "doTween/UIPlayerHead/HeadIcon"
local playerHeadFg_path = "doTween/UIPlayerHead/Foreground"
local canvasGroup_path = "doTween"
local heroHead_path = "doTween/Text/UIHeroCellSmall"
local hero_right_icon_path = "doTween/Text/hero_right_icon"

local TweenPosY = {
    Start = -40,
    Idle = 0,
    Idle1 = -10,
    End = 70,
}

local fadeInTime = 0.2
local fadeInTime1 = 0.1
local fadeOutTime = 0.4

local function OnCreate(self)
    base.OnCreate(self)
    self.msgTxtN = self:AddComponent(UITextMeshProUGUIEx, msgTxt_path)
    self.playerHeadN = self:AddComponent(UIBaseContainer, playerHead_path)
    self.playerHeadIconN = self:AddComponent(UIPlayerHead, playerHeadIcon_path)
    self.playerHeadFg = self:AddComponent(UIImage, playerHeadFg_path)
    self.canvasGroupN = self:AddComponent(UICanvasGroup, canvasGroup_path)
    -- self.heroHead = self:AddComponent(UIHeroCellSmall,heroHead_path)  -- 无英雄系统，见文件头说明
    self.heroHead = nil
    self.girlhead = self:AddComponent(UIImage,"doTween/Text/Image-Girl")
    self.hero_right_icon = self:AddComponent(UIImage, hero_right_icon_path)
    self.alliancePointText = self:AddComponent(UITextMeshProUGUIEx, "doTween/Text/alliancePointText")
end

local function OnDestroy(self)
    DOTween.Kill(self.canvasGroupN.rectTransform:GetComponent(typeof(CS.UnityEngine.CanvasGroup)))
    DOTween.Kill(self.canvasGroupN.rectTransform)
    self.msgTxtN = nil
    if self.delayTimer ~= nil then
        self.delayTimer:Stop()
        self.delayTimer = nil
    end
    base.OnDestroy(self)
end

--从开始显示到准备隐藏的时间为 timeBeforeFadeOut
--隐藏动画时长不能超过上面的值，不然两个预制不够
local function FadeIn(self, tipInfo, showEndTime)
    if not string.IsNullOrEmpty(tipInfo.sound) then
        SUSoundUtil.PlayEffect(tipInfo.sound)
    else
        SUSoundUtil.PlayEffect("commonMessageBar")
    end
    
    self:ResetItem()
    
    local msg = tipInfo.msg
    local msgId = tipInfo.msgId
	local param = tipInfo.params
    if msg~=nil and msg~="" then
        self.msgTxtN:SetText(msg)
    elseif msgId ~= nil then
		-- 如果携带了参数；那么就要处理一下，参数是table的话表示是多个，所以要unpack
		if param then
			if type(param) == 'table' then
				self.msgTxtN:SetLocalText(msgId, SafeUnpack(param))
			else
				self.msgTxtN:SetLocalText(msgId, param)
			end
		else
        	self.msgTxtN:SetLocalText(msgId)
		end
    else
        self.msgTxtN:SetLocalText(100378) 
    end
    
    --有'自定义'头像才显示
    if tipInfo and tipInfo.playerHead then
        self.hero_right_icon:SetActive(false)
        if self.heroHead then self.heroHead:SetActive(false) end
        self.playerHeadN:SetActive(true)
        self.playerHeadIconN:SetData(tipInfo.playerHead.uid, tipInfo.playerHead.pic, tipInfo.playerHead.picVer)
        if tipInfo.playerHead.HeadBg then
            self.playerHeadFg:SetActive(true)
            self.playerHeadFg:LoadSprite(tipInfo.playerHead.HeadBg)
        else
            self.playerHeadFg:SetActive(false)
        end
    elseif tipInfo and tipInfo.heroHead and tipInfo.heroHead.heroId and self.heroHead then
        -- 本项目无英雄系统，self.heroHead 恒为 nil，此分支不会进入（见文件头说明）
        self.playerHeadN:SetActive(false)
        self.heroHead:SetActive(true)
        self.heroHead:InitWithConfigId(tipInfo.heroHead.heroId,tipInfo.heroHead.quality,tipInfo.heroHead.level,
                tipInfo.heroHead.state,tipInfo.heroHead.skillInfos,tipInfo.heroHead.rankId,
                tipInfo.heroHead.isWakeUp, tipInfo.heroHead.heroCallback, tipInfo.heroHead.camp)
                self.heroHead:SetHeroTag("0")
                self.heroHead:SetCampActive(false)
        if tipInfo.heroHead.noShowStart then
            self.heroHead:SetStarActive(false)
        else
            self.heroHead:SetStarActive(true)
        end
        if tipInfo.heroHead.right_icon ~= nil and tipInfo.heroHead.right_icon ~= "" then
            self.hero_right_icon:SetActive(true)
            self.hero_right_icon:LoadSprite(tipInfo.heroHead.right_icon)
        else
            self.hero_right_icon:SetActive(false)
        end
    else
        self.playerHeadN:SetActive(false)
        if self.heroHead then self.heroHead:SetActive(false) end
        self.hero_right_icon:SetActive(false)
    end
    self.girlhead:SetActive(false)
    if tipInfo and tipInfo.girlicon then
        self.girlhead:SetActive(true)
        self.girlhead:LoadSprite(tipInfo.girlicon)
    end
    self.alliancePointText:SetActive(false)
    if tipInfo and tipInfo.alliancePoint then
        self.alliancePointText:SetActive(true)
        self.alliancePointText:SetText("+" .. tipInfo.alliancePoint)
    end

    DOTween.Kill(self.canvasGroupN.rectTransform:GetComponent(typeof(CS.UnityEngine.CanvasGroup)))
    DOTween.Kill(self.canvasGroupN.rectTransform)
    --self.canvasGroupN.rectTransform:GetComponent(typeof(CS.UnityEngine.CanvasGroup)):DOFade(1, 0.3):SetEase(CS.DG.Tweening.Ease.InSine)
    self.canvasGroupN:SetAlpha(1)
    self.canvasGroupN.rectTransform:DOAnchorPosY(TweenPosY.Idle, fadeInTime):SetEase(CS.DG.Tweening.Ease.InSine):OnComplete(function()
        self.canvasGroupN.rectTransform:DOAnchorPosY(TweenPosY.Idle1, fadeInTime1)
    end)


    self.delayTimer = self:DelayInvoke(function()
        if self.delayTimer ~= nil then
            self.delayTimer:Stop()
            self.delayTimer = nil
        end
        self:FadeOut()
    end, showEndTime - fadeInTime - fadeInTime1 - fadeOutTime)
end

local function FadeOut(self, advance)
    DOTween.Kill(self.canvasGroupN.rectTransform:GetComponent(typeof(CS.UnityEngine.CanvasGroup)))
    DOTween.Kill(self.canvasGroupN.rectTransform)
    self.canvasGroupN.rectTransform:GetComponent(typeof(CS.UnityEngine.CanvasGroup)):DOFade(0, 0.4)
    if advance then
        self.canvasGroupN.rectTransform:DOAnchorPosY(TweenPosY.End, fadeOutTime):SetEase(CS.DG.Tweening.Ease.OutQuart)
    else
        self.canvasGroupN.rectTransform:DOAnchorPosY(TweenPosY.End, fadeOutTime):SetEase(CS.DG.Tweening.Ease.OutSine)
    end
end

local function ResetItem(self)
    if self.delayTimer ~= nil then
        self.delayTimer:Stop()
        self.delayTimer = nil
    end
    DOTween.Kill(self.canvasGroupN.rectTransform:GetComponent(typeof(CS.UnityEngine.CanvasGroup)))
    DOTween.Kill(self.canvasGroupN.rectTransform)
    self.canvasGroupN:SetAlpha(0)
    self.canvasGroupN.rectTransform:Set_localPosition(0, TweenPosY.Start, 0)
end


CommonMessageBarItem.OnCreate = OnCreate
CommonMessageBarItem.OnDestroy = OnDestroy

CommonMessageBarItem.FadeIn = FadeIn
CommonMessageBarItem.MoveUp = MoveUp
CommonMessageBarItem.FadeOut = FadeOut
CommonMessageBarItem.ResetItem = ResetItem

return CommonMessageBarItem