---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by guqu.
--- DateTime: 2020/11/9 17:29
---
local UICommonMessageBarView = BaseClass("UICommonMessageBarView",UIBaseView)
local base = UIBaseView

local CommonMessageBarItem = require "UI.UICommonMessageBar.View.CommonMessageBarItem"

local closeBtn_path = "Panel"
local messageItem_path = "Panel/msgItem"

local timeBeforeFadeOut = 1
local defaultposy = -9999
local defaultposx = -9999
function UICommonMessageBarView:OnCreate()
    base.OnCreate(self)
    
    self.closeBtnN = self:AddComponent(UIButton, closeBtn_path)
    self.closeBtnN:SetOnClick(function()  
        self.ctrl:CloseSelf()
    end)
    if defaultposy == -9999 then
        local vec2 = self.closeBtnN:GetAnchoredPosition()
        defaultposx,defaultposy = vec2.x,vec2.y
    end
    self.messageItems = {}
    for i = 1, 2 do
        local tempItem = self:AddComponent(CommonMessageBarItem, messageItem_path .. i)
        table.insert(self.messageItems, tempItem)
    end

    self.isReady = true
    self.displayTime = 0
    self.inUseItems = self.messageItems--暂时没用
    self.outUseItems = {}--暂时没用
    self.displayingIndex = 0
    self:TryDisplayNext()
end

function UICommonMessageBarView:OnDestroy()
    if self.messageItems~=nil then
        for i, v in ipairs(self.messageItems) do
            v:ResetItem()
        end
    end
    self.tmppos = 0
    self:ResetPanelPos()
    self.closeBtnN = nil
    self.messageItems = nil
    self.msgQueue = nil

    self:DeleteTimer()
    base.OnDestroy(self)
end

function UICommonMessageBarView:OnEnable()
    base.OnEnable(self)
    self.isReady = true
end

function UICommonMessageBarView:OnDisable()
    base.OnDisable(self)
end

function UICommonMessageBarView:ResetPanelPos()
    if self.closeBtnN then
        self.closeBtnN:SetAnchoredPositionXY(defaultposx,defaultposy)
    end
end

function UICommonMessageBarView:SetPanelPosCaches(offsetx,offsety)
    self.tmpposy = offsety
end

function UICommonMessageBarView:SetPanelPos(offsetx,offsety)
    if self.closeBtnN then
        self.closeBtnN:SetAnchoredPositionXY(defaultposx+offsetx,defaultposy+offsety)
    end
end

--新提示
--playerHead = {uid = "", pic = "", picVer = ""}
function UICommonMessageBarView:AddNewMsg(newMsg, showTime)
    if not self.msgQueue then
        self.msgQueue = {}
    end
    if self.msgQueue == nil then
        self.msgQueue = {}
    end
    if showTime ~= nil then
        self.showEndTime = tonumber(showTime)
    end
    if showTime == nil or self.showEndTime == 0 then
        self.showEndTime = 2
    end
    table.insert(self.msgQueue, newMsg)
    if not self.timer then
        self:TryDisplayNext()
        self.timer = TimerManager:GetInstance():GetTimer(timeBeforeFadeOut, self.TimerAction , self, false,false,false)
        self.timer:Start()
    end
    if self.timer and (not self.timer.started or self.timer.over) then--self.isReady then
        self.timer:Reset()
    end
end

--新提示
function UICommonMessageBarView:AddNewMsg_Msg(msg,showTime, playerHead,heroHead,girlicon,alliancePoint, timebeforefadeout, sound)
    local newMsg = {
        msg = msg,
        playerHead = playerHead,
        heroHead = heroHead,
        girlicon = girlicon,
        alliancePoint = alliancePoint,
        sound = sound
    }
    if timebeforefadeout ~= nil then
        timeBeforeFadeOut = timebeforefadeout
    end
    self:AddNewMsg(newMsg, showTime)
end

function UICommonMessageBarView:AddNewMsg_MsgId(msgId,showTime, playerHead,heroHead,girlicon,alliancePoint)
    local newMsg = {
        msgId = msgId,
		params = nil,
        playerHead = playerHead,
        heroHead = heroHead,
        girlicon = girlicon,
        alliancePoint = alliancePoint,
    }
    self:AddNewMsg(newMsg, showTime)
end

function UICommonMessageBarView:AddNewMsg_MsgIdParams(msgId, params, showTime, playerHead,heroHead,girlicon,alliancePoint)
	local newMsg = {
		msgId = msgId,
		params = params,
		playerHead = playerHead,
		heroHead = heroHead,
		girlicon = girlicon,
		alliancePoint = alliancePoint,
	}
	self:AddNewMsg(newMsg, showTime)
end

function UICommonMessageBarView:TryDisplayNext()
    if self.isReady then
        if self.msgQueue and #self.msgQueue > 0 then
            local freeItem, freeIndex = self:GetOneFreeItem()
            local nextMsg = self:GetNextMsg()
            freeItem:ResetItem()
            freeItem:FadeIn(nextMsg, self.showEndTime)
            self.displayTime = 0

            local displayingItem = self:GetDisplayingItem()
            if displayingItem then
                displayingItem:FadeOut(true)
            end
            self.displayingIndex = freeIndex 
            self.isReady = false
        else
            if self.displayTime >= self.showEndTime then
                self.ctrl:CloseSelf()
            end
        end
        if self.tmpposy == nil then
            self.tmpposy = 0
        end
        self:SetPanelPos(0,self.tmpposy)
    end
end

function UICommonMessageBarView:GetNextMsg()
    if self.msgQueue and #self.msgQueue > 0 then
        local msg = self.msgQueue[1]
        table.remove(self.msgQueue, 1)
        if msg then
            return msg
        end
    end
end

function UICommonMessageBarView:Clear()
    self.msgQueue = nil
    self:DeleteTimer()
end

function UICommonMessageBarView:TimerAction()
    if self.displayTime == nil then
        return
    end
    self.isReady = true
    self.displayTime = self.displayTime + timeBeforeFadeOut
    self:TryDisplayNext()
end

function UICommonMessageBarView:DeleteTimer()
    if self.timer ~= nil then
        self.timer:Stop()
        self.timer = nil
    end
end

--临时只有两个，可扩展支持同时显示多个
function UICommonMessageBarView:GetOneFreeItem()
    if self.displayingIndex ~= 1 then
        return self.messageItems[1], 1
    else
        return self.messageItems[2], 2
    end
end

function UICommonMessageBarView:GetDisplayingItem()
    if self.displayingIndex ~= 0 then
        return self.messageItems[self.displayingIndex]
    else
        return nil
    end
end

function UICommonMessageBarView:OnAddListener()
    base.OnAddListener(self)
    self:AddUIListener(EventId.LoadingState, self.OnLoginState)
end

function UICommonMessageBarView:OnRemoveListener()
    base.OnRemoveListener(self)
    self:RemoveUIListener(EventId.LoadingState, self.OnLoginState)
end
--LuaEntry里面会把所有timer都清掉，这个地方做个容错处理
function UICommonMessageBarView:OnLoginState(state)
    -- 10 = LoadingState.EnterGame。barrel 里这个枚举在 Loading/Const.lua，
    -- 本框架没有该文件，AppStartupLoading.lua:17 的 LoadingState 是 local 表、外部取不到，
    -- 故直接用字面量。改动 AppStartupLoading 的枚举值时需同步这里。
    if state == 10 then
        self.ctrl:CloseSelf()
    end
end

return UICommonMessageBarView