--[[
-- added by wsh @ 2017-11-30
-- UI模块配置表，添加新UI模块时需要在此处加入
--]]

local UIConfig = {
	[UIWindowNames.UIMasteryExpTip] = "UI.UIMasteryExpTip.Config",
	-- 巨龙战场
	[UIWindowNames.UIEnterDragonWorld] = "UI.UIEnterDragonWorld.Config",
	[UIWindowNames.UIActDragonRule] = "UI.UIActDragon.UIActDragonRule.Config",
	[UIWindowNames.UIActDragonBattleTime] = "UI.UIActDragon.UIActDragonBattleTime.Config",
	[UIWindowNames.UIActDragonHistory] = "UI.UIActDragon.UIActDragonHistory.Config",
	[UIWindowNames.UIDragonAllianceSelectMember] = "UI.UIDragonAllianceSelectMember.Config",
	[UIWindowNames.UIDragonSelectMember] = "UI.UIDragonSelectMember.Config",
	[UIWindowNames.UIDragonBattleResult] = "UI.UIDragonBattleResult.Config",
	[UIWindowNames.UIWorldBuildList] = "UI.UIWorldBuildList.Config",
	-- 模块 = 模块配置表
	[UIWindowNames.UIChampionBattleSettlementView] = "UI.UIChampionBattleView.UIChampionBattleSettlementView.Config",
	[UIWindowNames.UIFirstCharge] = "UI.UIFirstCharge.UIFirstCharge.Config",
	[UIWindowNames.UIFirstChargeTip] = "UI.UIFirstCharge.UIFirstChargeTip.Config",
	[UIWindowNames.UIFirstCharge2] = "UI.UIFirstCharge2.Config",
	[UIWindowNames.UIFirstPayNew] = "UI.UIFirstPayNew.Config",
	[UIWindowNames.UIFirstPayNewNvJing] = "UI.UIFirstPayNewNvJing.Config",
	[UIWindowNames.UIChampionBattleCard] =  "UI.UIChampionBattleCard.Config",
	-----CityScene------
	[UIWindowNames.UITutorialAnimation] = "UI.UICityScene.UITutorialAnimation.Config",
	[UIWindowNames.UITutorialAnimation1] = "UI.UICityScene.UITutorialAnimation1.Config",
	[UIWindowNames.UITutorialAnimation2] = "UI.UICityScene.UITutorialAnimation2.Config",
	-----CityScene------
	[UIWindowNames.UIUpPower] = "UI.UIUpPower.Config",
	[UIWindowNames.UICombatActivityPop] = "UI.UICombatActivityPopView.Config",
	---------survival-----------
	[UIWindowNames.UIDownloadProgress] = "UI.UIDownloadProgress.Config",
	[UIWindowNames.UIBagView] = "UI.UIBagView.Config",
	--[UIWindowNames.UIBagView] = "UI.UIBagViewNew.Config",
	[UIWindowNames.UIBagPropStatis] = "UI.UIBagPropStatis.Config",
	[UIWindowNames.UIFinalWaveTip] = "UI.UIParkour.UIFinalWaveTip.Config",
	[UIWindowNames.UIBagPickUp] = "UI.UIBagPickUp.Config",
	[UIWindowNames.UIBagSplit] = "UI.UIBagSplit.Config",
	[UIWindowNames.UIBagUpgrade] = "UI.UIBagUpgrade.Config",
	[UIWindowNames.UIGirlSelect] = "UI.UIGirlSelect.Config",
	[UIWindowNames.UIGridDebug] = "UI.UIGridDebug.Config",
	[UIWindowNames.UIGive] = "UI.UIGive.Config",
	[UIWindowNames.UITriggerGiveItem] = "UI.UITriggerGiveItem.Config",
	[UIWindowNames.UIPrograssBar] = "UI.UIPrograssBar.Config",
	[UIWindowNames.UIMainPromptView] = "UI.UIMainPromptView.Config",
	[UIWindowNames.UIMainMsgView] = "UI.UIMainMsgView.Config",
	[UIWindowNames.UISelectLevel] = "UI.UISelectLevel.Config",
	[UIWindowNames.UISUWorldCollect] = "UI.UISUWorldCollect.Config",
	[UIWindowNames.UIQTEView] = "UI.UIQTEView.Config",
	[UIWindowNames.UIMainChapterTask] = "UI.SU_MainChapterTask.Config",
	[UIWindowNames.UnlockNewFunction] = "UI.SU_UnlockNewFunction.Config",
	[UIWindowNames.UnlockNewSkill] = "UI.SU_UnlockNewSkill.Config",
	[UIWindowNames.UnlockGirl] = "UI.SU_UnlockGirl.Config",
	---------survival-----------

	[UIWindowNames.UIGiftPackage] = "UI.UIGiftPackage.Config",
	[UIWindowNames.UIMainPlayerReportTable] = "UI.UIMainPlayerReportTable.Config",
	[UIWindowNames.UIMain] = "UI.MainUI_SU.Config",
--	[UIWindowNames.UIMainMailTipsPanel] = "UI.UIMainMailTipsPanel.Config",
	[UIWindowNames.UIGiftPackageRewardGet] = "UI.UIGiftPackageRewardGet.Config",
	[UIWindowNames.UIGetRewardView] = "UI.UIGetRewardView.Config",
	[UIWindowNames.UICommonShop] = "UI.UICommonShop.Config",
	[UIWindowNames.UIMultiBuy] = "UI.UIMultiBuy.Config",
	[UIWindowNames.UITradeCenter] = "UI.UITradeCenter.Config",
	[UIWindowNames.UIResourceReport] = "UI.UIResourceReport.Config",
	[UIWindowNames.UIResourceBag] = "UI.UIResourceBag.Config",
	[UIWindowNames.UIScience] = "UI.UIScience.Config",
	[UIWindowNames.UIScienceInfo] = "UI.UIScienceInfo.Config",
	[UIWindowNames.UIJoinAlliance] = "UI.UIAlliance.UIJoinAlliance.Config",
	[UIWindowNames.UIAlLeaderVote] = "UI.UIAlliance.UIAlLeaderVote.Config",
	[UIWindowNames.UIAlMemberRecommend] = "Slg.UI.UIAlliance.UIAlMemberRecommend.Config",
	[UIWindowNames.UIAlLeaderCandidates] = "UI.UIAlliance.UIAlLeaderCandidates.Config",
	[UIWindowNames.UIAllianceSelectRole] = "Slg.UI.UIAlliance.UIAllianceSelectRole.Config",
	[UIWindowNames.UIAlLeaderCongratulate] = "UI.UIAlliance.UIAlLeaderCongratulate.Config",
	[UIWindowNames.UIAllianceQa] = "UI.UIAlliance.UIAllianceQa.Config",
	[UIWindowNames.UIAlLeaderElectSignUp] = "UI.UIAlliance.UIAlLeaderElectSignUp.Config",
	[UIWindowNames.UIAlLeaderElectResult] = "UI.UIAlliance.UIAlLeaderElectResult.Config",
	[UIWindowNames.UIAllianceIntro] = "Slg.UI.UIAllianceIntro.Config",
	[UIWindowNames.UIMineCaveTips] = "UI.UIMineCaveTips.Config",
	[UIWindowNames.UIMineCaveLog] = "UI.UIMineCaveLog.Config",
	[UIWindowNames.UIMineCaveCross] = "UI.UIMineCaveCross.Config",
	[UIWindowNames.UIMineCaveCrossTip] = "UI.UIMineCaveCrossTip.Config",
	[UIWindowNames.UISeasonActGuideTips] = "UI.UISeasonActGuideTips.Config",

	[UIWindowNames.UISeasonGrading] = "UI.UISeason.UISeasonGrading.Config",
	[UIWindowNames.UIAllianceMainTable] = "Slg.UI.UIAlliance.UIAllianceMainTable.Config",
	[UIWindowNames.UIAllianceWarMainTable] = "Slg.UI.UIAlliance.UIAllianceWarMainTable.Config",

	[UIWindowNames.UIAllianceWarDetail] = "UI.UIAlliance.UIAllianceWarDetail.Config",
	[UIWindowNames.UIAllianceAlertDetail] = "UI.UIAlliance.UIAllianceAlertDetail.Config",
	[UIWindowNames.UIAllianceEveryDayTask] = "UI.UIAlliance.UIAllianceEveryDayTask.Config",
	[UIWindowNames.UIAllianceCompeteNew] = "UI.UIAllianceCompeteNew.Config",
	[UIWindowNames.UIAllianceCompeteTaskTip] = "UI.UIAllianceCompeteTaskTip.Config",
	[UIWindowNames.UILeagueMatchAlliances] = "UI.LeagueMatch.UILeagueMatchAlliances.Config",
	[UIWindowNames.UIAllianceLeaderReward] = "UI.UIAllianceLeaderReward.Config",
	[UIWindowNames.UIAllianceCompeteRank] = "UI.UIAllianceCompete.UIAllianceCompeteRank.Config",
	[UIWindowNames.UIAllianceCompeteReward] = "UI.UIAllianceCompete.UIAllianceCompeteReward.Config",
	[UIWindowNames.UILeagueMatchReward] = "UI.LeagueMatch.UILeagueMatchReward.Config",
	[UIWindowNames.UIResSupport] = "UI.UIResSupport.Config",
	[UIWindowNames.UISearch] = "UI.UISearch.Config",
	[UIWindowNames.UISearchLod] = "UI.UISearchLod.Config",
	[UIWindowNames.UITrain] = "UI.UITrain.Config",
	[UIWindowNames.UIHospital] = "UI.UIHospital.Config",
	[UIWindowNames.UISelectDigFinalReward] = "UI.UISelectDigFinalReward.Config",
	[UIWindowNames.UIGetPickaxe] = "UI.UIGetPickaxe.Config",
	[UIWindowNames.UIDigReward] = "UI.UIDigReward.Config",
	[UIWindowNames.UIDigLevelReward] = "UI.UIDigLevelReward.Config",
	[UIWindowNames.UIDigActivityRank] = "UI.UIDigActivityRank.Config",
	[UIWindowNames.UIMineCaveUnlock] = "UI.UIMineCaveUnlock.Config",
	[UIWindowNames.UIPopupPackage] = "UI.UIPopupPackage.Config",
	[UIWindowNames.UISpeed] = "UI.UISpeed.Config",

	[UIWindowNames.UISpeedAutoSelect] = "UI.UISpeedAutoSelect.Config",
	[UIWindowNames.UIPlayerInfo] = "Slg.UI.UIPlayerInfo.Config",
	
	[UIWindowNames.UIChangeName] = "UI.UIChangeName.Config",
	[UIWindowNames.UIChangeNameGender] = "UI.UIChangeNameGender.Config",
	[UIWindowNames.UIAllianceGift] = "Slg.UI.UIAlliance.UIAllianceGift.Config",
	[UIWindowNames.UIAllianceFlag] = "Slg.UI.UIAlliance.UIAllianceFlag.Config",
	[UIWindowNames.UIRankTable] = "Slg.UI.UIRank.UIRankTable.Config",
	[UIWindowNames.UIRankDetailList] = "Slg.UI.UIRank.UIRankDetailList.Config",
	[UIWindowNames.UICampPveHeroInfo] = "Slg.UI.UICampPveHeroInfo.Config",
	[UIWindowNames.UIArenaPlayerArmy] = "Slg.UI.UIArenaPlayerArmy.Config",
	[UIWindowNames.UIArenaPlayerEquipInfo] = "Slg.UI.UIArenaPlayerEquipInfo.Config",
	[UIWindowNames.UIAllianceGiftInfo] = "UI.UIAlliance.UIAllianceGiftInfo.Config",
	[UIWindowNames.UIAllianceHelp] = "Slg.UI.UIAlliance.UIAllianceHelp.Config",
	[UIWindowNames.UIGolloesCamp] = "UI.UIGolloesCamp.Config",
	[UIWindowNames.UIGolloesTraderRecord] = "UI.UIGolloesTraderRecord.Config",
	[UIWindowNames.UIAllianceMemberTip] = "Slg.UI.UIAlliance.UIAllianceMemberTip.Config",
	[UIWindowNames.UISetAlOfficialPos] = "Slg.UI.UIAlliance.UISetAlOfficialPos.Config",
	[UIWindowNames.UIAllianceRankSelect] = "Slg.UI.UIAlliance.UIAllianceRankSelect.Config",
	[UIWindowNames.UISetting] = "UI.UISetting.UISetting.Config",
	[UIWindowNames.UISettingConsole] = "UI.UISetting.UISettingConsole.Config",
	[UIWindowNames.UISettingNotice] = "UI.UISetting.UISettingNotice.Config",
	[UIWindowNames.UISettingLanguage] = "UI.UISetting.UISettingLanguage.Config",
	[UIWindowNames.UIAllianceShop] = "Slg.UI.UIAlliance.UIAllianceShop.Config",
	[UIWindowNames.UISettingSet] = "Slg.UI.UISetting.UISettingSet.Config",
	[UIWindowNames.UISettingFlag] = "UI.UISetting.UISettingFlag.Config",
	[UIWindowNames.UISettingRedemptionCode] = "UI.UISetting.UISettingRedemptionCode.Config",
	[UIWindowNames.UISettingChangeUid] = "UI.UISetting.UISettingChangeUid.Config",
	[UIWindowNames.UIGotoAllowTracking] = "UI.UISetting.UIGotoAllowTracking.Config",
	[UIWindowNames.UIRoles] = "UI.UISetting.UIRoles.Config",
	[UIWindowNames.UIChooseServer] = "Slg.UI.UISetting.UIChooseServer.Config",
	[UIWindowNames.UIRoleLogin] = "UI.UISetting.UIRoleLogin.Config",
	[UIWindowNames.UIRoleCreate] = "UI.UISetting.UIRoleCreate.Config",
	[UIWindowNames.UIAllianceScienceInfo] = "Slg.UI.UIAlliance.UIAllianceScienceInfo.Config",
	[UIWindowNames.UIAllianceScience] = "Slg.UI.UIAlliance.UIAllianceScience.Config",
	[UIWindowNames.UISettingGameSpeed] = "UI.UISetting.UISettingGameSpeed.Config",
	[UIWindowNames.UIHeroRankList] = "Slg.UI.UIRank.UIHeroRankList.Config",
	[UIWindowNames.UIMoreInformation] = "Slg.UI.UIMoreInformation.Config",

	---账号---
	[UIWindowNames.UIPrivacy] = "UI.UIPrivacy.Config",
	[UIWindowNames.UISettingAccount] = "UI.UIAccount2.UISettingAccount.Config",
	[UIWindowNames.UIBindAccount] = "UI.UIAccount2.UIBindAccount.Config",
	[UIWindowNames.UICreateAccount] = "UI.UIAccount2.UICreateAccount.Config",
	[UIWindowNames.UIAccountVerify] = "UI.UIAccount2.UIAccountVerify.Config",
	[UIWindowNames.UIBindSuccess] = "UI.UIAccount2.UIBindSuccess.Config",
	[UIWindowNames.UIAccountList] = "UI.UIAccount2.UIAccountList.Config",
	[UIWindowNames.UIAddAccount] = "UI.UIAccount2.UIAddAccount.Config",
	[UIWindowNames.UILoginConfirm] = "UI.UIAccount2.UILoginConfirm.Config",
	[UIWindowNames.UIForgetPassword] = "UI.UIAccount2.UIForgetPassword.Config",
	[UIWindowNames.UIModifyPassword] = "UI.UIAccount2.UIModifyPassword.Config",
	[UIWindowNames.UIModifySuccess] = "UI.UIAccount2.UIModifySuccess.Config",
	------
	[UIWindowNames.TouchScreenEffect] = "UI.TouchScreenEffect.Config",
	[UIWindowNames.UIAllianceChangeName] = "UI.UIAlliance.UIAllianceChangeName.Config",
	[UIWindowNames.UIAllianceChangeAbbr] = "UI.UIAlliance.UIAllianceChangeAbbr.Config",
	[UIWindowNames.UIAllianceChangeLanguage] = "UI.UIAlliance.UIAllianceChangeLanguage.Config",
	[UIWindowNames.UISettingAlliance] = "Slg.UI.UIAlliance.UISettingAlliance.Config",
	[UIWindowNames.UIAllianceApplyList] = "Slg.UI.UIAlliance.UIAllianceApplyList.Config",
	[UIWindowNames.UICreateAlliance] = "UI.UIAlliance.UICreateAlliance.Config",
	[UIWindowNames.UIAllianceDetail] = "Slg.UI.UIAlliance.UIAllianceDetail.Config",
	[UIWindowNames.UIAllianceMemberDetail] = "Slg.UI.UIAlliance.UIAllianceMemberDetail.Config",
	[UIWindowNames.UIAllianceRankTable] = "Slg.UI.UIAlliance.UIAllianceRankTable.Config",
	[UIWindowNames.UIAllianceCreatePopUp] = "UI.UIAlliance.UIAllianceCreatePopUp.Config",
	[UIWindowNames.UIBindAccountCreate] = "UI.UIAccount.UIBindAccountCreate.Config",
	[UIWindowNames.UILogin] = "UI.UIAccount.UILogin.Config",
	[UIWindowNames.UIBindAccountAlready] = "UI.UIAccount.UIBindAccountAlready.Config",
	[UIWindowNames.UIChangeMail] = "UI.UIAccount.UIChangeMail.Config",
	[UIWindowNames.UIVerifyMail] = "UI.UIAccount.UIVerifyMail.Config",
	[UIWindowNames.UIPinInput] = "UI.UIPin.UIPinInput.Config",
	[UIWindowNames.UIPinSet] = "UI.UIPin.UIPinSet.Config",
	[UIWindowNames.UIPinUseSet] = "UI.UIPin.UIPinUseSet.Config",
	[UIWindowNames.UIPinForget] = "UI.UIPin.UIPinForget.Config",
	[UIWindowNames.UIAccountBan] = "UI.UIAccount.UIAccountBan.Config",
	[UIWindowNames.UIBuildDes] = "UI.UIBuildDes.Config",

	--英雄 BEGIN--
	[UIWindowNames.UIHeroList] = "UI.UIHero2.SU_UIHeroList.Config",
	[UIWindowNames.UIHeroInfo] = "UI.UIHero2.UIHeroInfo.Config",
	[UIWindowNames.UINewHero] = "UI.UIHero2.UINewHero.Config",
	[UIWindowNames.UIHeroTip] = "UI.UIHero2.UIHeroTip.Config",
	[UIWindowNames.UIHeroSkillTip] = "UI.UIHero2.UIHeroSkillTip.Config",
	[UIWindowNames.UIHeroSkillUpgradeSuccess] = "UI.UIHero2.UIHeroSkillUpgradeSuccess.Config",
	[UIWindowNames.UIHeroSkillUpgrade] = "UI.UIHero2.UIHeroSkillUpgrade.Config",
	[UIWindowNames.UIHeroMedalExchange] = "UI.UIHero2.UIHeroMedalExchange.Config",
	[UIWindowNames.UIHeroResetSuccess] = "UI.UIHero2.UIHeroResetSuccess.Config",
	[UIWindowNames.UIHeroLvUp] = "UI.UIHero2.UIHeroLvUp.Config",
	[UIWindowNames.UIHeroBeyond] = "UI.UIHero2.UIHeroBeyond.Config",
	[UIWindowNames.UIHeroMilitaryRank] = "UI.UIHero2.UIHeroMilitaryRank.Config",
	[UIWindowNames.UIHeroRecruit] = "UI.UIHero2.UIHeroRecruit.Config",
	[UIWindowNames.UIHeroRecruitReward] = "UI.UIHero2.UIHeroRecruitReward.Config",
	[UIWindowNames.UIHeroRecruitTip] = "UI.UIHero2.UIHeroRecruitTip.Config",
	[UIWindowNames.UIHeroRecruitChangeCamp] = "UI.UIHero2.UIHeroRecruitChangeCamp.Config",
	[UIWindowNames.UIRecruitLotteryTip] = "UI.UIHero2.UIRecruitLotteryTip.Config",
	[UIWindowNames.UIHeroJigsawReward] = "UI.UIHero2.UIHeroJigsawReward.Config",
	[UIWindowNames.UIHeroSkillAdvance] = "UI.UIHero2.UIHeroSkillAdvance.Config",
	[UIWindowNames.UIHeroMilitaryRankIntro] = "UI.UIHero2.UIHeroMilitaryRankIntro.Config",
	[UIWindowNames.UIHeroPosterExchangePop] = "UI.UIHero2.UIHeroPosterExchangePop.Config",
	[UIWindowNames.UIHeroPosterExchangeMain] = "UI.UIHero2.UIHeroPosterExchangeMain.Config",
	[UIWindowNames.UIHeroMilitaryRankIntroNew] = "UI.UIHero2.UIHeroMilitaryRankIntroNew.Config",
	[UIWindowNames.SU_NewHero] = "UI.UIHero2.SU_NewHero.Config",
	[UIWindowNames.UIHeroMilitaryAdvanceSuccess] = "UI.UIHero2.UIHeroMilitaryAdvanceSuccess.Config",
	[UIWindowNames.UIHeroDetailTips] = "UI.UIHeroDetailTips.Config",
	--英雄 END--
	
	--活动--
	[UIWindowNames.UIActivityCenterTable] = "UI.UIActivityCenterTable.Config",
	[UIWindowNames.UIDailyActivity] = "UI.UIDailyActivity.Config",
	[UIWindowNames.UIActivityOverview] = "UI.UIActivityOverview.Config",
	[UIWindowNames.UIActivitySummary] = "UI.UIActivitySummary.Config",
	[UIWindowNames.UIActivitySummaryPreview] = "UI.UIActivitySummaryPreview.Config",
	[UIWindowNames.UIActivitySummaryReward] = "UI.UIActivitySummaryReward.Config",
	[UIWindowNames.UIActivityRewardTip] = "UI.UIActivityRewardTip.Config",
	[UIWindowNames.UIActMonsterTowerDiffTips] = "UI.UIActMonsterTowerDiffTips.Config",
	[UIWindowNames.UIActMonsterTowerRank] = "UI.UIActMonsterTowerRank.Config",
	[UIWindowNames.UILandLockTips] = "UI.UI_LandLockTips.Config",
	[UIWindowNames.UILandLockTips1] = "UI.UI_LandLockTips1.Config",
	[UIWindowNames.UIActMonsterTowerReward] = "UI.UIActMonsterTowerReward.Config",
	[UIWindowNames.UIActMonsterTowerTask] = "UI.UIActMonsterTowerTask.Config",
	[UIWindowNames.UIMonsterTowerTips] = "UI.UIMonsterTowerTips.Config",
	[UIWindowNames.UIMonsterTowerRewardGet] = "UI.UIMonsterTowerRewardGet.Config",
	[UIWindowNames.UIPackageContentTip] = "UI.UIPackageContentTip.Config",
	[UIWindowNames.UIActivityEdenWarTips] = "UI.UIActivityEdenWarTips.Config",
	[UIWindowNames.UIAllianceBossRewardAndRankPanel] = "UI.UIAllianceBoss.UIAllianceBossRewardAndRankPanel.Config",
	[UIWindowNames.UIAllianceBossAllianceRewardPanel] = "UI.UIAllianceBoss.UIAllianceBossAllianceRewardPanel.Config",
	[UIWindowNames.UIAllianceBossBounsTipsPanel] = "UI.UIAllianceBoss.UIAllianceBossBounsTipsPanel.Config",
	[UIWindowNames.UIAllianceBossWorldPointTipPanel] = "UI.UIAllianceBoss.UIAllianceBossWorldPointTipPanel.Config",
	[UIWindowNames.UIAllianceBossViewPanel] = "UI.UIAllianceBoss.UIAllianceBossViewPanel.Config",
	[UIWindowNames.UIWorldAllianceBossTip] = "UI.UIAllianceBoss.UIWorldAllianceBossTip.Config",

	[UIWindowNames.UIBookMarkPositionCollect] ="UI.UIBookMarkPositionCollect.Config",
	[UIWindowNames.UIBookMark] ="UI.UIBookMark.Config",
	[UIWindowNames.UIBookMarkAdd] ="UI.UIBookMarkAdd.Config",
	[UIWindowNames.UIPositionTip] ="UI.UIPositionTip.Config",
	[UIWindowNames.UIPositionAdd] ="Slg.UI.UIPositionAdd.Config",
	[UIWindowNames.UIPositionFavorite] ="UI.UIPositionFavorite.Config",
	[UIWindowNames.UIPositionShare] ="UI.UIPositionShare.Config",
	[UIWindowNames.UIPositionShareConfirm] ="UI.UIPositionShareConfirm.Config",
	[UIWindowNames.UICommonMessageTip] ="UI.UICommonMessageTip.Config",
	[UIWindowNames.UICommonMessageSpecialBar] ="UI.UICommonMessageSpecialBar.Config",
	[UIWindowNames.UICommonIntroTip] ="UI.UICommonIntroTip.Config",
	[UIWindowNames.UICommonUseItemTip] ="UI.UICommonUseItemTip.Config",
	[UIWindowNames.UICommonMessageBar] ="UI.UICommonMessageBar.Config",
	[UIWindowNames.UICommonSingleMsgBar] = "UI.UICommonSingleMsgBar.Config",
	[UIWindowNames.UINoticeTips] ="UI.UINoticeTips.Config",
	[UIWindowNames.UINoticeHeroTips] ="UI.UINoticeHeroTips.Config",
	[UIWindowNames.UICommonBuyItem] ="UI.UICommonBuyItem.Config",
	[UIWindowNames.UICommonUseResItemTips] ="UI.UICommonUseResItemTips.Config",
	[UIWindowNames.UICommonItemProbability] ="UI.UICommonItemProbability.Config",
	[UIWindowNames.UICommonItemProbabilityNew] ="UI.UICommonItemProbabilityNew.Config",
	[UIWindowNames.UIBuildList] ="UI.SU_UIBuildList.Config",
	[UIWindowNames.UIWorldTileUI] ="UI.SU_UIWorldTileUI.Config",
	[UIWindowNames.UIBuildDetails] ="UI.UIBuildDetails.Config",
	[UIWindowNames.UICollectReward] ="UI.UICollectReward.Config",
	[UIWindowNames.UIFactoryAddTip] ="UI.UIFactoryAddTip.Config",
	[UIWindowNames.UIDomeUpdate] ="UI.UIDomeUpdate.Config",
	[UIWindowNames.UICapacityAdd] = "UI.UICapacityAdd.Config",

	[UIWindowNames.UIAllianceChangeAnnounce] ="Slg.UI.UIAlliance.UIAllianceChangeAnnounce.Config",
	[UIWindowNames.UIAllianceInviteTip] ="Slg.UI.UIAlliance.UIAllianceInviteTip.Config",
	[UIWindowNames.UIAllianceChangeRestriction] ="UI.UIAlliance.UIAllianceChangeRestriction.Config",
	[UIWindowNames.UIScienceTab] = "UI.UIScienceTab.Config",
	[UIWindowNames.UIScienceTabLock] = "UI.UIScienceTabLock.Config",
	[UIWindowNames.UIOtherPlayerInfo] = "Slg.UI.UIOtherPlayerInfo.Config",

	[UIWindowNames.UIBuildUnlock] = "UI.UIBuildUnlock.Config",
	[UIWindowNames.UIBuildUpgradeAddDes] = "UI.UIBuildUpgradeAddDes.Config",
	-- 踢人界面
	[UIWindowNames.UIChatKickUser] = "UI.UIChatNew.UIChatKickUser.Config",
	[UIWindowNames.UIBuildQueue] = "UI.UIBuildQueue.Config",
	[UIWindowNames.UIBuildQueueLease] = "UI.UIBuildQueueLease.Config",
	[UIWindowNames.UIPasture] = "UI.UIPasture.Config",
	[UIWindowNames.UIFormationSoldierChoose] = "UI.UIFormation.UIFormationSoldierChoose.Config",
	[UIWindowNames.UIFormationDefenceTable] = "UI.UIFormationDefence.UIFormationDefenceTable.Config",
	[UIWindowNames.UIFormationState] = "UI.UIFormation.UIFormationState.Config",
	[UIWindowNames.UIPlayerChangeHeadIcon] = "Slg.UI.UIPlayerChangeHeadIcon.Config",
	[UIWindowNames.UIPlayerHeadIconSelect] = "Slg.UI.UIPlayerHeadIconSelect.Config",
	[UIWindowNames.UICapacityFull] = "UI.UICapacityFull.Config",
	[UIWindowNames.UISellConfirm] = "UI.UISellConfirm.Config",

	[UIWindowNames.UIVip] = "Slg.UI.UIVip.Config",
	[UIWindowNames.UIVipPurchase] = "Slg.UI.UIVip.UIVipPurchase.Config",
	[UIWindowNames.UIVipRewardTip] = "Slg.UI.UIVip.UIVipRewardTip.Config",
	[UIWindowNames.UIVIPUpgradePopUp] = "Slg.UI.UIVip.UIVIPUpgradePopUp.Config",
	[UIWindowNames.UIVIPRewardPopUp] = "Slg.UI.UIVip.UIVIPRewardPopUp.Config",
	[UIWindowNames.UIVipAddTime] = "Slg.UI.UIVipAddTime.Config",

	[UIWindowNames.UIStrongCommanderPre] = "UI.UIStrongCommander.UIStrongCommanderPre.Config",
	[UIWindowNames.UIStrongCommander] = "UI.UIStrongCommanderMain.Config",
	[UIWindowNames.UIStrongCommanderPop] = "UI.UIStrongCommander.UIStrongCommanderPop.Config",
	[UIWindowNames.UIPersonalArmsScore] = "UI.UIPersonalArmsScore.Config",
	[UIWindowNames.UIAllianceCompeteDayTaskTip] = "UI.UIAllianceCompeteDayTaskTip.Config",
	[UIWindowNames.UIAllianceCompeteDayTaskPop] = "UI.UIAllianceCompeteDayTaskPop.Config",
	[UIWindowNames.UIAllianceCompeteFightNotice] = "UI.UIAllianceCompeteFightNotice.Config",
	[UIWindowNames.UILeagueMatchResult] = "UI.LeagueMatch.UILeagueMatchResult.Config",
	--[[
		新邮件部分
	]]
	[UIWindowNames.UIMailNew] = "Slg.UI.UIMailNew.UIMailMainPanel.Config",
	[UIWindowNames.UIMailInfo] = "Slg.UI.UIMailNew.UIMailInfo.Config",
	[UIWindowNames.UIMailDetailReportView] = "Slg.UI.UIMailNew.UIMailDetailReportView.Config",
	[UIWindowNames.UIMailTroopInfoListView] = "Slg.UI.UIMailNew.UIMailTroopInfoListView.Config",
	[UIWindowNames.UIShareMail] = "Slg.UI.UIMailNew.UIShareMail.Config",
	[UIWindowNames.UIMailAllUserHeroesView] = "Slg.UI.UIMailNew.UIMailAllUserHeroesView.Config",
	[UIWindowNames.UIMailTroopBuffAddPanel] = "Slg.UI.UIMailNew.UIMailTroopBuffAddPanel.Config",
	[UIWindowNames.UIMailSend] = "Slg.UI.UIMailNew.UIMailSend.Config",
	[UIWindowNames.UIMailBattleReportDetail] = "UI.UIMailBattleReportDetail.Config",
	[UIWindowNames.UIReportEquipTip] = "Slg.UI.UIMailNew.UIReportEquipTip.Config",
	[UIWindowNames.UIBattleReportInfo] = "Slg.UI.UIMailNew.UIBattleReportInfo.Config",

	[UIWindowNames.UIResourceCost] = "UI.UIResourceCost.Config",

	[UIWindowNames.UIItemTips] = "UI.SU_ItemTips.Config",
	[UIWindowNames.UIHeroTips] = "UI.UIHeroTips.Config",
	[UIWindowNames.UIHeroTips2] = "UI.UIHeroTips2.Config",

	[UIWindowNames.UIWorldCollectMessageTip] = "UI.UIWorldCollect.UIWorldCollectMessageTip.Config",

	[UIWindowNames.UIWorldBlackTile] = "UI.UIWorldBlackTile.Config",
	[UIWindowNames.UIMoveCity] = "UI.UIMoveCity.Config",
	[UIWindowNames.UIMoveCityTip] = "UI.UIMoveCityTip.Config",
	[UIWindowNames.UIFormationAssistance] = "UI.UIFormationAssistance.Config",
	--选择服务器界面
	[UIWindowNames.UIDebugChooseServer] = "UI.UILoading.UIDebugChooseServer.Config",
	--选择服务器账户列表
	[UIWindowNames.UIChooseServerAccountList] = "UI.UILoading.UIChooseServerAccountList.Config",
	[UIWindowNames.UISpeedUpConfirm] = "UI.UISpeedUpConfirm.Config",
	[UIWindowNames.UIDetectEvent] = "UI.UIRadarCenter.UIDetectEvent.Config",
	[UIWindowNames.UIDetectEventLevelUpgrade] = "UI.UIRadarCenter.UIDetectEventLevelUpgrade.Config",

	[UIWindowNames.UICityManage] = "UI.UICityManage.Config",
	[UIWindowNames.UICityMainTip] = "UI.UICityMainTip.Config",
	[UIWindowNames.UICityWeather] = "UI.UICityWeather.Config",

	[UIWindowNames.UIDetectEventPowerUpgrade] = "UI.UIRadarCenter.UIDetectEventPowerUpgrade.Config",
	[UIWindowNames.UIWorldSamplePointUI] = "UI.UIWorldSamplePointUI.Config",
	[UIWindowNames.UIWorldExplorePointUI] = "UI.UIWorldExplorePointUI.Config",
	[UIWindowNames.UIArrow] = "UI.UIArrow.Config",
	[UIWindowNames.UIAssistanceThrone] = "UI.UIAssistanceThrone.Config",
	[UIWindowNames.UIHeadIconShow] = "UI.UIHeadIconShow.Config",
	[UIWindowNames.UIFingerArrow] = "UI.UIFingerArrow.Config",
	[UIWindowNames.UIForcesDetail] = "UI.UIForcesDetail.Config",
	[UIWindowNames.UIWorldGarbagePointUI] = "UI.UIWorldGarbage.Config",
	[UIWindowNames.UIGuideTalk] = "UI.UIGuideTalk.Config",
	[UIWindowNames.UIGuideTalk2] = "UI.UIGuideTalk2.Config",
	[UIWindowNames.UIGuideTalk3] = "UI.UIGuideTalk3.Config",
	[UIWindowNames.UIGuideTalk4] = "UI.UIGuideTalk4.Config",
	[UIWindowNames.UIGuideTalk5] = "UI.UIGuideTalk5.Config",
	[UIWindowNames.UIGuideArrow] = "UI.SU_GuideArrow.Config",
	[UIWindowNames.UIGuideArrowNew] = "UI.SU_GuideArrowNew.Config",
	[UIWindowNames.UIGuideMoveArrow] = "UI.UIGuideMoveArrow.Config",
	[UIWindowNames.UIDetectEventRewardFlyEffect] = "UI.UIDetectEventRewardFlyEffect.Config",
	[UIWindowNames.UIResourceLack] = "UI.UIResourceLack.Config",
	[UIWindowNames.UIResourceLackNew] = "UI.UIResourceLackNew.Config",
	[UIWindowNames.UIResourceLackNew1] = "UI.UIResourceLackNew1.Config",
	[UIWindowNames.UIResourceLackNew2] = "UI.UIResourceLackNew2.Config",
	[UIWindowNames.UIResourceExchange] = "UI.UIResourceExchange.Config",
	[UIWindowNames.UIGuideVideo] = "UI.UIGuideVideo.Config",
	[UIWindowNames.UIDisconnect] = "UI.SU_UIDisconnect.Config",
	[UIWindowNames.UIFormationSelectListNew] = "UI.UIFormation.UIFormationSelectListNew.Config",
	[UIWindowNames.UIArmyTips] = "UI.UIFormation.UIArmyTips.Config",
	[UIWindowNames.UIGarbageRewardShow] = "UI.UIGarbageRewardShow.Config",
	[UIWindowNames.UILoadEditorBuild] = "UI.UILoadEditorBuild.Config",
	[UIWindowNames.UIFirstPay] = "UI.UIFirstPay.Config",
	[UIWindowNames.UICreateSetAlliance] = "UI.UIAlliance.UICreateSetAlliance.Config",
	[UIWindowNames.UISetPlayerNation] = "UI.UISetPlayerNation.Config",
	[UIWindowNames.UIArenaChallenge] = "UI.UIArenaChallenge.Config",
	[UIWindowNames.UIArenaHistory] = "UI.UIArenaHistory.Config",
	[UIWindowNames.UIArenaConfirm] = "UI.UIArenaConfirm.Config",
	[UIWindowNames.UIArenaPanel] = "UI.UIArenaPanel.Config",
	[UIWindowNames.UIArenaSeasonResetPopup] = "UI.UIArenaSeasonResetPopup.Config",
	[UIWindowNames.UIAllianceAutoJoinRally] = "UI.UIAlliance.UIAllianceAutoJoinRally.Config",
	[UIWindowNames.UIAllianceAssembleConfirm] = "UI.UIAlliance.UIAllianceAssembleConfirm.Config",
	[UIWindowNames.UIMoveCityAssemble] = "UI.UIAlliance.UIMoveCityAssemble.Config",
	[UIWindowNames.UIAllianceAssemble] = "UI.UIAlliance.UIAllianceAssemble.Config",
	[UIWindowNames.UIAllianceRallyOperate] = "UI.UIAlliance.UIAllianceRallyOperate.Config",
	[UIWindowNames.UIAllianceAssembleBox] = "UI.UIAlliance.UIAllianceAssembleBox.Config",
	[UIWindowNames.UIAllianceExitTip] = "UI.UIAlliance.UIAllianceExitTip.Config",
	[UIWindowNames.UIStorageShopMain] = "UI.UIStorageShopMain.Config",
	[UIWindowNames.UIStorageShop] = "UI.UIStorageShop.Config",
	[UIWindowNames.UIStorageShopSelect] = "UI.UIStorageShopSelect.Config",
	[UIWindowNames.UIStorageShopList] = "UI.UIStorageShopList.Config",
	[UIWindowNames.UIStorageShopRetrieve] = "UI.UIStorageShopRetrieve.Config",
	[UIWindowNames.UIStorageShopRetrieveNew] = "UI.UIStorageShopRetrieveNew.Config",
	[UIWindowNames.UIUnLockSuccess] = "UI.UIUnLockSuccess.Config",
	[UIWindowNames.UIGuideGarbage] = "UI.UIGuideGarbage.Config",
	[UIWindowNames.UIBuildUpgradeTip] = "UI.UIBuildUpgradeTip.Config",
	[UIWindowNames.UIWorldPoint] ="Slg.UI.UIWorldPoint.Config",
	[UIWindowNames.UIWorldResistanceTips] ="UI.UIWorldResistanceTips.Config",
	[UIWindowNames.UIFormationTableNew] = "UI.UIFormation.UIFormationTableNew2.Config",
	[UIWindowNames.UISetAttackTimes] = "UI.UISetAttackTimes.Config",
	[UIWindowNames.UINoInput] = "UI.UINoInput.Config",
	[UIWindowNames.UIShowBlack] = "UI.UIShowBlack.Config",
	[UIWindowNames.UIBlackView] = "UI.UIBlackView.Config",
	[UIWindowNames.UIPlaceBuild] = "UI.SU_UIPlaceBuild.Config",
	[UIWindowNames.UIPlaceBuildWorld] = "UI.SU_UIPlaceBuildWorld.Config",
	--
	[UIWindowNames.UIGroceryStore] = "UI.UIGroceryStore.Config",
	[UIWindowNames.UIWorldSiegePoint] = "Slg.UI.UIWorldSiegePoint.Config",
	[UIWindowNames.UIWorldFortPoint] = "UI.UIWorldFortPoint.Config",
	[UIWindowNames.UIArmyInfo] = "UI.UIArmyInfo.Config",
	[UIWindowNames.UIArmySelect] = "UI.UIArmySelect.Config",
	[UIWindowNames.UIArmyTips1] = "UI.UIArmyTips1.Config",
	[UIWindowNames.UIArmyTips2] = "UI.UIArmyTips2.Config",
	[UIWindowNames.UIGuideHeadTalk] = "UI.UIGuideHeadTalk.Config",
	[UIWindowNames.UIResourceItemLack] = "UI.UIResourceItemLack.Config",
	[UIWindowNames.UIAllianceCity] = "Slg.UI.UIAlliance.UIAllianceCity.Config",
	[UIWindowNames.UIAllianceCityBuffBox] = "Slg.UI.UIAlliance.UIAllianceCityBuffBox.Config",
	[UIWindowNames.UIAllianceTask] = "UI.UIAlliance.UIAllianceTask.Config",
	[UIWindowNames.UIGuideTip] = "UI.UIGuideTip.Config",
	[UIWindowNames.UISoliderGetTip] = "UI.UISoliderGetTip.Config",
	[UIWindowNames.UIWorldRuinsPopUp] = "UI.UIWorldRuinsPopUp.Config",
	[UIWindowNames.UIWorldOccupyMessageBar] = "UI.UIWorldOccupyMessageBar.Config",
	[UIWindowNames.UILuckyRollRewardTip] = "UI.UILuckyRollRewardTip.Config",
	[UIWindowNames.UIXmasLuckyRollProb] = "UI.UIXmasLuckyRollProb.Config",
	[UIWindowNames.UILuckyRollRewardGet] = "UI.UILuckyRollRewardGet.Config",
	[UIWindowNames.AttZombiePuzzleTaskPanel] = "UI.AttZombiePuzzleTaskPanel.Config",
	[UIWindowNames.UIChapterSwitch] = "UI.UIChapterSwitch.Config",
	[UIWindowNames.UISceneNoInput] = "UI.UISceneNoInput.Config",
	[UIWindowNames.UILevelUp] = "UI.UILevelUp.Config",
	[UIWindowNames.UICommonDesTip] = "UI.UICommonDesTip.Config",
	[UIWindowNames.UIFormationLackPower] = "UI.UIFormationLackPower.Config",
	[UIWindowNames.UIFormationTip] = "UI.UIFormation.UIFormationTip.Config",
	[UIWindowNames.UIGuideUnlockMask] = "UI.UIGuideUnlockMask.Config",
	[UIWindowNames.UIFiveStarGet] = "UI.SU_FiveStarGet.Config",
	[UIWindowNames.UIFiveStarFeedBack] = "UI.UIFiveStarFeedBack.Config",
	[UIWindowNames.UIChangeAllianceCityName] = "UI.UIChangeAllianceCityName.Config",
	[UIWindowNames.UIJoystick] = "UI.UIJoystick.Config",
	[UIWindowNames.UIChangeAllianceCityName] = "UI.UIChangeAllianceCityName.Config",
	[UIWindowNames.UIComplexTip] = "UI.UIComplexTip.Config",

	[UIWindowNames.UIChampionBattleMain] = "Slg.UI.UIChampionBattleView.UIChampionBattleMainView.Config",
	[UIWindowNames.UIChampionBattleReward] = "Slg.UI.UIChampionBattleView.UIChampionBattleRewardView.Config",
	[UIWindowNames.UIChampionpropaganda] = "Slg.UI.UIChampionBattleView.Championpropaganda.Config",
	[UIWindowNames.UIChampionBattleFormation] = "Slg.UI.UIChampionBattleView.UIChampionBattleFormationView.Config",
	[UIWindowNames.LFChampionBattleFight] = "Slg.UI.UIChampionBattleView.UIChampionBattleFight.Config",
	[UIWindowNames.LFChampionBattleReport] = "Slg.UI.UIChampionBattleView.UIChampionBattleReport.Config",
	[UIWindowNames.ChampionBattleBettingrecord] = "Slg.UI.UIChampionBattleView.UIChampionBattleBettingrecordView.Config",
	[UIWindowNames.ChampionBattleBetting] = "Slg.UI.UIChampionBattleView.ChampionBattleBetting.Config",

	[UIWindowNames.UIPiggyBank] = "UI.UIPiggyBank.Config",
	[UIWindowNames.UIPiggyBankTip] = "UI.UIPiggyBankTip.Config",
	[UIWindowNames.UIEnergyBank] = "UI.UIEnergyBank.Config",
	[UIWindowNames.UIEnergyBankTip] = "UI.UIEnergyBankTip.Config",
	[UIWindowNames.UINoticeEquipTips] = "UI.UINoticeEquipTips.Config",
	[UIWindowNames.UINoticeAlCompeteTips] = "UI.UINoticeAlCompeteTips.Config",
	[UIWindowNames.UICapacityBoxSelect] = "UI.UICapacityBoxSelect.Config",
	[UIWindowNames.UIWorldTrendRank] = "UI.UIWorldTrend.UIWorldTrendRank.Config",
	[UIWindowNames.UIAddStamina] = "UI.UIAddStamina.Config",
	[UIWindowNames.UIScrollPack] = "UI.UIScrollPack.Config",
	[UIWindowNames.UIRobotPack] = "UI.UIRobotPack.RobotPack.Config",
	[UIWindowNames.UILovelyFavor] = "UI.UIRobotPack.LovelyFavor.Config",
	[UIWindowNames.UIGolloesMonthCard] = "UI.UIGolloesMonthCard.Config",
	[UIWindowNames.UIGolloesUnlockReward] = "UI.UIGolloesUnlockReward.Config",
	[UIWindowNames.UIFormationShare] = "UI.UIFormationShare.Config",
	[UIWindowNames.UIKonbini] = "UI.UIKonbini.Config",

	--[UIWindowNames.UIGarageRefit] = "UI.UIGarageRefit.Config",
	[UIWindowNames.UIPoliceStation] = "UI.UIPoliceStation.Config",
	[UIWindowNames.UIMailBattleAttrDetail] = "Slg.UI.UIMailNew.UIMailBattleAttrDetail.Config",
	[UIWindowNames.UIChampionBattleResultHintView] = "UI.UIChampionBattleView.UIChampionBattleResultHintView.Config",
	[UIWindowNames.UIChampionBattleRankView] = "Slg.UI.UIChampionBattleView.UIChampionBattleRankView.Config",
	[UIWindowNames.UIAllianceCareerEdit] = "UI.UIAlliance.UIAllianceCareer.Config",
	[UIWindowNames.UIAllianceCareerEffectTip] = "UI.UIAlliance.UIAllianceCareerEffectTip.Config",
	[UIWindowNames.UIRocketFailedLanding] = "UI.UIRocketFailedLanding.Config",
	[UIWindowNames.UIWorldBattleNews] = "UI.UIWorldBattleNews.Config",
	[UIWindowNames.UIMainAccountBind] = "UI.UIMainAccountBind.Config",
	[UIWindowNames.UINpcQN] = "UI.UINpcQN.Config",
	[UIWindowNames.UIWorldNewsTips] = "UI.UIWorldNewsTips.Config",
	[UIWindowNames.UIMainTask] = "UI.UIMainTask.Config",
	[UIWindowNames.UIHeroOfficial] = "UI.UIHeroOfficial.Config",
	[UIWindowNames.UIWorldNewsAbbrDetail] = "UI.UIWorldNewsAbbrDetail.Config",
	[UIWindowNames.UIWoundedCompensate] = "UI.UIWoundedCompensate.Config",
	[UIWindowNames.UIDawnTaskProgressReward] = "UI.UIDawnTaskProgressReward.Config",
	[UIWindowNames.UICompensateMonthCardLetter] = "UI.UICompensateMonthCardLetter.Config",
	[UIWindowNames.UICompensateMonthCardPop] = "UI.UICompensateMonthCardPop.Config",

	--PVE
	[UIWindowNames.UIPVEScene] = "UI.UIPVE.UIPVEScene.Config",
	[UIWindowNames.UIPVEResult] = "UI.UIPVE.UIPVEResult.Config",
	[UIWindowNames.MainUI_SU] = "UI.MainUI_SU.Config",
	[UIWindowNames.UIMainMiniMap] = "UI.UIMainMiniMap.Config",
	[UIWindowNames.UIPVELoading] = "UI.UIPVE.UIPVELoading.Config",
	[UIWindowNames.UIItemPurchases] = "UI.UIItemPurchases.Config",
	[UIWindowNames.UIPVPStartFight] = "UI.UIPVPStartFight.Config",
	[UIWindowNames.UIPVEStartFightVS] = "UI.UIPVPStartFightVS.Config",
	[UIWindowNames.UIPVPDamageDate] = "UI.UIPVPDamageDate.Config",
	[UIWindowNames.UIPVEChallengeWarning] = "UI.UIPVE.UIPVEChallengeWarning.Config",

	[UIWindowNames.UIFormationRestraint] =  "UI.UIFormation.UIFormationRestraint.Config",
	[UIWindowNames.UIHeroCampRestraint] =  "UI.UIFormation.UIHeroCampRestraint.Config",
	[UIWindowNames.UIMailCampRestraintDetail] =  "UI.UIFormation.UIMailCampRestraintDetail.Config",
	[UIWindowNames.UIHeroMonthCard] =  "UI.UIHeroMonthCard.Config",
	[UIWindowNames.UIGuideCommunicationTalk] =  "UI.UIGuideCommunicationTalk.Config",
	[UIWindowNames.UIStorageShopHistory] =  "UI.UIStorageShopHistory.Config",
	[UIWindowNames.UIMoving] =  "UI.UIMoving.Config",

	[UIWindowNames.UIWorldBossTroop] = "UI.UIWorldBossTroop.Config",
	[UIWindowNames.UIWorldBossRank] = "UI.UIWorldBossRank.Config",
	[UIWindowNames.UIActBossTips] = "UI.UIActBossTips.Config",

	[UIWindowNames.UIResourceGetTip] = "UI.UIResourceGetTip.Config",
	[UIWindowNames.UIPVEShop] = "UI.UIPVE.UIPVEShop.Config",
	
	[UIWindowNames.UIPveBattleSoldierList] = "UI.UIPVE.UIPveBattleSoldierList.Config",

	[UIWindowNames.UIWorldDeclareWar] = "UI.UIWorldDeclareWar.Config",
	[UIWindowNames.UIDeclareWarList] = "UI.UIDeclareWarList.Config",
	[UIWindowNames.UIWorldDeclareWarInfo] = "UI.UIWorldDeclareWarInfo.Config",
	[UIWindowNames.UIWorldDeclareList] = "UI.UIWorldDeclareList.Config",

    [UIWindowNames.UIWorldDeclareWarRe] = "UI.UIWorldDeclareWarRe.Config",

	[UIWindowNames.UIGiftScoreTips] = "UI.UIGiftScoreTips.Config",
	[UIWindowNames.UIBlackChangeMask] = "UI.UIBlackChangeMask.Config",
	[UIWindowNames.UIFormationAddStamina] = "UI.UIFormation.UIFormationAddStamina.Config",
	[UIWindowNames.UIPuzzleMonsterRank] = "UI.UIPuzzleMonster.UIPuzzleMonsterRank.Config",
	[UIWindowNames.UIPuzzleMonsterList] = "UI.UIPuzzleMonster.UIPuzzleMonsterList.Config",
	[UIWindowNames.UIPuzzleMonsterCreate] = "UI.UIPuzzleMonster.UIPuzzleMonsterCreate.Config",

	[UIWindowNames.UIHeroEntrust] = "UI.UIHeroEntrust.Config",

	[UIWindowNames.UIArenaReward] = "UI.UIArenaReward.Config",
	[UIWindowNames.UIGuideNoNpcTalk] = "UI.UIGuideNoNpcTalk.Config",
	[UIWindowNames.UIBattlePassBuy] = "UI.UIBattlePassBuy.Config",
	[UIWindowNames.UIBattlePassGiftPackagePopUp] = "UI.UIBattlePassGiftPackagePopUp.Config",
	[UIWindowNames.UIHeroBattlePassPop] = "UI.UIHeroBattlePassPop.Config",
	[UIWindowNames.UIHeroResetShop] = "UI.UIHeroResetShop.Config",
	[UIWindowNames.UIHeroExchange] = "UI.UIHeroExchange.Config",
	[UIWindowNames.UIShowFakeNewHero] = "UI.UIShowFakeNewHero.Config",
	[UIWindowNames.UIHeroBountyTask] = "UI.UIHeroBountyTask.Config",
	[UIWindowNames.UIHeroBountyMain] = "UI.UIHeroBountyMain.Config",
	[UIWindowNames.UIGuideLoadMask] = "UI.UIGuideLoadMask.Config",
	[UIWindowNames.UIGuideLoadBlackMask] = "UI.UIGuideLoadBlackMask.Config",
	[UIWindowNames.UIPersonalArmsConvert] = "UI.UIPersonalArmsConvert.Config",
	[UIWindowNames.UIHeroSkillAdvanceSuccess] = "UI.UIHero2.UIHeroSkillAdvanceSuccess.Config",

	[UIWindowNames.UIGolloesCardsRP] = "UI.UIGolloesCardsRP.Config",
	[UIWindowNames.UIGolloesCardsExShop] = "UI.UIGolloesCardsExShop.Config",
	[UIWindowNames.UIGolloesCardsRank] = "UI.UIGolloesCardsRank.Config",

	[UIWindowNames.UIArmyUnlock] = "UI.UIArmyUnlock.Config",
	[UIWindowNames.UICrossServerList] = "UI.UICrossServerList.Config",
	[UIWindowNames.UICheckServer] = "UI.UICheckServer.Config",
	[UIWindowNames.UIIDCardAuthenticate] = "UI.UIIDCardAuthenticate.Config",
	[UIWindowNames.UIPveActMain] = "UI.UIPveAct.UIPveActMain.Config",
	[UIWindowNames.UIPveActRank] = "UI.UIPveAct.UIPveActRank.Config",
	[UIWindowNames.UITimelineJump] = "UI.UITimelineJump.Config",
	[UIWindowNames.UIHeadTalk] = "UI.UIHeadTalk.Config",
	[UIWindowNames.UIPing] = "UI.UISetting.UIPing.Config",
	[UIWindowNames.UIAlCompeteTips] = "UI.UIAlCompeteTips.Config",
	[UIWindowNames.UIAllianceCompeteMemberScore] = "UI.UIAllianceCompeteMemberScore.Config",
	[UIWindowNames.UIIDCardDesTips] = "UI.UIIDCardDesTips.Config",
	[UIWindowNames.UIIDCardAgeTips] = "UI.UIIDCardAgeTips.Config",
	[UIWindowNames.UIHeroDebrisExchange] = "UI.UIHero2.UIHeroDebrisExchange.Config",
	[UIWindowNames.UIHeroDecompose] = "UI.UIHero2.UIHeroDecompose.Config",
	[UIWindowNames.UIHeroDecomposeBatch] = "UI.UIHero2.UIHeroDecomposeBatch.Config",
	[UIWindowNames.UIHeroBag] = "UI.UIHero2.UIHeroBag.Config",
	[UIWindowNames.UISelectArmy] = "UI.UISelectArmy.Config",
	[UIWindowNames.UIMainNotice] = "UI.UIMainNotice.Config",
	[UIWindowNames.UIActivityNoticeTip] = "UI.UIActivityNoticeTip.Config",
	[UIWindowNames.UIBuildUpgradeSuccess] = "UI.UIBuildUpgradeSuccess.Config",
--	[UIWindowNames.UIReachLimit] = "UI.UIReachLimit.Config",
	[UIWindowNames.UIBlackHoleMask] = "UI.UIBlackHoleMask.Config",
	[UIWindowNames.UIPathArrow] = "UI.UIPathArrow.Config",
	[UIWindowNames.UICampBonus] = "UI.UICampBonus.Config",
	[UIWindowNames.UIDeadArmyRecord] = "UI.UIDeadArmyRecord.Config",
	[UIWindowNames.UIPlayerGenderSelect] = "Slg.UI.UIPlayerGenderSelect.Config",
	--[UIWindowNames.UIEquipmentMain] = "UI.UIEquipment.UIEquipmentMain.Config",
	--[UIWindowNames.EquipmentBag] = "UI.UIEquipment.EquipmentBag.Config",
	--[UIWindowNames.UIEquipmentInfo] = "UI.UIEquipment.UIEquipmentInfo.Config",
	--[UIWindowNames.UIEquipmentUpgrade] = "UI.UIEquipment.UIEquipmentUpgrade.Config",
	--[UIWindowNames.UIEquipmentSuitInfo] = "UI.UIEquipment.UIEquipmentSuitInfo.Config",
	--[UIWindowNames.UIEquipmentChoose] = "UI.UIEquipment.UIEquipmentChoose.Config",
	--[UIWindowNames.UIEquipmentSuitQualityIntro] = "UI.UIEquipment.UIEquipmentSuitQualityIntro.Config",
	--[UIWindowNames.UIEquipmentAdvanceSuccess] = "UI.UIEquipment.UIEquipmentAdvanceSuccess.Config",
	
	[UIWindowNames.UIStoryResult] = "UI.UIStory.UIStoryResult.Config",
	[UIWindowNames.UIStoryHangup] = "UI.UIStory.UIStoryHangup.Config",
	[UIWindowNames.UIStoryHangupChange] = "UI.UIStory.UIStoryHangupChange.Config",
	[UIWindowNames.UIStoryRank] = "UI.UIStory.UIStoryRank.Config",
	[UIWindowNames.UIStorySelectLevel] = "UI.UIStory.UIStorySelectLevel.Config",

	[UIWindowNames.UIAllianceWarPersonalList] = "Slg.UI.UIAlliance.UIAllianceWarPersonalList.Config",
	[UIWindowNames.UIBlackKnightRank] = "UI.UIBlackKnightRank.Config",
	[UIWindowNames.UIBlackKnightInfo] = "UI.UIBlackKnightInfo.Config",
	[UIWindowNames.UIBlackKnighReservation] = "UI.UIBlackKnighReservation.Config",
	
	[UIWindowNames.UI_SUBuildRepair] = "UI.UIBuildRepair.Config",
	[UIWindowNames.UI_VideoPlayer] = "UI.UIVideoLayer.Config",

	[UIWindowNames.UI_GetRewardTips] = "UI.UI_GetRewardTips.Config",
	[UIWindowNames.UI_GuideFullScreenDialog] = "UI.UIGuide.UI_GuideFullScreenDialog.Config",
	[UIWindowNames.UI_DayNight] = "UI.UIGuide.UI_DayNight.Config",
	[UIWindowNames.UI_GuideMoviePrologue] = "UI.UIGuide.UI_GuideMoviePrologue.Config",
	[UIWindowNames.UIPVELevelLoading] = "UI.UIPVE.UIPVELevelLoading.Config",
	[UIWindowNames.UI_BuildUseFullScreenDialog] = "UI.UIGuide.UI_BuildUseFullScreenDialog.Config",
	[UIWindowNames.UIFullScreenBlackBG] = "UI.UIPVE.UIFullScreenBlackBG.Config",
	[UIWindowNames.UIGuideIntroBubble] = "UI.UIGuide.UIGuideIntroBubble.Config",
	[UIWindowNames.UIGuideIntroBubble1] = "UI.UIGuide.UIGuideIntroBubble1.Config",
	[UIWindowNames.UIActivityTip]= "UI.UIActivityTip.Config",
	[UIWindowNames.UITaskPromptTips] = "UI.UITaskPromptTips.Config",
--	[UIWindowNames.UIHeroMedalShop] = "UI.UIHeroMedalShop.Config",
	[UIWindowNames.UI_PicGuide] = "UI.UIGuide.UI_PicGuide.Config",
	[UIWindowNames.UI_PicGuideList] = "UI.UIGuide.UI_PicGuideList.Config",
	[UIWindowNames.UIPVELevelReward_SU] = "UI.UIPVE.UIPVELevelReward_SU.Config",
	[UIWindowNames.UIWorldMarchDetail] = "UI.UIWorldMarchDetail.Config",
	[UIWindowNames.UIWorldMultiSelect] = "UI.UIWorldMultiSelect.Config",
	[UIWindowNames.UIPVEMonsterToLevel] = "UI.UIPVE.UIPVEMonsterToLevel.Config",
	[UIWindowNames.UINewBuildUpgrade] = "UI.SU_UINewBuildUpgrade.Config",
	[UIWindowNames.UIDecorationMain] = "UI.UIDecoration.UIDecorationMain.Config",
	[UIWindowNames.UIDecorateUnlock] = "UI.UIDecoration.UIDecorateUnlock.Config",
	[UIWindowNames.UIDecorationEffect] = "UI.UIDecoration.UIDecorationEffect.Config",
	[UIWindowNames.UIDecorationGift] = "UI.UIDecorationGift.Config",
	[UIWindowNames.UIConsumeItem] = "UI.UIConsumeItem.Config",
	[UIWindowNames.UIHeroLackTips] = "UI.UIHeroLackTips.Config",
	[UIWindowNames.UIAllianceMerge] = "UI.UIAllianceMerge.Config",
	[UIWindowNames.UIPVEHeroBossFightStart] = "UI.UIPVE.UIPVEHeroBossFightStart.Config",
	[UIWindowNames.UILensBlackEdge] = "UI.UILensBlackEdge.Config",
	[UIWindowNames.UICameraInfo] = "UI.UICameraInfo.Config",
	[UIWindowNames.UIScrollPackNew] = "UI.UIScrollPackNew.Config",
	[UIWindowNames.UISubtitle] = "UI.UISubtitle.Config",
	[UIWindowNames.UIFadeBlack] = "UI.UIFadeBlack.Config",
	[UIWindowNames.UISevenLogin] = "UI.UISevenLogin.Config",
	[UIWindowNames.UIRewardBox] = "UI.UIRewardBox.Config",
	[UIWindowNames.UIScreenCenterTips] = "UI.UIScreenCenterTips.Config",
	[UIWindowNames.SevenDayBox] = "UI.SevenDayBox.Config",
	[UIWindowNames.UIBuildUpUnlock] = "UI.UIBuildUpUnlock.Config",

	[UIWindowNames.UIParkourBattleMain] = "UI.UIParkour.MainUI.Config",
	[UIWindowNames.UIParkourBattleWin] = "UI.UIParkour.WinUI.Config",
	[UIWindowNames.UIParkourBattleLose] = "UI.UIParkour.LoseUI.Config",
	[UIWindowNames.UIParkourMap] = "UI.UIParkour.MapUI.Config",
	[UIWindowNames.UIParkourFormation] = "UI.UIParkour.FormationUI.Config",
	[UIWindowNames.UIParkourThreeChoices] = "UI.UIParkour.ThreeChoicesUI.Config",
	[UIWindowNames.UIBarrelGetStronger] = "UI.UIParkour.GetStronger.Config",
	[UIWindowNames.UILetterBoxing] = "UI.UIParkour.UILetterBoxing.Config",
	[UIWindowNames.UIHeroPreviewSkillWindow] = "UI.UIHero2.UIHeroPreviewSkillWindow.Config",
	[UIWindowNames.UIAircraftPreviewSkillWindow] = "UI.UIAircraftPreviewSkillWindow.Config",
	[UIWindowNames.UIAircraftSkillTip] = "UI.UIAircraftSkillTip.Config",
	[UIWindowNames.UIAircraftGradingTip] = "UI.UIAircraftGradingTip.Config",
	[UIWindowNames.UIAircraftUpgrade] = "UI.UIAircraftUpgrade.Config",
	[UIWindowNames.UIAircraftRank] = "UI.UIAircraftRank.Config",
	[UIWindowNames.UIBarrelBoxRewardGet] = "UI.UIBarrelBoxRewardGet.Config",
	[UIWindowNames.UIBarrelHeroFightTip] = "UI.UIParkour.UIBarrelHeroFightTip.Config",
	[UIWindowNames.UIBarrelCarFightTip] = "UI.UIParkour.UIBarrelHeroFightTip.CarConfig",

	[UIWindowNames.UIZombieBattleMain] = "UI.UIZombieBattle.Config",
	[UIWindowNames.UIDrakeBossUseItem] = "UI.UIDrakeBossUseItem.Config",
	[UIWindowNames.UIDrakeBossRewardTip] = "UI.UIDrakeBossRewardTip.Config",
	[UIWindowNames.UIDrakeBossAutoJoinTips] = "UI.UIDrakeBossAutoJoinTips.Config",

	[UIWindowNames.UILuckyRollRank] = "UI.UILuckyRollRank.Config",
	[UIWindowNames.UILuckyRollGiftPackList] = "UI.UILuckyRollGiftPackList.Config",
	[UIWindowNames.UILuckyRollTip] = "UI.UILuckyRollTip.Config",
	[UIWindowNames.UIPoliceInsigniaShow] = "UI.UIPoliceInsigniaShow.Config",
	[UIWindowNames.UIBarterShopNoticeTask] = "UI.UIBarterShopNoticeTask.Config",

	[UIWindowNames.UIUnlockCompetition] = "UI.UIUnlockCompetition.Config",
	[UIWindowNames.UITimeCompeRank] = "UI.UITimeCompeRank.Config",
	[UIWindowNames.UITimeCompePop] = "UI.UITimeCompePop.Config",
	[UIWindowNames.UIWorldBossRankPop] = "UI.UIWorldBossRankPop.Config",
	[UIWindowNames.UIArenaRankPop] = "UI.UIArenaRankPop.Config",
	[UIWindowNames.UITimelineMask] = "UI.UITimelineMask.Config",
	[UIWindowNames.UITimelineMaskNoInput] = "UI.UITimelineMaskNoInput.Config",
	[UIWindowNames.UIDetectNpc] = "UI.UIRadarCenter.UIDetectNpc.Config",
	[UIWindowNames.UIFormationDispatchTask] = "UI.UIFormation.UIFormationDispatchTask.Config",
	[UIWindowNames.UIFormationDispatchTip] = "UI.UIFormation.UIFormationDispatchTip.Config",
	[UIWindowNames.UIHeroTrialReward] = "UI.UIHeroTrialReward.Config",
	[UIWindowNames.UILWDispatchTaskLog] = "UI.UILWDispatchTaskLog.Config",
	[UIWindowNames.UIMedalGet] = "UI.UIMedalGet.Config",
	
	[UIWindowNames.UIGovernmentMain] = "UI.UIGovernment.UIGovernmentMain.Config",
	[UIWindowNames.UIThronePresidentHonour] = "UI.UIGovernment.UIThronePresidentHonour.Config",
	[UIWindowNames.UIThronePresidentReward] = "UI.UIGovernment.UIThronePresidentReward.Config",
	[UIWindowNames.UIGovernmentInfo] = "UI.UIGovernment.UIGovernmentInfo.Config",
	[UIWindowNames.UIThroneRewardSelectMember] = "UI.UIGovernment.UIThroneRewardSelectMember.Config",
	[UIWindowNames.ThroneRecordView] = "Slg.UI.UIThroneRecord.Config",
	[UIWindowNames.UITowerRecord] = "Slg.UI.UITowerRecord.Config",

	[UIWindowNames.UIHeroEquip] = "UI.UIHeroEquip.Config",
	[UIWindowNames.UIHeroEquipInfo] = "UI.UIHeroEquipInfo.Config",
	[UIWindowNames.UIHeroEquipReplace] = "UI.UIHeroEquipReplace.Config",
	[UIWindowNames.UIHeroEquipPromotion] = "UI.UIHeroEquipPromotion.Config",
	[UIWindowNames.UIHeroSPEquip] = "UI.UIHeroSPEquip.Config",
	[UIWindowNames.UIHeroSPEquipSuccess] = "UI.UIHeroSPEquipSuccess.Config",
	[UIWindowNames.UIHeroEquipEvolutionSuccess] = "UI.UIHeroEquipEvolutionSuccess.Config",
	[UIWindowNames.UIHeroEquipRank] = "UI.UIHeroEquipRank.Config",
	[UIWindowNames.UIHeroEquipTips] = "UI.UIHeroEquipTips.Config",

	[UIWindowNames.UIBPSelectPack] = "UI.UIBPSelectPack.Config",

	[UIWindowNames.UIStrongCommanderTask] = "UI.UIStrongCommander.UIStrongCommanderTask.Config",
	[UIWindowNames.UIStrongCommanderRank] = "UI.UIStrongCommander.UIStrongCommanderRank.Config",

	[UIWindowNames.UICommonHeadTip] = "UI.UICommonHeadTip.Config",
	-- 火车的UI
	[UIWindowNames.UILWTrainDeparture] =  "UI.UILWRailway.UILWTrainDeparture.Config",
	[UIWindowNames.UILWTrainList] =  "UI.UILWRailway.UILWTrainList.Config",
	[UIWindowNames.UILWTrainDetail] =  "UI.UILWRailway.UILWTrainDetail.Config",
	[UIWindowNames.UILWTrainReward] =  "UI.UILWRailway.UILWTrainReward.Config",
	[UIWindowNames.UILWTrainScene] =  "UI.UILWRailway.UILWTrainScene.Config",
	[UIWindowNames.UITrainDriverInvite] =  "UI.UILWRailway.UITrainDriverInvite.Config",
	[UIWindowNames.UITrainPrepare] =  "UI.UILWRailway.UITrainPrepare.Config",
	[UIWindowNames.UITrainBuy] =  "UI.UILWRailway.UITrainBuy.Config",
	[UIWindowNames.UITrainInfo] =  "UI.UILWRailway.UITrainInfo.Config",
	[UIWindowNames.UITrainBattleRecord] =  "UI.UILWRailway.UITrainBattleRecord.Config",

	[UIWindowNames.UIRankNew] = "UI.UIRank.UIRankNew.Config",

	--纵向形式的奖励清单
	[UIWindowNames.UIRewardVListTip] = "UI.UIRewardVListTip.Config",

	-- 
	[UIWindowNames.UILoPowerLack] = "UI.UILandingOperation.UILOPowerLack.Config",
	[UIWindowNames.UILoMap] = "UI.UILandingOperation.UILOMap.Config",
	[UIWindowNames.UILOShop] = "UI.UILandingOperation.UILOShop.Config",
	[UIWindowNames.UILOResult] = "UI.UILandingOperation.UILOResult.Config",
	
	[UIWindowNames.UIDetectHelpMessageBar] = "UI.UIDetectHelpMessageBar.Config",
	[UIWindowNames.UIBossDamageRecord] = "UI.UIBossDamageRecord.Config",
	
	-- 账号删除UI
	[UIWindowNames.UIDeleteAccountIntro] = "UI.UISetting.UIDeleteAccountIntro.Config",
	[UIWindowNames.UIDeleteAccountPrivacy] = "UI.UISetting.UIDeleteAccountPrivacy.Config",
	[UIWindowNames.UIDeleteAccountConfirm] = "UI.UISetting.UIDeleteAccountConfirm.Config",
	[UIWindowNames.UIDeleteAccountNotice] = "UI.UISetting.UIDeleteAccountNotice.Config",
	[UIWindowNames.UIAccountDeleteVerify] = "UI.UIAccount2.UIAccountDeleteVerify.Config",
	[UIWindowNames.CardGetReward] = "UI.UIGiftPackage.Component.WeekCard.CardGetReward.Config",
	
	[UIWindowNames.UIJeepAdventureMain] = "UI.UIJeepAdventure.UIJeepAdventureMain.Config",
	[UIWindowNames.UIJeepAdventureTask] = "UI.UIJeepAdventure.UIJeepAdventureTask.Config",
	
	[UIWindowNames.UIResourceReplenish] = "UI.UIResourceReplenish.Config",
	[UIWindowNames.UIPersonalArmsReward] = "UI.UIPersonalArmsReward.Config",
	
	[UIWindowNames.UIRuinsReward] = "UI.UIRuinsReward.Config",
	[UIWindowNames.UIRuinRecord] = "Slg.UI.UIRuinRecord.Config",
	[UIWindowNames.UIRuinsRewardPreview] = "UI.UIRuinsRewardPreview.Config",
	[UIWindowNames.UIRuinRewardDetail] = "UI.UIRuinRewardDetail.Config",
	[UIWindowNames.UIRuinsRankDetail] = "UI.UIRuinsRankDetail.Config",
	[UIWindowNames.UIRuinsHistoryRecord] = "UI.UIRuinsHistoryRecord.Config",
	
	[UIWindowNames.UISeasonAllianceRewardDisplayDetail] = "UI.UISeason.UISeasonAllianceRewardDisplayDetail.Config",
	[UIWindowNames.UISeasonAllianceRewardDisplayMain] = "UI.UISeason.UISeasonAllianceRewardDisplayMain.Config",
	
	[UIWindowNames.UIAllianceClearMember] = "Slg.UI.UIAlliance.UIAllianceClearMember.Config",
	
	[UIWindowNames.UIAllianceCityBar] = "UI.UIAllianceCityBar.Config",
	[UIWindowNames.UICrossDisconnect] = "UI.UICrossDisconnect.Config",
	[UIWindowNames.UICampBonusMailTip] = "Slg.UI.UIMailNew.UICampBonusMailTip.Config",

	[UIWindowNames.UIGuideShowDogItem] = "UI.UIGuideShowDogItem.Config",
	
	--爱情通讯
	[UIWindowNames.UILoveNewsletter] = "UI.UILoveNewsletter.Config",
	[UIWindowNames.UILoveNewsletterFilter] = "UI.UILoveNewsletterFilter.Config",
	[UIWindowNames.UILoveNewsletterMM] = "UI.UILoveNewsletterMM.Config",
	
	[UIWindowNames.UIMailSoldierTips] = "Slg.UI.UIMailNew.UIMailSoldierTips.Config",
	[UIWindowNames.UIBuildQueueList] = "UI.UIBuildQueueList.Config",
	[UIWindowNames.UIMonthMsgPass] = "UI.UIMonthMsgPass.Config",
	[UIWindowNames.UIChoseWeekCard] = "UI.UIChoseWeekCard.Config",
	[UIWindowNames.UIPointOrigin] = "UI.UIPointOrigin.Config",

	[UIWindowNames.UISevenDay] = "UI.UISevenDay.Config",
	[UIWindowNames.UISevenDayNew] = "UI.UISevenDayNew.Config",
	[UIWindowNames.UISevenDayNewGuide] = "UI.UISevenDayNewGuide.Config",
	[UIWindowNames.SevenDayBoxNew] = "UI.SevenDayBoxNew.Config",
	
	[UIWindowNames.UIPlaceWorldBuild] = "UI.UIPlaceWorldBuild.Config",
	[UIWindowNames.UIAllianceBuildingCollect] = "UI.UIAllianceBuildingCollect.Config",

	[UIWindowNames.UICompletePoliceStationUpgrade] = "UI.UICompletePoliceStationUpgrade.Config",
	[UIWindowNames.ThroneRewardView] = "UI.UIThroneReward.Config",
	[UIWindowNames.ThroneRankView] = "UI.UIThroneRanking.Config",
	[UIWindowNames.ThroneDefendView] = "UI.ThroneDefend.Config",
	[UIWindowNames.UIThroneSendList] = "UI.UIGovernment.UIThroneSendList.Config",
	[UIWindowNames.ThronePopupView] = "UI.ThronePopup.Config",
	
	[UIWindowNames.UIAircraftMain] = "UI.UIAircraftMain.Config",
	[UIWindowNames.UIAircraftMainPreview] = "UI.UIAircraftMainPreview.Config",
	
	[UIWindowNames.UICrossDisconnect] = "UI.UICrossDisconnect.Config",
	
	[UIWindowNames.UIBlackGradientWindow] = "UI.UIBlackGradientWindow.Config",
	[UIWindowNames.UIGuideWaitToBuildFence] = "UI.UIGuideWaitToBuildFence.Config",
	
	[UIWindowNames.UIPositionAppointSearch] = "UI.UIGovernment.UIPositionAppointSearch.Config",
	[UIWindowNames.UICompletePoliceStation] = "UI.UICompletePoliceStation.Config",
	[UIWindowNames.UIBossRunAway] = "UI.UIBossRunAway.Config",
	[UIWindowNames.UIHeroEquipStrength] ="UI.UIHeroEquipStrength.Config",
	[UIWindowNames.UIGuideShowDogItem] = "UI.UIGuideShowDogItem.Config",
	
	[UIWindowNames.UIGetPolicewoman] = "UI.UIGetPolicewoman.Config",
	[UIWindowNames.UIGuideGurtain] = "UI.UIGuideGurtain.Config",
	--爱情通讯
	[UIWindowNames.UILoveNewsletter] = "UI.UILoveNewsletter.Config",
	[UIWindowNames.UILoveNewsletterFilter] = "UI.UILoveNewsletterFilter.Config",
	[UIWindowNames.UILoveNewsletterMM] = "UI.UILoveNewsletterMM.Config",

	[UIWindowNames.UISettingDebugReward] = "UI.UISetting.UISettingDebugReward.Config",
	
	-- 英雄小人
	[UIWindowNames.UISmallPeopleBox] = "UI.UIHseroSmallPeople.UISmallPeopleBox.Config",
	[UIWindowNames.UISmallPeopleSurvivors] = "UI.UIHseroSmallPeople.UISmallPeopleSurvivors.Config",
	[UIWindowNames.UISmallPeopleVisit] = "UI.UIHseroSmallPeople.UISmallPeopleVisit.Config",
	[UIWindowNames.UISmallPeopleTask] = "UI.UIHseroSmallPeople.UISmallPeopleTask.Config",
	[UIWindowNames.UISmallPeopleBuildInfo] = "UI.UIHseroSmallPeople.UISmallPeopleBuildInfo.Config",
	[UIWindowNames.UISmallPeopleSurvivorsList] = "UI.UIHseroSmallPeople.UISmallPeopleSurvivorsList.Config",
	[UIWindowNames.UISmallPeopleReplaceConfirm] = "UI.UIHseroSmallPeople.UISmallPeopleReplaceConfirm.Config",
	[UIWindowNames.UISmallPeopleBook] = "UI.UIHseroSmallPeople.UISmallPeopleBook.Config",
	
	[UIWindowNames.UIHeroEquipPromotionSelect] = "UI.UIHeroEquipPromotionSelect.Config",
	[UIWindowNames.UICompletePoliceStationUpgrade] = "UI.UICompletePoliceStationUpgrade.Config",
	
	[UIWindowNames.UINewNvJingBuyResult] = "UI.UIFirstPayNewNvJing.SubView.Config",
	
	[UIWindowNames.UIRadarCloud] = "UI.UIRadarCloud.Config",
	[UIWindowNames.UIPresidentAppoint] = "UI.UIGovernment.UIPresidentAppoint.Config",

	[UIWindowNames.UIDonateSoldierReward] = "UI.UIDonateSoldierReward.Config",
	[UIWindowNames.UIDonateSoldierSelect] = "UI.UIDonateSoldierSelect.Config",
	[UIWindowNames.UIDonateSoldierOpenReward] = "UI.UIDonateSoldierOpenReward.Config",
	[UIWindowNames.UIDonateSoldierInfo] = "UI.UIDonateSoldierInfo.Config",
	[UIWindowNames.UIDonateSoldierRank] = "UI.UIDonateSoldierRank.Config",
	[UIWindowNames.UIDonateSoldierReservation] = "UI.UIDonateSoldierReservation.Config",

	[UIWindowNames.UIPhotoWall] = "UI.UIPhotoWall.Config",
	[UIWindowNames.UIPhotoWallDetail] = "UI.UIPhotoWallDetail.Config",
	[UIWindowNames.UIPhotoWallBox] = "UI.UIPhotoWallBox.Config",
	----------------------------------------------------------------------------------------------------------------
	-- 下面是分支的，主干的加到上面
	

	[UIWindowNames.UIActGiftBoxReward] = "UI.UIActGiftBox.UIActGiftBoxReward.Config",
	[UIWindowNames.UIActGiftBoxOpen] = "UI.UIActGiftBox.UIActGiftBoxOpen.Config",
	[UIWindowNames.UIGiftBoxRank] = "UI.UIGiftBoxRank.Config",
	[UIWindowNames.UIGiftBoxProgressReward] = "UI.UIGiftBoxProgressReward.Config",
	
	[UIWindowNames.UIScienceBuildList] = "UI.UIScienceBuildList.Config",
	
	[UIWindowNames.UICommonTextTips] = "UI.UICommonTextTips.Config",

	[UIWindowNames.UIGiftVipPackage] = "UI.UIGiftVipPackage.Config",
	[UIWindowNames.UICrossWonderRank] = "UI.UICrossWonder.UICrossWonderRank.Config",
	[UIWindowNames.UICrossWonderReward] = "UI.UICrossWonder.UICrossWonderReward.Config",
	[UIWindowNames.UICrossWonderRule] = "UI.UICrossWonder.UICrossWonderRule.Config",
	[UIWindowNames.UICrossWonderTarget] = "UI.UICrossWonder.UICrossWonderTarget.Config",
	[UIWindowNames.UIDragonBattleScore] = "UI.UIDragonBattleScore.Config",
	[UIWindowNames.UIDragonMark] = "UI.UIDragonMark.Config",
	[UIWindowNames.UIDragonCommand] = "UI.UIDragonCommand.Config",
	[UIWindowNames.UIDragonMoveCityConform] = "UI.UIDragonMoveCityConform.Config",
	[UIWindowNames.UICrossWonderAct] = "UI.UICrossWonder.UICrossWonderAct.Config",
	[UIWindowNames.GodzillaGift] = "UI.GodzillaGift.Config",
	[UIWindowNames.UICrossWonderActRankList] = "UI.UICrossWonder.UICrossWonderActRankList.Config",
	[UIWindowNames.UICrossWonderHistory] = "UI.UICrossWonder.UICrossWonderHistory.Config",
	[UIWindowNames.UICrossWonderMoveCityTips] = "UI.UICrossWonder.UICrossWonderMoveCityTips.Config",
	[UIWindowNames.UIHeroDressList] = "UI.UIHero2.UIHeroDress.UIHeroDressList.Config",
	[UIWindowNames.UIHeroDressFilter] = "UI.UIHero2.UIHeroDress.UIHeroDressFilter.Config",
	[UIWindowNames.UIGetDress] = "UI.UIHero2.UIHeroDress.UIGetDress.Config",
	[UIWindowNames.UISkinShop] = "UI.UISkinShop.Config",
	
	
	[UIWindowNames.UIHeroIntensify] = "UI.UIHeroIntensify.Config",
	[UIWindowNames.UIHeroIntensifyInfo] = "UI.UIHeroIntensifyInfo.Config",
	[UIWindowNames.UIHeroIntensifyTip] = "UI.UIHeroIntensifyTip.Config",
	
	[UIWindowNames.UIRobotWarsRule] = "UI.UIRobotWarsRule.Config",
	[UIWindowNames.UIDailyPackageChangePanel] = "UI.UIDailyPackageChangePanel.Config",
	
	[UIWindowNames.UIGiftBoxPackageList] = "UI.UIActGiftBox.UIGiftBoxPackageList.Config",
	
	[UIWindowNames.UIBuildTimeOfChange] = "UI.UIBuildTimeOfChange.Config",
	[UIWindowNames.UILoveNewsletterUnlockPic] = "UI.UILoveNewsletterUnlockPic.Config",
	
	[UIWindowNames.DispatchOneKey] = "UI.UIActivityCenterTable.Component.DispatchTask.DispatchOneKey.Config",
	[UIWindowNames.DispatchRefreshBox] = "UI.UIActivityCenterTable.Component.DispatchTask.DispatchRefreshBox.Config",
	[UIWindowNames.DispatchStealDescBox] = "UI.UIActivityCenterTable.Component.DispatchTask.DispatchStealDescBox.Config",
	[UIWindowNames.UIMineCaveScoreTip] = "UI.UIMineCaveScoreTip.Config",

	[UIWindowNames.UIGiftPackageRewardSelect] = "UI.UIGiftPackageRewardSelect.Config",
	[UIWindowNames.UIHeroSkinUseItem] = "UI.UIHero2.UIHeroSkinUseItem.Config",
	[UIWindowNames.UIRedenvelopeSelectView] = "UI.UIActivityCenterTable.Component.RedEnvelope.RedEnvelopeSelect.Config",
	[UIWindowNames.UIRedenvelopeSuccess] = "UI.UIActivityCenterTable.Component.RedEnvelope.RedEnvelopeSuccess.Config",
	
	[UIWindowNames.UIWorldNoSelectable] = "UI.UIWorldNoSelectable.Config",
	
	[UIWindowNames.UIBarrelHeroBottomInfo] = "UI.UIParkour.UIBarrelHeroBottomInfo.Config",
	[UIWindowNames.UILuckyShopPreview] = "UI.UILuckyShopPreview.Config",
	
	[UIWindowNames.UIGiftPackageSelfSelect] = "UI.UIGiftPackageSelfSelect.Config",
	--赛季
	[UIWindowNames.UISeasonGroundManage] = "Slg.UI.UISeason.UISeasonGroundManage.Config", --地块管理
	[UIWindowNames.UISeasonForceStageReward] = "UI.UISeason.UISeasonForceStageReward.Config", --地块管理
	[UIWindowNames.UISeasonHint] = "UI.UISeasonHint.Config", 
	[UIWindowNames.UIGloryGroup] = "UI.UIGlory.UIGloryGroup.Config",
	[UIWindowNames.UIDesertForceList] = "UI.UISeason.UIDesertForceList.Config",
	[UIWindowNames.UISeasonForceRewardDetail] = "UI.UISeason.UISeasonForceRewardDetail.Config",
	[UIWindowNames.UISeasonForceLackView] = "UI.UISeason.UISeasonForceLackView.Config",
	[UIWindowNames.UISeasonHeroPreview] = "UI.UISeasonHeroPreview.Config",
	
	[UIWindowNames.UIDrakaBoss2Pre] = "UI.UIActivityCenterTable.Component.UIDrakaBoss2.UIDrakaBoss2Pre.Config",	
	[UIWindowNames.UIAircraftMainTip] = "UI.UIAircraftMainTip.Config",
	[UIWindowNames.UISeasonGlorySweep] = "Slg.UI.UISeason.UISeasonGlorySweep.Config",
	[UIWindowNames.UISeasonWeek] = "Slg.UI.UISeasonWeek.Config",
	[UIWindowNames.UIGloryDeclare] = "UI.UIGlory.UIGloryDeclare.Config",
	[UIWindowNames.UIGloryAllianceDeclareRecord] = "UI.UIGlory.UIGloryAllianceDeclareRecord.Config",
	[UIWindowNames.UIGloryInfo] = "UI.UIGlory.UIGloryInfo.Config",
	[UIWindowNames.UIGloryAllianceSetTruce] = "Slg.UI.UIGlory.UIGloryAllianceSetTruce.Config",
	[UIWindowNames.UIGloryMatch] = "Slg.UI.UIGlory.UIGloryMatch.Config",
	[UIWindowNames.UIGloryRankReward] = "UI.UIGlory.UIGloryRankReward.Config",
	
	[UIWindowNames.UIPVETowerClimbJump] = "UI.UIPVE.UIPVETowerClimbJump.Config",
	[UIWindowNames.UIPVETowerClimbJumpReward] = "UI.UIPVE.UIPVETowerClimbJumpReward.Config",

	[UIWindowNames.UILike] = "UI.UILike.Config",
	[UIWindowNames.UILikeHistory] = "UI.UILike.UILikeHistory.Config",
	[UIWindowNames.UILikeMessageTips] = "UI.UILike.UILikeMessageTips.Config",
	[UIWindowNames.UILikeMessageBigTips] = "UI.UILike.UILikeMessageBigTips.Config",
	
	[UIWindowNames.UIItemBaubleTip] = "UI.UIItemBaubleTip.Config",
	[UIWindowNames.UIBaubleInfo] = "UI.UIBauble.UIBaubleInfo.Config",
	[UIWindowNames.UIBaubleUpgrade] = "UI.UIBauble.UIBaubleUpgrade.Config",
	[UIWindowNames.UIBaubleExchange] = "UI.UIBauble.UIBaubleExchange.Config",
	[UIWindowNames.UIPlaceBauble] = "UI.UIPlaceBauble.Config",
	[UIWindowNames.UICommonCountTimeMessageTip] ="UI.UICommonCountTimeMessageTip.Config",
	
	[UIWindowNames.UIGloryRule] = "UI.UIGlory.UIGloryRule.Config",
	[UIWindowNames.UIGloryDeclareWarPopTips] = "UI.UIGlory.UIGloryDeclareWarPopTips.Config",
	[UIWindowNames.UILWTrainRefreshBox] = "UI.UILWRailway.UILWTrainRefreshBox.Config",

	[UIWindowNames.UISmallPeopleFilter] = "UI.UIHseroSmallPeople.UISmallPeopleFilter.Config",
	
	[UIWindowNames.UIMineTips] = "UI.UIMinePlunder.UIMineTipsPanel.Config",
	[UIWindowNames.UIMineCountTipsPanel] = "UI.UIMinePlunder.UIMineCountTipsPanel.Config",
	[UIWindowNames.UIMinePlunderDispatch] = "UI.UIMinePlunder.UIMinePlunderDispatch.Config",
	[UIWindowNames.UIMinePlunderCrossPanel] = "UI.UIMinePlunder.UIMinePlunderCrossPanel.Config",
	[UIWindowNames.UISeasonForceTitleUnlock] = "UI.UISeasonForceTitleUnlock.Config",
	[UIWindowNames.UIWorldOccupyFirst] = "UI.UIWorldOccupyFirst.Config",
	[UIWindowNames.UILuckyShopProgressReward] = "UI.UILuckyShopProgressReward.Config",
	[UIWindowNames.UIGloryDeclareWarPop] = "UI.UIGloryDeclareWarPop.Config",
	[UIWindowNames.UISeasonGloryDeclareEndPopup] = "UI.UISeasonGloryDeclareEndPopup.Config",
	[UIWindowNames.UILuckyShopRank] = "UI.UILuckyShopRank.Config",

	[UIWindowNames.UIChatNew] ="Slg.UI.UIChatNew.Config",
	[UIWindowNames.UIChatCommanderTips] ="Slg.UI.UIChatCommanderTips.Config",
	[UIWindowNames.UIChatItemOperatorView] ="Slg.UI.UIChatItemOperatorView.Config",
	[UIWindowNames.UIChatPrivateRoomSet] = "Slg.UI.UIChatPrivateRoomSet.Config",
	[UIWindowNames.UIChatRoomSetting] ="Slg.UI.UIChatRoom.UIChatRoomSetting.Config",
	[UIWindowNames.UIChatInviteToJoin] = "Slg.UI.UIChatInviteToJoin.Config",
	[UIWindowNames.UIChatRemoveMember] ="Slg.UI.UIChatRoom.UIChatRemoveMember.Config",
	[UIWindowNames.UIChangeChatRoomName] ="Slg.UI.UIChatRoom.UIChangeChatRoomName.Config",
	[UIWindowNames.ChatAtMember] = "Slg.UI.UIChatAtMember.Config",
	[UIWindowNames.UIChatRoomPlayerTip] ="Slg.UI.UIChatRoom.UIChatRoomPlayerTip.Config",
	[UIWindowNames.UIAllianceAnnouncementEdit] = "Slg.UI.UIAlliance.UIAllianceAnnouncementEdit.Config",
	[UIWindowNames.UIPublishALAnnouncement] = "Slg.UI.UIPublishALAnnouncement.Config",
	[UIWindowNames.UIChatVoteCreat] = "Slg.UI.UIChatVoteCreat.Config",
	[UIWindowNames.UIChatSetLevelLimit] = "Slg.UI.UIChatSetLevelLimit.Config",
	[UIWindowNames.UIChatPrivateSet] ="Slg.UI.UIChatPrivateSet.Config",
	[UIWindowNames.UISettingBlock] = "Slg.UI.UIFriend.UISettingBlock.Config",
	[UIWindowNames.UIFriendApply] = "Slg.UI.UIFriend.UIFriendApply.Config",
	[UIWindowNames.UIFriendFind] = "Slg.UI.UIFriend.UIFriendFind.Config",
	[UIWindowNames.UIChangeFriendName] = "Slg.UI.UIFriend.UIChangeFriendName.Config",
	--红包
	[UIWindowNames.UIRedenvelopeView] = "Slg.UI.UIRedenvelope.UIRedenvelopeView.Config",
	[UIWindowNames.UIRedenvelopeSend] = "Slg.UI.UIRedenvelope.UIRedenvelopeSend.Config",
	[UIWindowNames.UIRedenvelopeReceive] = "Slg.UI.UIRedenvelope.UIRedenvelopeReceive.Config",
	[UIWindowNames.UIRedenvelopeReceiveInfo] = "Slg.UI.UIRedenvelope.UIRedenvelopeReceiveInfo.Config",
	[UIWindowNames.UIChatReport] = "Slg.UI.UIChatReport.Config",


	[UIWindowNames.UICommonCredit] = "Slg.UI.UICommonCredit.Config",
	[UIWindowNames.UICreditMainPanel] = "Slg.UI.UICreditMainPanel.Config",

	[UIWindowNames.UIHeroInfoEquipInfoNew] = "UI.UIHeroInfoEquipInfoNew.Config",

	[UIWindowNames.UIMsgAwait] = "Slg.UI.UIMsgAwait.Config",
	[UIWindowNames.UIChatVoteMember] = "Slg.UI.UIChatVoteMember.Config",
	[UIWindowNames.UIAllianceAnnouncementUrgentReleaseView] = "Slg.UI.UIAlliance.UIAllianceAnnouncementUrgentReleaseView.Config",


	[UIWindowNames.UIAircraftUpgradePreview] = "UI.UIAircraftUpgradePreview.Config",

	[UIWindowNames.UIAllianceWarInfoView] = "Slg.UI.UIAlliance.UIAllianceWarInfo.Config",
	[UIWindowNames.UIAllianceChangeRankName] = "Slg.UI.UIAlliance.UIAllianceChangeRankName.Config",
	[UIWindowNames.UICheckAlliance] = "Slg.UI.UIAlliance.UICheckAlliance.Config",
	[UIWindowNames.UIAllianceGiftReward] = "Slg.UI.UIAlliance.UIAllianceGiftReward.Config",
	[UIWindowNames.UIAllianceLog] = "Slg.UI.UIAlliance.UIAllianceLog.Config",
	[UIWindowNames.UIRuinCityLog] = "Slg.UI.UIRuinCityLog.Config",

	[UIWindowNames.UIAllianceKickMemberView] = "Slg.UI.UIAlliance.UIAllianceKickMember.Config", 
	[UIWindowNames.UIAllianceRankReward] = "Slg.UI.UIAlliance.UIAllianceRankReward.Config",
	[UIWindowNames.UIAllianceScienceDetail] = "Slg.UI.UIAlliance.UIAllianceScienceDetail.Config",
	[UIWindowNames.UIAllianceShopBuyPanel] = "Slg.UI.UIAlliance.UIAllianceShopBuyPanel.Config",
	[UIWindowNames.UIAllianceJoinCondition] = "Slg.UI.UIAlliance.UIAllianceJoinCondition.Config",

	[UIWindowNames.UIGloryDeclareWarLastHit] = "UI.UIGloryDeclareWarLastHit.Config",

	[UIWindowNames.UIAircraftComponInfo] = "UI.UIAircraftComponInfo.Config",
	[UIWindowNames.UIAircraftComponPartPanel] = "UI.UIAircraftComponPartPanel.Config",
	[UIWindowNames.UIAircraftComponMerge] = "UI.UIAircraftComponMerge.Config",
	[UIWindowNames.UIAircraftComponPreviewPanel] = "UI.UIAircraftComponPreviewPanel.Config",

	[UIWindowNames.UIAircraftComponPartTip] = "UI.UIAircraftComponPartTip.Config",

	[UIWindowNames.UISeasonGloryGroup] 	= "Slg.UI.UISeason.UISeasonGloryGroup.Config",
	[UIWindowNames.UISeasonRankList] 	= "Slg.UI.UIRank.UISeasonRankList.Config",
	[UIWindowNames.UISeasonGloryReward] = "Slg.UI.UISeason.UISeasonGloryReward.Config",
	[UIWindowNames.UISeasonGloryRule]  	= "Slg.UI.UISeason.UISeasonGloryRule.Config",
	[UIWindowNames.UIBattlePassPrivilege] = "Slg.UI.UIBattlePassPrivilege.Config",
	[UIWindowNames.UISeasonRank]        = "Slg.UI.UISeason.UISeasonRank.Config",
	[UIWindowNames.UISeasonMultExchange] = "Slg.UI.UISeason.UISeasonMultExchange.Config",	
	[UIWindowNames.UISeasonForceReward] = "Slg.UI.UISeason.UISeasonForceReward.Config",

	[UIWindowNames.UIBattlePassGifSeasonPopUp] = "Slg.UI.UIBattlePassGifSeasonPopUp.Config",
	
	[UIWindowNames.UIChampionBattleInvitationLetterView] = "Slg.UI.UIChampionBattleView.UIChampionBattleInvitationLetterView.Config",
	[UIWindowNames.UIChampionBattleRuleView] = "Slg.UI.UIChampionBattleView.UIChampionBattleRuleView.Config",
	-- [UIWindowNames.UIChampionBattleGuessPopup] = "Slg.UI.UIChampionBattleView.UIChampionBattleGuessPopup.Config",
	[UIWindowNames.UISeasonGloryRewardAllot] = "Slg.UI.UISeason.UISeasonGloryRewardAllot.Config",
	
	[UIWindowNames.UIChampionBattleGuessPopupView] = "Slg.UI.UIChampionBattleView.UIChampionBattleGuessPopup.Config",
	[UIWindowNames.UISeasonForceRank] = "Slg.UI.UISeason.UISeasonForceRank.Config",
	[UIWindowNames.UISeasonForceList] = "Slg.UI.UISeason.UISeasonForceList.Config",
	[UIWindowNames.UICommonResourceComfirmView] = "Slg.UI.UICommonResourceComfirm.Config",
	[UIWindowNames.UIChampionBattleBattleInfo] = "Slg.UI.UIChampionBattleView.UIChampionBattleBattleInfo.Config",
	[UIWindowNames.UIChampionBattleManifestoView] = "Slg.UI.UIChampionBattleView.UIChampionBattleManifestoView.Config",
	
	[UIWindowNames.UISeasonGlorySelectMember] = "Slg.UI.UISeason.UISeasonGlorySelectMember.Config",
	[UIWindowNames.UISeasonGloryRecord] = "Slg.UI.UISeason.UISeasonGloryRecord.Config",
	[UIWindowNames.DigTreasureGift] = "UI.DigTreasureGift.Config",
	[UIWindowNames.UISmallPeopleReward] = "UI.UISmallPeopleReward.Config",
	[UIWindowNames.MonopolyActivityDrawStageReward] = "UI.MonopolyActivity.MonopolyActivityDrawStageReward.Config",
	[UIWindowNames.ShowItemTips] = "UI.SU_ShowItemTips.Config",
	
	[UIWindowNames.UIFlipFunMainview] = 'Slg.UI.UIActFlipFun.UIFlipFunMainView.Config',
	[UIWindowNames.UIFlipFunHelpList] = 'Slg.UI.UIActFlipFun.UIFlipFunHelpList.Config',

	[UIWindowNames.UIDroppedTreasureTips] = "UI.DroppedTreasure.UIDroppedTreasureTips.Config",
	
	[UIWindowNames.UILuckyRollHeroBigRewardRank] = "UI.UILuckyRollHeroBigRewardRank.Config",
	[UIWindowNames.UILuckyRollHeroRewardPreview] = "UI.UILuckyRollHeroRewardPreview.Config",
	[UIWindowNames.UILuckyRollHeroPop]="UI.UILuckyRollHeroPop.Config",
	[UIWindowNames.UILayoutChange]="UI.UISetting.UILayoutChange.Config",
	[UIWindowNames.UIVerticalInviteList] = "UI.UIVerticalInviteList.Config",
	[UIWindowNames.UIActExchangeMainView] = 'Slg.UI.UIActExchange.UIActExchangeMainView.Config',
	[UIWindowNames.UIExchangeView] = 'Slg.UI.UIActExchange.UIExchangeView.Config',
	[UIWindowNames.UIExchangeRecordView] = 'Slg.UI.UIActExchange.UIExchangeRecordView.Config',
	[UIWindowNames.UIExchangeConfirmView] = 'Slg.UI.UIActExchange.UIExchangeConfirmView.Config',

	[UIWindowNames.UIThronePosition] = "UI.UIGovernment.UIThronePosition.Config",
	[UIWindowNames.UICrossWonderPointRank] = "UI.UICrossWonder.UICrossWonderPointRank.Config",
	[UIWindowNames.UICrossWonderBadge] = "UI.UICrossWonder.UICrossWonderBadge.Config",

	[UIWindowNames.UIVerticalInviteRulePop] = "UI.UIVerticalInviteRulePop.Config",
	[UIWindowNames.UIAllianceVerticalInviteMain] = "UI.UIAllianceVerticalInviteMain.Config",
	
	[UIWindowNames.UISceneCloud] = "UI.UISceneCloud.Config",

	[UIWindowNames.UISeasonRankReward] = "UI.UISeasonRankReward.Config",
}
--[[
local UIConfig = {}
for _,ui_module in pairs(UIModule) do 
	for _,ui_config in pairs(ui_module) do
		local ui_name = ui_config.Name
		assert(UIConfig.ui_name == nil, "Aready exsits : "..ui_name)
		if ui_config.View then
			assert(ui_config.PrefabPath ~= nil and #ui_config.PrefabPath > 0, ui_name.." PrefabPath empty.")
		end
		UIConfig[ui_name] = ui_config
	end
end
]]
return ConstClass("UIConfig", UIConfig)