--[[
-- [INPUT]: 依赖全局 ConstClass 包装为只读枚举表
-- [OUTPUT]: 对外提供只读 TimeUpEventId 枚举(如 ReqActWorldBossMarch)
-- [POS]: Updater 模块 TimeUp 体系的事件 ID 常量表，作为 TimeUpManager 分组监听的键；新增到点触发业务时在此登记枚举
-- [PROTOCOL]: 变更时更新此头部，然后检查 CLAUDE.md
--]]

---
--- Generated by LiBin
--- File name : TimeUpEventId.lua.txt
--- DateTime : 2024/10/17
--- Description :
---

---@class TimeUpEventId
local TimeUpEventId = {
    ReqActWorldBossMarch = 1, --世界BOSS活动界面，重新请求世界BOSS数据
}

return ConstClass("TimeUpEventId", TimeUpEventId)