---
--- Generated by LiBin
--- File name : TimeUpManager.lua.txt
--- DateTime : 2024/10/17
--- Description : 时间到达管理器
--- 用于解决玩家长时间停留在存有时间倒计时的界面，倒计时结束，数据未刷新产生的问题

---@class TimeUpManager
local TimeUpManager = BaseClass("TimeUpManager", Singleton)

local TimeUper = require "Framework.Updater.TimeUper"

--region base api

function TimeUpManager:__init()
    --每秒回调
    self.timeFunc = nil

    --每秒计时器
    self.timer = nil
    
    --缓冲池
    ---@type TimeUper[]
    self.pool = nil
    
    --事件集合
    ---@type table<TimeUpEventId, TimeUper[]>
    self.eventHandlers = nil
end

function TimeUpManager:__delete()
    if self.timer ~= nil then
        self.timer:Stop()
        self.timer = nil
    end
    self.timeFunc = nil

    self.pool = nil
    self.eventHandlers = nil
end

---启动
---@public
function TimeUpManager:Startup()
    Logger.Log('TimeUpManager Startup!')

    self.pool = {}
    self.eventHandlers = {}

    self.timeFunc = function()
        self:Update()
    end
    self.timer = TimerManager:GetInstance():GetTimer(1, self.timeFunc, self, false, false, false)
    self.timer:Start()
end

---释放
---@public
function TimeUpManager:Dispose()
    Logger.Log('TimeUpManager Dispose!')

    if self.timer ~= nil then
        self.timer:Stop()
        self.timer = nil
    end
    self.timeFunc = nil

    self.pool = {}
    self.eventHandlers = {}
end

---每秒刷新
---@private
function TimeUpManager:Update()
    ---获得当前时间
    local serverTime = UITimeManager:GetInstance():GetServerTime()
    local year, month, day, hour, min, sec = UITimeManager:GetInstance():GetYearAndMonthAndDayAndHourAndMinAndSec(serverTime)

    for _, handlers in pairs(self.eventHandlers) do
        for i, handler in pairs(handlers) do
            handler:Update(year, month, day, hour, min, sec)
        end
    end
end

--endregion

--region listener

---注册时间到监听(时间戳)
---@public
---@param eventId TimeUpEventId
---@param timeStamp number
---@param owner table
---@param handler function
---@param userData any
function TimeUpManager:AddListenerByTimeStamp(eventId, timeStamp, owner, handler, userData)
    local year, month, day, hour, min, sec = UITimeManager:GetInstance():GetYearAndMonthAndDayAndHourAndMinAndSec(timeStamp)
    self:AddListenerBySimple(eventId, year, month, day, hour, min, sec, owner, handler, userData)
end

---注册时间到监听
---@public
---@param eventId TimeUpEventId
---@param year number
---@param month number
---@param day number
---@param hour number
---@param min number
---@param sec number
---@param owner table
---@param handler function
---@param userData any
function TimeUpManager:AddListenerBySimple(eventId, year, month, day, hour, min, sec, owner, handler, userData)
    ---@type TimeUper
    local timeUper = self:TimeUpDequeue()
    timeUper:Init(year, month, day, hour, min, sec, owner, handler, userData, eventId)
    
    local handlers = self.eventHandlers[eventId]
    if handlers == nil then
        handlers = {}
        self.eventHandlers[eventId] = handlers
    end
    local flag = self:CheckContains(handlers, timeUper)
    if not flag then
        table.insert(handlers, timeUper)
    end
end

---@param handlers TimeUper[]
---@param timeUper TimeUper
function TimeUpManager:CheckContains(handlers, timeUper)
    for i, handler in pairs(handlers) do
        if handler.year == timeUper.year 
                and handler.month == timeUper.month 
                and handler.day == timeUper.day 
                and handler.hour == timeUper.hour 
                and handler.min == timeUper.min 
                and handler.sec == timeUper.sec
        then
            return true
        end
    end
    
    return false
end

---移除时间到监听
---@public
---@param eventId TimeUpEventId
function TimeUpManager:RemoveAllListener(eventId)
    local handlers = self.eventHandlers[eventId]
    if handlers ~= nil then
        for i = #handlers, 1, -1 do
            local timeUper = handlers[i]
            self:TimeUpEnqueue(timeUper)
            table.remove(handlers, i)
        end
        self.eventHandlers[eventId] = {}
    end
end

---@param timeUper TimeUper
function TimeUpManager:RemoveOneListener(timeUper)
    local eventId = timeUper.eventId
    local handlers = self.eventHandlers[eventId]
    if nil ~= handlers and table.count(handlers) > 0 then
        table.removebyvalue(handlers, timeUper)
    end
end

--endregion

--region pool

---入队
---@param timeUper TimeUper
function TimeUpManager:TimeUpEnqueue(timeUper)
    timeUper:Clear()
    table.insert(self.pool, timeUper)
end

---出队
---@return TimeUper
function TimeUpManager:TimeUpDequeue()
    local count = #self.pool
    if count > 0 then
        local timeUper = table.remove(self.pool, count)
        return timeUper
    else
        local timeUper = TimeUper.New()
        return timeUper
    end
end

--endregion



return TimeUpManager