---
--- Generated by LiBin
--- File name : TimeUper.lua.txt
--- DateTime : 2024/10/17
--- Description : 
---

---@class TimeUper
local TimeUper = BaseClass("TimeUper")

local TimerNextID = 1

---@protected
function TimeUper:__init()
    TimerNextID = TimerNextID + 1
    self.timer_id = TimerNextID
    
    ---@type number
    self.year = nil
    ---@type number
    self.month = nil
    ---@type number
    self.day = nil
    ---@type number
    self.hour = nil
    ---@type number
    self.min = nil
    ---@type number
    self.sec = nil
    ---@type table
    self.owner = nil
    ---@type function
    self.callback = nil
    ---@type any
    self.userData = nil
    ---@type number
    self.eventId = nil
end

---@protected
function TimeUper:__delete()
    self.timer_id = nil
    self.year = nil
    self.month = nil
    self.day = nil
    self.hour = nil
    self.min = nil
    self.sec = nil
    self.owner = nil
    self.callback = nil
    self.userData = nil
    self.eventId = nil
end

---@public
function TimeUper:Clear()
    self.year = 0
    self.month = 0
    self.day = 0
    self.hour = 0
    self.min = 0
    self.sec = 0
    self.owner = nil
    self.callback = 0
    self.userData = 0
    self.eventId = nil
end

---@public
function TimeUper:Init(year, month, day, hour, min, sec, owner, callback, userData, eventId)
    self.year = year
    self.month = month
    self.day = day
    self.hour = hour
    self.min = min
    self.sec = sec
    self.owner = owner
    self.callback = callback
    self.userData = userData
    self.eventId = eventId
end

---@public
---@param year number
---@param month number
---@param day number
---@param hour number
---@param min number
---@param sec number
function TimeUper:Update(year, month, day, hour, min, sec)
    if self.year and self.month and self.day then
        --固定时间检测
        if year == self.year and month == self.month and day == self.day 
            and hour == self.hour and min == self.min and sec == self.sec
        then
            if self.callback then
                self.callback(self.owner, self.userData)
                TimeUpManager:GetInstance():RemoveOneListener(self)
            end            
        end
    else
        --每天检测
        if hour == self.hour and min == self.min and sec == self.sec then
            if self.callback then
                self.callback(self.owner, self.userData)
                TimeUpManager:GetInstance():RemoveOneListener(self)
            end
        end
    end
end

return TimeUper