---
--- Generated by LiBin
--- File name : TimeUpEventId.lua.txt
--- DateTime : 2024/10/17
--- Description : 
---

---@class TimeUpEventId
local TimeUpEventId = {
    ReqActWorldBossMarch = 1, --世界BOSS活动界面，重新请求世界BOSS数据
}

return ConstClass("TimeUpEventId", TimeUpEventId)