---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangliheng.
--- DateTime: 2023/5/17 10:33
---
--- 

---@class ListenerHandler
local ListenerHandler = BaseClass("ListenerHandler")

function ListenerHandler:__init()
    self.__event_handlers = {}
    self.delayEvents = {}
end

function ListenerHandler:__delete()
    self:RemoveAllListeners()
    self:RemoveAllDelayEvents()
end

function ListenerHandler:AddListener(msg_name, callback)
    local bindFunc = function(...) callback(self, ...) end
    self.__event_handlers[msg_name] = bindFunc
    EventManager:GetInstance():AddListener(msg_name, bindFunc)
end

function ListenerHandler:RemoveListener(msg_name)
    local bindFunc = self.__event_handlers[msg_name]
    if not bindFunc then
		if App.IsEditor() then
        	Logger.LogError(msg_name, " not register")
		end
        return
    end
    self.__event_handlers[msg_name] = nil
    EventManager:GetInstance():RemoveListener(msg_name, bindFunc)
end

function ListenerHandler:RemoveAllListeners()
    if not self.__event_handlers then return end

    for name, bindFunc in pairs(self.__event_handlers) do
        EventManager:GetInstance():RemoveListener(name, bindFunc)
    end

    self.__event_handlers = {}
end

function ListenerHandler:AddDelayEvent(callback, delay)
    if callback == nil then
        return
    end
    
    local timer = TimerManager:GetInstance():DelayInvoke(callback, delay)
    table.insert(self.delayEvents, timer)
end

function ListenerHandler:RemoveAllDelayEvents()
    if self.delayEvents ~= nil then
        for _,v in pairs(self.delayEvents) do
            v:Stop()
        end
        
        self.delayEvents = {}
    end
end

return ListenerHandler
