---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangliheng.
--- DateTime: 5/6/2025 11:41 AM
---

local CS_UnityWebRequest = CS.UnityEngine.Networking.UnityWebRequest
local CS_UnityWebRequest_Result = CS_UnityWebRequest.Result

---@class LuaWebRequest
local LuaWebRequest = BaseClass("LuaWebRequest")

local StateType = {
    Init = 1,
    Requesting = 2,
    Success = 3,
    TimeOut = 4,
    Failed = 5,
}

function LuaWebRequest:__init(url, unityWebRequest)
    self.elapseTime = 0
    self.timeout = 9
    self.url = url
    self.error = nil

    assert(unityWebRequest ~= nil, "#LuaWebRequest# param unityWebRequest is nil!")
    self.unityWebRequest = unityWebRequest
    self.unityWebRequest:SetRequestHeader("User-Agent", HTTP_USER_AGENT)
    self:__applyCertificateHandler()
    
    self.curState = StateType.Init
end

function LuaWebRequest:__delete()
    self:DisposeRequest()
    
    self.elapseTime = nil
    self.timeout = nil
    self.url = nil
    self.error = nil
    self.curState = nil
end

--设置https证书不验证
function LuaWebRequest:__applyCertificateHandler()
    if string.startswith(self.url, "https://") then
        local hasByPassCertificate = HasCSClassMap.ByPassCertificate
        Logger.Log('#zlh# #LuaWebRequest# hasByPassCertificate : ' .. tostring(hasByPassCertificate))
        if hasByPassCertificate then
            self.unityWebRequest.certificateHandler = CS.BypassCertificate()
        else
            XPCALL(function()
                xlua.private_accessible(CS.Main.Scripts.Application.LoadingState.HttpRequest)
                self.unityWebRequest.certificateHandler = CS.Main.Scripts.Application.LoadingState.HttpRequest.WebRequestCertificateHandler()
            end)
        end
    end
end

function LuaWebRequest:SetCallback(timeoutCallback, failedCallback, successCallback)
    self.timeoutCallback = timeoutCallback
    self.failedCallback = failedCallback
    self.successCallback = successCallback
end

function LuaWebRequest:SendRequest()
    if self.unityWebRequest ~= nil then
        self.unityWebRequest:SendWebRequest()
        Logger.LogFormat("#zlh# #LuaWebRequest# : SendRequest url:{%s}", tostring(self.url))
        self.curState = StateType.Requesting
    end
end

function LuaWebRequest:DisposeRequest()
    self.timeoutCallback = nil
    self.failedCallback = nil
    self.successCallback = nil
    
    if self.unityWebRequest then
        self.unityWebRequest:Abort()
        self.unityWebRequest:Dispose()
        self.unityWebRequest = nil
    end
end

function LuaWebRequest:OnUpdate()
    if self.unityWebRequest == nil then
        return
    end

    if self.curState == StateType.Requesting then
        if self.unityWebRequest.isDone then
            if self.unityWebRequest.result ~= CS_UnityWebRequest_Result.Success then
                self:OnRequestFailure(self.unityWebRequest.error)
            else
                self:OnRequestSuccess(self.unityWebRequest.downloadHandler)
            end
        else
            self.elapseTime = self.elapseTime + Time.deltaTime
            if self.elapseTime > self.timeout then
                self:OnRequestTimeout()
            end
        end
    end
end

function LuaWebRequest:OnRequestTimeout()
    self.curState = StateType.TimeOut
    self.error = 'timeout'
    if self.timeoutCallback ~= nil then
        self.timeoutCallback(self)
    end
end

function LuaWebRequest:OnRequestFailure(error)
    self.curState = StateType.Failed
    self.error = tostring(error)
    if self.failedCallback ~= nil then
        self.failedCallback(self, error)
    end
end

function LuaWebRequest:OnRequestSuccess(downloadHandler)
    self.curState = StateType.Success
    if self.successCallback ~= nil then
        self.successCallback(self, downloadHandler)
    end
end

function LuaWebRequest.Get(url)
    local unityRequest = CS_UnityWebRequest.Get(url)
    return LuaWebRequest.New(url, unityRequest)
end

function LuaWebRequest.Post(url, wwwForm)
    local unityRequest = CS_UnityWebRequest.Post(url, wwwForm)
    return LuaWebRequest.New(url, unityRequest)
end


return LuaWebRequest
