---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangliheng.
--- DateTime: 2022/08/31 21:12
---
--- SettingManager 对有关字符串传递和重复拼接相关gc的简单优化

---@class SettingManager
local SettingManager = {}
local cs_setting = CS.GameEntry.Setting

function SettingManager:HasSetting(keyStr)
    local keyId = _ToID(keyStr)
    local has = cs_setting:HasSettingById(keyId)
    return has
end

function SettingManager:Save()
    cs_setting:Save()
end

function SettingManager:RemoveSetting(keyStr)
    cs_setting:RemoveSettingById(_ToID(keyStr))
end

function SettingManager:RemoveAllSettings()
    cs_setting:RemoveAllSettings()
end

function SettingManager:GetPublicBool(keyStr, ...)
    local v = cs_setting:GetBoolById(_ToID(keyStr), ...)
    return v
end

-- 注意这里参数是...表示用户可以传递nil
-- 如果不写成...，则会把nil传给C#，这样就会导致参数类型不匹配从而报错
function SettingManager:GetPublicInt(keyStr, ...)
    local v = cs_setting:GetIntById(_ToID(keyStr), ...)
    return v
end

function SettingManager:GetPublicFloat(keyStr, ...)
    local v = cs_setting:GetFloatById(_ToID(keyStr), ...)
    return v
end

function SettingManager:GetPublicString(keyStr, defValue)
    local keyId = _ToID(keyStr)
	
	-- 大部分情况下，访问字符串都是有值的。
	-- 所以这里先去获取字符串；如果返回是''，表示有可能是没有key的情况；
	-- 此时再通过HasId去判断一下，如果确定是没有key，那么返回defValue
	-- 这样便可以减少一次调用；另外
	-- Unity底层PlayerPrefs.GetString("key", null)没有key也是返回一个''
    local v = cs_setting:GetStringById(keyId)
	if string.IsNullOrEmpty(v) then
		if not cs_setting:HasSettingById(keyId) then
			return defValue or ''
		end
	end
    return v
end

function SettingManager:SetPublicBool(keyStr, value)
    cs_setting:SetBoolById(_ToID(keyStr), value)
end

function SettingManager:SetPublicInt(keyStr, value)
    cs_setting:SetIntById(_ToID(keyStr), value)
end

function SettingManager:SetPublicFloat(keyStr, value)
    cs_setting:SetFloatById(_ToID(keyStr), value)
end

function SettingManager:SetPublicString(keyStr, value)
    if keyStr == SettingKeys.GAME_UID then
        local _oldvalue = Setting:GetPublicString(SettingKeys.GAME_UID, "")
        if not string.IsNullOrEmpty(_oldvalue) then
            local str = value .. "__" .. debug.traceback()
            PostEventLog.Record("ChangeUid", str)
        end
    end
    cs_setting:SetStringById(_ToID(keyStr), _ToID(value))
end

function SettingManager:SetGameUid(gameUid)
	cs_setting.GameUid = gameUid
end

---以下仅仅只是针对Private的简单封装 和C#的交互全交由上面的Public相关接口


function SettingManager:GetUid()
    local uid
    if LuaEntry ~= nil and LuaEntry.Player ~= nil then
        uid = LuaEntry.Player:GetUid()
        if uid ~= nil then
            return uid
        end
    end

	Logger.Debug("SettingManager:GetUid warning!")
    uid = SettingManager:GetPublicString(SettingKeys.GAME_UID)
    return uid
end

function SettingManager:GenPrivateKey(keyStr)
	if keyStr == nil then
		Logger.LogError(debug.traceback('SettingManager:GenPrivateKey'))
	end
    return tostring(keyStr) .. self:GetUid()
end

function SettingManager:HasPrivateSetting(keyStr)
	keyStr = self:GenPrivateKey(keyStr)
	return self:HasSetting(keyStr)
end

function SettingManager:SetPrivateBool(keyStr, value)
	keyStr = self:GenPrivateKey(keyStr)
	self:SetPublicBool(keyStr, value)
end

function SettingManager:GetPrivateBool(keyStr, ...)
    keyStr = self:GenPrivateKey(keyStr)
    return self:GetPublicBool(keyStr, ...)
end

function SettingManager:GetPrivateInt(keyStr, ...)
    keyStr = self:GenPrivateKey(keyStr)
    return self:GetPublicInt(keyStr, ...)
end

function SettingManager:GetPrivateFloat(keyStr, ...)
    keyStr = self:GenPrivateKey(keyStr)
    return self:GetPublicFloat(keyStr, ...)
end

function SettingManager:GetPrivateString(keyStr, defValue)
    keyStr = self:GenPrivateKey(keyStr)
    return self:GetPublicString(keyStr, defValue)
end

function SettingManager:SetPrivateInt(keyStr, value)
    keyStr = self:GenPrivateKey(keyStr)
    self:SetPublicInt(keyStr, value)
end

function SettingManager:SetPrivateFloat(keyStr, value)
    keyStr = self:GenPrivateKey(keyStr)
    self:SetPublicFloat(keyStr, value)
end

function SettingManager:SetPrivateString(keyStr, value)
    keyStr = self:GenPrivateKey(keyStr)
    self:SetPublicString(keyStr, value)
end


-- 暂时兼容一下
function SettingManager:SetBool(keyStr, value)
    if App.IsEditor() then
        Logger.LogError("[Deprecated] please call SetPrivateBool instead")
    end
	self:SetPrivateBool(keyStr, value)
end

function SettingManager:GetBool(keyStr, ...)
    if App.IsEditor() then
        Logger.LogError("[Deprecated] please call GetPrivateBool instead")
    end
	return self:GetPrivateBool(keyStr, ...)
end

function SettingManager:SetInt(keyStr, value)
    if App.IsEditor() then
        Logger.LogError("[Deprecated] please call SetPrivateInt instead")
    end
	
	self:SetPrivateInt(keyStr, value)
end

function SettingManager:GetInt(keyStr, ...)
    if App.IsEditor() then
        Logger.LogError("[Deprecated] please call GetPrivateInt instead")
    end
	return self:GetPrivateInt(keyStr, ...)
end

function SettingManager:SetString(keyStr, value)
    if App.IsEditor() then
        Logger.LogError("[Deprecated] please call SetPrivateString instead")
    end
	self:SetPrivateString(keyStr, value)
end

function SettingManager:GetString(keyStr, ...)
    if App.IsEditor() then
        Logger.LogError("[Deprecated] please call GetPrivateString instead")
    end
	return self:GetPrivateString(keyStr, ...)
end

function SettingManager:SetFloat(keyStr, value)
    if App.IsEditor() then
        Logger.LogError("[Deprecated] please call SetPrivateFloat instead")
    end
	self:SetPrivateFloat(keyStr, value)
end

function SettingManager:GetFloat(keyStr, ...)
    if App.IsEditor() then
        Logger.LogError("[Deprecated] please call GetPrivateFloat instead")
    end
	return self:GetPrivateFloat(keyStr, ...)
end

return SettingManager
