---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangliheng.
--- DateTime: 2021/12/31 16:12
---

local CS_LookupTable = CS.LuaStringLookupTable
-- 字符串缓存类，
-- 主要是为了降低lua传字符串给C#，导致每次C#分配小的字符串GC
-- 尽量把lua和C#之间的字符串传值降到最低

local StringLookupTable = {}

-- 在这里可以手填一些初始的字符串映射。常用的。
-- 但其实并不是很建议填写。
local str_lookup_table = 
{
	-- ["abcdefg"] = 10,
}

function StringLookupTable.Init()
	CS_LookupTable.Init(str_lookup_table)
end

function StringLookupTable.Get(str)
	if str == nil then
		Logger.Debug("Get str is nil!")
		str = "" -- 这里简单兼容一下，否则str为nil时会报错
	end
	
	local id = str_lookup_table[str]
	if id == nil then
		id = CS_LookupTable.Add(str)
		str_lookup_table[str] = id
	end
	
	return id
end


return StringLookupTable
