--[[
-- [INPUT]: 依赖 CS.LuaStringLookupTable 做 C# 侧字符串登记，依赖 Logger
-- [OUTPUT]: 对外提供 StringLookupTable 表，暴露 Init 与 Get(str)->id；其 Get 在 Global.lua 中被赋给全局 _ToID
-- [POS]: Global 模块的字符串驻留表，把常用字符串映射为整型 id 复用，压低 Lua↔C# 字符串传值产生的小对象 GC，被 SettingManager/Network 等大量调用
-- [PROTOCOL]: 变更时更新此头部,然后检查 CLAUDE.md
--]]

---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangliheng.
--- DateTime: 2021/12/31 16:12
---

local CS_LookupTable = CS.LuaStringLookupTable
-- 字符串缓存类，
-- 主要是为了降低lua传字符串给C#，导致每次C#分配小的字符串GC
-- 尽量把lua和C#之间的字符串传值降到最低

local StringLookupTable = {}

-- 在这里可以手填一些初始的字符串映射。常用的。
-- 但其实并不是很建议填写。
local str_lookup_table = 
{
	-- ["abcdefg"] = 10,
}

function StringLookupTable.Init()
	CS_LookupTable.Init(str_lookup_table)
end

function StringLookupTable.Get(str)
	if str == nil then
		Logger.Debug("Get str is nil!")
		str = "" -- 这里简单兼容一下，否则str为nil时会报错
	end
	
	local id = str_lookup_table[str]
	if id == nil then
		id = CS_LookupTable.Add(str)
		str_lookup_table[str] = id
	end
	
	return id
end


return StringLookupTable
