---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 
--- DateTime:
---
local UIShipBackground = {
    Name       = UIWindowNames.UIShipBackground,
    Layer      = UILayer.Normal,
    Ctrl       = require "UI.UIShipBackground.Controller.UIShipBackgroundCtrl",
    View       = require "UI.UIShipBackground.View.UIShipBackgroundView",
    PrefabPath = "Assets/Landscape/Main/Prefabs/UI/SU_Main/UIShipBackground.prefab",
}

return {
    UIShipBackground = UIShipBackground,
}
