--[[
-- [INPUT]: 依赖 Framework 的 BaseClass 构造 OOP 类；纯 Lua 位运算实现，无外部模块依赖
-- [OUTPUT]: 对外提供 ApsRandom 类(SetSeed/GetSeed/Next/NextInt)
-- [POS]: Common 的确定性随机数发生器,复刻 Java LCG 算法保证与服务器同种子同序列,用于战斗/掉落等需前后端一致的随机逻辑
-- [PROTOCOL]: 变更时更新此头部,然后检查 CLAUDE.md
--]]
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Beef.
--- DateTime: 2022/3/4 17:07
---

--[[
    可以与服务器同步的随机数生成器
]]

local ApsRandom = BaseClass("ApsRandom")

local MULTIPLIER = 0x5DEECE66D
local ADDEND = 0xB
local MASK_31 = 0x7fffffff
local MASK_48 = 0xffffffffffff

local function __init(self, seed)
    self.seed = 0
    if seed then
        self:SetSeed(seed)
    end
end

local function __delete(self)
    self.seed = nil
end

local function InitialScramble(seed)
    return (seed ~ MULTIPLIER) & MASK_48
end

local function SetSeed(self, seed)
    self.seed = InitialScramble(seed)
end

local function GetSeed(self)
    return self.seed
end

local function Next(self, bits)
    self.seed = (self.seed * MULTIPLIER + ADDEND) & MASK_48
    return self.seed >> (48 - bits) & MASK_31
end

-- 返回随机整数 [0, bound)
local function NextInt(self, bound)
    local r = self:Next(31)
    local m = bound - 1
    if (bound & m) == 0 then
        r = ((bound * r) >> 31) & MASK_31
    else
        local u = r
        r = u % bound
        while u - r + m < 0 do
            u = self:Next(31)
            r = u % bound
        end
    end
    return r
end

ApsRandom.__init = __init
ApsRandom.__delete = __delete
ApsRandom.SetSeed = SetSeed
ApsRandom.GetSeed = GetSeed
ApsRandom.Next = Next
ApsRandom.NextInt = NextInt

return ApsRandom