---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangliheng.
--- DateTime: 9/11/2024 3:04 PM
---
--local Stack = require "Common.Tools.stack"

local debug = debug

local attached = false
local _cache = {}
local _id_generator = 0
local _ignore_count = 0 -- 出错之后得恢复，但是看起来这里也是有点问题
local _level_count = 0  -- 主要用来防止没有调用begin就调用end！
--local myStack = Stack.new()

local function lua_profiler_hook (event, line)
    if event == 'call' then
        local func = debug.getinfo (2, 'f').func
        local show_name = _cache[func]

        if show_name then
			-- myStack:push(show_name)
			ProfilerUtil.BeginSample2 (show_name)
			_level_count = _level_count + 1
        else
            local ar = debug.getinfo (2, 'Sn')
            local method_name = ar.name
            local linedefined = ar.linedefined

            if linedefined ~= -1 or (method_name and method_name ~= '__index')  then
                local short_src = ar.short_src
                method_name = method_name or '[unknown]'

                local index = short_src:match ('^.*()[/\\]')
                local filename  = index and short_src:sub (index + 1) or short_src
                show_name = method_name .. '(),' .. filename .. ':' .. linedefined

                --local id = _id_generator + 1
                --_id_generator = id
                _cache[func] = show_name

				--myStack:push(show_name)
				ProfilerUtil.BeginSample2 (show_name)
				_level_count = _level_count + 1
            else
                _ignore_count = _ignore_count + 1
            end
        end
    elseif event == 'return' then
		local func = debug.getinfo (2, 'f').func
		local show_name = _cache[func]
		
        if _ignore_count == 0 then
            if _level_count == 0 then
                return
            end
            
            _level_count = _level_count - 1
--			local t = myStack:peek()
--			if show_name ~= t then
--				Logger.Log("name diff: ", tostring(show_name), "/", tostring(t))
--			end
			ProfilerUtil.EndSample2 ()
			--myStack:pop()
        else
            _ignore_count = _ignore_count - 1
        end
    end
end

-- 开启LUA调试。。。所有函数都进行打点处理
function start_profiler()
    Logger.Log('profiler已开启！')
    if attached then
        return
    end
    attached = true
    debug.sethook(lua_profiler_hook, 'cr', 0)
end

function stop_profiler()
    debug.sethook()
    attached = false
    Logger.Log('profiler已关闭！')
end

function is_profiler_attached()
    return attached
end
