--[[
-- [INPUT]: 依赖 CS.UnityEngine.RectTransformUtility(WorldToScreenPoint/ScreenPointToLocalPointInRectangle)
-- [OUTPUT]: 对外提供 PosConverse 表(WorldToScreenPos/ScreenToUIPos)
-- [POS]: Common 的坐标转换封装,统一世界/屏幕/UI 局部坐标互转,屏蔽 C# RectTransformUtility 多返回值细节供 UI 层调用
-- [PROTOCOL]: 变更时更新此头部,然后检查 CLAUDE.md
--]]
---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mac.
--- DateTime: 7/22/21 3:53 PM
---
local PosConverse = {}

-- 世界坐标转屏幕坐标
function PosConverse.WorldToScreenPos(worldPos, camera)
    local screenPos = CS.UnityEngine.RectTransformUtility.WorldToScreenPoint(camera, worldPos);
    return screenPos
end

-- 屏幕坐标转换成UI坐标
function PosConverse.ScreenToUIPos( rect, screenPos, camera )
    local _, localPoint = CS.UnityEngine.RectTransformUtility.ScreenPointToLocalPointInRectangle(rect, screenPos, camera);
    return localPoint
end



return PosConverse