---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mac.
--- DateTime: 7/22/21 3:53 PM
---
local PosConverse = {}

-- 世界坐标转屏幕坐标
function PosConverse.WorldToScreenPos(worldPos, camera)
    local screenPos = CS.UnityEngine.RectTransformUtility.WorldToScreenPoint(camera, worldPos);
    return screenPos
end

-- 屏幕坐标转换成UI坐标
function PosConverse.ScreenToUIPos( rect, screenPos, camera )
    local _, localPoint = CS.UnityEngine.RectTransformUtility.ScreenPointToLocalPointInRectangle(rect, screenPos, camera);
    return localPoint
end



return PosConverse