---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangliheng.
--- DateTime: 9/25/2024 5:09 PM
--- 监视表的写入操作



---@ 工具函数：监视表的写入操作
---@param t table 需要监视的表
---@param log_file string 日志文件名称[可选的]  
function watch_dog(t, log_file)
    if App.IsFinalRelease() then
        return t
    end

    local function get_mem_addr (o)
        return tostring(o):sub(type(o):len() + 3)
    end

    local address = tostring(get_mem_addr(t))
    local class_name = t._class_type ~= nil and t._class_type.__cname ~= nil and string.format('classname:[%s] ', tostring(t._class_type.__cname)) or ''  
    local table_name = t.name ~= nil and string.format('name:[%s] ', tostring(t.name)) or ''  
    
    local function log_to_file(msg)
        msg = string.format('#zlh# #watch_dog# address:[%s] %s%s%s', address, class_name, table_name, msg)
        print(msg)
        
        if string.IsNullOrEmpty(log_file) or not App.IsEditor() then
            return
        end
        
        local file = io.open(log_file, "a")
        file:write(msg .. "\n")
        file:close()
    end
    
    --附加的时候打印一下
    log_to_file(debug.traceback('watchdog attached!', 2))

    local proxy = {}
    local mt = {
        __index = t,
        __newindex = function(_, key, value)
            local stack_info = string.format("write detected!  key:[%s], value:[%s]", tostring(key), tostring(value))
            log_to_file(debug.traceback(stack_info, 2))

            t[key] = value
        end
    }

    setmetatable(proxy, mt)
    return proxy
end


---测试用例
--[[
local Person = BaseClass("Person")
function Person:__init(name, age)
	self.name = name
	self.age = age or 1
end

local p1 = Person.New("person_a", 32)
local p2 = Person.New("person_b", 18)
p1 = watch_dog(p1)
p2 = watch_dog(p2, 'person_b.log')

p1.age = 22
p2.age = 8
p1.age = 42
]]