---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mac.
--- DateTime: 8/17/21 2:40 PM
---

---@class CircleImage : UIBaseComponent
--[[
-- [INPUT]: 依赖 UIBaseComponent 基类、CS.CircleImage 原生圆形图片组件
-- [OUTPUT]: 对外提供 CircleImage 组件类，含 LoadSprite 按路径加载贴图（带路径去重）、SetIsCircle 圆形开关
-- [POS]: Component 层对 CS 圆形裁剪 Image 的 Lua 封装，用于头像等需圆形显示的图片
-- [PROTOCOL]: 变更时更新此头部,然后检查 CLAUDE.md
--]]
local CircleImage = BaseClass("CircleImage", UIBaseComponent)
local base = UIBaseComponent
local UnityImage = typeof(CS.CircleImage)

-- 创建
local function OnCreate(self)
    base.OnCreate(self)
    self.unity_image = self.gameObject:GetComponent(UnityImage)
end

local function LoadSprite(self, sprite_path, default_sprite)
    if self.spritePath == sprite_path then
        return
    end
    self.spritePath = sprite_path
    self.unity_image:LoadSprite(sprite_path, default_sprite)
end

local function SetIsCircle(self,state)
    --self.unity_image.isCircle = state
end

-- 销毁
local function OnDestroy(self)
    self.unity_image = nil
    base.OnDestroy(self)
end

CircleImage.OnCreate = OnCreate
CircleImage.LoadSprite = LoadSprite
CircleImage.OnDestroy = OnDestroy
CircleImage.SetIsCircle = SetIsCircle
return CircleImage