---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zzl.
--- DateTime:
---
--[[
-- [INPUT]: 依赖 UIBaseComponent 基类、CS.HorizontalInfinityScrollView 原生横向无限滚动组件
-- [OUTPUT]: 对外提供 HorizontalInfinityScrollView 组件类，含 Init 绑定 cell 回调、SetItemCount 设置总数、ForceUpdate 强刷、MoveItemByIndex 定位
-- [POS]: Component 层的横向无限循环列表封装，与 GridInfinityScrollView 同族，专用于横向大数据滚动
-- [PROTOCOL]: 变更时更新此头部,然后检查 CLAUDE.md
--]]
local HorizontalInfinityScrollView = BaseClass("HorizontalInfinityScrollView", UIBaseComponent)
local base = UIBaseComponent
local UnityScrollView = typeof(CS.HorizontalInfinityScrollView)
local function OnCreate(self)
    base.OnCreate(self)
    self.content = self.gameObject:GetComponent(UnityScrollView)
end

local function OnDestroy(self)
    self.content:Dispose()
    self.content = nil
    base.OnDestroy(self)
end

local function Init(self, action1, action2, action3,obj)
    self.content:Init(action1, action2, action3,obj)
end

local function SetItemCount(self,itemCount_)
    self.content:SetItemCount(itemCount_)
    self.content:ForceUpdate()
end

local function ForceUpdate(self)
    self.content:ForceUpdate()
end

--index从0开始
local function MoveItemByIndex(self,index,delay)
    self.content:MoveItemByIndex(index,delay)
end

--不可复用
local function CenterItemByIndex(self, index, delay)
    
end

HorizontalInfinityScrollView.OnCreate = OnCreate
HorizontalInfinityScrollView.OnDestroy = OnDestroy
HorizontalInfinityScrollView.Init = Init
HorizontalInfinityScrollView.SetItemCount = SetItemCount
HorizontalInfinityScrollView.ForceUpdate = ForceUpdate
HorizontalInfinityScrollView.MoveItemByIndex = MoveItemByIndex
return HorizontalInfinityScrollView