---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mac.
--- DateTime: 6/8/21 2:18 PM
---

---@class UILoopListView2 : UIBaseContainer
local UILoopListView2 = BaseClass("UILoopListView2", UIBaseContainer)
local base = UIBaseContainer
local UnityUILoopListView2 = typeof(CS.SuperScrollView.LoopListView2)

-- 创建
local function OnCreate(self, relative_path)
    base.OnCreate(self)
    -- Unity侧原生组件
    self.unity_looplistview2 = self.gameObject:GetComponent(UnityUILoopListView2)
end

local function OnDestroy(self)
    local listview = self.unity_looplistview2
    if listview then
        pcall(function()
            listview:SetOnBeginDragAction(nil)
            listview:SetOnDragingAction(nil)
            listview:SetOnEndDragAction(nil)
            listview:SetOnListClickAction(nil)
            listview.OnGetItemByIndex = nil
            listview.OnGetItemNameByIndex = nil
            if self._snapFinished then
                self.unity_looplistview2.mOnSnapItemFinished = nil--:RemoveListener(self._snapFinished)
                self._snapFinished = nil
            end
            if self._snapNearestChanged then
                self.unity_looplistview2.mOnSnapNearestChanged = nil --:RemoveListener(self._snapNearestChanged)
                self._snapNearestChanged = nil
            end
        end)
    end
    self.unity_looplistview2 = nil
end

--[[
    初始化looplistview
]]
local function InitListView(self, itemTotalCount, onGetItemByIndex)
    if (self.unity_looplistview2 == nil) then
        return;
    end
    self.unity_looplistview2:InitListView(itemTotalCount, onGetItemByIndex);
end

local function InitListViewParam(self, itemTotalCount, onGetItemByIndex, initParam)
    if (self.unity_looplistview2 == nil) then
        return;
    end
    self.unity_looplistview2:InitListView(itemTotalCount, onGetItemByIndex, initParam);
end

--zlh: 带初始化参数的init
function UILoopListView2:InitWithParam(itemTotalCount, onGetItemByIndex, param)
    if self.unity_looplistview2 == nil then
        return
    end
    
    --老版本兼容
    if not HasCSClassMap.LoopListViewInitParam then
        self:InitListView(itemTotalCount, onGetItemByIndex)
        return
    end
    
    --mDistanceForRecycle0 should be larger than mDistanceForNew0
    --mDistanceForRecycle1 should be larger than mDistanceForNew1
    local initParam = CS.SuperScrollView.LoopListViewInitParam()
    initParam.mDistanceForRecycle0 = param.mDistanceForRecycle0 or 200
    initParam.mDistanceForNew0 = param.mDistanceForNew0 or math.max(10, initParam.mDistanceForRecycle0 - 100)
    initParam.mDistanceForRecycle1 = param.mDistanceForRecycle1 or 200
    initParam.mDistanceForNew1 = param.mDistanceForNew1 or math.max(10, initParam.mDistanceForRecycle1 - 100)
    
    self.unity_looplistview2:InitListView(itemTotalCount, onGetItemByIndex, initParam)
end


--[[
    设置刚刚开始滑动的回调函数
]]
local function SetOnBeginDragAction( self, callback )
    if (self.unity_looplistview2 == nil) then
        return;
    end
    self.unity_looplistview2:SetOnBeginDragAction( callback )
end

--[[
    设置开始拖动的回调函数
]]
local function SetOnDragingAction( self, onDragingAction)
    if (self.unity_looplistview2 == nil) then
        return;
    end
    self.unity_looplistview2:SetOnDragingAction(onDragingAction)
end

--[[
    设置停止拖动的回调函数
]]
local function SetOnEndDragAction( self,  onEndDragAction )
    if (self.unity_looplistview2 == nil) then
        return;
    end
    self.unity_looplistview2:SetOnEndDragAction(onEndDragAction)
end

--[[
    点击滑动列表的回调函数
]]
local function SetOnListClickAction( self, callback )
    if (self.unity_looplistview2 == nil) then
        return;
    end
    self.unity_looplistview2:SetOnListClickAction( callback )
end

--[[
    返回指定的item
]]
local function GetShownItemByItemIndex( self, itemidx)
    if (self.unity_looplistview2 == nil) then
        return nil;
    end
    return self.unity_looplistview2:GetShownItemByItemIndex(itemidx);
end

--[[
    返回指定item中的相对坐标
]]
local function GetItemCornerPosInViewPort( self, item )
    if (self.unity_looplistview2 == nil) then
        return nil;
    end
    return self.unity_looplistview2:GetItemCornerPosInViewPort( item )
end

--[[
    刷新listview 这个和下面的 RefreshAllShownItem 需要仔细考虑下
    itemTotalCount 总的子控件个数
    moveToMinPos 滑动到最小位置 / moveToMaxPos 滑动到最大位置  / 不填对当前位置不做变动
]]
local function SetListItemCount( self, itemTotalCount, moveToMinPos, moveToMaxPos )
    if (self.unity_looplistview2 == nil) then
        return;
    end
    self.unity_looplistview2:SetListItemCount(itemTotalCount, moveToMinPos, moveToMaxPos);
end

--[[
    刷新listview
]]
local function RefreshAllShownItem(self)
    if (self.unity_looplistview2 == nil) then
        return;
    end
    self.unity_looplistview2:RefreshAllShownItem()
end


local function SetInteractable(self,value)
    self.unity_looplistview2.interactable = value
end

local function MovePanelToItemIndex(self, index, offset)
    self.unity_looplistview2:MovePanelToItemIndex(index, offset)
end

local function StopMovement(self)
    self.unity_looplistview2.ScrollRect:StopMovement()
end

local function GetViewPortWidth(self)
    return self.unity_looplistview2.ViewPortWidth
end

local function ClearAllItems(self)
    self.unity_looplistview2:ClearAllItems()
end

local function RefreshItemByItemIndex(self, index)
    self.unity_looplistview2:RefreshItemByItemIndex(index)
end

local function GetCurShowIndexes(self)
    return self.unity_looplistview2:GetCurShowIndexes()
end

local function SetMoveType(self, type)
    self.unity_looplistview2:SetMoveType(type)
end

local function SetEnable(self, value)
    self.unity_looplistview2.enabled = value
end

local function OnItemSizeChanged(self, itemIndex)
    self.unity_looplistview2:OnItemSizeChanged(itemIndex)
end

local function SetItemSnapEnable(self, value)
    self.unity_looplistview2.ItemSnapEnable = value
end

local function SetSnapItemFinished(self,callback)
    if callback then
		if self._snapFinished then
			self.unity_looplistview2.mOnSnapItemFinished = nil --:RemoveListener(self._snapFinished)
		end
		self._snapFinished = callback
		self.unity_looplistview2.mOnSnapItemFinished = self._snapFinished--:AddListener(self._snapFinished)
	elseif self._snapFinished then
		self.unity_looplistview2.mOnSnapItemFinished = nil--:RemoveListener(self._snapFinished)
		self._snapFinished = nil
	end
end

local function SetSnapNearestChanged(self,callback)
    if callback then
		if self._snapNearestChanged then
			self.unity_looplistview2.mOnSnapNearestChanged = nil--:RemoveListener(self._snapNearestChanged)
		end
		self._snapNearestChanged = callback
		self.unity_looplistview2.mOnSnapNearestChanged = self._snapNearestChanged--:AddListener(self._snapNearestChanged)
	elseif self._snapNearestChanged then
		self.unity_looplistview2.mOnSnapNearestChanged = nil --:RemoveListener(self._snapNearestChanged)
		self._snapNearestChanged = nil
	end
end
UILoopListView2.OnCreate = OnCreate
UILoopListView2.OnDestroy = OnDestroy
UILoopListView2.InitListView = InitListView
UILoopListView2.SetOnBeginDragAction = SetOnBeginDragAction
UILoopListView2.SetOnDragingAction = SetOnDragingAction
UILoopListView2.SetOnEndDragAction = SetOnEndDragAction
UILoopListView2.SetOnListClickAction = SetOnListClickAction
UILoopListView2.GetShownItemByItemIndex = GetShownItemByItemIndex
UILoopListView2.GetItemCornerPosInViewPort = GetItemCornerPosInViewPort
UILoopListView2.SetListItemCount = SetListItemCount
UILoopListView2.RefreshAllShownItem = RefreshAllShownItem
UILoopListView2.SetInteractable = SetInteractable
UILoopListView2.MovePanelToItemIndex = MovePanelToItemIndex
UILoopListView2.StopMovement = StopMovement
UILoopListView2.GetViewPortWidth = GetViewPortWidth
UILoopListView2.ClearAllItems = ClearAllItems
UILoopListView2.SetMoveType = SetMoveType
UILoopListView2.SetEnable = SetEnable
UILoopListView2.OnItemSizeChanged = OnItemSizeChanged
UILoopListView2.SetItemSnapEnable = SetItemSnapEnable
UILoopListView2.SetSnapItemFinished = SetSnapItemFinished
UILoopListView2.SetSnapNearestChanged = SetSnapNearestChanged
UILoopListView2.RefreshItemByItemIndex = RefreshItemByItemIndex
UILoopListView2.GetCurShowIndexes = GetCurShowIndexes
UILoopListView2.InitListViewParam = InitListViewParam



return UILoopListView2