---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Imaginaerum.
--- DateTime: 2021/8/30 15:14
---
local UINewText = BaseClass("UINewText", UIBaseComponent)
local base = UIBaseComponent
local UnityText = typeof(CS.NewText)

-- 创建
local function OnCreate(self)
    base.OnCreate(self)
    -- Unity侧原生组件
    self.unity_text = self.gameObject:GetComponent(UnityText)
end

-- 获取文本
local function GetText(self)
    return self.unity_text.text
end

local function GetUnityText(self)
	return self.unity_text
end

-- 设置文本
local function SetText(self, text)
	if string.IsNullOrEmpty(text) then
		self.unity_text.text = nil
	else
    	self.unity_text.text = text
	end
end

local function SetLocalText(self, dialogId, ...)
	dialogId = Localization.GetRealId(dialogId)
	self.unity_text:SetLocalText(dialogId, ...)
end

local function SetText_Cache(self, text)
	self.unity_text:SetTextCacheID(_ToID(text))
end

-- 销毁
local function OnDestroy(self)
    self.unity_text = nil
    base.OnDestroy(self)
end

local function SetColor(self,value)
    self.unity_text:Set_color(value.r, value.g, value.b, value.a)
end

local function GetColor(self)
	local r,g,b,a = self:GetColorRGBA()
	return Color.New(r,g,b,a)
end

local function SetColorRGBA(self,r,g,b,a)
	--self.unity_image.color = value
	self.unity_text:Set_color(r, g, b, a)
end

local function GetColorRGBA(self)
	return self.unity_text:Get_color()
end

local function GetWidth(self)
    return self.unity_text.preferredWidth
end

local function GetHeight(self)
    return self.unity_text.preferredHeight
end


function UINewText:SetAlignment( _alignment )
    self.unity_text.alignment = _alignment
end

local function SetPreferSize(self, value)
    self.rectTransform.sizeDelta = value
end

UINewText.OnCreate = OnCreate
UINewText.GetText = GetText
UINewText.GetUnityText = GetUnityText
UINewText.SetText = SetText
UINewText.SetLocalText = SetLocalText
UINewText.SetText_Cache = SetText_Cache
UINewText.OnDestroy = OnDestroy
UINewText.SetColor = SetColor
UINewText.GetWidth = GetWidth
UINewText.GetHeight = GetHeight
UINewText.SetPreferSize = SetPreferSize
UINewText.GetColor = GetColor
UINewText.SetColorRGBA = SetColorRGBA
UINewText.GetColorRGBA = GetColorRGBA

return UINewText