---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangliheng.
--- DateTime: 8/6/21 6:43 PM
---

---@class UIPlayerHead
local UIPlayerHead = BaseClass("UIPlayerHead", UIBaseComponent)
local base = UIBaseComponent
local CS_UIPlayerHead = typeof(CS.UIPlayerHead)

local function OnCreate(self)
    base.OnCreate(self)
    self.unityHead = self.gameObject:GetComponent(CS_UIPlayerHead)
    if App.IsGPTest() then
        CS.UIPlayerHead.HEAD_URL = "http://10.7.88.22:89/img/"
    end
end

local function OnDestroy(self)
    if self.unityHead~=nil then
        self.unityHead:SetCustomLoadCallback(nil)
    end
    self.unityHead = nil
    
    base.OnDestroy(self)
end

function UIPlayerHead:OnEnable()
    base.OnEnable(self)
end

-- 隐藏
function UIPlayerHead:OnDisable()
    base.OnDisable(self)
end

local function SetData(self, uid, pic, picVer, useBig)
    if useBig == nil then
        useBig = false
    end
    if uid then
        if not pic and not picVer then
            self.unityHead:UseSystemHead()
        else
			-- 简单处理一下
			if pic == "player_head_2" then
				pic = "player_head_2.png"
			elseif pic == "player_head_3" then
				pic = "player_head_3.png"
            elseif pic == "player_head_4" then
                pic = "player_head_4.png"
            end
            self.unityHead:SetData(uid, pic, tonumber(picVer), useBig)
        end 
    end
end

local function LoadSprite(self, pic)
    self.unityHead:LoadSprite(pic)
end

local function SetCustomLoadCallback(self, callback)
    self.unityHead:SetCustomLoadCallback(callback)
end

function UIPlayerHead:SetGray(isGray)
   --[[ local img = self.gameObject:GetComponent(typeof(CS.CircleImage))
    if img ~= nil then
        if isGray then
            DataCenter.ShaderEffectManager:SetGrayMaterial(function(mat)
                img.material = mat
            end)
        else
            img.material = nil
        end
    end]]
end


UIPlayerHead.OnCreate = OnCreate
UIPlayerHead.OnDestroy = OnDestroy
UIPlayerHead.SetData = SetData
UIPlayerHead.LoadSprite = LoadSprite
UIPlayerHead.SetCustomLoadCallback = SetCustomLoadCallback

return UIPlayerHead