---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Beef.
--- DateTime: 2024/7/15 21:43
---
--[[
-- [INPUT]: 依赖 UIBaseContainer 基类、UI.UICommonIcon.UICommonPlayerHead 业务头像预设组件
-- [OUTPUT]: 对外提供 UIPlayerHeadNew 组件类，含 SetData 设置头像、SetClickable 可点开关、OnClick 点击回调、ComponentDefine/DataDefine 生命周期辅助
-- [POS]: Component 层的新版玩家头像容器，桥接 UI 层业务头像组件 UICommonPlayerHead；与 UIPlayerHead/UICommonHead 同为头像展示家族
-- [PROTOCOL]: 变更时更新此头部,然后检查 CLAUDE.md
--]]
---@class UIPlayerHeadNew : UIBaseContainer
local UIPlayerHeadNew = BaseClass("UIPlayerHeadNew", UIBaseContainer)
local base = UIBaseContainer
local UICommonPlayerHead = require "UI.UICommonIcon.UICommonPlayerHead"

local this_path = ""

local function OnCreate(self)
    base.OnCreate(self)
    self:ComponentDefine()
    self:DataDefine()
end

local function OnDestroy(self)
    self.DataDestroy()
    self.ComponentDestroy()
    base.OnDestroy(self)
end

local function ComponentDefine(self)
    ---@type UICommonPlayerHead
    self.commonPlayerHead = self:AddComponent(UICommonPlayerHead,"")
    self.btn = self:AddComponent(UIButton, this_path)
    self.btn:SetOnClick(function()
        self:OnClick()
    end)
end

local function ComponentDestroy(self)
    
end

local function DataDefine(self)
    self.data = nil
    self.uid = 0
    self.clickable = true
end

local function DataDestroy(self)
    
end

local function SetData(self, data)
    self.data = data
    self.uid = data.uid or data.ownerId
    
    local pic1 = self.data.pic or self.data.headPic
    local picVer1 = self.data.picVer or self.data.headPicVer
    local headBgImg = DataCenter.DecorationDataManager:GetHeadFrame(self.data.headSkinId, self.data.headSkinET)
    local param = {
        uid = self.uid,
        pic = pic1,
        picVer = picVer1,
        headBg = headBgImg
    }
    self.commonPlayerHead:ReInit(param)
end

local function SetClickable(self, clickable)
    self.clickable = clickable
end

local function OnClick(self)
    if self.data == nil then
        return
    end
    if not self.clickable then
        return
    end

    if self.data.clickCallback then
        self.data.clickCallback()
        return
    end

    if self.uid ~= LuaEntry.Player.uid then
        UIManager:GetInstance():OpenWindow(UIWindowNames.UIOtherPlayerInfo, self.uid)
    else
        UIManager:GetInstance():OpenWindow(UIWindowNames.UIPlayerInfo, LuaEntry.Player.uid)
    end
end

UIPlayerHeadNew.OnCreate = OnCreate
UIPlayerHeadNew.OnDestroy = OnDestroy
UIPlayerHeadNew.ComponentDefine = ComponentDefine
UIPlayerHeadNew.ComponentDestroy = ComponentDestroy
UIPlayerHeadNew.DataDefine = DataDefine
UIPlayerHeadNew.DataDestroy = DataDestroy
UIPlayerHeadNew.SetData = SetData
UIPlayerHeadNew.SetClickable = SetClickable
UIPlayerHeadNew.OnClick = OnClick

return UIPlayerHeadNew