---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangliheng.
--- DateTime: 7/7/21 11:29 AM
---

---@class UIRawImage:UIBaseComponent
local UIRawImage = BaseClass("UIRawImage", UIBaseComponent)
local base = UIBaseComponent
local UnityRawImage = typeof(CS.UnityEngine.UI.RawImage)
local ResourceManager = CS.GameEntry.Resource

local function OnCreate(self)
    base.OnCreate(self)
    self.unityRawImage = self.gameObject:GetComponent(UnityRawImage)
end

local function OnDestroy(self)
    self.unityRawImage = nil
    base.OnDestroy(self)
end

local function SetTexture(self, texture)
    self.unityRawImage.texture = texture
end

local function SetColor(self, value)
    self.unityRawImage:Set_color(value.r, value.g, value.b, value.a)
end

local function SetColorRGBA(self,r,g,b,a)
	--self.unity_image.color = value
	self.unityRawImage:Set_color(r, g, b, a)
end

local function GetColorRGBA(self)
	return self.unityRawImage:Get_color()
end

local function GetColor(self)
	local r,g,b,a = self:GetColorRGBA()
	return Color.New(r,g,b,a)
end

local function SetEnable(self,enable)
    self.unityRawImage.enabled = enable
end

local function SetNativeSize(self)
    self.unityRawImage:SetNativeSize()
end

local function LoadSprite(self, sprite_path, default_sprite, forceReplaceTexture)
    if string.IsNullOrEmpty(sprite_path) then
        return
    end

    if forceReplaceTexture == nil then
        forceReplaceTexture = false --不管self.spritePath == sprite_path，都替换
    end

    local pngStr = ".png"
    local pngIndex = string.find(sprite_path, pngStr, -4)
    if pngIndex == nil then
        sprite_path = sprite_path .. pngStr
    end

    if self.spritePath == sprite_path and not forceReplaceTexture then
        return
    end
    self.spritePath = sprite_path

    if not IsNull(self.asset) then
        self.asset:Release()
        self.asset = nil
    end
    self.asset = ResourceManager:LoadAsset(self.spritePath, typeof(CS.UnityEngine.Texture))
    -- self.asset = CS.VEngine.Asset.Load(self.spritePath, typeof(CS.UnityEngine.Texture))

    if not IsNull(self.asset) and not self.asset.isError then
        self.unityRawImage.texture = self.asset.asset.texture
    end

    -- self.unity_image:LoadSprite(sprite_path, default_sprite)
end

UIRawImage.OnCreate = OnCreate
UIRawImage.LoadSprite = LoadSprite
UIRawImage.OnDestroy = OnDestroy
UIRawImage.SetTexture = SetTexture
UIRawImage.SetColor = SetColor
UIRawImage.GetColor = GetColor
UIRawImage.SetEnable = SetEnable
UIRawImage.SetColorRGBA = SetColorRGBA
UIRawImage.GetColorRGBA = GetColorRGBA
UIRawImage.SetNativeSize = SetNativeSize

return UIRawImage