---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangxiaowu.
--- DateTime: 2024/11/6 下午12:01
---
local UIScrollViewExclusive = BaseClass("UIScrollViewExclusive", UIBaseContainer)
local base = UIBaseContainer
local function OnCreate(self)
    base.OnCreate(self)
    self.parentScroll = nil
    self.isSelf = false
    self.isVertical = false
    self.scroll = nil
end

local function OnDestroy(self)
    self.scroll = nil
    self.parentScroll = nil
    base.OnDestroy(self)
end

--扩展方法 父级的组件是ScrollRect 
--isFirstSelf  通过 GetComponentsInParent 获取的第一个组件是否是自己 是自己的话父级那个就是第2个
--如果自己使用的是 ScrollRect isFirstSelf = true 否则的话相反
local function ReInitScrollRect(self, scrollView, trigger, isVertical, isFirstSelf)
    self.isVertical = isVertical
    self.scroll = scrollView
    if self.parentScroll == nil then
        local allUIScroll = scrollView.gameObject.transform:GetComponentsInParent(typeof(CS.UnityEngine.UI.ScrollRect))   
        if isFirstSelf then
            self.parentScroll = allUIScroll[1]
        else
            self.parentScroll = allUIScroll[0]
        end        
    end
    trigger:OnBeginDrag(function(eventData)
        self:OnBeginDrag(eventData)
    end)
    trigger:OnDrag(function(eventData)
        self:OnDrag(eventData)
    end)
    trigger:OnEndDrag(function(eventData)
        self:OnEndDrag(eventData)
    end)
end

local function ReInit(self, scrollView, trigger, isVertical)
    self.isVertical = isVertical
    self.scroll = scrollView
    if self.parentScroll == nil then
        local allUIScroll = scrollView.gameObject.transform:GetComponentsInParent(typeof(CS.ScrollView));
        --allUIScroll.gameObject.name
        self.parentScroll = allUIScroll[1]
    end
    trigger:OnBeginDrag(function(eventData)
        self:OnBeginDrag(eventData)
    end)
    trigger:OnDrag(function(eventData)
        self:OnDrag(eventData)
    end)
    trigger:OnEndDrag(function(eventData)
        self:OnEndDrag(eventData)
    end)
end

local function OnBeginDrag(self, eventData)
    local touchDeltaPosition = Vector2.zero
    if CS.SDKManager.IS_UNITY_EDITOR() then
        local deltaX = CS.UnityEngine.Input.GetAxis("Mouse X");
        local deltaY = CS.UnityEngine.Input.GetAxis("Mouse Y");
        touchDeltaPosition = Vector2.New(deltaX, deltaY)
    elseif CS.SDKManager.IS_UNITY_ANDROID() or CS.SDKManager.IS_UNITY_IOS() then
        touchDeltaPosition = CS.UnityEngine.Input.GetTouch(0).deltaPosition;
    end
    if self.isVertical then
        if math.abs(touchDeltaPosition.x) < math.abs(touchDeltaPosition.y) then
            self.isSelf = true
            self.scroll:OnBeginDrag(eventData)
        else
            self.isSelf = false
            self.parentScroll:OnBeginDrag(eventData)
        end
    else
        if math.abs(touchDeltaPosition.x) > math.abs(touchDeltaPosition.y) then
            self.isSelf = true
            self.scroll:OnBeginDrag(eventData)
        else
            self.isSelf = false
            self.parentScroll:OnBeginDrag(eventData)
        end
    end
end

local function OnEndDrag(self, eventData)
    if self.isSelf then
        self.scroll:OnEndDrag(eventData)
    else
        self.parentScroll:OnEndDrag(eventData)
    end
end

local function OnDrag(self, eventData)
    if self.isSelf then
        self.scroll:OnDrag(eventData)
    else
        self.parentScroll:OnDrag(eventData)
    end
end

UIScrollViewExclusive.OnCreate = OnCreate
UIScrollViewExclusive.OnDestroy = OnDestroy
UIScrollViewExclusive.ReInit = ReInit
UIScrollViewExclusive.OnBeginDrag = OnBeginDrag
UIScrollViewExclusive.OnEndDrag = OnEndDrag
UIScrollViewExclusive.OnDrag = OnDrag
UIScrollViewExclusive.ReInitScrollRect = ReInitScrollRect
return UIScrollViewExclusive