---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zzl.
--- DateTime:

---@class UIScrollPage:UIBaseComponent
--[[
-- [INPUT]: 依赖 UIBaseComponent 基类、CS.PageViewComponent 原生分页视图组件
-- [OUTPUT]: 对外提供 UIScrollPage 组件类，含 Refresh/RefreshByCell 刷新页、PageTo 翻到指定页
-- [POS]: Component 层的分页滚动封装，用于整页翻动的横幅/引导页等；区别于连续滚动的 ScrollView 家族
-- [PROTOCOL]: 变更时更新此头部,然后检查 CLAUDE.md
--]]
local UIScrollPage = BaseClass("UIScrollPage", UIBaseComponent)
local base = UIBaseComponent
local UnityScrollView = typeof(CS.PageViewComponent)
local function OnCreate(self)
    base.OnCreate(self)
    self.scroll_view = self.gameObject:GetComponent(UnityScrollView)
end

local function OnDestroy(self)
    self.scroll_view.onPageChanged = nil
    self.scroll_view = nil
    base.OnDestroy(self)
end

local function Refresh(self,action)
    self.scroll_view:Refresh(action)
end

local function RefreshByCell(self,action)
    self.scroll_view:RefreshByCell(action)
end

--从0开始
local function PageTo(self, index)
    self.scroll_view:pageTo(index) 
end

UIScrollPage.OnCreate = OnCreate
UIScrollPage.OnDestroy = OnDestroy
UIScrollPage.Refresh = Refresh
UIScrollPage.RefreshByCell = RefreshByCell
UIScrollPage.PageTo = PageTo
return UIScrollPage