---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mac.
--- DateTime: 8/24/21 11:27 AM
---

---@class UITextMeshProUGUI : UIBaseComponent
local UITextMeshProUGUI = BaseClass("UITextMeshProUGUI", UIBaseComponent)
local base = UIBaseComponent
local UnityTextMeshPro = typeof(CS.TMPro.TextMeshProUGUI)


-- 创建
local function OnCreate(self)
    base.OnCreate(self)
    -- Unity侧原生组件
    self.unity_tmpro = self.gameObject:GetComponent(UnityTextMeshPro)
    self.unity_text = self.unity_tmpro
end

-- 获取文本
local function GetText(self)
    return self.unity_tmpro.text
end

-- 设置文本
local function SetText(self, text)
    text = text and text or ""
    self.unity_tmpro:Native_SetText(text)
end

local function SetLocalText(self, dialogId, ...)
    dialogId = Localization.GetRealId(dialogId)
    self.unity_tmpro:SetLocalText(dialogId, ...)
end

local function SetTextCacheID(self, text)
	self.unity_tmpro:SetTextCacheID(_ToID(text))
end

-- 销毁
local function OnDestroy(self)
    self.unity_tmpro = nil
    self.unity_text = nil
    base.OnDestroy(self)
end

local function SetColor(self,value)
    self.unity_tmpro.color = value
end

local function GetColor(self)
    return self.unity_tmpro.color
end

local function GetWidth(self)
    return self.unity_tmpro.preferredWidth
end

local function GetHeight(self)
    return self.unity_tmpro.preferredHeight
end

local function GetLinkInfo(self)
    return self.unity_tmpro.textInfo.linkInfo
end

UITextMeshProUGUI.OnCreate = OnCreate
UITextMeshProUGUI.GetText = GetText
UITextMeshProUGUI.SetText = SetText
UITextMeshProUGUI.SetLocalText = SetLocalText
UITextMeshProUGUI.SetTextCacheID = SetTextCacheID
UITextMeshProUGUI.OnDestroy = OnDestroy
UITextMeshProUGUI.SetColor = SetColor
UITextMeshProUGUI.GetWidth = GetWidth
UITextMeshProUGUI.GetHeight = GetHeight
UITextMeshProUGUI.GetColor = GetColor
UITextMeshProUGUI.GetLinkInfo = GetLinkInfo

return UITextMeshProUGUI