---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mac.
--- DateTime: 9/28/21 12:28 PM
---
---@class UITextMeshProUGUIEx : UIBaseComponent
local UITextMeshProUGUIEx = BaseClass("UITextMeshProUGUIEx", UIBaseComponent)
local base = UIBaseComponent
local UnityTextMeshProEx = typeof(CS.NewTMPText)
local Resource = CS.GameEntry.Resource


-- 创建
local function OnCreate(self)
    base.OnCreate(self)
    -- Unity侧原生组件
    self.unity_tmpro = self.gameObject:GetComponent(UnityTextMeshProEx)
	if self.unity_tmpro == nil then
		Logger.LogError("tmpro not found: ", self.__var_arg)
	end
end

-- 获取文本
local function GetText(self)
    return self.unity_tmpro.text
end

-- 设置文本
local function SetText(self, text)
    self.unity_tmpro:Native_SetText(text)
end

local function SetLocalText(self, dialogId, ...)
    dialogId = Localization.GetRealId(dialogId)
    self.unity_tmpro:SetLocalText(dialogId, ...)
end

local function SetText_Cache(self, text)
    self.unity_tmpro:SetTextCacheID(_ToID(text))
end

local function ForceMeshUpdate(self)
    self.unity_tmpro:ForceMeshUpdate()
end

local function GetTotalCharacterCount(self)
    local totalVisibleCharacters = self.unity_tmpro.textInfo.characterCount;
    return totalVisibleCharacters
end

local function SetMaxVisibleCharacters(self, count)
    self.unity_tmpro.maxVisibleCharacters = count
end

-- 销毁
local function OnDestroy(self) 
    if IsNull(self.unity_tmpro) then
		if self.unity_tmpro then
        	Logger.LogError("[BUG]!! fn not found! ", tostring(self.__var_arg))
		end
    else
        self.unity_tmpro.onPointerClick = nil
    end
	
	self.unity_tmpro = nil
    base.OnDestroy(self)
end

local function SetColor(self,value)
    self.unity_tmpro.color = value
end

local function GetColor(self)
    return self.unity_tmpro.color
end

local function GetWidth(self)
    return self.unity_tmpro.preferredWidth
end

local function GetHeight(self)
    return self.unity_tmpro.preferredHeight
end

local function GetLinkInfo(self)
    return self.unity_tmpro.textInfo.linkInfo
end

local function OnPointerClick(self,onPointerClick)
    self.unity_tmpro.onPointerClick = onPointerClick
end

local function SetPreferSize(self, value)
    self.rectTransform.sizeDelta = value
end

local function SetColorRGBA(self,r,g,b,a)
    self.unity_tmpro:Set_color(r, g, b, a)
end

local function GetColorRGBA(self)
    return self.unity_tmpro:Get_color()
end

local function SetAlpha(self,value)
    local color = self:GetColor()
    self:SetColorRGBA(color.r,color.g,color.b,value)
end

local function GetAlpha(self)
    local r,g,b,a = self:GetColorRGBA()
    return a
end

local function SetAlignment( self,_alignment )
    self.unity_tmpro.alignment = _alignment
end

local function SetFontSize(self, size )
    self.unity_tmpro.fontSize = size
end

local function SetMaterial(self, material)
    self.unity_tmpro.fontMaterial = material
end

local function SetColorGradient(self, topLeftColor, topRightColor, bottomLeftColor, bottomRightColor)
    local colorGradient = self.unity_tmpro.colorGradient
    colorGradient.topLeft = topLeftColor
    colorGradient.topRight = topRightColor
    colorGradient.bottomLeft = bottomLeftColor
    colorGradient.bottomRight = bottomRightColor
    self.unity_tmpro.colorGradient = colorGradient
end
local function SetCodeEffectText(self, str, callback, startIndex, speed)
	if (speed == nil and startIndex ~= nil) then
		self.unity_tmpro:SetCodeEffectText(str, callback, startIndex)
	elseif speed == nil and startIndex == nil then
		self.unity_tmpro:SetCodeEffectText(str, callback)
	else
		self.unity_tmpro:SetCodeEffectText(str, callback, startIndex, speed)
	end
end

local function SetCodeSpeed(self, speed)
	self.unity_tmpro:SetCodeSpeed(speed)
end

local function ShowCodeTextEffDirect(self)
	self.unity_tmpro:ShowCodeTextEffDirect()
end

local function SetFontMaterialByType(self,materialType)
    if materialType then
        if MediumFontMaterialType[materialType] == nil  then
            Logger.LogError("未注册对应的字体材质")
            return
        end
        if self.materialModel then
            self.materialModel:Release()
            self.materialModel = nil
        end

        self.materialModel = Resource:LoadAssetAsync(string.format(LoadPath.TMPMaterialPath,MediumFontMaterialType[materialType]), typeof(CS.UnityEngine.Material))
        if self.materialModel == nil then
            return
        end
        self.materialModel:completed('+', function(req)
            if self.materialModel and self.materialModel.asset then
                if not self.unity_tmpro then
                    self.materialModel:Release()
                    self.materialModel = nil
                    return
                end
                local material = self.materialModel.asset
                cast(material, typeof(CS.UnityEngine.Material))
                self:SetMaterialPreset(material)
            end
        end)
    end
end

--传入一个材质装上
local function SetMaterialPreset(self,material)
    if self.unity_tmpro  then
        self.unity_tmpro.fontMaterial = material
    end

end

function UITextMeshProUGUIEx:SetEnable(enable)
    self.unity_tmpro.enabled = enable
end

function UITextMeshProUGUIEx:SetRichTextEnable(enable)
    self.unity_tmpro.richText = enable
end

UITextMeshProUGUIEx.OnCreate = OnCreate
UITextMeshProUGUIEx.GetText = GetText
UITextMeshProUGUIEx.SetText = SetText
UITextMeshProUGUIEx.OnDestroy = OnDestroy
UITextMeshProUGUIEx.SetColor = SetColor
UITextMeshProUGUIEx.GetWidth = GetWidth
UITextMeshProUGUIEx.GetHeight = GetHeight
UITextMeshProUGUIEx.GetColor = GetColor
UITextMeshProUGUIEx.GetLinkInfo = GetLinkInfo
UITextMeshProUGUIEx.OnPointerClick = OnPointerClick
UITextMeshProUGUIEx.SetPreferSize = SetPreferSize
UITextMeshProUGUIEx.SetLocalText = SetLocalText
UITextMeshProUGUIEx.SetText_Cache = SetText_Cache
UITextMeshProUGUIEx.SetColorRGBA = SetColorRGBA
UITextMeshProUGUIEx.GetColorRGBA = GetColorRGBA
UITextMeshProUGUIEx.SetAlpha = SetAlpha
UITextMeshProUGUIEx.GetAlpha = GetAlpha
UITextMeshProUGUIEx.SetAlignment = SetAlignment
UITextMeshProUGUIEx.SetFontSize = SetFontSize
UITextMeshProUGUIEx.SetMaterial = SetMaterial
UITextMeshProUGUIEx.SetColorGradient = SetColorGradient

UITextMeshProUGUIEx.ShowCodeTextEffDirect = ShowCodeTextEffDirect
UITextMeshProUGUIEx.ForceMeshUpdate = ForceMeshUpdate
UITextMeshProUGUIEx.GetTotalCharacterCount = GetTotalCharacterCount
UITextMeshProUGUIEx.SetMaxVisibleCharacters = SetMaxVisibleCharacters
UITextMeshProUGUIEx.SetCodeEffectText = SetCodeEffectText
UITextMeshProUGUIEx.SetCodeSpeed = SetCodeSpeed
UITextMeshProUGUIEx.SetFontMaterialByType = SetFontMaterialByType
UITextMeshProUGUIEx.SetMaterialPreset = SetMaterialPreset
return UITextMeshProUGUIEx