---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mac.
--- DateTime: 8/24/21 11:27 AM
---

---@class UITextMeshProUGUI : UIBaseComponent
--[[
-- [INPUT]: 依赖 UIBaseComponent 基类、CS.TMPro.TextMeshProUGUI 原生 TMP 组件；SetLocalText 依赖 Localization
-- [OUTPUT]: 对外提供 UITextMeshProUGUI 组件类，含 GetText/SetText/SetLocalText/SetTextCacheID、SetColor/GetColor、GetWidth/GetHeight、GetLinkInfo 超链接
-- [POS]: Component 层对原生 TMP TextMeshProUGUI 的 Lua 封装；与项目自定义 NewTMPText 相对，后者为推荐的增强版
-- [PROTOCOL]: 变更时更新此头部,然后检查 CLAUDE.md
--]]
local UITextMeshProUGUI = BaseClass("UITextMeshProUGUI", UIBaseComponent)
local base = UIBaseComponent
local UnityTextMeshPro = typeof(CS.TMPro.TextMeshProUGUI)


-- 创建
local function OnCreate(self)
    base.OnCreate(self)
    -- Unity侧原生组件
    self.unity_tmpro = self.gameObject:GetComponent(UnityTextMeshPro)
    self.unity_text = self.unity_tmpro
end

-- 获取文本
local function GetText(self)
    return self.unity_tmpro.text
end

-- 设置文本
local function SetText(self, text)
    text = text and text or ""
    self.unity_tmpro:Native_SetText(text)
end

local function SetLocalText(self, dialogId, ...)
    dialogId = Localization.GetRealId(dialogId)
    self.unity_tmpro:SetLocalText(dialogId, ...)
end

local function SetTextCacheID(self, text)
	self.unity_tmpro:SetTextCacheID(_ToID(text))
end

-- 销毁
local function OnDestroy(self)
    self.unity_tmpro = nil
    self.unity_text = nil
    base.OnDestroy(self)
end

local function SetColor(self,value)
    self.unity_tmpro.color = value
end

local function GetColor(self)
    return self.unity_tmpro.color
end

local function GetWidth(self)
    return self.unity_tmpro.preferredWidth
end

local function GetHeight(self)
    return self.unity_tmpro.preferredHeight
end

local function GetLinkInfo(self)
    return self.unity_tmpro.textInfo.linkInfo
end

UITextMeshProUGUI.OnCreate = OnCreate
UITextMeshProUGUI.GetText = GetText
UITextMeshProUGUI.SetText = SetText
UITextMeshProUGUI.SetLocalText = SetLocalText
UITextMeshProUGUI.SetTextCacheID = SetTextCacheID
UITextMeshProUGUI.OnDestroy = OnDestroy
UITextMeshProUGUI.SetColor = SetColor
UITextMeshProUGUI.GetWidth = GetWidth
UITextMeshProUGUI.GetHeight = GetHeight
UITextMeshProUGUI.GetColor = GetColor
UITextMeshProUGUI.GetLinkInfo = GetLinkInfo

return UITextMeshProUGUI