---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mac.
--- DateTime: 7/12/21 2:51 PM
---


--[[
-- [INPUT]: 依赖全局 ConstClass 包装为只读表，依赖 string 的 findlast 扩展
-- [OUTPUT]: 对外提供只读 PathUtil，暴露 GetFileNameWithoutExtension
-- [POS]: Common 层轻量路径工具，当前仅剥离目录与扩展名取纯文件名；以 ConstClass 包装保证只读
-- [PROTOCOL]: 变更时更新此头部，然后检查 CLAUDE.md
--]]

local PathUtil = {}


local function GetFileNameWithoutExtension(filepath)
    local filename
    local i = filepath:findlast("[/\\]")
    if i then
        filename = filepath:sub(i + 1)
    else
        filename = filepath
    end

    i = filename:findlast(".", true)
    if i then
        return filename:sub(1, i - 1)
    else
        return filename
    end
end

PathUtil.GetFileNameWithoutExtension = GetFileNameWithoutExtension

return ConstClass("PathUtil", PathUtil)