---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Imaginaerum.
--- DateTime: 2021/6/29 15:34
---

---@class CommonUtil
local CommonUtil = {}
local Vibrator = CS.Vibrator
--local Const = require("Scene.PVEBattleLevel.Const")
local CS_Resource = CS.GameEntry.Resource

local LastVibratorTime = 0
local VibratorDuringTime = 200
local useLuaWorldPoint = true

---判断是否在龙战斗服
---@return boolean
local function IsInDragonActivity(targetSeverId)
    local flag1 = LuaEntry.Player.serverType == ServerType.DRAGON_BATTLE_FIGHT_SERVER
    ---加severId的容错
    local curServerId = targetSeverId or LuaEntry.Player:GetCurServerId()
    local flag2 = DataCenter.ActDragonManager:IsDragonSeverId(curServerId)
    
    if flag1 or flag2 then
        return true
    end
    return false
end

--[[
    是否使用新版世界
    在editor模式下使用新版
    在apk模式下  debug 判定版本号
                release下判定大版本号
]]
local function CheckIsNewWorld()
    New_Lua_World = true
    
    --if App.IsEditor() then
    --    New_Lua_World = true
    --else
    --    local _versionCode = App.GetVersionCode()
    --    if App.IsDebug() then
    --        if _versionCode >= 682 then
    --            New_Lua_World = true
    --        else
    --            New_Lua_World = false
    --        end
    --    else
    --        local _version = App.GetVersion()
    --        if string.IsNullOrEmpty(_version) then
    --            New_Lua_World = false
    --        else
    --            local _tabVersion = string.split(_version, '.')
    --            if table.count(_tabVersion) == 3 then
    --                if tonumber(_tabVersion[3]) > 638 then
    --                    New_Lua_World = true
    --                else
    --                    New_Lua_World = false
    --                end
    --            else
    --                New_Lua_World = false
    --            end
    --        end
    --    end
    --end    
end

function CommonUtil.CheckDeepLinkOpenView()
    if  CS.ApplicationLaunch.Instance.GetDeepLinkUrl~=nil then
        local url = CS.ApplicationLaunch.Instance:GetDeepLinkUrl()
        if not string.IsNullOrEmpty(url) then
            local arr = string.split(url,"=")
            if #arr>=2 then
                if DataCenter.LoginPopManager.showReplaceTip == false then
                    DataCenter.LoginPopManager.showDeepLinkOpen = true
                    DataCenter.LoginPopManager.isOpenZooming = false
                    local sceneName = arr[2]
                    if sceneName == "msj" then
                        --DataCenter.FoodFestivalManager:PopFoodFestivalPanel()
                    end
                end
            end
        end
        CS.ApplicationLaunch.Instance:SetDeepLinkUrl("")
    end

end

--[[
local function SendErrorMessageToServer(curTime, delayTime, errorMsg)
    if CommonUtil.IsEditor() then
        return
    end

    --目前c项目日志都是client_event记录的， 这里先屏蔽
    --if LuaEntry.DataConfig:CheckSwitch("bug_report") ==  true then
    --    SFSNetwork.SendMessage(MsgDefines.ClientLog,curTime, delayTime, errorMsg)
    --end
end
]]
local function GetTimeDiamondCost(remainSec, useK4)
    if remainSec <= 0 then
        return 0
    end
    if remainSec < 1 then
        return 1
    end
    local costNum = 1
    local k1 = LuaEntry.DataConfig:TryGetNum("cd_gold","k1")
    local k2 = LuaEntry.DataConfig:TryGetNum("cd_gold","k2")
    local k3 = LuaEntry.DataConfig:TryGetNum("cd_gold","k3")
    if useK4 == true then
        local k4 = LuaEntry.DataConfig:TryGetNum("cd_gold","k4")
        if k4 == 0 then
            k4 = 1
        end
        costNum = math.floor(tonumber(k4) * remainSec*tonumber(k3)/(tonumber(k1)*Mathf.Pow(remainSec/3600,(tonumber(k2)/100))))
    else
        costNum = math.floor(remainSec*tonumber(k3)/(tonumber(k1)*Mathf.Pow(remainSec/3600,(tonumber(k2)/100))))
    end
    if costNum<=0 then
        costNum = 1
    end
    return costNum
end

local function IsCrossServerIgnoreThrone()
    local curServerId = LuaEntry.Player:GetCurServerId()
    if CrossServerUtil:GetIsCrossServer() then
        local crossBuildData = DataCenter.BuildManager:GetFunbuildByItemID(BuildingTypes.WORM_HOLE_CROSS)
        if crossBuildData == nil or crossBuildData.server ~= curServerId then
            return true
        end
    end
    return false
end

local function IsCrossThroneStart()
    return DataCenter.CrossWonderManager:IsCrossThroneStart()
end

local function GetResourceDescriptionByType (resourceType)
    local template = DataCenter.ResourceTemplateManager:GetResourceTemplate(resourceType)
    if template ~= nil then
        return Localization:GetString(template.description)
    end
    return ""
end

local function GetResOrItemCount(resOrItemId)
    if resOrItemId > ResourceType.None and resOrItemId < ResourceType.Max then
        if resOrItemId == ResourceType.Gold then
            return LuaEntry.Player.gold
        end
        
        return LuaEntry.Resource:GetCntByResType(resOrItemId)
    end
    
    return CommonUtil.GetItemCount(resOrItemId)
end

local function GetGuideClickAutoStopTime()
    return GuideClickAutoStopTime
end

local function GetResOrItemIcon(resOrItemId)
    resOrItemId = tonumber(resOrItemId)
    if resOrItemId == nil then
        return string.format(LoadPath.ItemPath, '')
    end
    
    if resOrItemId > ResourceType.None and resOrItemId < ResourceType.Max then
        assert(ResourceTypeIconName[resOrItemId] ~= nil, 'GetResOrItemIcon res icon is nil! resOrItemId:' .. tostring(resOrItemId))
        return ResourceTypeIconName[resOrItemId] or ''
    end
    
    local template = DataCenter.ItemTemplateManager:GetItemTemplate(resOrItemId)
    --assert(template ~= nil, 'GetResOrItemIcon template is nil! resOrItemId:' .. tostring(resOrItemId))
    if template == nil then
        Logger.LogError('GetResOrItemIcon template is nil! resOrItemId:' .. tostring(resOrItemId))
    end
    
    return string.format(LoadPath.ItemPath, template and template.icon or '')
end

function CommonUtil.GetSoundGroupId(itemId)
    local goodTemplate = DataCenter.ItemTemplateManager:GetItemTemplate(itemId)
    return goodTemplate and goodTemplate:GetSoundGroupId() or nil
end


--获取种类
local function GetBuildBaseType(id)
    return id - id % BuildLevelCap
end

--获取等级
local function GetBuildLv(id)
    return id % BuildLevelCap
end

--获取种类
local function GetScienceBaseType(id)
    return id - id % ScienceLevelCap
end

--获取等级
local function GetScienceLv(id)
    return id % ScienceLevelCap
end


DetectEventColor =
{
    DETECT_EVENT_WHITE = 1,
    DETECT_EVENT_GREEN = 2,
    DETECT_EVENT_BLUE = 3 ,
    DETECT_EVENT_PURPLE = 4,
    DETECT_EVENT_ORANGE = 5,
    DETECT_EVENT_GOLDEN = 6,
    DETECT_EVENT_RED    = 7,
}

local function GetDetectEventQualityColor(quality)
    if quality == DetectEventColor.DETECT_EVENT_WHITE then
        return DetectEventWhiteColor
    elseif quality == DetectEventColor.DETECT_EVENT_GREEN then
        return DetectEventGreenColor
    elseif quality == DetectEventColor.DETECT_EVENT_BLUE then
        return DetectEventBlueColor
    elseif quality == DetectEventColor.DETECT_EVENT_PURPLE then
        return DetectEventPurpleColor
    elseif quality == DetectEventColor.DETECT_EVENT_ORANGE then
        return DetectEventOrangeColor
    elseif quality == DetectEventColor.DETECT_EVENT_GOLDEN then
        return DetectEventGoldenColor
    elseif quality == DetectEventColor.DETECT_EVENT_RED then
        return DetectEventRedColor
    end
    return DetectEventWhiteColor
end

function CommonUtil.GetDetectEventQualityColorStr(quality)
    if quality == DetectEventColor.DETECT_EVENT_WHITE then
        return "#BEB7C0FF"
    elseif quality == DetectEventColor.DETECT_EVENT_GREEN then
        return "#94E138FF"
    elseif quality == DetectEventColor.DETECT_EVENT_BLUE then
        return "#5FA3EDFF"
    elseif quality == DetectEventColor.DETECT_EVENT_PURPLE then
        return "#A66CF0FF"
    elseif quality == DetectEventColor.DETECT_EVENT_ORANGE then
        return "#FA8843FF"
    elseif quality == DetectEventColor.DETECT_EVENT_GOLDEN then
        return "#FCCD38FF"
    elseif quality == DetectEventColor.DETECT_EVENT_RED then
        return "#F26A67FF"
    end
    return "#BEB7C0FF"
end

local function GetDetectEventQualityName(quality)
    if quality == DetectEventColor.DETECT_EVENT_WHITE then
        return GameDialogDefine.QUALITY_NAME_WHITE
    elseif quality == DetectEventColor.DETECT_EVENT_GREEN then
        return GameDialogDefine.QUALITY_NAME_GREEN
    elseif quality == DetectEventColor.DETECT_EVENT_BLUE then
        return GameDialogDefine.QUALITY_NAME_BLUE
    elseif quality == DetectEventColor.DETECT_EVENT_PURPLE then
        return GameDialogDefine.QUALITY_NAME_PURPLE
    elseif quality == DetectEventColor.DETECT_EVENT_ORANGE then
        return GameDialogDefine.QUALITY_NAME_ORANGE
    elseif quality == DetectEventColor.DETECT_EVENT_GOLDEN then
        return GameDialogDefine.QUALITY_NAME_GOLDEN
    elseif quality == DetectEventColor.DETECT_EVENT_RED then
        return GameDialogDefine.QUALITY_NAME_RED
    end
    --logErrorWithTag("GetQualityName", "Undefined quality_"..quality)
    return ""
end

function CommonUtil.GetDetectEventBannerQualityName(quality)
    if quality == DetectEventColor.DETECT_EVENT_WHITE then
        return "Detect_event_greys"
    elseif quality == DetectEventColor.DETECT_EVENT_GREEN then
        return "Detect_event_greens"
    elseif quality == DetectEventColor.DETECT_EVENT_BLUE then
        return "Detect_event_blues"
    elseif quality == DetectEventColor.DETECT_EVENT_PURPLE then
        return "Detect_event_purples"
    elseif quality == DetectEventColor.DETECT_EVENT_ORANGE then
        return "Detect_event_oranges"
    elseif quality == DetectEventColor.DETECT_EVENT_GOLDEN then
        return "Detect_event_golds"
    elseif quality == DetectEventColor.DETECT_EVENT_RED then
        return "Detect_event_reds"
    end
    --logErrorWithTag("GetQualityName", "Undefined quality_"..quality)
    return ""
end

--得到中间点的连接方向（用于连路特效）
local function GetDirByPos(lastPos,curPos,nextPos)
    if (lastPos == nil or (lastPos.x == 0 and lastPos.y == 0)) and (nextPos == nil or (nextPos.x == 0 and nextPos.y == 0)) then
        return ConnectDirection.Right, ConnectDirection.LeftToRight
    elseif lastPos == nil or (lastPos.x == 0 and lastPos.y == 0) then
        if nextPos.x == curPos.x then
            if nextPos.y < curPos.y then
                return ConnectDirection.Down, ConnectDirection.TopToDown
            else
                return ConnectDirection.Top, ConnectDirection.DownToTop
            end
        else
            if nextPos.x < curPos.x then
                return ConnectDirection.Left, ConnectDirection.RightToLeft
            else
                return ConnectDirection.Right, ConnectDirection.LeftToRight
            end
        end
    elseif nextPos == nil or (nextPos.x == 0 and nextPos.y == 0) then
        if lastPos.x == curPos.x then
            if lastPos.y > curPos.y then
                return ConnectDirection.Top, ConnectDirection.TopToDown
            else
                return ConnectDirection.Down, ConnectDirection.DownToTop
            end
        else
            if lastPos.x > curPos.x then
                return ConnectDirection.Right, ConnectDirection.RightToLeft
            else
                return ConnectDirection.Left, ConnectDirection.LeftToRight
            end
        end
    else
        if lastPos.x == curPos.x then
            if lastPos.y > curPos.y then
                if nextPos.x == curPos.x then
                    if nextPos.y < curPos.y then
                        return ConnectDirection.TopToDown, ConnectDirection.TopToDown
                    else
                        return ConnectDirection.Top, ConnectDirection.DownToTop
                    end
                elseif nextPos.x > curPos.x then
                    return ConnectDirection.TopToRight, ConnectDirection.TopToRight
                else
                    return ConnectDirection.TopToLeft, ConnectDirection.TopToLeft
                end
            else
                if nextPos.x == curPos.x then
                    if nextPos.y > curPos.y then
                        return ConnectDirection.DownToTop, ConnectDirection.DownToTop
                    else
                        return ConnectDirection.Down, ConnectDirection.TopToDown
                    end
                elseif nextPos.x > curPos.x then
                    return ConnectDirection.DownToRight, ConnectDirection.DownToRight
                else
                    return ConnectDirection.DownToLeft, ConnectDirection.DownToLeft
                end
            end
        elseif lastPos.x > curPos.x then
            if nextPos.y == curPos.y then
                if nextPos.x < curPos.x then
                    return ConnectDirection.RightToLeft, ConnectDirection.RightToLeft
                else
                    return ConnectDirection.Right, ConnectDirection.LeftToRight
                end
            elseif nextPos.y > curPos.y then
                return ConnectDirection.RightToTop, ConnectDirection.RightToTop
            else
                return ConnectDirection.RightToDown, ConnectDirection.RightToDown
            end
        else
            if nextPos.y == curPos.y then
                if nextPos.x > curPos.x then
                    return ConnectDirection.LeftToRight, ConnectDirection.LeftToRight
                else
                    return ConnectDirection.Left, ConnectDirection.RightToLeft
                end
            elseif nextPos.y > curPos.y then
                return ConnectDirection.LeftToTop, ConnectDirection.LeftToTop
            else
                return ConnectDirection.LeftToDown, ConnectDirection.LeftToDown
            end
        end
    end

    return ConnectDirection.Right, ConnectDirection.LeftToRight
end

--是否满足科技条件
local function CheckIsScienceEnough(scienceId,scienceLv)
    if scienceId==nil or scienceLv == nil then
        return true
    else
        return DataCenter.ScienceManager:GetScienceLevel(scienceId)>=scienceLv
    end
end
--是否满足建筑条件
local function CheckIsBuildEnough(buildId,buildLv)
    if buildId==nil or buildLv == nil then
        return true
    else
        return DataCenter.BuildManager:IsExistBuildByTypeLv(buildId,buildLv)
    end
end
--是否满足资源道具条件
local function CheckIsResourceGoodsEnough(needGoodsId,needGoodsNum)
    if needGoodsId ==nil or needGoodsNum == nil then
        return true
    else
        local cnt = 0
        local item = DataCenter.ResourceItemDataManager:GetItemDataByItemId(needGoodsId)
        if item~=nil then
            cnt = item.number
        end
        return needGoodsNum <= cnt
    end
end
--是否满足资源条件
local function CheckIsResourceEnough(needResourceType,needResourceNum)
    if needResourceType==nil or needResourceNum == nil then
        return true
    else
        local totalNum = needResourceNum
        return totalNum <= LuaEntry.Resource:GetCntByResType(needResourceType)
    end
end

--钻石抵资源换算
local function GetResGoldByType(type,num)
    if ResourceCanNotChangeByDiamond[type] then
        return 0
    end
    
    local ret = 0
    local a = 0
    local b = 0
    local c = 0
    local d = 0
    local k = 0
    local cost_k1 = LuaEntry.DataConfig:TryGetNum("resource_cost", "k1")
    local cost_k2 = LuaEntry.DataConfig:TryGetNum("resource_cost", "k2")
    local cost_k3 = LuaEntry.DataConfig:TryGetNum("resource_cost", "k3")
    local cost_k4 = LuaEntry.DataConfig:TryGetNum("resource_cost", "k4")
    if type == ResourceType.Oil then
        d = LuaEntry.DataConfig:TryGetNum("resource_num3", "k2")
    elseif type == ResourceType.Metal then
        d = LuaEntry.DataConfig:TryGetNum("resource_num3", "k4")
    elseif type == ResourceType.Electricity then
        d = LuaEntry.DataConfig:TryGetNum("resource_num3", "k5")
    elseif type == ResourceType.Money then
        d = LuaEntry.DataConfig:TryGetNum("resource_num3", "k6")
        k = LuaEntry.DataConfig:TryGetNum("resource_num3", "k7")
    elseif type == ResourceType.Water then
        d = LuaEntry.DataConfig:TryGetNum("resource_num3", "k8")
    elseif type == ResourceType.Wood then
        d = LuaEntry.DataConfig:TryGetNum("resource_num3", "k9")
    end
    local curNum = num*d
    if curNum<=cost_k1 then
        a = LuaEntry.DataConfig:TryGetNum("resource_num1", "k1")
        b = LuaEntry.DataConfig:TryGetNum("resource_num1", "k2")
        c = LuaEntry.DataConfig:TryGetNum("resource_num1", "k3")
   elseif curNum>cost_k1 and curNum<=cost_k2 then
        a = LuaEntry.DataConfig:TryGetNum("resource_num1", "k4")
        b = LuaEntry.DataConfig:TryGetNum("resource_num1", "k5")
        c = LuaEntry.DataConfig:TryGetNum("resource_num1", "k6")
    elseif curNum>cost_k2 and curNum<=cost_k3 then
        a = LuaEntry.DataConfig:TryGetNum("resource_num1", "k7")
        b = LuaEntry.DataConfig:TryGetNum("resource_num1", "k8")
        c = LuaEntry.DataConfig:TryGetNum("resource_num1", "k9")
    elseif curNum>cost_k3 and curNum<=cost_k4 then
        a = LuaEntry.DataConfig:TryGetNum("resource_num1", "k10")
        b = LuaEntry.DataConfig:TryGetNum("resource_num1", "k11")
        c = LuaEntry.DataConfig:TryGetNum("resource_num1", "k12")
    elseif curNum>cost_k4 then
        a = LuaEntry.DataConfig:TryGetNum("resource_num2", "k1")
        b = LuaEntry.DataConfig:TryGetNum("resource_num2", "k2")
        c = LuaEntry.DataConfig:TryGetNum("resource_num2", "k3")
    end
    if type == ResourceType.Money then
        ret = math.floor(Mathf.Pow(curNum,b)*k*a+c) 
    else
        ret = math.floor(Mathf.Pow(curNum,b)*a+c)
    end
    ret = math.max(ret,1)
    return ret
end

local function GetNameByParams(msgId,paramList)
    if msgId==nil or msgId=="" then
        return ""
    end
    local num = 0
    local text = ""
    if paramList~=nil then
        num = #paramList
    end
	
	-- FIXME: 我没看明白，这个不就是一个unpack操作吗？
	-- 下面这段代码等同： text = CS.GameEntry.Localization:GetString(msgId, unpack(paramList)) ？？？？
    if num<1 then
        text = CS.GameEntry.Localization:GetString(msgId)
    elseif num ==1 then
        text = CS.GameEntry.Localization:GetString(msgId,paramList[1])
    elseif num ==2 then
        text = CS.GameEntry.Localization:GetString(msgId,paramList[1],paramList[2])
    elseif num ==3 then
        text = CS.GameEntry.Localization:GetString(msgId,paramList[1],paramList[2],paramList[3])
    elseif num ==4 then
        text = CS.GameEntry.Localization:GetString(msgId,paramList[1],paramList[2],paramList[3],paramList[4])
    elseif num ==5 then
        text = CS.GameEntry.Localization:GetString(msgId,paramList[1],paramList[2],paramList[3],paramList[4],paramList[5])
    elseif num ==6 then
        text = CS.GameEntry.Localization:GetString(msgId,paramList[1],paramList[2],paramList[3],paramList[4],paramList[5],paramList[6])
    elseif num ==7 then
        text = CS.GameEntry.Localization:GetString(msgId,paramList[1],paramList[2],paramList[3],paramList[4],paramList[5],paramList[6],paramList[7])
    elseif num ==8 then
        text = CS.GameEntry.Localization:GetString(msgId,paramList[1],paramList[2],paramList[3],paramList[4],paramList[5],paramList[6],paramList[7],paramList[8])    
    end
    return text
end

local function GetResourceNameByType(resourceType)
    return DataCenter.ResourceManager:GetResourceNameByType(resourceType)
end


-- FIXME: UnityEngine.GUIUtility.systemCopyBuffer = "Target String";
-- 如上代码不好用吗？没有详细测试
local function CopyTextToClipboard(content)
    local te = CS.UnityEngine.TextEditor()
    te.text = content
    te:OnFocus()
    te:Copy()
end

-- 获取所有active = true的节点集合
-- FIXME：这种操作要放到C#层
--[[
local function GetNodeActivePaths(obj, parentName, tblActive, tblInactive)

	local fullName
	if string.IsNullOrEmpty(parentName) then
		fullName = obj.name
	else
		fullName = parentName .. '/' .. obj.name
	end

	if obj.activeSelf then
		if tblActive then
			tblActive[#tblActive+1] = fullName
		end
	else
		if tblInactive then
			tblInactive[#tblInactive+1] = fullName
		end
	end

	local nodeRoot = obj.transform
	local childCount = nodeRoot.childCount
	for i = 0, childCount - 1 do
		local child = nodeRoot:GetChild(i).gameObject

		GetNodeActiveNames(child, fullName, tbl)
	end
end

-- 根据路径设置所有的节点为true
local function SetNodeActivePaths(obj, tblActive, tblInactive)
	for k,v in ipairs(tblActive) do
		local t = obj.transform:Find(v)
		if t then
			t:SetActive(true)
		end
	end
	
	for k,v in ipairs(tblInactive) do
		local t = obj.transform:Find(v)
		if t then
			t:SetActive(false)
		end
	end
	
end
]]

function CommonUtil.GetRoleDialogIdByLandState( landId, stateType )
    if landId == nil then return end
    local _speech = GetTableData(TableName.LandLock, landId, "speech")
    if string.IsNullOrEmpty(_speech) then return end
    local _tabSpeech = string.string2array_i(_speech, ';')
    if table.count(_tabSpeech) ~= 4 then
        return
    end
    return _tabSpeech[stateType]
end

--钻石抵资源换算
local function GetItemGoldByItemId(itemId,num)
    local ret = 0
    local goods = DataCenter.ItemTemplateManager:GetItemTemplate(itemId)
    if goods ~= nil and goods.price > 0 then
        ret = math.ceil(goods.price * num)
    end
    return ret
end

local function GetValueWithLocalType(value, localType)
    if localType == EffectLocalType.Num then
        return string.GetFormattedSeperatorNum(value)
    elseif localType == EffectLocalType.Time then
        return UITimeManager:GetInstance():SecondToFmtString(value)
    elseif localType == EffectLocalType.Percent then
        return value .. "%"
    elseif localType == EffectLocalType.Dialog then
        return Localization:GetString(value)
    elseif localType == EffectLocalType.PositiveNum then
        return "+" .. string.GetFormattedSeperatorNum(value)
    elseif localType == EffectLocalType.NegativeNum then
        return "-" .. string.GetFormattedSeperatorNum(value)
    elseif localType == EffectLocalType.PositiveTime then
        return "+" .. UITimeManager:GetInstance():SecondToFmtString(value)
    elseif localType == EffectLocalType.NegativeTime then
        return "-" .. UITimeManager:GetInstance():SecondToFmtString(value)
    elseif localType == EffectLocalType.PositivePercent then
        return "+" .. value .. "%"
    elseif localType == EffectLocalType.NegativePercent then
        return "-" .. value .. "%"
    else
        return value
    end
end

local function GetEffectReasonDesc(reasonType)
    if reasonType == EffectReasonType.Science then
        return 100025
    elseif reasonType == EffectReasonType.Building then
        return 310148
    elseif reasonType == EffectReasonType.Hero then
        return 100275
    elseif reasonType == EffectReasonType.VIP then
        return 320293
    elseif reasonType == EffectReasonType.MONTH_CARD then
        return 320243
    elseif reasonType == EffectReasonType.PLAYER_LEVEL then
        return 120987
    elseif reasonType == EffectReasonType.Hero_Station then
        return 110179
    elseif reasonType == EffectReasonType.Science_Activity then
        return 100374 -- 其他
    elseif reasonType == EffectReasonType.Alliance_Science then
        return 390148
    elseif reasonType == EffectReasonType.World_Alliance_City then
        return 300724
    elseif reasonType == EffectReasonType.Status then
        return 100162
    elseif reasonType == EffectReasonType.Tank then
        return 131200
    elseif reasonType == EffectReasonType.Career then
        return 395000
    elseif reasonType == EffectReasonType.Alliance_Career then
        return 395003
    else
        return 100374 -- 其他
    end
end

--播放游戏BGM
local function PlayGameBgMusic()
    --local guideBgmName =  DataCenter.GuideManager:GetGuideBgmName()
    --if guideBgmName ~= nil and guideBgmName ~= "" then
    --    CS.GameEntry.Sound:PlayBGMusicByName(guideBgmName)
    --elseif DataCenter.BuildManager:IsInNewUserWorld() then
    --    CS.GameEntry.Sound:PlayGuideSceneBgMusic()
    --else
    --    CS.GameEntry.Sound:PlayMainSceneBGMusic()
    --end
end


--震动手机统一接口
local function VibratorLightImpact()
    local curTime = UITimeManager:GetInstance():GetServerTime()
    local durTime = curTime - LastVibratorTime
    if durTime >= VibratorDuringTime then
        LastVibratorTime = curTime
        Vibrator.LightImpact()
    end
end


-- 从池中加载资源
-- 需要保存返回值，并在不使用的时候手动释放
local function LoadResAsync(resPath, func, presetParent)
	local id = StringLookupTable.Get(resPath)
	local Request = CS_Resource:InstantiateAsyncId(id, 
		function (req)
			
			if req.isError then
				Logger.LogError("Load prefab error : ", resPath)
				--return
			end
			
			if req.gameObject == nil then
				Logger.LogError("Load prefab null : ", resPath)
				--return
			end
			
			if func then
				func(req)
			end
		end, presetParent)
	
	if Request == nil then
		Logger.LogError("LoadResAsync error. ", resPath)
	end
	return Request
end

local function isFort( cityId )
    if cityId ~= nil and ( cityId == Fort_1 or cityId == Fort_2 or cityId == Fort_3)  then
        return true
    end
    return false
end

-- 获取服务器ID
local function GetServerId()
	local zoneStr = Setting:GetPublicString(SettingKeys.SERVER_ZONE, "")
	if string.IsNullOrEmpty(zoneStr) then
		Logger.LogError("GetServerId no server zone!")
		return 0
	end

	local t = string.match(zoneStr, '%d+')
	if t == nil then
		Logger.LogError("GetServerId is Wrong!!!", zoneStr)
		return 0
	end

	return math.tointeger(t)
end

local function GetOwnCountByCommonCostType(needType, itemId)
    if needType == CommonCostNeedType.Resource then
        return LuaEntry.Resource:GetCntByResType(itemId)
    elseif needType == CommonCostNeedType.ResourceItem then
        return DataCenter.ResourceItemDataManager:GetCountByItemId(itemId)
    elseif needType == CommonCostNeedType.Goods then
        --return CommonUtil.GetItemCount(itemId)
        return CommonUtil.GetItemCount(itemId)
    end
end


local function GetOwnCountByCommonCostType(needType, itemId)
    if needType == CommonCostNeedType.Resource then
        return LuaEntry.Resource:GetCntByResType(itemId)
    elseif needType == CommonCostNeedType.ResourceItem then
        return DataCenter.ResourceItemDataManager:GetCountByItemId(itemId)
    elseif needType == CommonCostNeedType.Goods then
        return CommonUtil.GetItemCount(itemId)
    end
end

function Is(obj, typeClass)
    local is_generic = xlua.get_generic_method(CS.CommonUtils, 'Is') --取得泛型方法
    local is_func = is_generic(typeClass) --为泛型方法指定类型
    local ret = is_func(obj)

    return ret
end

function CommonUtil.PlayAnimationReturnTime(simpleAnimation, animName)
    local anim = simpleAnimation:GetState(animName)
    if anim == nil then
        return false
    end

    simpleAnimation:Play(animName)
    return true, simpleAnimation:GetClipLength(animName)
end

function List_GetFirstTypeObject(list, typeClass)
    for _, obj in pairs(list) do
        if Is(obj, typeClass) then
            return obj
        end
    end

    return nil
end

function IsEditor()
	return App.IsEditor()
end

--[[
function CommonUtil.OnDisConnect()
    GoToUtil.CloseAllWindows()
    if not CrossServerUtil:GetIsCrossServer() and SceneManager.IsInWorld() then
        DataCenter.WorldPointManager:OnChangeServerRemove()
    end
    CrossServerUtil.OnDisConnect()
    --DataCenter.VitaManager:SetDoTimeAction(false)
    EventManager:GetInstance():Broadcast(EventId.Disconnect)
end
]]

-- 这里包一层，主要是为了防止json解析出错！而导致的程序异常情况！！
function JsonDecode(text)
	local rapidjson = require "rapidjson"
	local ok, ret = xpcall(rapidjson.decode, debug.traceback, text)
	if ok then 
		return ret
	else
		Logger.LogError("JsonDecode error: ", text)
		return {}
	end
end

-- 打开商店
function OpenGooglePlay()
	Logger.Log("OpenGooglePlay:", LuaEntry.GlobalData.downloadurl)
	CS.CommonUtils.OpenURL(LuaEntry.GlobalData.downloadurl);
end

function CommonUtil.IsTaskSuccess(questId)
    local template = DataCenter.QuestTemplateManager:GetQuestTemplate(questId)
    if template == nil then
        Logger.LogError("questId not found: ", tostring(questId))
        return false
    end

    -- 13表示关卡任务
    if template.type1 == 13 then
        return DataCenter.TaskManager:CheckLevelIsSuccess(questId)
    else
        return DataCenter.ChapterTaskManager:CheckIsSuccess(questId)
    end
end


--道具是否为survival道具
function CommonUtil.IsSurvivalItem(itemId)
    local template = DataCenter.ItemTemplateManager:GetItemTemplate(itemId)
    local type = template and template.type or 0
    return type >= SurvivalItemType.Sundries and type <= SurvivalItemType.Feed
end

--统一获取道具数量接口
function CommonUtil.GetItemCount(itemId)
    --survival rpg
    --if CommonUtil.IsSurvivalItem(itemId) then
    --    return DataCenter.BagGridDataManager:GetPlayerItemCount(itemId, true)
    --end

    --aps slg
    local count = DataCenter.ItemData:GetItemCount(itemId)
    return count
end

--获取排行显示图片路径和显示文字
--前三iconName不为nil showName为nil
--rank == 0 或者 == nil iconName 为nil  showName为 "未上榜"
--其他 iconName 为nil  showName为 rank
local function GetRankImgAndShowText(rank)
    local iconName = nil
    local showName = nil
    if rank == nil or rank <= 0 then
        showName = CS.GameEntry.Localization:GetString(GameDialogDefine.UN_RANK)
    elseif rank <= SpecialRankNum then
        iconName = string.format("Assets/Main/Sprites/UI/UIAlliance/rank/UIalliance_rankingbg0%s.png", rank)
    else
        showName = tostring(rank)
    end
    return iconName, showName
end

function CommonUtil.GetRankItemBg(rank, isSelf)
    if isSelf then
        return RankItemBg[5]
    end
    
    if rank > 3 then
        return RankItemBg[4]
    end
    
    return RankItemBg[rank]
end

-- 是否大富翁开始
local function IsMonopolyActive()
    return DataCenter.BuildManager:HasBuilding(BuildingTypes.FUN_BUILD_VILLA)
end

local function IsUseLuaWorldPoint()
    return useLuaWorldPoint
end
local function SetIsUseLuaWorldPoint(value)
    useLuaWorldPoint = value
end

function CommonUtil.GetColorName(color,str)
    if str == nil or color == nil then
        return nil
    end
    local t = {}
    t[1] = "<color="
    t[2] = color
    t[3] = ">"
    t[4] = str
    t[5] = "</color>"
    return table.concat(t)
end

function CommonUtil.GetFreeSpeedUpBubbleIcon()
    local reBubbleInfo = {}
    local mistressId = LuaEntry.DataConfig:TryGetNum("free_build_mistress", "k1")
    if DataCenter.MistressLvTemplateManager:IsUnlock(mistressId) then
        local baseData = DataCenter.MistressLvTemplateManager:GetBaseData(mistressId)
        if baseData then
            reBubbleInfo.type = FreeTimeBubbleType.Girl
            reBubbleInfo.icon = string.format(LoadPath.GirlIconsSmall, baseData.bubblesIcon)
            reBubbleInfo.name = baseData.name
            return reBubbleInfo
        end
    else
        local hero = DataCenter.HeroDataManager:GetFreeAddTimeHero(EffectDefine.BUILD_TIME_REDUCE)
        if hero then
            reBubbleInfo.type = FreeTimeBubbleType.Hero
            reBubbleInfo.icon = HeroUtils.GetHeroIconRoundPath(hero.heroId)
            reBubbleInfo.name = hero.config.name
            return reBubbleInfo
        end
    end
    
    reBubbleInfo.type = FreeTimeBubbleType.Build
    reBubbleInfo.icon = string.format(LoadPath.ItemPath,"item200")
    reBubbleInfo.name = 100291
    return reBubbleInfo
end

local defaultcarimg = "Assets/Main/Sprites/UI/UIMain2.0/UIMainNew/biandui_icon_car0.png"
function CommonUtil.GetFormationCarIcon()
    local carskinid = DataCenter.GarageRefitManager:GetCarUnlockIndex(true)
    local carshowtemplate = DataCenter.GarageRefitManager:GetCarShowConfig(carskinid)
    if carshowtemplate and not string.IsNullOrEmpty(carshowtemplate.icon_army) then
        local iconpath = string.format(LoadPath.UIMainNew2,carshowtemplate.icon_army)
        return iconpath
    else
        return defaultcarimg
    end
end

function CommonUtil.NeedShowPrivacy()
    if App.IsDebug() then
        local alreadyShow = Setting:GetPublicBool(SettingKeys.ALREADY_SHOW_PLAYER_PRIVACY, false)
        return not alreadyShow
    end
    
    if CS.GameEntry.Sdk.IsShowEuropeanUnionPrivacy~=nil and CS.GameEntry.Sdk.IsShowEuropeanUnionPrivacy()==true then
        local alreadyShow = Setting:GetPublicBool(SettingKeys.ALREADY_SHOW_PLAYER_PRIVACY, false)
        return not alreadyShow
    end
    
    return false
end

--[[
function CommonUtil.CheckRecordPlayerPrivacy()
    local needRecord = Setting:GetPublicBool(SettingKeys.NEED_RECORD_PLAYER_PRIVACY, false)
    if needRecord then
        local deviceId = App.GetDeviceUid()
        local curVersion = CS.GameEntry.Sdk.Version
        local deviceType = CS.GameEntry.GlobalData.analyticID
        local uid = LuaEntry.Player.uid
        local net = CS.GameEntry.Device:GetNetworkTypeDesc()
        local curTime = UITimeManager:GetInstance():GetServerTime()
        SFSNetwork.SendMessage(MsgDefines.UserAgreeTos, deviceId, net, uid, tostring(curTime), curVersion, deviceType)
        Setting:SetPublicBool(SettingKeys.NEED_RECORD_PLAYER_PRIVACY, false)
    end
end
]]

function CommonUtil.IsEUCountry()
    local gmFlag = Setting:GetPublicInt(SettingKeys.GM_FLAG, 0)
    if gmFlag == 1 then
        return true
    end
    
    for _, v in ipairs(DmaCountry) do
        if v == App.GetFromCountry() then
            return true
        end
    end
    return false
end

function CommonUtil:OpenUrl(url)
    CS.GameEntry.Sdk:OpenUrl(url)
end

--region 位运算

---获得二进制标志位
---@public
---@param bit number
---@param index number
---@return number (0 或者 1)
function CommonUtil.GetBitFlag(bit, index)
    return (bit & (1 << index)) >> index
end

---设置二进制标志位
---@public
---@param bit number
---@param index number
---@param value number (0 或者 1)
---@return number
function CommonUtil.SetBitFlag(bit, index, value)
    local tmp = 1 << index
    if value > 0 then
        bit = bit | tmp
    else
        bit = bit & ~tmp
    end
    return bit
end

--endregion

-- 是否是官网包
function CommonUtil.IsLocalAPK()
    local _packageName = App.GetPackageName()
    if _packageName == "com.readygo.barrel.local" then
        return true
    end
    return false
end

function CommonUtil.HasSeasonFormationEffect()
    local seasonFormationAtkAdd = LuaEntry.Effect:GetGameEffect(EffectDefine.SEASON_FORMATION_ATK_ADD)
    local seasonFormationDefAdd = LuaEntry.Effect:GetGameEffect(EffectDefine.SEASON_FORMATION_DEF_ADD)
    local seasonFormationDamageAdd = LuaEntry.Effect:GetGameEffect(EffectDefine.SEASON_FORMATION_DAMAGE_ADD)
    return seasonFormationAtkAdd > 0 or seasonFormationDefAdd > 0 or seasonFormationDamageAdd > 0
end

CommonUtil.IsUseLuaWorldPoint = IsUseLuaWorldPoint
CommonUtil.SetIsUseLuaWorldPoint = SetIsUseLuaWorldPoint

CommonUtil.IsMonopolyActive = IsMonopolyActive
CommonUtil.GetTimeDiamondCost = GetTimeDiamondCost
CommonUtil.GetResourceDescriptionByType = GetResourceDescriptionByType
CommonUtil.GetResOrItemCount = GetResOrItemCount
CommonUtil.GetResOrItemIcon = GetResOrItemIcon
CommonUtil.GetScienceBaseType = GetScienceBaseType
CommonUtil.GetScienceLv = GetScienceLv
CommonUtil.GetBuildBaseType = GetBuildBaseType
CommonUtil.GetBuildLv = GetBuildLv
CommonUtil.GetDetectEventQualityColor = GetDetectEventQualityColor
CommonUtil.GetDetectEventQualityName = GetDetectEventQualityName
CommonUtil.GetDirByPos = GetDirByPos
CommonUtil.CheckIsScienceEnough = CheckIsScienceEnough
CommonUtil.CheckIsBuildEnough = CheckIsBuildEnough
CommonUtil.CheckIsResourceGoodsEnough = CheckIsResourceGoodsEnough
CommonUtil.CheckIsResourceEnough = CheckIsResourceEnough
CommonUtil.GetResGoldByType = GetResGoldByType
CommonUtil.GetNameByParams = GetNameByParams
CommonUtil.GetResourceNameByType = GetResourceNameByType
CommonUtil.CopyTextToClipboard = CopyTextToClipboard
CommonUtil.GetNodeActivePaths = GetNodeActivePaths
CommonUtil.GetItemGoldByItemId = GetItemGoldByItemId
--CommonUtil.SendErrorMessageToServer = SendErrorMessageToServer
CommonUtil.GetValueWithLocalType = GetValueWithLocalType
CommonUtil.GetEffectReasonDesc = GetEffectReasonDesc
CommonUtil.PlayGameBgMusic = PlayGameBgMusic

CommonUtil.VibratorLightImpact = VibratorLightImpact
CommonUtil.LoadResAsync = LoadResAsync
CommonUtil.GetOwnCountByCommonCostType = GetOwnCountByCommonCostType
CommonUtil.IsEditor = IsEditor
CommonUtil.JsonDecode = JsonDecode
CommonUtil.OpenGooglePlay = OpenGooglePlay
--CommonUtil.GetServerId = GetServerId
CommonUtil.GetServerId = GetServerId
CommonUtil.GetRankImgAndShowText = GetRankImgAndShowText
CommonUtil.GetGuideClickAutoStopTime = GetGuideClickAutoStopTime
CommonUtil.isFort = isFort
CommonUtil.IsCrossThroneStart = IsCrossThroneStart
CommonUtil.IsCrossServerIgnoreThrone = IsCrossServerIgnoreThrone
CommonUtil.CheckIsNewWorld = CheckIsNewWorld
CommonUtil.IsInDragonActivity = IsInDragonActivity
	
return ConstClass("CommonUtil", CommonUtil)