---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zlh.
--- DateTime: 2022/12/2 11:17
---
-- 声音系统
-- 原则，策划将声音配在一个表内，便于维护
-- 程序写代码的时候，按照声音的基本属性（描述）去播放音效，
-- 这样可以达成音效播放的灵活性
-- (*) 声音表格注释
-- 声音表主要由group，SubType，param1, param2 来标识声音的来源
-- group 表示声音的分类，详细参考SoundGroupId；不同的group，subtype及param表示的含义不同
-- playType 则用来控制声音播放的规则
-- soundType 表示声音文件的类型
-- soundList 表示声音的列表
-- 代码在处理的时候，是分别按照类型来处理的


local CS_Sound = CS.GameEntry.Sound
---@class SoundUtil
local SoundUtil = {}

local SoundGroupId = 
{
	Misc = 1,		-- 无法分类的音效，用一个id来表示，类似语言id
	UI = 2,			-- UI音效             SubType 表示UI的prefabname
	Gather = 3,		-- 可拾取物           SubType 表示声音分组id
	Actor = 4,		-- 表示角色动作音效    SubType 表示角色模型的prefab  param1 表示动作名称
	Weapon = 5,		-- 使用武器时的音效    SubType 表示使用的武器模型prefab name, param1 表示是攻击attack还是采集tool
	Scene = 6,		-- 表示关卡的声音
	Building = 7,	-- 建筑音效           SubType 表示建筑ID， param1 表示建筑正在进行的状态，譬如正在生产XX东西
	Item = 8,		-- 道具音效     
	Action = 9,		-- 行为音效			  SubType 行为字符串标识，某个行为对应一个音效
	Button = 10,	-- 按钮音效			  SubType 按钮的名称（根据按钮名称播放声音），另外可以配置到按钮的UIExtraData组件上
	Hero = 11,      -- 英雄音效           SubType 英雄ID
}



local SoundType =
{
    Music = 0,
    Effect = 1
}

local PlayType =
{
    None = 0,
    Sequence = 1,
    Random = 2,
}

-- 开箱子的音效param1类型
local GatherAction = 
{
	Lock = 1,
	Unlock = 2,
}

-- 武器音效的param1类型
local WeaponAction = 
{
	Attack = 1,  	-- 武器攻击，挥出
	Tool = 2,	 	-- 武器采集
	Broken = 3,  	-- 武器损坏
	BeHit = 4,	 	--	击中
	BeHitKill = 5 	--	击杀
}
SoundUtil.WeaponAction = WeaponAction

-- 道具声音param2动作类型
local ItemAction = 
{
	Select = 1,		-- 选中 
	Put	= 2,		-- 放置
	Use = 3,		-- 使用
	Forge = 4,		-- 蓝图制作
}
SoundUtil.ItemAction = ItemAction

-- 白天夜晚
local DayNight =
{
	Day = 1,
	Night = 2,
}
SoundUtil.DayNight = DayNight

--SceneGroup下BGM的类型
--1=前期引导环节：进行引导剧情时播放，可通过noviceboot配置
--2=主城日常-白天：进入主城场景，为白天时间时播放。
--3=主城日常-夜晚：进入主城场景，为夜晚时间时播放。
--4=关卡战斗：进入战斗关卡时播放。
--5=特殊战斗：进入特殊类型战斗时播放，如竞技场战斗
--6=服务器-世界-和平：进入世界场景，和平状态时播放。
--7=服务器-世界-战斗：进入世界场景，被攻击/战争狂热时播放。
--9=竞技场备战界面音乐
--10=竞技场获胜音乐
--11=巨龙战场(峡谷争夺战)音乐
local SceneSoundSubType = 
{
	Guide = 1,
	MainCity_Day = 2,
	MainCity_Night = 3,
	BarrelBattle = 4,
	OtherBattle = 5,
	World_Peace = 6,
	World_War = 7,
	Throne_War = 8,
	Arena_Prepare = 9,
	Arena_Trump = 10,
	Dragon_Battle = 11,
}
SoundUtil.SceneSoundSubType = SceneSoundSubType
-- 声音总表，里面存储着具体的分类
-- 
local soundTable = {}

-- 初始化系统声音表格
-- 此时subtype表示一个唯一的音效索引，类似于语言id
function SoundUtil.InitSystemSound(lineData)
	local line = {}
	
	local rawId = math.tointeger(lineData["id"])
	
	return rawId, nil, line
end

-- 同步AudioListener的位置
function SoundUtil.SyncListenerPos(x, y, z)
	CS_Sound:SetAudioListenerPosition(x, y, z)
end

function SoundUtil.Play3DSound(go, name)	
	return CS_Sound:Play3DSoundAtGO(go, name)
end

function SoundUtil.Stop3DSound(go)
	return CS_Sound:Stop3DSoundAtGO(go)
end

function SoundUtil.Remove3DSoundAll()
	CS_Sound:Remove3DSoundAll()
end

-- 初始化系统声音表格
-- 此时subtype表示一个UI的prefabname
function SoundUtil.InitUISound(lineData)
	local line = {}

	local prefabname = lineData["SubType"]

	return prefabname, nil, line
end

-- 可拾取物声音表格
-- 此时subtype表示gather id，如果是-1的话，表示通用音效
function SoundUtil.InitLootSound(lineData)
	local line = {}
	local k2 = GatherAction.Unlock

	local gatherSoundGroupId = math.tointeger(lineData["SubType"])
	
	-- lock/ unlock 表示箱子是否为第一次开
	if lineData["param1"] == 'lock' then
		k2 = GatherAction.Lock
	end

	return gatherSoundGroupId, k2, line
end

-- 角色动作声音表格
-- 此时subtype表示角色的模型字符串，如果是0的话，表示主角
-- param1 表示的是角色的动作
function SoundUtil.InitActorSound(lineData)
	local line = {}

	local actor_name = lineData["SubType"]
	local actor_action = lineData["param1"]

	return actor_name, actor_action, line
end

-- 使用武器声音表格
-- 此时subtype表示武器的类型
-- param1 表示的是武器的动作, attack = 1, tool = 2
function SoundUtil.InitWeaponSound(lineData)
	local line = {}
	local k2 = WeaponAction.Tool

	local weapon_name = lineData["SubType"]
	local weapon_action = lineData["param1"]
	
	if weapon_action == 'attack' then
		k2 = WeaponAction.Attack
	elseif weapon_action == 'break' then
		k2 = WeaponAction.Broken
	elseif weapon_action == 'behit' then
		k2 = WeaponAction.BeHit
	elseif weapon_action == 'behitkill' then
		k2 = WeaponAction.BeHitKill
	end

	return weapon_name, k2, line
end

-- 场景背景音乐
-- 此时SubType存放的是场景id
function SoundUtil.InitSceneMusic(lineData)
	local line = {}
	
	local sceneSoundSubType = math.tointeger(lineData["SubType"])
	local param = math.tointeger(lineData["playType"]) or 0

	if sceneSoundSubType == SceneSoundSubType.BarrelBattle then
		--主线关卡和其他Scene组的param含义不同！！！
		local param1Str = lineData["param1"]
		if (string.contains(param1Str, '-')) then
			--关卡范围
			local Range1, Range2 = string.split_ii(param1Str,'-')
			param = {}
			param.min = Range1
			param.max = Range2
		elseif tonumber(param1Str) ~= nil then
			--指定关卡
			param = tonumber(param1Str)
		else
			--加入随机
			param = nil
		end
		
	end
	
	return sceneSoundSubType, param, line
end

--[[
14 		电锯丧尸
22      英雄派遣
4;2   	普通怪
4;3   	巨型丧尸
22  	废墟
4;9		狂暴首领

11;85     中立城市
11;1     王座
11;103  炮塔
]]
function SoundUtil.PlayWorldMusic(pointType, subType, param, pointIndex)
	if pointType == 14 then -- 电锯丧尸
		SoundUtil.PlayEffect(SoundAssets.Click_Butcher)
	elseif pointType == 22 then -- 废墟
		SoundUtil.PlayEffect(SoundAssets.Click_Container)
	elseif pointType == 4 then
		if subType == 2 then
			local index = math.random(1,3)
			local _randNum = Mathf.Random()
			if _randNum > 0.5 then
				SoundUtil.PlayEffect(SoundAssets.Click_Monster_Female .. tostring(index))
			else
				SoundUtil.PlayEffect(SoundAssets.Click_Monster_Male .. tostring(index))
			end
		elseif subType == 3 then -- 集结怪
			SoundUtil.PlayEffect(SoundAssets.Click_Gaint)
		elseif subType == 9 then -- 狂暴首领
			SoundUtil.PlayEffect(SoundAssets.Click_Worldboss)
		end
	elseif pointType == 11 then
		if subType ~= nil then
			if subType == 1 then  -- 王座
				SoundUtil.PlayEffect(SoundAssets.Click_Throne)
			elseif subType == 103 then -- 炮台
				SoundUtil.PlayEffect(SoundAssets.Click_Turret)
			else
				SoundUtil.PlayEffect(SoundAssets.Click_WorldCity)
			end
		end
	elseif pointType == 13 then
		if pointIndex ~= nil then
			local data = DataCenter.WorldPointManager:GetSamplePointInfoByIndex(pointIndex)
			if data and data.eventId then
				local template = DataCenter.DetectEventTemplateManager:GetDetectEventTemplate(data.eventId)
				if template then
					if template.type == DetectEventType.RESCUE or template.type == DetectEventType.DetectEventPickGarbage then
						SoundUtil.PlayEffect("world/effect_click_container")
					end
				end
			end
		end
	end
end

-- 建筑音乐
function SoundUtil.InitBuildingMusic(lineData)
	local line = {}

	local buildingId = math.tointeger(lineData["SubType"])
	local param = math.tointeger(lineData["param1"])
	
	return buildingId, param, line
end

-- 道具音乐
-- item 的音效注释
--默认点选音效
--SubType = 0
--param2 = 1表示选中 2表示放置

--特定道具播放音效（最优先）
--SubType = 1 表示播放特定itemid的音效
--param1 = itemId
--param2 = 1表示选中 2表示放置

--道具分类型播放音效
--SubType = 2
--param1 = group id ，填在goods表的某列，表示道具的逻辑类型
--param2 = 1表示选中 2表示放置
--param2 = 3表示使用
--param2 = 4表示蓝图制作
function SoundUtil.InitItemMusic(lineData)
	local line = {}

	local subType = math.tointeger(lineData["SubType"])	
	local param1 = math.tointeger(lineData["param1"])
	local param2 = math.tointeger(lineData["param2"])
	
	-- key1 = 0表示通用特效
	-- key1 = 2用负数表示sound group
	local key1 
	if subType == 0 then
		key1 = 0
	elseif subType == 1 then
		key1 = param1
	elseif subType == 2 then
		key1 = -param1
	end

	return key1, param2, line
end

-- 行为绑定音乐
-- 这个和1无法归类的区别就是，1使用一个id去表示一个音效
-- 而这个使用一个字符串去表示一个音效，维护起来相对容易一些
function SoundUtil.InitActionMusic(lineData)
	local line = {}

	local actionname = tostring(lineData["SubType"])

	return actionname, nil, line
end

-- 初始化按钮声音
function SoundUtil.InitButtonEffect(lineData)
	local line = {}

	local buttonname = lineData["SubType"]

	return buttonname, nil, line
end

-- 初始化英雄音效
function SoundUtil.InitHeroSound(lineData)
	local line = {}

	local heroId = tonumber(lineData["SubType"])

	return heroId, nil, line
end

-- 解析声音配置的每一行，主要是解析ID，SubType，param1, param2这几个字段
-- 其余的字段是惰性解析的
function ParseSoundLine(id, lineData)
	
	local k1,k2,v
	
	-- 声音大的分类
	local typeId = lineData['group']

	-- 根据不同类型的规则去进行解析
	-- 有些类型只有一个索引，有些类型是两级索引
	if typeId == SoundGroupId.Misc then
		k1,k2,v = SoundUtil.InitSystemSound(lineData)
		
	elseif typeId == SoundGroupId.UI then
		k1,k2,v = SoundUtil.InitUISound(lineData)
		
	elseif typeId == SoundGroupId.Gather then
		k1,k2,v = SoundUtil.InitLootSound(lineData)
		
	elseif typeId == SoundGroupId.Actor then
		k1,k2,v = SoundUtil.InitActorSound(lineData)
		
	elseif typeId == SoundGroupId.Weapon then
		k1,k2,v = SoundUtil.InitWeaponSound(lineData)
		
	elseif typeId == SoundGroupId.Scene then
		k1,k2,v = SoundUtil.InitSceneMusic(lineData)
		
	elseif typeId == SoundGroupId.Building then
		k1,k2,v = SoundUtil.InitBuildingMusic(lineData)
	
	elseif typeId == SoundGroupId.Item then
		k1,k2,v = SoundUtil.InitItemMusic(lineData)
	
	elseif typeId == SoundGroupId.Action then
		k1,k2,v = SoundUtil.InitActionMusic(lineData)

	elseif typeId == SoundGroupId.Button then
		k1,k2,v = SoundUtil.InitButtonEffect(lineData)

	elseif typeId == SoundGroupId.Hero then
		k1,k2,v = SoundUtil.InitHeroSound(lineData)
		
	end

	if k1 == nil then
		return
	end
	
	-- 设置原始声音id
	v.c_sound_id = id
	
	-- 加入到指定类型列表
	if soundTable[typeId] == nil then
		soundTable[typeId] = {}
	end

	local typeTable = soundTable[typeId]
	
	--单独处理场景音效
	--先以k1(SceneSoundSubType)存储各种情况下的音效
	--再以k2(PlayType)存储统一情况下的不同播放方式(Sequence or Random)的音效
	--对于SceneSoundSubType.BarrelBattle类型下，不用考虑k2这种播放方式，而是单独的播放策略：param1配了范围则范围内的关卡播放，没配则在所有没配的里随机一个
	if typeId == SoundGroupId.Scene then
		if typeTable[k1] == nil then
			typeTable[k1] = {}
		end
		if k1 ~= SceneSoundSubType.BarrelBattle then
			if typeTable[k1][k2] == nil then
				typeTable[k1][k2] = {}
			end
			table.insert(typeTable[k1][k2],v)
		else
			local typeK2 = type(k2)
			if typeK2 == "table" then
				for i = k2.min,k2.max do
					typeTable[k1][i] = v
				end
			elseif typeK2 == "number" then
				typeTable[k1][k2] = v
			else
				if typeTable[k1].RandomRange == nil then
					typeTable[k1].RandomRange = {}
				end
				table.insert(typeTable[k1].RandomRange,v)
			end
		end
		return
	end
	
	-- 一个索引和两个索引的情况
	if k2 == nil then
		typeTable[k1] = v
	else 
		if typeTable[k1] == nil then
			typeTable[k1] = {}
		end
		typeTable[k1][k2] = v
	end
	
	return
end

-- 初始化声音表格
function SoundUtil.InitSound()
	table.clear(soundTable)
	LocalController:instance():visitTable(TableName.C_Sound, ParseSoundLine)
	--local t
	--SoundUtil.SceneMusicTableProcess()
end

function SoundUtil.SceneMusicTableProcess() --场景音乐Table处理
	for k,v in pairs(soundTable[SoundGroupId.Scene]) do
		--local Range = string.split_ii_array(k,'-')  -- 配置表中是这样配置 例如 "300-305"
		--if table.count(Range) > 1  then
		if string.contains(k, '-') then
			local Range1, Range2 = string.split_ii(k,'-')  -- 配置表中是这样配置 例如 "300-305"
			if Range1 and Range2 then
				if Range2 < Range1 then return end  --右值小于左值，则区间不成立
				for i = Range1, Range2 do     --1是范围区间最小值，2是范围区间最大值
					soundTable[SoundGroupId.Scene][i] = v
				end
				soundTable[SoundGroupId.Scene][k] = nil   --移除表中类似300-305这样的键值对，让表只保留key为关卡Id，一一对应
			end
		end
	end
end

function SoundUtil.GetSoundInternal(v, soundList, playType)
	
    local length = table.length(soundList)
    if length <= 1 or playType == PlayType.None then
        return soundList[1]
    end

    if playType == PlayType.Random then
        local idx = math.random(length)
        return soundList[idx]
    end

    if playType == PlayType.Sequence then
        local lastIdxFromZero = v.curIdxFromZero or -1
        local curIdxFromZero = Mathf.Repeat(lastIdxFromZero + 1, length)
        v.curIdxFromZero = curIdxFromZero

        return soundList[curIdxFromZero + 1] -- to lua index 
    end

    return soundList[1]
end

-- 获取播放的声音名字
function SoundUtil.GetSoundName(v)
	local t_sound = TableName.C_Sound
	local playType = LocalController:instance():getValue(t_sound, v.c_sound_id, 'playType')

	-- 第一次的时候解析一次
	if v.soundListArray == nil then
		local soundListStr = LocalController:instance():getValue(t_sound, v.c_sound_id, 'soundList')
		if string.find(soundListStr, '|') == nil then
			v.soundListArray = soundListStr
		else
			v.soundListArray = string.split_ss_array(soundListStr, '|')
		end
	end

	-- 获取一个声音文件
	local soundName = v.soundListArray
	if type(v.soundListArray) == 'table' then
		soundName = SoundUtil.GetSoundInternal(v, v.soundListArray, playType)
	end
	
	return soundName
end

-- 最终播放一条声音数据
function SoundUtil.FinalPlaySound(v)
	local t_sound = TableName.C_Sound
	local soundType = v.soundType 
	local soundName = v.soundListArray
	local volume = 1
	
	if v.c_sound_id ~= nil then
		soundType = GetTableNumber(t_sound, v.c_sound_id, 'soundType', 1)
		--@liusiyang 不在代码中控制音量了
		--volume = GetTableNumber(t_sound, v.c_sound_id, 'Volume')
		--if volume <= 0 then
		--	volume = 1.0
		--else
		--	volume = tonumber(volume) or 1.0
		--end
		
		soundName = SoundUtil.GetSoundName(v)
	end
	
	-- 根据类型播放，到底是音乐还是音效
	if soundType == SoundType.Music then
		local curSoundName = CS_Sound:GetCurPlayMusicName()
		if curSoundName ~= soundName then
			CS_Sound:PlayBGMusicByName(soundName, volume)
		end
		return -1
	end
	
	-- 这个代码这么临时处理一下吧，否则修改的地方略多，播放英雄声音的时候，使用playsound
	if v.group == SoundGroupId.Hero then
		local soundAsset = "Assets/Main/Sound/Effect/" .. soundName .. ".ogg"
		local playId = CS_Sound:PlaySound(soundAsset, "Hero", nil, false)
		return playId
	end
	
	-- loop的简易处理
	-- 底层loop同时只能播放一个，这样我们必须要手动控制好
	local loop = false
	if v.c_sound_id ~= nil then
		loop = GetTableNumber(t_sound, v.c_sound_id, 'Loop')
		if loop == 1 then
			loop = true
			local group = GetTableNumber(t_sound, v.c_sound_id, 'group')
			if group ~= 1 then
				Logger.LogError('loop effect must be group = 1!!')
				return -1
			end
		else
			loop = false
		end
	end
	--Logger.Log("SUSoundUtils.FinalPlay" .. soundName)
	local playId = CS_Sound:PlayEffect(_ToID(soundName), loop, volume)
	return playId
end

function SoundUtil.GetCurPlayMusicName()
	local curSoundName = CS_Sound:GetCurPlayMusicName()
	return curSoundName
end

-- 通过文件名播放声音
function SoundUtil.PlayEffect(effectName)
	local v = {}
	v.soundListArray = effectName
	v.soundType = SoundType.Effect
	return SoundUtil.FinalPlaySound(v)
end

function SoundUtil.PlaySound(soundName)
	local v = {}
	v.soundListArray = soundName
	v.soundType = SoundType.Music
	return SoundUtil.FinalPlaySound(v)
end

-- 播放loop的声音，播放完要记得stop
function SoundUtil.PlayLoopEffect(effectName)
	local serialID = CS_Sound:PlayEffect(effectName, true)
	return serialID
end

function SoundUtil.StopLoopEffect(serialID)
	CS_Sound:StopSound(serialID)
end

-- 播放loop的声音，这个要传groupName，因为一个Group中只能同时有一个Loop声音
-- 这个时候要传递完整的路径
function SoundUtil.PlayLoopSound(soundFullPath, groupName)
	if groupName == nil then groupName = SoundGround.LoopSound end
	local serialID = CS_Sound:PlaySound(soundFullPath, groupName, nil, true)
	SoundUtil.ResetGroupMute(groupName)
	return serialID
end

function SoundUtil.StopGroupSound(groupName)
	CS_Sound:StopGroupSound(_ToID(groupName))
end

-- 播放未归类的声音，未归类声音就靠一个id来表示唯一性
-- 此时可以获取一个音效的播放id，然后可以停止
function SoundUtil.PlaySoundById(soundId)
    --local cfg = LocalController:instance():getLine(TableName.C_Sound, soundId)
	local cfg = soundTable[SoundGroupId.Misc][soundId]
    if cfg == nil then
        Logger.LogError('SoundUtil:PlaySoundById error! cfg not exist! soundId:' .. soundId)
        return -1
    end
	
	local id = SoundUtil.FinalPlaySound(cfg)
	return id
end

-- 播放第一次拾取声音
function SoundUtil.PlayFirstGatherSound(gatherId)
		
	local soundtype = GetTableNumber(TableName.PVETriggerGather, gatherId, 'soundtype')
	if soundtype <= 0 then
		return
	end
	
	local cfg = soundTable[SoundGroupId.Gather][soundtype]
	if cfg and cfg[GatherAction.Lock] then
		SoundUtil.FinalPlaySound(cfg[GatherAction.Lock])	
		return
	end
	
end

-- 播放拾取声音 
function SoundUtil.PlayGatherSound(gatherId)
	local soundtype = GetTableNumber(TableName.PVETriggerGather, gatherId, 'soundtype')
	if soundtype <= 0 then
		return 
	end
	
	local cfg = soundTable[SoundGroupId.Gather][soundtype]
	if cfg and cfg[GatherAction.Unlock] then
		SoundUtil.FinalPlaySound(cfg[GatherAction.Unlock])
		return
	end

	-- 如果要播放默认声音的话，让策划自己在gather表里配一个soundtype即可
end

-- 播放人物动作音效
-- actorPrefabName = '0' 表示主角
function SoundUtil.PlayActorActionSound(actorPrefabName, action)
	
	local cfg = soundTable[SoundGroupId.Actor][actorPrefabName]
	if cfg and cfg[action] then
		SoundUtil.FinalPlaySound(cfg[action])
	end
end

-- 播放主角动作音效
function SoundUtil.PlayMainActorActionSound(action)

	local cfg = soundTable[SoundGroupId.Actor]["0"]
	if cfg and cfg[action] then
		SoundUtil.FinalPlaySound(cfg[action])
	end
end

-- 播放武器攻击音
-- 通过武器的名字和武器的动作来处理
-- 这里主要用来播放：武器的出手，击中对方，击杀对方三种音效
function SoundUtil.PlayWeaponEffect(weapon_name, action)

	-- print('PlayWeaponEffect play : ' .. weapon_name .. ", action: " .. tostring(action))
	local cfg = soundTable[SoundGroupId.Weapon][weapon_name]
	if cfg and cfg[action] then
		SoundUtil.FinalPlaySound(cfg[action])
		return
	end
	
	-- -1表示默认声音
	cfg = soundTable[SoundGroupId.Weapon]['-1']
	if cfg and cfg[action] then
		SoundUtil.FinalPlaySound(cfg[action])
		return
	end
end

-- 播放武器采集音效
function SoundUtil.PlayWeaponGatherEffect(weapon_name)

	local cfg = soundTable[SoundGroupId.Weapon][weapon_name]
	if cfg and cfg[WeaponAction.Tool] then
		SoundUtil.FinalPlaySound(cfg[WeaponAction.Tool])
		return
	end
	
	-- -1表示默认声音
	cfg = soundTable[SoundGroupId.Weapon]['-1']
	if cfg and cfg[WeaponAction.Tool] then
		SoundUtil.FinalPlaySound(cfg[WeaponAction.Tool])
		return
	end
	
end

-- 武器损坏时播放
function SoundUtil.PlayWeaponBrokenEffect(weapon_name)

	local cfg = soundTable[SoundGroupId.Weapon][weapon_name]
	if cfg and cfg[WeaponAction.Broken] then
		SoundUtil.FinalPlaySound(cfg[WeaponAction.Broken])
		return
	end
	
	-- -1表示默认声音
	cfg = soundTable[SoundGroupId.Weapon]['-1']
	if cfg and cfg[WeaponAction.Broken] then
		SoundUtil.FinalPlaySound(cfg[WeaponAction.Broken])
		return
	end
end


---- 播放场景音乐
---- 场景音乐有白天和夜晚
--function SoundUtil.PlaySceneMusic(sceneId, dayOrNight, isStart)
--	dayOrNight = dayOrNight or DayNight.Day
--	isStart = isStart or false
--	local cfg = soundTable[SoundGroupId.Scene][sceneId]
--	
--	if cfg then
--		-- 如果有夜晚的话，声音就要根据时间切换
--		if cfg[DayNight.Night] then
--			if cfg[dayOrNight] then
--				SoundUtil.FinalPlaySound(cfg[dayOrNight])		
--			end
--			return
--		end
--			
--		-- 没有夜晚音乐，表示只有白天音乐，那么只有第一次的时候播放
--		-- 否则切换白天黑夜的时候声音会有一个断裂
--		if cfg[DayNight.Day] and isStart then
--			SoundUtil.FinalPlaySound(cfg[DayNight.Day]) 
--			return
--		end
--		
--	end	
--end

--sceneSoundSubType:SceneSoundSubType枚举
--playType:PlayType枚举，当sceneSoundSubType为BarrelBattle时playType无意义，不使用
--param:sceneSoundSubType为BarrelBattle时指代关卡的id，其他时指代列表循环递增的值
function SoundUtil.PlaySceneMusic(sceneSoundSubType, playType, param)
	local sceneSubGroup = soundTable[SoundGroupId.Scene][sceneSoundSubType]
	if not sceneSubGroup then
		return -1
	end
	if sceneSoundSubType == SceneSoundSubType.BarrelBattle then
		local targetSound = sceneSubGroup[param]
		if not targetSound and sceneSubGroup.RandomRange ~= nil and #sceneSubGroup.RandomRange > 0 then
			local randomLength = #sceneSubGroup.RandomRange
			targetSound = sceneSubGroup.RandomRange[Mathf.Random(1,randomLength)]
		end
		if targetSound then
			return SoundUtil.FinalPlaySound(targetSound)
		end
		return
	end
	playType = playType == nil and PlayType.Sequence or playType
	local sounds_of_playType = sceneSubGroup[playType]
	if not sounds_of_playType or #sounds_of_playType == 0 then
		Logger.LogError('SoundUtil:PlaySceneMusic error! Guide no sounds of target play type ' .. tostring(playType))
		return -1
	end
	local targetSound = nil
	if playType == PlayType.None then
		_,targetSound = next(sounds_of_playType)
	elseif playType == PlayType.Sequence then
		local seqLength = #sounds_of_playType
		local increaseParam = param or 1
		local key = increaseParam % seqLength
		key = key == 0 and seqLength or key
		targetSound = sounds_of_playType[key]
	elseif playType == PlayType.Random then
		local randomLength = #sounds_of_playType
		local key = Mathf.Random(1,randomLength)
		targetSound = sounds_of_playType[key]
	end
	if targetSound then
		return SoundUtil.FinalPlaySound(targetSound)
	end
end

-- 一个building是否有音乐
function SoundUtil.IsBuildingHasSound(buildingId)
	local cfg = soundTable[SoundGroupId.Building][buildingId]
	if cfg then
		return true
	end
	
	return false
end

-- 通过建筑和建筑参数来获取当前建筑应该播放的声音
function SoundUtil.GetBuildingSound(buildingId, productId)
	local cfg = soundTable[SoundGroupId.Building][buildingId]
	if cfg and cfg[productId] then
		return SoundUtil.GetSoundName(cfg[productId])
	end

	return ""
end

-- 停止所有音乐，包括正在加载中的（一般在切换场景中的时候）
function SoundUtil.StopAllSounds()
	CS_Sound:StopAllSounds()
end

-- 暂停所有的音乐，一般防止和视频音乐混淆
function SoundUtil.PauseAllSounds()
	CS_Sound:PauseAllSound()
end

-- 恢复所有的音乐
function SoundUtil.ResumeAllSounds()
	CS_Sound:ResumeAllSound()
end

-- 暂停某音乐
function SoundUtil.PauseSound(serialID)
	CS_Sound:PauseSound(serialID)
end

-- 恢复某音乐
function SoundUtil.ResumeSound(serialID)
	CS_Sound:ResumeSound(serialID)
end

-- 播放一个道具音效
-- action表示操作道具的具体动作
function SoundUtil.PlayItemEffect(itemId, action)
	
	-- 首先进行itemId匹配
	local cfg = soundTable[SoundGroupId.Item][itemId]
	if cfg and cfg[action] then
		SoundUtil.FinalPlaySound(cfg[action])
		return
	end
	
	-- 然后进行soundgroup处理
	local itemSoundGroupId = CommonUtil.GetSoundGroupId(itemId)
	if itemSoundGroupId then
		cfg = soundTable[SoundGroupId.Item][-itemSoundGroupId]
		if cfg and cfg[action] then
			SoundUtil.FinalPlaySound(cfg[action])
			return
		end
	end
	
	-- 播放一个默认的声音
	cfg = soundTable[SoundGroupId.Item][0]
	if cfg and cfg[action] then
		SoundUtil.FinalPlaySound(cfg[action])
		return
	end
end

-- 点选一个道具音效
function SoundUtil.PlayItemSelectEffect(itemId)
	SoundUtil.PlayItemEffect(itemId, ItemAction.Select)
end

-- 放置一个道具音效
function SoundUtil.PlayItemPutEffect(itemId)
	SoundUtil.PlayItemEffect(itemId, ItemAction.Put)
end

-- 使用一个道具音效
function SoundUtil.PlayItemUseEffect(itemId)
	SoundUtil.PlayItemEffect(itemId, ItemAction.Use)
end

-- 打造一个道具音效
function SoundUtil.PlayItemCraftEffect(itemId)
	SoundUtil.PlayItemEffect(itemId, ItemAction.Forge)
end

-- 播放一个附加音效，需要绑定在UIExtraData组件上
function SoundUtil.PlayGameObjectSound(gameObject)
	local soundId = gameObject:GetComponent_UIExtraSound()
	if soundId > 0 then
		SoundUtil.PlaySoundById(soundId)
	end
	return soundId
end

function SoundUtil.PlayTransformSound(transform)
	local soundId = transform:GetComponent_UIExtraSound()
	if soundId > 0 then
		SoundUtil.PlaySoundById(soundId)
	end
	return soundId
end

-- 当打开UI的时候播放一个UI音效
function SoundUtil.PlayUISoundEffect(ui_name)
	-- 有些UI开启的比较早或者其他原因，这里要处理一下，防止nil
	local t = soundTable[SoundGroupId.UI]
	if t == nil then
		return 
	end

	-- 通用提示条不播发打开声音
	if ui_name == UIWindowNames.UICommonMessageBar then
		return
	end
	
	local cfg = t[ui_name]
	if cfg == nil then
		-- 默认播放一个音效
		--@20241112 @liusiyang 不配的话就不播了
		--CS.GameEntry.Sound:PlayEffect(_ToID('ui/InterfaceOpen'))
		return
	end

	SoundUtil.FinalPlaySound(cfg)
end

-- 播放一个动作音效
function SoundUtil.PlayActionEffect(action_name)
	local t = soundTable[SoundGroupId.Action]
	if t == nil then
		return
	end

	local cfg = t[action_name]
	if cfg == nil then
		return
	end

	SoundUtil.FinalPlaySound(cfg)
end

-- 返回serialID
function SoundUtil.PlayDub(dub_name, callback)
	return CS_Sound:PlayDub(dub_name, callback)
end

function SoundUtil.StopSound(serialID)
	CS_Sound:StopSound(serialID)
end

-- 播放英雄音效
function SoundUtil.PlayHeroSound(heroId)
	-- 有些UI开启的比较早或者其他原因，这里要处理一下，防止nil
	local t = soundTable[SoundGroupId.Hero]
	if t == nil then
		return -1
	end

	local cfg = t[heroId]
	if cfg == nil then
		return -1
	end

	cfg.group = SoundGroupId.Hero
	return SoundUtil.FinalPlaySound(cfg)
end


-- 播放美女配音
-- Mistress和Dub合并
function SoundUtil.PlayMistressDub(dubid, action)
	return CS_Sound:PlayDub(dubid, action)
	
	--dubid = tostring(dubid)
	--
	--if (string.IsNullOrEmpty(dubid)) then
	--	Logger.Debug("playdub invalid name!")
	--	return -1
	--end
	--
	--local lang = App.GetLanguageName()
	--local assetPath = string.format("Assets/Main/Sound/Mistress/%s/%s.ogg", lang, dubid)
	--
	--if (not CS.GameEntry.Resource:HasAsset(assetPath)) then
	--	assetPath = string.format("Assets/Main/Sound/Mistress/en/%s.ogg", dubid)
	--end
	--
	----Assets/Main/Sound/Mistress/en/893003.ogg
	--return CS_Sound:PlaySound(assetPath, "Dub", nil, nil, action)
end

local WorldScopeVolume = 1.0    --当前WorldScope音组的Volume值

---SetWorldScopeMute
---@param mute boolean
function SoundUtil.SetWorldScopeVolume(volume)
	if WorldScopeVolume == volume then
		return
	end
	Logger.Log("SoundUtil SetWorldScopeVolume " .. tostring(volume))
	WorldScopeVolume = volume
	CS_Sound:ChangeVolume(SoundGround.WorldScope, WorldScopeVolume, CS_Sound.PlayWorldScopeEffect and 0 or 0.2)
end

---ResetWorldScopeMute
function SoundUtil.ResetWorldScopeMute()
	WorldScopeVolume = 1.0;
	CS_Sound:ChangeVolume(SoundGround.WorldScope, WorldScopeVolume, CS_Sound.PlayWorldScopeEffect and 0 or 0.2)
end

local worldScopeVolumeEffect = {}
---PlayWorldScopeVolumeEffect
---@param effect_name string 特效名称
---@param random_index number 随机尾数（如果有）
---@return number
function SoundUtil.PlayWorldScopeVolumeEffect(effect_name, random_index)
	if random_index then
		effect_name = effect_name .. math.random(1, random_index)
	end

	local serverTimeS = UITimeManager:GetInstance():GetServerSeconds()
	local playTimes = worldScopeVolumeEffect[effect_name] 
	if playTimes == nil then
		worldScopeVolumeEffect[effect_name] = serverTimeS
	else
		if serverTimeS - playTimes > 0.1 then
			worldScopeVolumeEffect[effect_name] = serverTimeS
		else
			return
		end
	end
	
	if CS_Sound.PlayWorldScopeEffect ~= nil then
		return CS_Sound:PlayWorldScopeEffect(_ToID(effect_name))
	else
		return CS_Sound:PlayEffect(_ToID(effect_name), false, WorldScopeVolume, _ToID(SoundGround.WorldScope))
	end
end

function SoundUtil.GetSoundLength(serialId)
	return CS_Sound:GetSoundLength(serialId)
end

function SoundUtil.ResetGroupMute(GroupName)
	local effectIsMute = not Setting:GetPublicBool(SettingKeys.EFFECT_MUSIC_ON, true)
	CS_Sound:SetSoundGroupMute(GroupName, effectIsMute)
end

function SoundUtil:InitSoundSetting()
	local effectIsMute = not Setting:GetPublicBool(SettingKeys.EFFECT_MUSIC_ON, true)
	local bgIsMute = not Setting:GetPublicBool(SettingKeys.BG_MUSIC_ON, true)

	CS_Sound:SetSoundGroupMute(SoundGround.Music, bgIsMute)
	SoundUtil.__setEffectMuteRuntime(effectIsMute)

	--local hasSnapShot = HasCsClass("UnityEngine.Audio.AudioMixerSnapshot")
	local hasSnapShot = HasCSClassMap.AudioMixerSnapshot
	Logger.Log('#zlh# #sound# hasSnapShot : ' .. tostring(hasSnapShot))
	if hasSnapShot then
		--self:SetupAudioMixer()
	end
end

function SoundUtil:SetupAudioMixer()
	local groups = {
		[SoundGround.Music] = SoundGround.Music,
		[SoundGround.Effect] = SoundGround.Effect,
		[SoundGround.Dub] = SoundGround.Dub,
		[SoundGround.Hero] = SoundGround.Dub,
		[SoundGround.WorldScope] = SoundGround.Effect,
	}
	local GameObject = CS.UnityEngine.GameObject
	local CS_AudioMixer = typeof(CS.UnityEngine.Audio.AudioMixer)
	local CS_AudioSource = typeof(CS.UnityEngine.AudioSource)

	local function callback(req, groupName, mixerName)
		if req == nil or req.asset == nil then
			return
		end

		local asset = req.asset
		cast(asset, CS_AudioMixer)

		local tf = GameObject.Find(string.format('SoundComponent/SoundGroup_%s', groupName))
		if tf == nil then
			return
		end

		local audioSource = tf:GetComponent(CS_AudioSource)
		if audioSource == nil then
			return
		end

		local mg = asset:FindMatchingGroups('Master')
		if mg ~= nil and mg.Length > 0 then
			audioSource.outputAudioMixerGroup = mg[0]
		end
	end

	for groupName, mixerName in pairs(groups) do
		local assetReq = CS.GameEntry.Resource:LoadAssetAsync(string.format('Assets/Main/Sound/Mixer/%s.mixer', mixerName), CS_AudioMixer)
		if assetReq ~= nil then
			assetReq:completed('+', function(req)
				callback(req, groupName, mixerName)
			end)
		end
	end
end

function SoundUtil.__setEffectMuteRuntime(isMute)
	for _, groupName in pairs(SoundGround) do
		if groupName ~= SoundGround.Music then
			CS_Sound:SetSoundGroupMute(groupName, isMute)
		end
	end
end


function SoundUtil.SetEffectMutePersistent(isMute)
	SoundUtil.__setEffectMuteRuntime(isMute)
	Setting:SetPublicBool(SettingKeys.EFFECT_MUSIC_ON, not isMute)
end

function SoundUtil.MuteAllSoundTemporary()
	CS_Sound:SetSoundGroupMute(SoundGround.Music, true)
	SoundUtil.__setEffectMuteRuntime(true)
end

function SoundUtil.RecoverAllSoundMuteState()
	local bgIsMute = not Setting:GetPublicBool(SettingKeys.BG_MUSIC_ON, true)
	local effectIsMute = not Setting:GetPublicBool(SettingKeys.EFFECT_MUSIC_ON, true)

	CS_Sound:SetSoundGroupMute(SoundGround.Music, bgIsMute)
	SoundUtil.__setEffectMuteRuntime(effectIsMute)
end


return ConstClass("SoundUtil", SoundUtil)
