---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangliheng.
--- DateTime: 10/23/2024 2:28 PM
---
--- 先临时糊一版跨服管理器 由于NetProxy的OnExtensionResponse直接回调的CS的NetworkManager且没有区分是否跨服，因此不修改cs的情况下 
--- 只能在lua中直接调用SmartFox了，再找机会复用NetProxy吧

local SmartFox = CS.Sfs2X.SmartFox
local SFSEvent = CS.Sfs2X.Core.SFSEvent
local SFSObject = CS.Sfs2X.Entities.Data.SFSObject
local ExtensionRequest = CS.Sfs2X.Requests.ExtensionRequest
local LoginRequest = CS.Sfs2X.Requests.LoginRequest
local PingPongRequest = CS.Sfs2X.Requests.PingPongRequest

local CMD_WORLD_GET_CROSS = 'world.get.cross'
local CMD_CROSS_LOGIN = 'login'
local CMD_CROSS_LEAVE = 'user.leave.world'


---@class CrossNetWorkManager
local CrossNetworkManager = BaseClass("CrossNetworkManager")

-- 网络打印
local function NetPrint(fmt, ...)
    if App.IsFinalRelease() then
        return
    end
    
    local arg= {...}
    if #arg == 0 then
        print("#zlh# [cross] " .. tostring(fmt))
        return
    end

    print("#zlh# [cross] " .. string.format(fmt, ...))
    return
end

function CrossNetworkManager:__init()
    self.connectStartTime = 0
    self.connectTimeout = 8
    self.retryLimit = 10
    self.retryCount = 0

    self.lastPingPongTime = 0
    self.sendPingPongInterval = 5
    self.offMaxTime = 15
    self.sendPingPongCounter = 0
    self.pingPongReqObj = PingPongRequest()

    self.onConnectionHandler = BindCallback(self, self.__onConnection)
    self.onConnectionLostHandler = BindCallback(self, self.__onConnectionLost)
    self.onExtensionResponseHandler = BindCallback(self, self.__onExtensionResponse)
    self.onPublicMessageHandler = BindCallback(self, self.__onPublicMessage)
    self.onLoginHandler = BindCallback(self, self.__onLogin)
    self.onLoginErrorHandler = BindCallback(self, self.__onLoginError)
    self.onLogoutHandler = BindCallback(self, self.__onLogout)
    self.onSocketException = BindCallback(self, self.__onSocketException)
    self.onPingPong = BindCallback(self, self.__onPingPong)
    
    self.__update_handle = function() self:__update() end
    UpdateManager:GetInstance():AddUpdate(self.__update_handle)
end

function CrossNetworkManager:__delete()
    self:__clearSmartFox()
    UpdateManager:GetInstance():RemoveUpdate(self.__update_handle)
end


--region-----------------------------------对外接口----------------------------------------------

--向跨服目标服务器注册订阅
function CrossNetworkManager:ObserveNewSever(crossSeverParam)
    if crossSeverParam == nil then return end

    if self.isConnecting or self:IsConnected() then
        if self.crossSeverParam ~=nil and self.crossSeverParam.forceServerId == crossSeverParam.forceServerId then
            self.crossSeverParam = crossSeverParam
            if self.loggedIn then
                self:__sendGetCrossRequest()
            end

            return
        end
    end

    local forceServerId = crossSeverParam ~= nil and crossSeverParam.forceServerId
    local debugStr = string.format("ObserveNew serverId: %s", tostring(forceServerId))
    PostEventLog.Record("CrossNet", debugStr)
    NetPrint(debugStr)

    self.crossSeverParam = crossSeverParam
    self:__connect()
end

--取消跨服订阅
function CrossNetworkManager:StopObserver()
    if self:IsConnected() and self.loggedIn then
        self:__sendLeaveRequest()
    end

    local str = debug.traceback()
    PostEventLog.Record("关闭跨服", str)
    
    local forceServerId = self.crossSeverParam ~= nil and self.crossSeverParam.forceServerId
    local debugStr = string.format("StopObserver serverId: %s", tostring(forceServerId))
    PostEventLog.Record("CrossNet", debugStr)
    NetPrint(debugStr)

    self.crossSeverParam = nil
    self.loggedIn = false
    self.connectStartTime = 0
    self.retryCount = 0
    self.lastPingPongTime = 0

    self:__disconnect()
end

function CrossNetworkManager:IsConnecting()
    return self.isConnecting
end

function CrossNetworkManager:IsConnected()
    return self.smartFoxClient ~= nil and self.smartFoxClient.IsConnected
end
--endregion------------------------------------------------------------------------------------


--region-----------------------------------私有函数-----------------------------------------------

function CrossNetworkManager:__isInCrossState()
    --之后对于外部业务是否处于跨服的状态轮询直接放到 CrossServerUtil.GetIsCrossServer()中吧
    if not CrossServerUtil.GetIsCrossServer() then
        return false
    end
    
    if self.crossSeverParam == nil then
        return false
    end
    
    return true
end

function CrossNetworkManager:__initSmartFox()
    self.smartFoxClient = SmartFox()
    self.smartFoxClient.ThreadSafeMode = true

    self.smartFoxClient:AddEventListener(SFSEvent.CONNECTION, self.onConnectionHandler)
    self.smartFoxClient:AddEventListener(SFSEvent.CONNECTION_LOST, self.onConnectionLostHandler)
    self.smartFoxClient:AddEventListener(SFSEvent.EXTENSION_RESPONSE, self.onExtensionResponseHandler)
    self.smartFoxClient:AddEventListener(SFSEvent.PUBLIC_MESSAGE, self.onPublicMessageHandler)
    self.smartFoxClient:AddEventListener(SFSEvent.LOGIN, self.onLoginHandler)
    self.smartFoxClient:AddEventListener(SFSEvent.LOGIN_ERROR, self.onLoginErrorHandler)
    self.smartFoxClient:AddEventListener(SFSEvent.LOGOUT, self.onLogoutHandler)
    self.smartFoxClient:AddEventListener(SFSEvent.SOCKET_EXCEPTION, self.onSocketException)
    self.smartFoxClient:AddEventListener(SFSEvent.PING_PONG, self.onPingPong)
end

function CrossNetworkManager:__clearSmartFox()
    if self.smartFoxClient == nil then
        return
    end

    --先移除监听再disconnect
    self.smartFoxClient:RemoveEventListener(SFSEvent.CONNECTION, self.onConnectionHandler)
    self.smartFoxClient:RemoveEventListener(SFSEvent.CONNECTION_LOST, self.onConnectionLostHandler)
    self.smartFoxClient:RemoveEventListener(SFSEvent.EXTENSION_RESPONSE, self.onExtensionResponseHandler)
    self.smartFoxClient:RemoveEventListener(SFSEvent.PUBLIC_MESSAGE, self.onPublicMessageHandler)
    self.smartFoxClient:RemoveEventListener(SFSEvent.LOGIN, self.onLoginHandler)
    self.smartFoxClient:RemoveEventListener(SFSEvent.LOGIN_ERROR, self.onLoginErrorHandler)
    self.smartFoxClient:RemoveEventListener(SFSEvent.LOGOUT, self.onLogoutHandler)
    self.smartFoxClient:RemoveEventListener(SFSEvent.SOCKET_EXCEPTION, self.onSocketException)
    self.smartFoxClient:RemoveEventListener(SFSEvent.PING_PONG, self.onPingPong)

    self.smartFoxClient:Disconnect()
    self.smartFoxClient = nil
end

function CrossNetworkManager:__connect()
    self:__disconnect()

    if self.smartFoxClient == nil then
        self:__initSmartFox()
    end
    
    local crossServerId = LuaEntry.Player:GetCrossServerId()
    local dt = CrossServerUtil.GetTargetServerIdAndPort(crossServerId)
    local host = dt.host
    local port = dt.port
    if host == nil or port == nil then
        NetPrint('error: ip or port is nil! crossServerId:%s', tostring(crossServerId))
        return
    end
    
    self.connectStartTime = os.time()
    self.isConnecting = true
    self.loggedIn = false
    self:__syncPingPong()
    
    self.smartFoxClient:Connect(host, port)

    local debugStr = string.format("cross_network connect host {%s}, Port {%s}", host, tostring(port))
    PostEventLog.Record("CrossNet", debugStr)
    NetPrint(debugStr)
end

function CrossNetworkManager:__disconnect()
    NetPrint("CrossNetworkManager:do __disconnect")

    self:__clearSmartFox()
    self.loggedIn = false
    self.isConnecting = false
end

function CrossNetworkManager:__reconnect()
    self:__disconnect()

    if not self:__isInCrossState() then
        self:StopObserver()
        return
    end
    
    self.retryCount = self.retryCount + 1
    if self.retryCount > self.retryLimit then
        NetPrint("Max reconnect attempts reached. Aborting.")
        self.isConnecting = false
        return
    end

    local debugStr = string.format("Attempting reconnect (%d/%d)...", self.retryCount, self.retryLimit)
    PostEventLog.Record("CrossNet", debugStr)
    NetPrint(debugStr)
    
    self:__connect()
end

function CrossNetworkManager:__update()
    if self.smartFoxClient ~= nil then
        XPCALL(function()
            self.smartFoxClient:ProcessEvents()
        end)
    end

    if self.isConnecting then
        local now = os.time()
        if now > self.connectStartTime + self.connectTimeout then
            NetPrint("Connection timeout, start reconnect...")
            self:__reconnect()
        end
    end
    
    self:__checkOffline()
end

function CrossNetworkManager:__checkOffline()
    -- 如果在editor模式下，不去处理pingpong，防止调试被卡
    --if App.IsEditor() then
    --    return
    --end
    
    if LuaEntry.GlobalData.pushOffWithQuitGame then
        return
    end

    if AppStartupLoading:GetInstance():IsLoading() then
        return
    end

    if not self:IsConnected() then
        return
    end

    --send pingpong request
    self.sendPingPongCounter = self.sendPingPongCounter + Time.deltaTime
    if self.sendPingPongCounter >= self.sendPingPongInterval then
        self.sendPingPongCounter = 0
        self.smartFoxClient:Send(self.pingPongReqObj)
    end

    if self:__isPingPongTimeOut() then
        NetPrint("PingPong timeout, start reconnect...")
        self:__reconnect()
    end
end

function CrossNetworkManager:__syncPingPong()
    self.lastPingPongTime = os.time()
end

function CrossNetworkManager:__isPingPongTimeOut()
    if self.lastPingPongTime == 0 then
        return false
    end

    local now = os.time()
    if self.offMaxTime > 0 and now > self.lastPingPongTime + self.offMaxTime then
        return true
    end
    
    return false
end

function CrossNetworkManager:__sendLoginRequest()
    local msgId = CMD_CROSS_LOGIN
    local csSfsObj = SFSObject()
    local futureId = LuaEntry.Network:GetFutureManager():getFutureId()
    LuaEntry.Network:GetFutureManager():onSendRequest(futureId, _ToID(msgId))
    csSfsObj:PutInt("_id", futureId)

    local selfSid = LuaEntry.Player:GetSelfServerId()
    local userName = LuaEntry.Player:GetUid()
    local uidStr = selfSid .. "_" .. userName
    csSfsObj:PutUtfString('uid', uidStr)

    local nSid = LuaEntry.Player:GetCrossServerId()
    csSfsObj:PutInt("sid", nSid) 
    --举例注释：我在41服，点击45服查看45的地图  发送给45服务器的login信息(sid:45，fsid:41) byanning
    csSfsObj:PutInt("fsid", selfSid)
    csSfsObj:PutInt("loginType", 1)
    local appVersion = App.GetVersion()
    local appVersionCode = App.GetVersionCode()
    
    csSfsObj:PutUtfString("appVersion", appVersion)
    csSfsObj:PutUtfString("versionCode", appVersionCode)
    local zone = "APS" .. nSid
    
    if App.IsEditor() then
        local jsonStr = csSfsObj:ToJson()
        Logger.Log(string.format("<color=cyan>#zlh# #message# [req][cross] <%s> |</color> {%s}", msgId, jsonStr))
    end

    self.smartFoxClient:Send(LoginRequest(userName, "", zone, csSfsObj))
end

function CrossNetworkManager:__sendGetCrossRequest()
    if not self:__isInCrossState() then
        self:StopObserver()
        return
    end
    
    local msgId = CMD_WORLD_GET_CROSS
    
    local csSfsObj = SFSObject()
    csSfsObj:PutInt("x", self.crossSeverParam.x)
    csSfsObj:PutInt("y", self.crossSeverParam.y)
    csSfsObj:PutLong("timeStamp", UITimeManager:GetInstance():GetServerTime())
    csSfsObj:PutInt("type", self.crossSeverParam.type)
    if self.crossSeverParam.worldId ~= nil then
        csSfsObj:PutInt("worldId", self.crossSeverParam.worldId)
    end

    local sid = LuaEntry.Player:GetSelfServerId()
    if self.crossSeverParam.forceServerId ~= -1 then
        sid = self.crossSeverParam.forceServerId
    end
    csSfsObj:PutInt("serverId", sid)
    
    self:__sendExtensionMessage(msgId, csSfsObj)
end

function CrossNetworkManager:__sendLeaveRequest()
    if not self:IsConnected() and self.loggedIn then
        return
    end
    
    local csSfsObj = SFSObject()
    csSfsObj:PutInt("worldId", LuaEntry.Player:GetCurWorldId())
    self:__sendExtensionMessage(CMD_CROSS_LEAVE, csSfsObj)
end

function CrossNetworkManager:__sendExtensionMessage(msgId, csSfsObj)
    local futureId = LuaEntry.Network:GetFutureManager():getFutureId()
    LuaEntry.Network:GetFutureManager():onSendRequest(futureId, _ToID(msgId))
    csSfsObj:PutInt("_id", futureId)

    if App.IsEditor() then
        local jsonStr = csSfsObj:ToJson()
        Logger.Log(string.format("<color=cyan>#zlh# #message# [req][cross] <%s> |</color> {%s}", msgId, jsonStr))
    end

    self.smartFoxClient:Send(ExtensionRequest(msgId, csSfsObj))
end


--endregion------------------------------------------------------------------------------------


--region------------------------------------SmartFox回调-----------------------------------------

function CrossNetworkManager:__onConnection(baseEvent)
    PostEventLog.Record("CrossNet", "OnConnection")
    NetPrint("OnConnection!")
    
    self.isConnecting = false
    self.connectStartTime = 0
    self.retryCount = 0
    self.sendPingPongCounter = 0

    self:__sendLoginRequest()
end

function CrossNetworkManager:__onConnectionLost(reason, proxy)
    local debugStr = string.format("OnConnectionLost! reason: %s", tostring(reason))
    PostEventLog.Record("CrossNet", debugStr)
    NetPrint(debugStr)


    self:__reconnect()
end

function CrossNetworkManager:__onLogin(baseEvent)
    PostEventLog.Record("CrossNet", "OnLogin StepIn")
    NetPrint("OnLogin StepIn")
    
    self:__syncPingPong()

    local csSfsObj = baseEvent.Params:get_Item('data')
    if csSfsObj == nil then
        PostEventLog.Record("CrossNet", "__onLogin errorCode data is nil!")
        NetPrint("__onLogin errorCode: ", 'data is nil!')
        
        self.loggedIn = false
        self:__disconnect()

        return
    end

    if csSfsObj:ContainsKey('errorMessage') then
        local errorCode = csSfsObj:GetUtfString("errorMessage")
        PostEventLog.Record("CrossNet", string.format("__onLogin errorCode: %s", errorCode))
        NetPrint("__onLogin errorCode: ", 'data is nil!')
        
        self.loggedIn = false
        self:__disconnect()

        return
    end

    local loginResult = false
    if csSfsObj:ContainsKey('loginStatus') then
        if csSfsObj:GetInt('loginStatus') == 0 then
            loginResult = true
        end
    end

    if not loginResult then
        PostEventLog.Record("CrossNet", "__onLogin errorCode: loginResult is false !")
        NetPrint("__onLogin errorCode: loginResult is false !")
        
        self.loggedIn = false
        self:__disconnect()

        return
    end

    PostEventLog.Record("CrossNet", "OnLogin Success!")
    NetPrint("OnLogin Success!")
    
    self.loggedIn = true
    self:__sendGetCrossRequest()
    EventManager:GetInstance():Broadcast(EventId.CrossNetConnectSuccess)
end

function CrossNetworkManager:__onLoginError(errCode, errorMessage)
    PostEventLog.Record("CrossNet", "OnLoginError")
    NetPrint("CrossNetworkManager:OnLoginError")
end

function CrossNetworkManager:__onLogout()
    NetPrint('CrossNetworkManager:OnLogout')
end

function CrossNetworkManager:__onPingPong(baseEvent)
    --NetPrint('CrossNetworkManager:OnPingPong')
    self:__syncPingPong()
end

function CrossNetworkManager:__onSocketException(exception)
    PostEventLog.Record("CrossNet", "OnSocketException")
    NetPrint('CrossNetworkManager:OnSocketException')
    self:__reconnect()
end

function CrossNetworkManager:__onExtensionResponse(baseEvent)
    self:__syncPingPong()

    if baseEvent == nil then
        return
    end

    local cmd = baseEvent.cmd
    if App.IsEditor() then
        local rawData = baseEvent.rawData
        local csSfsObj = SFSObject.NewFromBinaryData(rawData)
        local so = csSfsObj:GetSFSObject("p"):GetSFSObject("p")
        local jsonStr = so:ToJson()
        Logger.Log(string.format("<color=green>#zlh# #message# [res][cross] <%s> |</color> {%s}", cmd, jsonStr))
    end

    if cmd == CMD_WORLD_GET_CROSS or cmd == CMD_CROSS_LEAVE then
        --todo: nothing
    else
        --针对跨服服务器推送的消息 直接透传给原来的消息工厂处理即可
        CS.MessageFactory.Instance:DispatchResponse(baseEvent)
    end
end

function CrossNetworkManager:__onPublicMessage(baseEvent)
end

function CrossNetworkManager:SimulateKill()
    if self.smartFoxClient == nil then
        return
    end
    self.smartFoxClient:KillConnection();
end

--endregion------------------------------------------------------------------------------



return CrossNetworkManager