---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangliheng.
--- DateTime: 2023/1/30 17:52
---

local NetProxy = CS.GameKit.Base.NetProxy
local NetRawProxy = CS.GameKit.Base.NetRawProxy
local ProxyStatus = CS.GameKit.Base.ProxyStatus
local Const = require("Loading.Const")

---@class NetworkManager
local NetworkManager = BaseClass("NetworkManager")

-- 所有的线路列表
local LineList =
{
	{Name = "direct", Address = "game-lm-r1.metapoint.club"},
	{Name = "aws", Address = "game-lm-aws-r1.metapoint.club"},
	{Name = "gcp", Address = "game-lm-gcp-r1.metapoint.club"},
};


-- 网络打印
local function NetPrint(fmt, ...)
	local arg= {...}
	if #arg == 0 then
		print("[NET]" .. tostring(fmt))
		return
	end
	
	print("[NET]" .. string.format(fmt, ...))
	return
end

function NetworkManager:__init()
    self.GameServerUrl = ''
    self.GameServerPort = 0
    self.ZoneName = ''
    self.Uid = ''
    
    self.allSelectProxy = {}
    self.curProxy = nil
    self.cSharpNetwork = CS.GameEntry.Network
    self.futureManger = self.cSharpNetwork:getFutureManager()
	-- 是否正在连接中
	self.isConnecting = false

    self.lastUpdateTime = 0
    self.__update_handle = function() self:Update() end
    UpdateManager:GetInstance():AddUpdate(self.__update_handle)
	
	-- 设置全局变量处理；使用异步网络
--	if CS.NetworkManager.SetUseAsyncTcp ~= nil then
		CS.NetworkManager.SetUseAsyncTcp(1)
--		Logger.Log("!!!SetUseAsyncTCP!!!")
--	end

end

function NetworkManager:__delete()
    UpdateManager:GetInstance():RemoveUpdate(self.__update_handle)
    self.cSharpNetwork = nil
    self.curProxy = nil
	self.isConnecting = false
end

function NetworkManager:SetGameServerUrl(url)
    self.GameServerUrl = url
end

function NetworkManager:GetGameServerUrl()
    return self.GameServerUrl
end

function NetworkManager:SetGameServerPort(port)
    self.GameServerPort = tonumber(port)
end

function NetworkManager:GetGameServerPort()
    return self.GameServerPort
end

function NetworkManager:SetZoneName(zoneName)
    self.ZoneName = zoneName
end

function NetworkManager:GetZoneName()
    return self.ZoneName
end

function NetworkManager:SetUid(uid)
    self.Uid = uid
end

function NetworkManager:GetUid()
    return self.Uid
end

function NetworkManager:SyncPingPong(time)
    if self.curProxy ~= nil then
        time = time or -1
        self.curProxy:SyncPingPong(time)
    end
end

function NetworkManager:IsPingPongTimeOut()
    return self.curProxy and self.curProxy.IsPingPongTimeOut
end

function NetworkManager:SendPingpong()
	if self.curProxy ~= nil then
		self.curProxy:SendPingpong()
	end
	
	return false
end

function NetworkManager:GetServerIdBySharedUser()
    local ret = ''
    local zoneName = self.ZoneName
    if string.IsNullOrEmpty(zoneName) or string.len(zoneName) < 3 then
        return ret
    end

    ret = string.SubStr(zoneName, 4) --FIXME: 确认下是从3开始还是4
    return ret
end

-- 网络是否正在连接
function NetworkManager:IsConnecting()
    --return self.curProxy ~= nil and self.curProxy.IsConnecting
	return self.isConnecting
end

function NetworkManager:IsConnected()
    return self.curProxy ~= nil and self.curProxy.IsConnected
end

function NetworkManager:GetFutureManager()
    return self.futureManger
end

function NetworkManager:GetCurLineProxy()
    return self.curProxy
end

function NetworkManager:GetCurLineName()
    return self.curProxy and self.curProxy.proxyName or 'direct'
end

function NetworkManager:GetCurLineAddress()
	--内网直接返回
	if App.IsDebug() or App.IsGPTest() then
		return self:GetGameServerUrl()
	end

	--外网
	local curLineName = self:GetCurLineName()
	for _, v in pairs(LineList) do
		if v.Name == curLineName then
			return v.Address
		end
	end

	return self:GetGameServerUrl()
end

function NetworkManager:GetCurLineNameId()
    local name = self:GetCurLineName()
    return _ToID(name)
end

function NetworkManager:ClearAllLines()
    for _, p in pairs(self.allSelectProxy) do
        p:Disconnect()
    end

    table.clear(self.allSelectProxy)
end

-- 代理的端口转发规则
function NetworkManager:GetPortId(zoneId)
	
	-- 有问题默认进1服
	zoneId = tonumber(zoneId) or 1
	local port = 8101
	if zoneId > 9000 then
		port = 10500 + zoneId - 9000
	else
		port = 8100 + zoneId
	end
		
	return port

end


-- 获取所有线路
function NetworkManager:GetProxyLines()
	local list = {}
	
	---- 首先加入
	--local oneData = {}
	--oneData.lineName = "direct"
	--oneData.lineUrl = self:GetGameServerUrl()
	--oneData.port = self:GetGameServerPort()
	--table.insert(list, oneData)
	
	-- 然后加入转发的proxy的代理服务器列表
	--zlh: release或者内网连外网服务器走多条线
	local isPublicHostUrl = App.IsEditorConnectedToRelease()
	if (not App.IsDebug() and (not App.IsGPTest())) or isPublicHostUrl  then
		local serverId = CommonUtil.GetServerId()
		if serverId > 0 then
			-- 端口规则：8100+服务器id
			local port = self:GetPortId(serverId)
			for _, v in pairs(LineList) do
				local oneData = {}
				oneData.lineName = v.Name
				oneData.lineUrl = v.Address
				oneData.port = port
				table.insert(list, oneData)					
			end
		end
	end
	
	return list
end

-- NetProxy 是指SmartFox
-- NetRawProxy 是指原始socket实现的网络接口
function NetworkManager:InitLine()
	NetPrint("NetworkManager:InitLine")
	
	table.clear(self.allSelectProxy)
	
    local proxyCfgList = self:GetProxyLines()
    local hasLine = false

    for _, data in pairs(proxyCfgList) do
        local lineName = tostring(data['lineName'])
        local lineUrl = tostring(data['lineUrl'])
        local port = tonumber(data['port'])

        if lineName ~= nil and lineUrl ~= nil and port ~= nil then
            local line = NetProxy(lineName, lineUrl, port, self.cSharpNetwork)
            --local line = NetRawProxy(lineName, lineUrl, port, self.cSharpNetwork)

            table.insert(self.allSelectProxy, line)
            hasLine = true
			
			NetPrint("insert proxy line - %s:%d", lineName, port)
        end
    end


	-- 如果没有转发的话 ，就直接使用直连
    if not hasLine then
        local serverUrl = self.GameServerUrl
        local serverPort = self.GameServerPort
		NetPrint("insert direct line - %s:%d", serverUrl, serverPort)
        
        local direct = NetProxy("direct", self.GameServerUrl, self.GameServerPort, self.cSharpNetwork)
        --local direct = NetRawProxy("direct", self.GameServerUrl, self.GameServerPort, self.cSharpNetwork)
        table.insert(self.allSelectProxy, direct)
		hasLine = true
    end
	
	if hasLine == false then
		Logger.LogError("no line!!")
	end
	
end

function NetworkManager:ChooseOneLine()
    self:InitLine()
    for _, p in pairs(self.allSelectProxy) do
        p:Connect()
    end
end

function NetworkManager:OnBeforeConnect()
    -- 外网连接
    --if not CS.CommonUtils.IsDebug() then
        --self.GameServerUrl = "47.254.93.20"
        --self.GameServerPort = 8088
        --self.ZoneName = "APS1"
        --self.Uid = "478473000001"
    --end
end

-- 设置当前的proxy
function NetworkManager:SetCurProxy(proxy)
	
	self.curProxy = proxy
	if self.cSharpNetwork then
		self.cSharpNetwork:SetCurProxy(proxy)
	else
		-- 这里永远不可能走到
		NetPrint("set cur proxy error")
	end
end

function NetworkManager:OnConnection(proxy) 
	NetPrint("OnConnection! proxy: " .. tostring(proxy and proxy.proxyName))
	
	-- 如果当前已经有连接到的proxy了，那么就放弃
    local curProxy = self:GetCurLineProxy()
	if curProxy ~= nil then
		NetPrint("OnConnection - already has proxy!")
		return false
	end
	
    for _, p in pairs(self.allSelectProxy) do
        if p.proxyName ~= proxy.proxyName then
            p:Disconnect()
        end
    end
    
	self:SetCurProxy(proxy)
    table.clear(self.allSelectProxy)
	self.isConnecting = false
	NetPrint("OnConnection - cur proxy = " .. proxy.proxyName)
    
    --消息推送相关
    local pushType = Setting:GetPrivateString(SettingKeys.GAME_ACCOUNT, "")
    if not string.IsNullOrEmpty(pushType) then
        Setting:SetPrivateString('CATCH_PUSH_TYPE', "")
    end

    --if self.onConnectionEvent then
        --self.onConnectionEvent(Const.LoginErrorCode.ERROR_SUCCESS)
    --end

	--编辑器连线上服自动处理下
	if App.IsEditor() then
		local t = App.IsEditorConnectedToRelease()
		Setting:SetPublicInt('Editor_ConnectOnline', t and 1 or 0)
	end
	
	EventManager:GetInstance():Broadcast(EventId.GameOnConnectOK, Const.LoginErrorCode.ERROR_SUCCESS)

    return true
end

-- 某一条代理连接错误
function NetworkManager:OnConnectionError(proxy, error, errorMessage)
	error = tostring(error)
	NetPrint("NetworkManager:OnConnectionError: " .. error)

	-- 连接的时候会有多个connect并发连接
	local allError = true
	if self:GetCurLineProxy() ~= nil then
		allError = true
	else
		-- 判断是否所有的proxy都已经连接错误了
		for _, p in pairs(self.allSelectProxy) do
			if p.Status ~= ProxyStatus.connectError then
				allError = false
				break
			end
		end
	end

	if allError then
		NetPrint("OnConnectionError - allerror")
		self:Disconnect()
		-- 停服公告
		-- 在每一次重连的时候,先去判定一下是否已经停服
		if AppStartupLoading:GetInstance():CheckServerStateStop() then
			EventManager:GetInstance():Broadcast(EventId.Net_Connect_Error, Const.LoginErrorCode.ERROR_MAINTENANCE)
			return
		end
		
		if self.onConnectionEvent ~= nil then
			if errorMessage ~= nil and string.contains(errorMessage, 'Network is unreachable') then
				self.onConnectionEvent(Const.LoginErrorCode.ERROR_UNREACHABLE, "OnConnectionError")
			else
				self.onConnectionEvent(Const.LoginErrorCode.ERROR_NETWORK, "OnConnectionError")
			end
		end

		local errCode = tonumber(error) or 0
		if error == Const.LoginErrorCode.ERROR_NO_NET or 
			error == Const.LoginErrorCode.ERROR_CONN_LOST or
			errCode < -200 then
			
			EventManager:GetInstance():Broadcast(EventId.Net_Connect_Error, error)
			return
		end

		EventManager:GetInstance():Broadcast(EventId.Net_Connect_Error, Const.LoginErrorCode.ERROR_CONNECT)
	end
end

function NetworkManager:OnConnectionLost(reason, proxy)
	NetPrint("OnConnectionLost")

	-- 在每一次重连的时候,先去判定一下是否已经停服
	if AppStartupLoading:GetInstance():CheckServerStateStop() then
		self:Disconnect()
		EventManager:GetInstance():Broadcast(EventId.Net_Connect_Error, Const.LoginErrorCode.ERROR_MAINTENANCE)
		return
	end
	
	-- 在连接状态的话，可能要处理其他线的情况
	if self:IsConnecting() then
		Logger.Log('OnConnectionLost - IsConnecting - line ', proxy.proxyName)
		--self:OnConnectionError(proxy, Const.LoginErrorCode.ERROR_CONN_LOST, '')
		return
	end
	
    local curLineName = self:GetCurLineName()
    Logger.LogFormat('Connection %s was lost, Reason:%s cur line %s', proxy.proxyName, reason, curLineName)
	
    local curProxy = self:GetCurLineProxy()
    if curProxy ~= nil and curProxy.proxyName ~= proxy.proxyName then
        Logger.LogFormat('line %s lost not cur %s line do nothing', proxy.proxyName, curLineName)
        return
    end

    if LuaEntry.GlobalData:IsInBackground() then
		NetPrint("connection lost but in background!")
		self:Disconnect()
        return
    end
 
    --被其他手机给顶了就不连了
    if LuaEntry.GlobalData.pushOffWithQuitGame then
		NetPrint("connection lost --- pushOffWithQuitGame!")
        self:Disconnect()
        return
    end
    ---- 在这块请求服务器状态
    --AppStartupLoading:GetInstance():RequestServerStateUrl()
	self:Disconnect()
    if not AppStartupLoading:GetInstance():CheckServerStateStop() then -- 如果停服的情况下,没有必要继续连接
        self:Reconnect('connection lost, reason:' .. reason)
    end
end

function NetworkManager:OnLogin(message)
	NetPrint("NetworkManager:OnLogin")
	
	-- 如果message为nil的话，就是未知错误！
	if message == nil then
		self:OnLoginError(0, "InternalError")
		return
	end
    
	AppStartupLoading:GetInstance():OnLogin(message)
end

function NetworkManager:OnLoginError(errCode, errorMessage)
	NetPrint("NetworkManager:OnLoginError")
	
    --local errCode = baseEvent.Params:get_Item('errorCode')
    --local errorMessage = baseEvent.Params:get_Item('errorMessage')
	AppStartupLoading:GetInstance():DoLoginError(errCode, errorMessage)
end

function NetworkManager:OnLogout()
	NetPrint('NetworkManager:OnLogout')
end

function NetworkManager:Update()
    local now = Time.time
    if now - self.lastUpdateTime > 3 then
        self.lastUpdateTime = now
        self:CheckOffline()
    end
    
    if self.curProxy ~= nil then
        self.curProxy:UpdateSmartFoxClient()
    else
        for _, proxy in pairs(self.allSelectProxy) do
            proxy:UpdateSmartFoxClient()
        end
    end
end

function NetworkManager:OnConnectionEvent(callback)
    self.onConnectionEvent = callback
end

function NetworkManager:Connect()
	NetPrint("NetworkManager:Connect begin")
	
    if App.IsEditor() then
        self:OnBeforeConnect()
    end

	-- 重连时清除配置缓存
	CS.GameEntry.ConfigCache:reset()
	
    --清理所有正在连接中的线路
    self:ClearAllLines()
    self:ChooseOneLine()
    local futureManager = self:GetFutureManager()
    if futureManager then
        futureManager:reset()
    end
	self.isConnecting = true
	
	NetPrint("NetworkManager:do Connect ok")
end

function NetworkManager:Disconnect()
	NetPrint("NetworkManager:do Disconnect")
    
    if self.curProxy ~= nil then
        self.curProxy:Disconnect()
        --self.curProxy = nil
		self:SetCurProxy(nil)
    end
	
	self:ClearAllLines()
	
	self.isConnecting = false
end


-- 这个地方其实写的不是很好
-- 1. reconnect 其实是弹出DisconnectView 这个UI，并不是真正的Reconnect。会在UI中判断
-- 2. 这个函数的职责不应该存在于Network中，而是LuaEntry中处理
function NetworkManager:Reconnect(recordStr)
    --CS.PostEventLog.Record(CS.PostEventLog.Defines.DISCONNECT_RETRY, recordStr or '')
	NetPrint('NetworkManager:Reconnect')

	if AppStartupLoading:GetInstance():IsLoading() then
		--NetPrint("CheckOffline - IsLoading")
		return
	end
    
	-- 已经处于重连窗口状态了，不重复处理；
    if UIManager:GetInstance():IsWindowOpen(UIWindowNames.UIDisconnect) then
		Logger.Log("UIDisconnect alreay open! Reconnect - ", recordStr)
        return
    end
	
	--躲避球里不关闭UI了，
	if DataCenter.LWBattleManager:IsInBattle() or SceneManager.IsArena() then
		
	else
		-- 只需要关闭普通窗口和引导层
		-- 普通窗口：因为很多时候普通窗口只是在开启的时候同步了一下服务器信息，譬如活动等
		--          如果不关闭的话，可能会有很多不同步的情况。场景信息必须同步，否则是BUG
		-- 引导层：这个要关闭，因为普通窗口关闭了，如果引导层不关闭，会留下箭头。
		UIManager:GetInstance():DestroyWindowByLayer(UILayer.Guide)
		UIManager:GetInstance():DestroyWindowByLayer(UILayer.Normal)
		UIManager:GetInstance():DestroyWindowByLayer(UILayer.Scene)
	end
	
	Logger.Log("UIDisconnect open! Reconnect - ", recordStr)
    UIManager:GetInstance():OpenWindow(UIWindowNames.UIDisconnect)
end

function NetworkManager:CheckOffline()
    if LuaEntry.GlobalData.pushOffWithQuitGame then
		NetPrint("CheckOffline - pushOffWithQuitGame")
        return
    end

    if AppStartupLoading:GetInstance():IsLoading() then
		--NetPrint("CheckOffline - IsLoading")
        return
    end

	if self:IsConnecting() then
		if App.IsDebug() or App.IsGPTest() then
			NetPrint("CheckOffline - IsConnecting")
		end
		return
	end
    
	-- 只有连接情况才进行pingpong检测；否则网络断开后pingping永远是超时啊
	if self:IsConnected() then 
		if App.IsEditor() then
			-- 如果在editor模式下，不去处理pingpong，防止调试被卡
		else
		    if self:IsPingPongTimeOut() then
				PostEventLog.Record("PingPongTimeOut")
		        self:Reconnect('PingPongTimeOut')
		    end
		end
	else
		PostEventLog.Record("CheckOffline - Not Connected!?")
	end
end


function NetworkManager:SendLuaMessage(msgId, sfsObjBinary)
    self.cSharpNetwork:SendLuaMessage(msgId, sfsObjBinary)
end

function NetworkManager:SendLuaMessageEx(msgId, sfsObj)
    local futureId = self.futureManger:getFutureId()
    self.futureManger:onSendRequest(futureId, _ToID(msgId))
    sfsObj:PutInt("_id", futureId)

    if App.IsEditor() then
        if msgId ~= 'survival.pve.heartbeat' then
			local t = sfsObj:ToLuaTable()
            --local rapidjson = require "rapidjson"
            --local jsonStr = rapidjson.encode(sfsObj)
			local rapidjson = require "rapidjson"
			local jsonStr = rapidjson.encode(t)

            Logger.Log(string.format("<color=cyan>#message# [req] <%s> |</color> {%s}", msgId, jsonStr))
        end
    end
    
    self.cSharpNetwork:SendLuaMessageEx(msgId, sfsObj)
end

function NetworkManager:SimulateKill()
	if self.curProxy ~= nil then
		self.curProxy:KillConnection()
	end
end

return NetworkManager