using System.Collections.Generic;
using System;
using XLua;
using CSObjectWrapEditor;

public static class GenConfig
{
	[GenPath]
	public static string GenPath => UnityEngine.Application.dataPath + "/Main/Scripts/XLuaGen";

    //lua中要使用到C#库的配置，比如C#标准库，或者Unity API，第三方库等。
    [CSharpCallLua]
    public static List<Type> CSharpCallLua = new List<Type>() {
	    // unityResourceUtils
	    typeof(Action),
	    typeof(Action<int>),
	    typeof(Action<float>),
	    typeof(Action<bool>),
	    typeof(Action<string>),
	    typeof(Action<string, string, int>),
	    typeof(Action<bool, int>),
	    typeof(Action<long, int>),
	    typeof(Action<int, int>),
	    typeof(Action<int, string>),
	    
	    typeof(System.Delegate),
	    typeof(System.MulticastDelegate),
	    
	    typeof(GameKit.Base.WebRequestManager.OnWebRequestCallback),
	    typeof(Action<VEngine.Asset>),
	    typeof(Action<UnityEngine.GameObject>),
	    typeof(Action<UnityEngine.Vector2>),
	    typeof(Action<UnityEngine.Vector3>),
	    typeof(Action<UnityEngine.Vector3, UnityEngine.Vector3>),
	    typeof(Action<UnityEngine.Vector3, UnityEngine.Vector3, UnityEngine.Vector3>),
	    typeof(Action<UnityEngine.Vector3, bool>),
	    typeof(Action<UnityEngine.Vector3, bool, bool>),
	    typeof(Action<LuaTable>),	// for LuaDatabaseManager
	    typeof(Action<UnityEngine.GameObject,int>),
	    typeof(Action<UnityEngine.GameObject,int,int>),
	    typeof(Action<UnityEngine.UI.Image>),
	    typeof(Action<UnityEngine.SceneManagement.Scene, UnityEngine.SceneManagement.LoadSceneMode>),
	    
	    typeof(Action<GameKit.Base.INetProxy, Sfs2X.Core.BaseEvent>),
	    typeof(Action<string, GameKit.Base.INetProxy>),
	    typeof(Action<string, GameKit.Base.INetProxy>),
	    
	    typeof(Action<InstanceRequest>),
	    typeof(Action<UnityEngine.EventSystems.PointerEventData>),
	    typeof(Action<UnityEngine.GameObject, UnityEngine.EventSystems.PointerEventData, UnityEngine.EventSystems.ExecuteEvents.EventFunction<UnityEngine.EventSystems.IBeginDragHandler>>),
	    typeof(UnityEngine.Events.UnityAction),         // Button
	    typeof(UnityEngine.Events.UnityAction<bool>),   // Toggle
        
	    typeof(LuaScriptInterface.UIManager),
	    //typeof(LuaScriptInterface.EventManager),
	    typeof(ScrollView.MoveItemDelegate),
        
	    //DoTween
//        typeof(DG.Tweening.Core.DOGetter<UnityEngine.Color>),
//        typeof(DG.Tweening.Core.DOSetter<UnityEngine.Color>),
	    typeof(DG.Tweening.Core.DOGetter<UnityEngine.Vector2>),
	    typeof(DG.Tweening.Core.DOSetter<UnityEngine.Vector2>),
	    typeof(DG.Tweening.Core.DOGetter<UnityEngine.Vector3>),
	    typeof(DG.Tweening.Core.DOSetter<UnityEngine.Vector3>),
	    typeof(DG.Tweening.Core.DOGetter<float>),
	    typeof(DG.Tweening.Core.DOSetter<float>),
	    typeof(DG.Tweening.TweenCallback),
	    typeof(DG.Tweening.Core.TweenerCore<UnityEngine.Vector3, UnityEngine.Vector3, DG.Tweening.Plugins.Options.VectorOptions>),
	    //typeof(Mopsicus.Plugins.MobileInput.ShowDelegate),
        
	    //superscrollview / looplistview
	    typeof(Func<SuperScrollView.LoopListView2, int, SuperScrollView.LoopListViewItem2>),
	    typeof(LuaBuildData),
	    typeof(List<LuaBuildData>),
	    typeof(List<BitBenderGames.WrappedTouch>),
	    //typeof(List<WayPointSimple>),
	    
	    typeof(BitBenderGames.TouchInputController.PinchStartDelegate),
	    typeof(BitBenderGames.TouchInputController.PinchUpdateExtendedDelegate),
	    typeof(BitBenderGames.TouchInputController.InputDragStartDelegate),
	    typeof(BitBenderGames.TouchInputController.DragUpdateDelegate),
	    typeof(BitBenderGames.TouchInputController.DragStopDelegate),
	    typeof(BitBenderGames.TouchInputController.InputClickDelegate),
	    
	    //typeof(Action<LW.CountBattle.SteerUnit>),
	    //typeof(Action<int, LW.CountBattle.SteerUnit>),
	    typeof(UnityEngine.Video.VideoPlayer.FrameReadyEventHandler),
    };

    [LuaCallCSharp]
    [ReflectionUse]
    public static List<Type> LuaCallCSharp = new List<Type>() {
	    typeof(Main.Scripts.Application.LoadingState.HttpRequest),
	    typeof(UnityEngine.Networking.DownloadHandler),
	    typeof(ApplicationLaunch),
	    //typeof(VisibleByCameraMono),
	    typeof(VEngine.DownloadInfo),
	    //typeof(SDK.TikTokBusinessSDK),
	    typeof(ShaderManager),
	    //typeof(SurvivalLod),
	    //typeof(CatmullRomUtils),
	    //typeof(SurvivalLodEx),
	    typeof(ConfigStatus),
	    //typeof(CameraMove),
	    //typeof(AutoAdjustLod),
	    //typeof(TerrainObjectMatSet),
	    //typeof(RegionRenderManager),
	    //typeof(ViewStatusListener),
	    //typeof(MonoUtils),
	    //typeof(MaterialChangeMgr),
	    //typeof(Mat_Type),
	    //typeof(FakeModelManager),
	    //typeof(ZendeskSDK),
		// system
		typeof(System.Object),
		typeof(System.Array),
		//typeof(System.Action),
		typeof(System.ValueType),
		typeof(System.Type),
		typeof(System.Delegate),
		typeof(System.MulticastDelegate),
		typeof(System.Reflection.BindingFlags),
		typeof(System.Collections.IEnumerator),
		
		typeof(VEngine.Manifest),
		typeof(GPUSkinningAnimation),
        typeof(UnityEngine.Object),
        typeof(UnityEngine.Touch),
        typeof(UnityEngine.Physics),
        typeof(UnityEngine.Collider),
        typeof(UnityEngine.Space),
        typeof(UnityEngine.Camera),
        typeof(UnityEngine.Camera.GateFitMode),
        typeof(UnityEngine.Camera.FieldOfViewAxis),
        typeof(UnityEngine.Camera.GateFitParameters),
        typeof(UnityEngine.Screen),
		typeof(UnityEngine.Rendering.OnDemandRendering),
		typeof(BezierUtils),
        // typeof(UnityEngine.Input),
        typeof(UnityEngine.GameObject),
        typeof(UnityEngine.Component),
        typeof(UnityEngine.Transform),
        typeof(UnityEngine.AudioSource),
        typeof(UnityEngine.AI.NavMesh),
        typeof(UnityEngine.AI.NavMeshAgent),
        typeof(UnityEngine.AI.NavMeshPath),
        typeof(UnityEngine.AI.NavMeshPathStatus),
        typeof(UnityEngine.AI.NavMeshData),
        typeof(UnityEngine.AI.NavMeshDataInstance),
        typeof(UnityEngine.AI.NavMeshObstacle),
        
        typeof(List<int>),
        typeof(List<UnityEngine.GameObject>),
        typeof(List<UnityEngine.Camera>),
        typeof(Action<string>),
        typeof(Action<float>),
        typeof(Action<int>),
        typeof(Action<UnityEngine.EventSystems.PointerEventData>),
        typeof(Action<UnityEngine.GameObject, UnityEngine.EventSystems.PointerEventData, UnityEngine.EventSystems.ExecuteEvents.EventFunction<UnityEngine.EventSystems.IBeginDragHandler>>),
        typeof(UnityEngine.Debug),
        typeof(UnityEngine.RuntimeAnimatorController),
        typeof(UnityEngine.SceneManagement.SceneManager),
        typeof(Action<UnityEngine.SceneManagement.Scene, UnityEngine.SceneManagement.LoadSceneMode>),

        typeof(DG.Tweening.DOTweenModuleUI),
        typeof(DG.Tweening.DOTween),
        typeof(DG.Tweening.DOVirtual),
        typeof(DG.Tweening.Ease),
        typeof(DG.Tweening.EaseFactory),
        typeof(DG.Tweening.Tweener),
        typeof(DG.Tweening.Tween),
        typeof(DG.Tweening.Sequence),
        typeof(DG.Tweening.TweenParams),
        typeof(DG.Tweening.Core.ABSSequentiable),
        typeof(DG.Tweening.TweenCallback),
        typeof(DG.Tweening.LoopType),
        typeof(DG.Tweening.TweenExtensions),
        typeof(DG.Tweening.TweenSettingsExtensions),
        typeof(DG.Tweening.ShortcutExtensions),
        typeof(DG.Tweening.Core.TweenerCore<UnityEngine.Vector3, UnityEngine.Vector3, DG.Tweening.Plugins.Options.VectorOptions>),
        typeof(DG.Tweening.Core.TweenerCore<UnityEngine.Color, UnityEngine.Color, DG.Tweening.Plugins.Options.ColorOptions>),
        typeof(DG.Tweening.Core.TweenerCore<float, float, DG.Tweening.Plugins.Options.FloatOptions>),
        typeof(DG.Tweening.Core.DOGetter<UnityEngine.Vector3>),
        typeof(DG.Tweening.Core.DOSetter<UnityEngine.Vector3>),
        typeof(DG.Tweening.Core.DOTweenComponent),
        typeof(DG.Tweening.DOTweenAnimation),
        typeof(DG.Tweening.DOTweenAnimation.AnimationType),
        typeof(DG.Tweening.DOTweenAnimation.TargetType),

        typeof(SuperScrollView.LoopListView2),
        typeof(SuperScrollView.LoopListViewItem2),
        typeof(SuperScrollView.LoopListViewInitParam),
        //typeof(EPOOutline.Outliner),
        
        typeof(Mopsicus.Plugins.MobileInputField),
        // unity结合lua，这部分导出很多功能在lua侧重新实现，没有实现的功能才会跑到cs侧
        typeof(UnityEngine.Bounds),
        typeof(UnityEngine.Color),
        typeof(UnityEngine.Color32),
        typeof(UnityEngine.LayerMask),
        typeof(UnityEngine.Mathf),
        typeof(UnityEngine.Plane),
        typeof(UnityEngine.Quaternion),
        typeof(UnityEngine.Ray),
        typeof(UnityEngine.RaycastHit),
        typeof(UnityEngine.Time),
        typeof(UnityEngine.Vector2),
        typeof(UnityEngine.Vector3),
        typeof(UnityEngine.Vector4),
        typeof(UnityEngine.Matrix4x4),
        typeof(UnityEngine.PrimitiveType),
        typeof(UnityEngine.Canvas),
        typeof(UnityEngine.Canvas.WillRenderCanvases),
        typeof(UnityEngine.Rect),
        typeof(UnityEngine.RectTransform),
        typeof(UnityEngine.RectTransform.Edge),
        typeof(UnityEngine.RectTransform.Axis),
        typeof(UnityEngine.RectOffset),
        typeof(UnityEngine.Sprite),
        typeof(UnityEngine.Renderer),
        typeof(UnityEngine.Material),
        typeof(UnityEngine.Behaviour),
        typeof(UnityEngine.MonoBehaviour),
        typeof(UnityEngine.U2D.SpriteAtlas),
        typeof(UnityEngine.EventSystems.UIBehaviour),
        typeof(UnityEngine.EventSystems.PointerEventData),
        typeof(UnityEngine.EventSystems.PointerEventData.InputButton),
        typeof(UnityEngine.EventSystems.PointerEventData.FramePressState),
        typeof(UnityEngine.EventSystems.EventSystem),
        typeof(UnityEngine.EventSystems.ExecuteEvents),
        typeof(UnityEngine.RenderTexture),
        typeof(UnityEngine.Texture),
        typeof(UnityEngine.Texture2D),
        typeof(UnityEngine.RenderTextureFormat),
        typeof(UnityEngine.RenderMode),
        typeof(UnityEngine.Rendering.BlendMode),
        typeof(UnityEngine.LODGroup),

        // UGUI
        typeof(UnityEngine.UI.Selectable),
        typeof(UnityEngine.UI.Selectable.Transition),
        typeof(UnityEngine.UI.Text),
        typeof(UnityEngine.UI.InputField),
        typeof(UnityEngine.UI.InputField.ContentType),
        typeof(UnityEngine.UI.InputField.InputType),
        typeof(UnityEngine.UI.InputField.CharacterValidation),
        typeof(UnityEngine.UI.InputField.LineType),
        typeof(UnityEngine.UI.InputField.OnChangeEvent),
        typeof(UnityEngine.UI.InputField.OnValidateInput),
        typeof(UnityEngine.UI.InputField.SubmitEvent),
        typeof(UnityEngine.UI.InputField.EndEditEvent),

        typeof(UnityEngine.UI.Button),
        typeof(UnityEngine.UI.Button.ButtonClickedEvent),
        typeof(UnityEngine.UI.Image),
        typeof(UnityEngine.UI.Image.Type),
        typeof(UnityEngine.UI.Image.FillMethod),
        typeof(UnityEngine.UI.Image.OriginHorizontal),
        typeof(UnityEngine.UI.Image.OriginVertical),
        typeof(UnityEngine.UI.Image.Origin90),
        typeof(UnityEngine.UI.Image.Origin180),
        typeof(UnityEngine.UI.Image.Origin360),
        typeof(UnityEngine.UI.ScrollRect),
        typeof(UnityEngine.UI.ScrollRect.MovementType),
        typeof(UnityEngine.UI.ScrollRect.ScrollbarVisibility),
        typeof(UnityEngine.UI.ScrollRect.ScrollRectEvent),
        typeof(UnityEngine.UI.Scrollbar),
        typeof(UnityEngine.UI.Slider),
        typeof(UnityEngine.UI.Slider.SliderEvent),
        typeof(UnityEngine.UI.Slider.Direction),
        typeof(UnityEngine.UI.Toggle),
        typeof(UnityEngine.UI.Toggle.ToggleTransition),
        typeof(UnityEngine.UI.Toggle.ToggleEvent),
        typeof(UnityEngine.UI.ToggleGroup),
        typeof(UnityEngine.UI.GridLayoutGroup),
        typeof(UnityEngine.UI.HorizontalOrVerticalLayoutGroup),
        typeof(UnityEngine.UI.HorizontalLayoutGroup),
        typeof(UnityEngine.UI.Shadow),
        typeof(UnityEngine.UI.Dropdown),
        typeof(UnityEngine.UI.Dropdown.OptionData),
        typeof(UnityEngine.UI.Dropdown.OptionDataList),
        typeof(UnityEngine.UI.Dropdown.DropdownEvent),
        
        
        typeof(UnityEngine.UI.MaskableGraphic),
        typeof(UnityEngine.UI.MaskableGraphic.CullStateChangedEvent),
        typeof(UnityEngine.UI.RawImage),
        typeof(UnityEngine.UI.LayoutElement),
        typeof(UnityEngine.UI.LayoutRebuilder),
        typeof(UnityEngine.UI.Graphic),
        typeof(UnityEngine.UI.BaseMeshEffect),
        typeof(UnityEngine.UI.Outline),
        typeof(UnityEngine.UI.Empty4Raycast),
        typeof(UnityEngine.UI.GraphicRaycaster),
        
        typeof(SuperTextMesh),
        typeof(SuperTextMesh.Alignment),
        typeof(UnityEngine.SpriteRenderer),
		typeof(UnityEngine.Application),
		typeof(UnityEngine.Application.AdvertisingIdentifierCallback),
		typeof(UnityEngine.Application.LowMemoryCallback),
		typeof(UnityEngine.Application.LogCallback),
        typeof(UnityEngine.CanvasGroup),
        typeof(UnityEngine.Animator),
        typeof(UnityEngine.AnimationClip),
        typeof(UnityEngine.Animation),
        typeof(UnityEngine.Motion),
        typeof(UnityEngine.BoxCollider2D),
        typeof(UnityEngine.BoxCollider),
        typeof(UnityEngine.SphereCollider),
        typeof(UnityEngine.Collider2D),
        typeof(UnityEngine.CapsuleCollider),
        typeof(UnityEngine.Rigidbody),
        typeof(UnityEngine.Events.UnityEventBase),
        typeof(UnityEngine.Events.UnityEvent),
        typeof(UnityEngine.Events.UnityEvent<string>),
        typeof(UnityEngine.Events.UnityEvent<float>),
        typeof(UnityEngine.Events.UnityEvent<bool>),
        typeof(UnityEngine.Events.UnityEvent<UnityEngine.Vector2>),
        typeof(UnityEngineObjectExtention),
        typeof(UnityEngineGameObjectExtention),
        typeof(ScrollView),
        typeof(ScrollView.MovementType),
        typeof(ScrollView.ScrollbarVisibility),
        typeof(ScrollView.ScrollViewLayoutType),
        typeof(ScrollView.ScrollRectEvent),
        typeof(ScrollView.MoveItemDelegate),

        typeof(UIEventTrigger),
        typeof(UnityEngine.TouchPhase),
        typeof(UnityEngine.SystemInfo),
        typeof(UnityEngine.Shader),
        typeof(UnityEngine.Graphics),
        typeof(UnityEngine.AssetBundle),
        
        // 粒子，必须要全导出；否则xlua加载的时候会通过反射导出，浪费。
        // 具体细节没看xlua代码
        typeof(UnityEngine.ParticleSystem),
        typeof(UnityEngine.ParticleSystem.MinMaxCurve),
        typeof(UnityEngine.ParticleSystem.MainModule),
        typeof(UnityEngine.ParticleSystem.EmissionModule),
        typeof(UnityEngine.ParticleSystem.ShapeModule),
        typeof(UnityEngine.ParticleSystem.SubEmittersModule),
        typeof(UnityEngine.ParticleSystem.TextureSheetAnimationModule),
        typeof(UnityEngine.ParticleSystem.Particle),
        typeof(UnityEngine.ParticleSystem.Burst),
        typeof(UnityEngine.ParticleSystem.MinMaxGradient),
        typeof(UnityEngine.ParticleSystem.EmitParams),
        typeof(UnityEngine.ParticleSystem.PlaybackState),
        typeof(UnityEngine.ParticleSystem.Trails),
        typeof(UnityEngine.ParticleSystem.VelocityOverLifetimeModule),
        typeof(UnityEngine.ParticleSystem.LimitVelocityOverLifetimeModule),
        typeof(UnityEngine.ParticleSystem.InheritVelocityModule),
        typeof(UnityEngine.ParticleSystem.ForceOverLifetimeModule),
        typeof(UnityEngine.ParticleSystem.ColorOverLifetimeModule),
        typeof(UnityEngine.ParticleSystem.ColorBySpeedModule),
        typeof(UnityEngine.ParticleSystem.ForceOverLifetimeModule),
        typeof(UnityEngine.ParticleSystem.SizeBySpeedModule),
        typeof(UnityEngine.ParticleSystem.RotationOverLifetimeModule),
        typeof(UnityEngine.ParticleSystem.RotationBySpeedModule),
        typeof(UnityEngine.ParticleSystem.ExternalForcesModule),
        typeof(UnityEngine.ParticleSystem.NoiseModule),
        typeof(UnityEngine.ParticleSystem.CollisionModule),
        typeof(UnityEngine.ParticleSystem.TriggerModule),
        typeof(UnityEngine.ParticleSystem.LightsModule),
        typeof(UnityEngine.ParticleSystem.TrailModule),
        typeof(UnityEngine.ParticleSystem.CustomDataModule),
        typeof(UnityEngine.ParticleSystem.SizeOverLifetimeModule),
        typeof(UnityEngine.ParticleSystem.ColliderData),
        typeof(UnityEngine.ParticleSystem.LifetimeByEmitterSpeedModule),

        // 其它
        typeof(UnityEngine.PlayerPrefs),
        typeof(UnityEngine.RenderSettings),
        //typeof(UnityEngine.Rendering.RenderPipelineAsset),
        
        
        // TODO: 后续需要什么脚本再添加进来
        typeof(SettingManager),
        typeof(GPUSkinningAnimator),
        typeof(GameKit.Base.ComponentExtensions),
        typeof(GameKit.Base.TransformExtentions),
        typeof(GameKit.Base.UnlimitedScrollView),
        typeof(GameKit.Base.WebRequestManager),
        typeof(GameFramework.Log),
        typeof(SDKManager),
        typeof(SoundComponent),
        typeof(SoundComponent.SoundGroup),
        typeof(SoundComponent.Sound3DGroup),
        typeof(SoundComponent.PlaySoundParams),
        
        typeof(TimerComponent),
        typeof(EventNotify),
        //typeof(ResourceUtils),
        //typeof(ResourceExtention),
        //typeof(UnityExtension),
        typeof(UnityEventEx),
        typeof(UnityUIExtension),
        typeof(LocalizationManager),
        typeof(CustomDataManager),
        typeof(NetworkManager),
        
        //typeof(ChatService),
        typeof(UIPlayerHead),
        //typeof(TargetFlow),
        typeof(CircleImage),
        typeof(UIGray),
        typeof(HorizontalInfinityScrollView),
        typeof(GridInfinityScrollView),
        typeof(PageViewComponent),
        typeof(UnityPing),
        //typeof(CustomLineRender),
        typeof(GameEntry),
        
        typeof(ResourceManager),
        typeof(ResourceManager.PreloadType),
        typeof(ResourceManager.PreloadCache),
        
        typeof(SimpleAnimation),
        typeof(SimpleAnimation.State),

        // 字典的多态
        typeof(Dictionary<int, string>),
        typeof(Dictionary<ResourceType, int>),
        typeof(Dictionary<ResourceType, long>),
        typeof(Dictionary<string, UnityEngine.GameObject>),
        
        typeof(UIUtils),
        typeof(CommonUtils),
        typeof(Raycast2DLineRect),
        //typeof(SceneManager),
        //typeof(WorldScene),
        //typeof(WorldPointManager),
        //typeof(WorldMarchDataManager),
        //typeof(LuaClientProfiler),
        typeof(NewQueueState),
        typeof(GlobalDataManager),
        typeof(GlobalDataManager.LoginServerInfo),
        //typeof(GameDialogDefine),
        typeof(ResourceType),
        typeof(BuildingState),
        typeof(StringUtils),
        //typeof(PlaceBuildType),
        typeof(MarchStatus),
        typeof(UnityEngine.Vector2Int),
        typeof(Action<int>),
	    //typeof(AutoAdjustScreenPos),
	    typeof(UIFormBlurEffect),
	    
	    typeof(UnityEngine.Animations.PositionConstraint),
	    typeof(UnityEngine.Animations.ParentConstraint),
	    typeof(UnityEngine.Animations.ConstraintSource),
	    typeof(UnityEngine.Playables.PlayableDirector),
	    typeof(UnityEngine.Playables.PlayableExtensions),
	    //typeof(WorldBuildObject),
	    typeof(ScrollRectWithoutEnable),
	    //typeof(WorldTroopManager),
	    //typeof(WorldTroop),
	    //typeof(ChangeSceneCircleSlider),
	    //typeof(SceneSpriteSlider),
	    //typeof(RealisticEyeMovements.LookTargetController),
        //typeof(RealisticEyeMovements.EyeAndHeadAnimator),
	    //TextMeshPro
	    typeof(TMPro.TextMeshPro),
	    typeof(TMPro.TextMeshProUGUI),
	    typeof(TMPro.TMP_TextUtilities),
	    typeof(TMPro.TMP_LinkInfo),
	    typeof(TMPro.TMP_Text),
	    typeof(TMPro.TMP_InputField),
	    typeof(TMPro.TMP_InputField.ContentType),
	    typeof(TMPro.TMP_InputField.InputType),
	    typeof(TMPro.TMP_InputField.CharacterValidation),
	    typeof(TMPro.TMP_InputField.LineType),
	    typeof(TMPro.TMP_InputField.SubmitEvent),
	    typeof(TMPro.TMP_InputField.OnChangeEvent),
	    typeof(TMPro.TMP_InputField.SelectionEvent),
	    typeof(TMPro.TMP_InputField.TextSelectionEvent),
	    typeof(TMPro.TMP_InputField.TouchScreenKeyboardEvent),
	    typeof(TMPro.TMP_Dropdown),
	    typeof(TMPro.TMP_Dropdown.OptionData),
	    typeof(TMPro.TMP_Dropdown.OptionDataList),
	    typeof(TMPro.TMP_Dropdown.DropdownEvent),
	    
	    typeof(AutoDoMovePos),
	    typeof(UnityEngine.UI.Button_LongPress),
	    typeof(PushNoticeManager),
	    //typeof(DCFog),
	    //typeof(ModelManager.ModelObject),
	    //typeof(ModelManager.GarbageObject),
	    typeof(UnityEngine.Video.VideoPlayer),
	    //typeof(BuildingGrowEffect),
	    typeof(LuaDatabaseManager),
	    //typeof(BuildSelect),
	    //typeof(SU_BuildSelect),
	    //typeof(SU_BuildSelectWorld),
	    typeof(UIImageLightAnim),
	    typeof(NewText),
	    typeof(NewButton),
	    typeof(NewTMPText),
	    typeof(NewTMPText.HorizontalAlignmentOptions),
	    typeof(NewTMPText.VerticalAlignmentOptions),
	    typeof(NewTMP3DText),
	    typeof(NewTMP3DText.HorizontalAlignmentOptions),
	    typeof(NewTMP3DText.VerticalAlignmentOptions),
	    typeof(CSUtils),
	    typeof(xLuaOptiUtils),
	    typeof(UnityGameFramework.SDK.AnalyticsEvent),
	    typeof(SpriteMeshRenderer),
	    typeof(UnityEngine.MeshRenderer),
	    typeof(UnityEngine.SkinnedMeshRenderer),
	    typeof(UnityEngine.ForceMode),
	    typeof(UnityEngine.HumanBodyBones),
	    // skeleton
	    typeof(Spine.Unity.SkeletonAnimation),
	    typeof(Spine.Unity.SkeletonUtilityBone),
	    typeof(Spine.Animation),
	    typeof(Spine.AnimationState),
	    typeof(Spine.TrackEntry),
	    typeof(Spine.AnimationStateData),
	    //typeof(Spine.Unity.SkeletonRenderer),

	    typeof(BitBenderGames.MobileTouchCamera),
	    //typeof(BitBenderGames.MobileTouchCamera.State),
	    typeof(BitBenderGames.MobileTouchCamera.ZoomParam),
	    typeof(BitBenderGames.TouchInputController),
	    typeof(BitBenderGames.MonoBehaviourWrapped),

	    //typeof(ITouchObject),
	    //typeof(ITouchObjectClickHandler),
	    //typeof(ITouchObjectBeginDragHandler),
	    //typeof(ITouchObjectDragHandler),
	    //typeof(ITouchObjectEndDragHandler),
	    //typeof(ITouchObjectPointerExitHandler),
	    typeof(TouchObjectEventTrigger),

	    typeof(InstanceRequest),
	    typeof(InstanceRequest.State),
	    
	    typeof(DCPlayer),
	    // World class!!!
	    typeof(NewMarchType),
	   // typeof(BoardPointInfo),
	    //typeof(WorldPointType),
	   // typeof(PointInfo),
	    //typeof(BuildPointInfo),
	    //typeof(GarbagePointInfo),
	   // typeof(CollectPointInfo),
	    //typeof(ExplorePointInfo),
	    //typeof(WorldMarch),
	    typeof(LuaBuildData),
	    typeof(List<LuaBuildData>),

	    //typeof(Vibrator),
	    typeof(UIGoodsFly),
	    typeof(CommonUtils),
	    typeof(LuaStringLookupTable),
		typeof(UnityExtension_Common),
		typeof(UnityExtension_Component),
		typeof(UnityExtension_Transform),
		typeof(UnityExtension_LocalText),
		typeof(UnityExtension_StringLookup),
		typeof(OptiUtils),
		typeof(UnityEngine.Networking.UnityWebRequest),
		typeof(UnityEngine.Networking.UnityWebRequest.Result),
		typeof(UnityEngine.WWWForm),
		typeof(UnityEngine.Networking.UnityWebRequestAsyncOperation),
		typeof(DeviceManager),
		typeof(UnityEngine.MaterialPropertyBlock),
		typeof(UnityEngine.ScriptableObject),
		typeof(EmojiText),
		
		typeof(LuaMonoBase),
		typeof(LuaMonoConfig),
		typeof(LuaMonoUpdate),
		typeof(PostEventLog),
		typeof(UnityEngine.CharacterController),
		// Spine
		// typeof(Spine.Unity.SkeletonGraphic),
		// typeof(Spine.Unity.SkeletonDataAsset),
		// typeof(Spine.SkeletonData),
		typeof(Spine.ExposedList<Spine.Animation>),
		
		typeof(DefaultNewButtonCurve),

		typeof(UnityEngine.Experimental.Rendering.Universal.RenderObjects),
		typeof(UnityEngine.Experimental.Rendering.Universal.RenderObjects.RenderObjectsSettings),
		typeof(UnityEngine.Experimental.Rendering.Universal.RenderObjects.CustomCameraSettings),

		// Delegate
	    typeof(GameKit.Base.UnlimitedScrollView.DragOnHeadOrTailOfTheScrollViewDelegate),
	    typeof(GameKit.Base.UnlimitedScrollView.OnPointerDownScrollViewDelegate),
	    typeof(GameKit.Base.UnlimitedScrollView.BeginDragDelegate),
	    typeof(GameKit.Base.UnlimitedScrollView.ItemMoveInDelegate),  // 由控件创建Item后回调
	    typeof(GameKit.Base.UnlimitedScrollView.ItemMoveOutDelegate),  // 由控件回收Item后回调
	    
	    // 输入器
	    typeof(BitBenderGames.TouchWrapper),
	    typeof(BitBenderGames.WrappedTouch),
	    typeof(BitBenderGames.MobileTouchCamera),
	    typeof(UnityEngine.Input),
	    typeof(UnityEngine.KeyCode),
	    
	    //typeof(AutoFaceToCamera),
	    
	    typeof(UnityEngine.QualitySettings),
	    typeof(UnityEngine.TextAsset),
	    typeof(UnityEngine.RectTransformUtility),
	    
	    typeof(VEngine.Asset),
	    //typeof(CitySpaceManAnimationListener),
	    typeof(ColliderEventHandler),
	    typeof(CameraAniHandler),
	    
	    //typeof(usky.uSkyTimeline),
	    //typeof(usky.uSkyLighting),
	    
	    typeof(GameKit.Base.NetProxy),
	    //typeof(PVEStaticManager),
	    typeof(ProfilerGraph),
	    typeof(FileUtils),

	    //------zlh start----
	    typeof(BypassCertificate),
	    //typeof(ObstacleCollect),
	    //typeof(SurvivalLodManager),
	    typeof(QualityChangeRegistry),
	    typeof(UIParticleSetUpBase),
	    typeof(UISurvivalParticleSetUp),
	    typeof(UIOrderInLayerSetUp),
	    typeof(SpriteMaskSetUp),
	    //typeof(Action<LW.CountBattle.SteerUnit>),
	    //typeof(Action<int, LW.CountBattle.SteerUnit>),
	    //typeof(FIMSpace.FProceduralAnimation.RagdollAnimator),
	    //------zlh end----
	    
	    typeof(TMPTeletypeComponent),
	    typeof(ZipDataTable),
	    //typeof(WayPointSimple),
	    
	    //typeof(FOWSystem),
	    //typeof(FowSystem2),
	    //typeof(FOWRevealer),
	    
	    typeof(UnityEngine.Random),
	    typeof(UnityEngine.Random.State),
	    typeof(UnityEngine.Rendering.Volume),
	    typeof(UnityEngine.Rendering.Universal.Bloom),
	    typeof(UnityEngine.Rendering.Universal.Tonemapping),
	    
	    
	    ///////////////////////////////////////
	    typeof(List<BitBenderGames.WrappedTouch>),
	    //typeof(List<WayPointSimple>),
	    
	    //typeof(UnityEngine.Rendering.Universal.UniversalRenderPipelineAsset),
	    typeof(UnityEngine.Rendering.Universal.UniversalAdditionalCameraData),
	    
	    typeof(GameFramework.Localization.Language),
	    typeof(AnimationCurveList),
	    typeof(UnityEngine.AnimationCurve),
	    typeof(UnityEngine.WeightedMode),
	    typeof(UnityEngine.Keyframe),
	    //typeof(TileCoordWorld),
	    //typeof(TileCoord),
	    typeof(GameUtility),
	    typeof(DownloadManifest),
	    typeof(PBController),
	    typeof(Main.Scripts.Network.FutureManager),
	    typeof(UnityEngine.QueryTriggerInteraction),
	    typeof(UnityEngine.RenderMode),
	    //typeof(CitySpaceManTrigger),
	    typeof(Sfs2X.Entities.Data.SFSObject),
	    typeof(LoginMessage),
	    typeof(PushManager),
	    //typeof(TouchObjectEvent),
	    //typeof(URPOutlineFeature),
	    //typeof(GrabRenderPassFeature),
	    //typeof(BlurURP),
	    //typeof(UIWorldLabel),
	    
	    //typeof(ITouchObjectPointerDownHandler),
	    //typeof(ITouchObjectBeginLongTabHandler),
	    //typeof(ITouchObjectDragHandler),
	    //typeof(ITouchObjectEndDragHandler),
	    
	    //typeof(LWBattleRVOManager),
	    //typeof(LWBattleRVOAgent),
		
	    //typeof(BuildFenceDoor),
	    
    };

    
    //黑名单
    // 这里只需要屏蔽一些打包时编译不过的接口
	[BlackList] // new List<string>() {类型的全路径, 成员或者方法名, 方法的参数类型的全路径}
	public static List<List<string>> BlackList = new List<List<string>>()  {
		// ReadOnlySpan<T>/Span<T> cannot be used as generic type argument in generated wrappers (Unity 2022+)
		new List<string>(){"UnityEngine.Object", "InstantiateAsync", "UnityEngine.Object", "System.Int32", "System.ReadOnlySpan`1[UnityEngine.Vector3]", "System.ReadOnlySpan`1[UnityEngine.Quaternion]"},
		new List<string>(){"UnityEngine.Object", "InstantiateAsync", "UnityEngine.Object", "System.ReadOnlySpan`1[UnityEngine.Vector3]", "System.ReadOnlySpan`1[UnityEngine.Quaternion]", "UnityEngine.Transform"},
		new List<string>(){"UnityEngine.Object", "InstantiateAsync", "UnityEngine.Object", "System.ReadOnlySpan`1[UnityEngine.Vector3]", "System.ReadOnlySpan`1[UnityEngine.Quaternion]", "UnityEngine.InstantiateParameters"},
		new List<string>(){"UnityEngine.GameObject", "SetGameObjectsActive", "System.ReadOnlySpan`1[System.Int32]", "System.Boolean"},
		// Transform batch methods with Span<Vector3>/ReadOnlySpan<Vector3> params
		new List<string>(){"UnityEngine.Transform", "TransformDirections", "System.Span`1[UnityEngine.Vector3]"},
		new List<string>(){"UnityEngine.Transform", "TransformDirections", "System.ReadOnlySpan`1[UnityEngine.Vector3]", "System.Span`1[UnityEngine.Vector3]"},
		new List<string>(){"UnityEngine.Transform", "InverseTransformDirections", "System.Span`1[UnityEngine.Vector3]"},
		new List<string>(){"UnityEngine.Transform", "InverseTransformDirections", "System.ReadOnlySpan`1[UnityEngine.Vector3]", "System.Span`1[UnityEngine.Vector3]"},
		new List<string>(){"UnityEngine.Transform", "TransformVectors", "System.Span`1[UnityEngine.Vector3]"},
		new List<string>(){"UnityEngine.Transform", "TransformVectors", "System.ReadOnlySpan`1[UnityEngine.Vector3]", "System.Span`1[UnityEngine.Vector3]"},
		new List<string>(){"UnityEngine.Transform", "InverseTransformVectors", "System.Span`1[UnityEngine.Vector3]"},
		new List<string>(){"UnityEngine.Transform", "InverseTransformVectors", "System.ReadOnlySpan`1[UnityEngine.Vector3]", "System.Span`1[UnityEngine.Vector3]"},
		new List<string>(){"UnityEngine.Transform", "TransformPoints", "System.Span`1[UnityEngine.Vector3]"},
		new List<string>(){"UnityEngine.Transform", "TransformPoints", "System.ReadOnlySpan`1[UnityEngine.Vector3]", "System.Span`1[UnityEngine.Vector3]"},
		new List<string>(){"UnityEngine.Transform", "InverseTransformPoints", "System.Span`1[UnityEngine.Vector3]"},
		new List<string>(){"UnityEngine.Transform", "InverseTransformPoints", "System.ReadOnlySpan`1[UnityEngine.Vector3]", "System.Span`1[UnityEngine.Vector3]"},
		new List<string>(){"VEngine.Manifest", "AddAsset"},
		new List<string>(){"VEngine.Manifest", "Save"},
		new List<string>(){"VEngine.Manifest", "AllAssetPaths"},
        new List<string>(){"UnityEngine.Texture2D", "alphaIsTransparency"},
        new List<string>(){"UnityEngine.Security", "GetChainOfTrustValue"},
        new List<string>(){"UnityEngine.CanvasRenderer", "onRequestRebuild"},
        new List<string>(){"UnityEngine.Light", "areaSize"},
        new List<string>(){"UnityEngine.Light", "lightmapBakeType"},
        new List<string>(){"UnityEngine.AnimatorOverrideController", "PerformOverrideClipListCleanup"},
        new List<string>(){"UnityEngine.Application", "ExternalEval"},
        new List<string>(){"UnityEngine.GameObject", "networkView"}, //4.6.2 not support
        new List<string>(){"UnityEngine.Component", "networkView"},  //4.6.2 not support
        new List<string>(){"UnityEngine.MonoBehaviour", "runInEditMode"},
        new List<string>(){"UnityEngine.Input", "location"},
		new List<string>(){ "UnityEngine.UI.Text", "OnRebuildRequested"},
		new List<string>(){ "SDKManager", "Android"},
		//new List<string>(){ "Type", "IS"},
		
		new List<string>(){ "GPUSkinningAnimator", "DeletePlayer"},
		new List<string>(){ "GPUSkinningAnimator", "Update_Editor"},
		new List<string>(){ "GPUSkinningAnimator", "OnValidate"},
		
		new List<string>(){ "UnityEngine.MeshRenderer", "additionalVertexStreams"},
		new List<string>(){ "UnityEngine.MeshRenderer", "subMeshStartIndex"},
		new List<string>(){ "UnityEngine.MeshRenderer", "scaleInLightmap"},
		new List<string>(){ "UnityEngine.MeshRenderer", "receiveGI"},
		new List<string>(){ "UnityEngine.MeshRenderer", "stitchLightmapSeams"},
		
		new List<string>(){ "UnityEngine.Camera", "stereoActiveEye"},
		new List<string>(){ "UnityEngine.Camera", "GetStereoNonJitteredProjectionMatrix"},
		new List<string>(){ "UnityEngine.Camera", "GetStereoViewMatrix"},
		new List<string>(){ "UnityEngine.Camera", "CopyStereoDeviceProjectionMatrixToNonJittered"},
		new List<string>(){ "UnityEngine.Camera", "GetStereoProjectionMatrix"},
		new List<string>(){ "UnityEngine.Camera", "SetStereoProjectionMatrix"},
		new List<string>(){ "UnityEngine.Camera", "ResetStereoProjectionMatrices"},
		new List<string>(){ "UnityEngine.Camera", "SetStereoViewMatrix"},
		new List<string>(){ "UnityEngine.Camera", "ResetStereoViewMatrices"},
		// new List<string>(){ "UnityEngine.Camera", "WorldToViewportPoint", "UnityEngine.Vector3", "UnityEngine.Camera+MonoOrStereoscopicEye"},
		new List<string>(){ "UnityEngine.Camera", "ViewportToWorldPoint", "UnityEngine.Vector3", "UnityEngine.Camera+MonoOrStereoscopicEye"},
		new List<string>(){ "UnityEngine.Camera", "ViewportPointToRay", "UnityEngine.Vector2", "UnityEngine.Camera+MonoOrStereoscopicEye"},
		new List<string>(){ "UnityEngine.Camera", "ViewportPointToRay", "UnityEngine.Vector3", "UnityEngine.Camera+MonoOrStereoscopicEye"},
		new List<string>(){ "UnityEngine.Camera", "stereoActiveEye"},
		new List<string>(){ "UnityEngine.Camera", "CalculateFrustumCorners"},
		new List<string>(){ "UnityEngine.Camera", "RenderToCubemap", "UnityEngine.RenderTexture", "System.Int32", "UnityEngine.Camera+MonoOrStereoscopicEye"},
		new List<string>(){ "UnityEngine.Camera", "StereoscopicEye"},

		new List<string>(){ "UnityEngine.RenderTexture", "ConvertToEquirect"},
		new List<string>(){ "UnityEngine.Texture", "imageContentsHash"},

		new List<string>(){ "UnityEngine.Input", "IsJoystickPreconfigured"},
		new List<string>(){ "UnityEngine.Input", "GetJoystickNames"},
		new List<string>(){ "UnityEngine.QualitySettings", "GetAllRenderPipelineAssetsForPlatform"},
		new List<string>(){ "UnityEngine.QualitySettings", "streamingMipmapsRenderersPerFrame"},
		
		new List<string>(){ "UnityEngine.UI.Graphic", "OnRebuildRequested"},
		new List<string>(){ "UnityEngine.UI.Graphic", "OnValidate"},
		
		
		new List<string>(){ "UnityEngine.AudioSource", "PlayOnGamepad"},
		new List<string>(){ "UnityEngine.AudioSource", "DisableGamepadOutput"},
		new List<string>(){ "UnityEngine.AudioSource", "SetGamepadSpeakerMixLevel"},
		new List<string>(){ "UnityEngine.AudioSource", "SetGamepadSpeakerMixLevelDefault"},
		new List<string>(){ "UnityEngine.AudioSource", "SetGamepadSpeakerRestrictedAudio"},
		new List<string>(){ "UnityEngine.AudioSource", "GamepadSpeakerOutputType"},
		new List<string>(){ "UnityEngine.AudioSource", "GamepadSpeakerSupportsOutputType"},
		new List<string>(){ "UnityEngine.AudioSource", "gamepadSpeakerOutputType"},
		
		new List<string>(){ "UnityEngine.ParticleSystem", "CollisionEvent"},

		// 3.33 新增的类处理掉
		new List<string>(){ "UnityEngine.QualitySettings", "realtimeGICPUUsage"},
		new List<string>(){ "UnityEngine.Material", "CopyMatchingPropertiesFromMaterial"},
		
		new List<string>(){ "System.Type", "MakeGenericSignatureType"},
		new List<string>(){ "System.Type", "IsCollectible"},
		
		new List<string>(){ "UniversalRenderPipelineAsset", "packagePath"},
		new List<string>(){ "UniversalRenderPipelineAsset", "editorResourcesGUID"},
		new List<string>(){ "UniversalRenderPipelineAsset", "Create"},
		
		

	};

}



