---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by mac.
--- DateTime: 8/31/21 12:28 PM
---
local UIButton_LongPress = BaseClass("UIButton_LongPress", UIBaseContainer)
local base = UIBaseContainer
local UnityButton = typeof(CS.UnityEngine.UI.Button_LongPress)
local ButtonRef = {}

function UIButton_LongPress.AddRef(btn, ref)
    ButtonRef[btn] = ref
end

function UIButton_LongPress.DecRef(btn)
    ButtonRef[btn] = nil
end

function UIButton_LongPress.GetRef(btn)
    return ButtonRef[btn]
end

-- 创建
local function OnCreate(self)
    base.OnCreate(self)
    -- Unity侧原生组件
    self.unity_uibutton = self.gameObject:GetComponent(UnityButton)
    UIButton_LongPress.AddRef(self.unity_uibutton, self)
    self.long_press_fun = {}
    self.click_fun = {}
    self.long_press_callback = function()
        self:LongPressCallback()
    end
    self.click_callback = function()
        self:ClickCallback()
    end
    self.long_press_enable = true
    if self.unity_uibutton ~= nil then
        self.unity_uibutton:SetLongPressAction(self.long_press_callback)
        self.unity_uibutton:SetClickAction(self.click_callback)
    end
end

local function OnDestroy(self)
    UIButton_LongPress.DecRef(self.unity_uibutton)
    self.long_press_fun = {}
    self.click_fun = {}
    self.unity_uibutton:SetLongPressAction(nil)
    self.unity_uibutton:SetClickAction(nil)
end

local function SetLongPressAction(self, callback )
    if callback ~= nil then
        local add = true
        if self.long_press_fun[1] ~= nil then
            for k,v in ipairs(self.long_press_fun) do
                if v == callback then
                    add = false
                    break
                end
            end
        end
        if add then
            table.insert(self.long_press_fun, callback)
        end
    end
end

function UIButton_LongPress:RemoveLongPressAction(callback)
    if callback ~= nil and self.long_press_fun[1] ~= nil then
        for k,v in ipairs(self.long_press_fun) do
            if v == callback then
                table.remove(self.long_press_fun, k)
                break
            end
        end
    end
end

local function SetClickAction(self, callback)
    if callback ~= nil then
        local add = true
        if self.click_fun[1] ~= nil then
            for k,v in ipairs(self.click_fun) do
                if v == callback then
                    add = false
                    break
                end
            end
        end
        if add then
            table.insert(self.click_fun, callback)
        end
    end
end

function UIButton_LongPress:RemoveClickAction(callback)
    if callback ~= nil and self.click_fun[1] ~= nil then
        for k,v in ipairs(self.click_fun) do
            if v == callback then
                table.remove(self.click_fun, k)
                break
            end
        end
    end
end

local function SetTouchBgGray(self, touchGray)
    self.unity_uibutton:SetTouchBgGray(touchGray)
end

local function SetPressDurationTime(self, pressDurationTime)
    self.unity_uibutton.pressDurationTime = pressDurationTime
end

function UIButton_LongPress:LongPressCallback()
    if self.long_press_enable and self.long_press_fun[1] ~= nil then
        for k,v in ipairs(self.long_press_fun) do
            v()
        end
    end
end

function UIButton_LongPress:ClickCallback()
    if self.click_fun[1] ~= nil then
        for k, v in ipairs(self.click_fun) do
            v()
        end
    end
end

function UIButton_LongPress:SetLongPressEnable(enable)
    self.long_press_enable = enable
end

function UIButton_LongPress:SetIsOnceLongPress(isonce)
    self.unity_uibutton.onceLongPress = isonce
end

UIButton_LongPress.OnCreate = OnCreate
UIButton_LongPress.OnDestroy = OnDestroy
UIButton_LongPress.SetLongPressAction = SetLongPressAction
UIButton_LongPress.SetClickAction = SetClickAction
UIButton_LongPress.SetTouchBgGray = SetTouchBgGray
UIButton_LongPress.SetPressDurationTime = SetPressDurationTime


return UIButton_LongPress