---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangliheng.
--- DateTime: 12/17/2024 9:33 PM
---

---@class DataCenter.PveMonster.BarrelMonsterBaseTemplate
local BarrelMonsterBaseTemplate = BaseClass("BarrelMonsterBaseTemplate")

local function __init(self)
end

local function __delete(self)
end

local function InitData(self, row)
    if row == nil then
        return
    end

    self.id = row:getValue("id")
    self.asset = row:getValue("asset")
    self.avatar = row:getValue("avatar")
    self.icon = row:getValue("icon")
    self.monster_type = tonumber(row:getValue("monster_type")) or 0
    self.is_attack = tonumber(row:getValue("is_attack")) or 0
    self.is_move = tonumber(row:getValue("is_move")) or 0
    self.move_speed = tonumber(row:getValue("move_speed")) or 0
    self.alert_range = tonumber(row:getValue("alert_range")) or 0
    self.hp_bar_num = tonumber(row:getValue("hp_bar_num")) or 0
    self.attack = tonumber(row:getValue("attack")) or 0
    self.attack_interval = tonumber(row:getValue("attack_interval")) or 0
    self.hp = tonumber(row:getValue("hp")) or 1
    self.hp_bar_height = tonumber(row:getValue("hp_bar_height")) or 2
    self.collide_radius = tonumber(row:getValue("collide_radius")) or 1
    self.death_trigger_item = tonumber(row:getValue("death_trigger_item"))
    self.model_size = tonumber(row:getValue("model_size")) or 1
    self.crash_kill = tonumber(row:getValue("crash_kill")) or 0
    self.is_boss = tonumber(row:getValue("is_boss")) or 0

    self.hp = tonumber(row:getValue("hp")) or 1
    self.physics_defence = tonumber(row:getValue("physics_defence")) or 0
    self.magic_defence = tonumber(row:getValue("magic_defence")) or 0

    local goldCfg = string.split_ii_array(row:getValue("gold") or '', '|')
    if goldCfg ~= nil and #goldCfg == 2 then
        self.gold = goldCfg[1]
        self.showDropGold = goldCfg[2] == 1
    end
    self.skill = row:getValue("skill")

    self.ignore_hit_stiff = tonumber(row:getValue("ignore_hit_stiff")) or 0
    self.ignore_hit_back = tonumber(row:getValue("ignore_hit_back")) or 0
    --self.property=row:getValue("property")
    self.monster_effect = tonumber(row:getValue("monster_effect")) or 0

    self.collide_count = tonumber(row:getValue("collide_count")) or -1
    self.collide_damage = nil
    local collide_damage = row:getValue("collide_damage")
    if #collide_damage == 3 then
        self.collide_damage = collide_damage
    end

    self.param = row:getValue('param')
    self.be_hit_sound = StringPool.New(row:getValue("behit_sound"),";")
    self.monster_ai = tonumber(row:getValue('monster_ai')) or 0
    self.death_asset = string.string2table_sf(row:getValue('death_asset') or "", '|', ';')
    self.prefab_change = string.split_ff_array(row:getValue('prefab_change') or '', '|')
    self.run_ani_speed = tonumber(row:getValue("run_ani_speed")) or 1
    self.born_show = StringPool.New(row:getValue("born_show"), ";")
    self.run_show = StringPool.New(row:getValue("run_show"), ";")
    self.death_show = StringPool.New(row:getValue("death_show"), ";")
    self.hide_damage_txt = tonumber(row:getValue('hide_damage_txt')) == 1
    self.move_sound = row:getValue('move_sound')
    self.dynamic_collider = row:getValue('dynamic_collider')
end


local deathAssetGlobalIdx = 0
local function GetRandomDeathAsset(self)
    if self.death_asset == nil or next(self.death_asset) == nil then
        return nil
    end

    local keys = table.keys(self.death_asset)
    local len = table.count(keys)
    deathAssetGlobalIdx = deathAssetGlobalIdx + 1
    if deathAssetGlobalIdx > len then
        deathAssetGlobalIdx = 1
    end

    local path = keys[deathAssetGlobalIdx]
    local duration = tonumber(self.death_asset[path])/ 1000

    return path, duration
end


BarrelMonsterBaseTemplate.__init = __init
BarrelMonsterBaseTemplate.__delete = __delete
BarrelMonsterBaseTemplate.InitData = InitData
BarrelMonsterBaseTemplate.GetRandomDeathAsset = GetRandomDeathAsset


return BarrelMonsterBaseTemplate
