---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenshaowen.
--- DateTime: 2022/5/24 5:57 PM
---

local LoadingStateBase = require("Loading.LoadingState.LoadingStateBase")
local AppUpdateState = BaseClass("AppUpdateState", LoadingStateBase)
--local GameEntry = CS.GameEntry
--local Const = require("Loading.Const")

function AppUpdateState:__init(startupLoading)
    LoadingStateBase:__init(startupLoading)
end

function AppUpdateState:OnEnter(args)
    --self:ShowAppUpgradeMessage()
end

function AppUpdateState:OnExit()

end

function AppUpdateState:OnUpdate()

end

function AppUpdateState:ShowAppUpgradeMessage(s)
    --local str = GameEntry.GlobalData.analyticID == "market_global" and "GOOGLE" or GameEntry.GlobalData.analyticID;
    --local content = Localization:GetString("129013", str);
    --
    --if GameEntry.GlobalData.updateType == 1 then
    --    UIUtil.ShowMessage(content, 2, "110003", "", function()
    --        if not LuaEntry.GlobalData.downloadurl.IsNullOrEmpty() then
    --            CS.CommonUtils.OpenURL(LuaEntry.GlobalData.downloadurl)
    --        end
    --    end, function()
    --        GameEntry.GlobalData.updateType = 0;
    --        self._startupLoading:SetState(Const.LoadingState.PushInit);
    --    end)
    --elseif GameEntry.GlobalData.updateType == 2 then
    --    UIUtil.ShowMessage(content, 1, "110003", "", function()
    --        if not LuaEntry.GlobalData.downloadurl.IsNullOrEmpty() then
    --            CS.CommonUtils.OpenURL(LuaEntry.GlobalData.downloadurl)
    --        end
    --    end, function()
    --        if not LuaEntry.GlobalData.downloadurl.IsNullOrEmpty() then
    --            CS.CommonUtils.OpenURL(LuaEntry.GlobalData.downloadurl)
    --        end
    --    end)
    --end
end

return AppUpdateState