---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenshaowen.
--- DateTime: 2022/5/24 6:07 PM
---

local LoadingStateBase = require("Loading.LoadingState.LoadingStateBase")
local AuthPinState = BaseClass("AuthPinState", LoadingStateBase)

function AuthPinState:__init(startupLoading)
    LoadingStateBase:__init(startupLoading)
end

function AuthPinState:OnEnter(args)
    --self._startupLoading.IsPushInitReceived = false
    --self:ShowAuthUI()
end

function AuthPinState:OnExit()

end

function AuthPinState:OnUpdate()

end

function AuthPinState:ShowAuthUI()
    --if not UIManager:GetInstance():IsWindowOpen(UIWindowNames.UIPinInput) then
    --    UIManager:GetInstance():OpenWindow(UIWindowNames.UIPinInput)
    --end
end

return AuthPinState