---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangliheng.
--- DateTime: 2023/8/30 10:25
---
--- 确保主城依赖资源都已准备完成

local LoadingStateBase = require("Loading.LoadingState.LoadingStateBase")
local CheckMainLevelRes = BaseClass("CheckMainLevelRes", LoadingStateBase)
--local Const = require("Loading.Const")
--local ResourceManager = CS.GameEntry.Resource
--local PVEScenePath = "Assets/Main/Prefabs/PVELevelScenes/%s/scene.prefab"


function CheckMainLevelRes:OnEnter(args)
    --local hasAsset, assetPath = self:__isLevelDownloaded(LevelId.Main)
    --if hasAsset then
    --    self:__onDownloadComplete()
    --    return
    --end
    --
    --self:__startDownload(assetPath)
end

function CheckMainLevelRes:OnExit()
    --if self.downloadingVersion ~= nil then
    --    if not self.downloadingVersion.isDone then
    --        self.downloadingVersion:Stop()
    --    end
    --
    --    self.downloadingVersion = nil
    --end
end

function CheckMainLevelRes:__isLevelDownloaded(levelId)
    --local scenePrefabName = GetTableData(TableName.PVELevel, levelId, "Scene")
    --scenePrefabName = string.gsub(scenePrefabName, '.prefab', '')
    --local assetPath = string.format(PVEScenePath, scenePrefabName)
    --local hasAsset = ResourceManager:IsAssetDownloaded(assetPath)
    --if hasAsset then
    --    Logger.Log('#CheckMainLevelRes# main city resource verify passed!')
    --    return true
    --end
    --
    --return hasAsset, assetPath
end

function CheckMainLevelRes:__startDownload(assetPath)
    --Logger.Log('#CheckMainLevelRes# step in __startDownload')
    --self.isDownloadComplete = false
    --self.assetPath = assetPath
    --
    --local List_BundleInfo = CS.System.Collections.Generic.List(CS.VEngine.BundleInfo)
    --self.needDownloadList = List_BundleInfo()
    --local isValid, totalSize, needDownloadSize = ResourceManager:GetBundleInfosOfAsset(self.assetPath, self.needDownloadList)
    --if not isValid then
    --    self:__onDownloadError('#zlh# CheckMainLevelRes 下载错误,资源在清单文件中不存在! assetPath:' .. tostring(self.assetPath))
    --    return
    --end
    --
    --if totalSize <= 0 then
    --    self:__onDownloadError('#zlh# CheckMainLevelRes 下载错误 totalSize is 0!')
    --    return
    --end
    --
    --self.totalSize = needDownloadSize
    ----后台开启高优先级下载
    --self.downloadingVersion = ResourceManager:StartHighestPriorityDownload(self.needDownloadList)
    --self._startupLoading:SetBundleDownloadTotalBytes(needDownloadSize)
    ----通知loadingView2
    --EventManager:GetInstance():Broadcast(EventId.SU_BeginDownloadMainLevelRes)
    --
    --Logger.Log('#CheckMainLevelRes# start download totalSize:' .. tostring(needDownloadSize))
end

function CheckMainLevelRes:__onDownloadComplete()
    --Logger.Log('#zlh# step in CheckMainLevelRes:OnDownloadComplete!')
    --self.isDownloadComplete = true
    --EventManager:GetInstance():Broadcast(EventId.SU_EndDownloadMainLevelRes)
    --self._startupLoading:StartConnect()
end

function CheckMainLevelRes:__onDownloadError(errorMsg)
    --Logger.LogError("#bundle# CheckMainLevelRes download error " .. errorMsg)
    --self._startupLoading:SetState(Const.LoadingState.LoadingError, Const.LoginErrorCode.ERROR_DOWNLOAD_UPDATE)
end

function CheckMainLevelRes:OnUpdate()
    --if self.isDownloadComplete then
    --    return
    --end
    --
    --if not self.downloadingVersion.isDone then
    --    local progress = self.downloadingVersion.progress
    --    --Logger.Log("#bundle# CheckMainLevelRes download progress: " .. progress)
    --    self._startupLoading:SetBundleDownloadProgress(progress)
    --else
    --    if self.downloadingVersion.isError then
    --        self:__onDownloadError(self.downloadVersions.error)
    --    else
    --        self:__onDownloadComplete()
    --    end
    --end
end

return CheckMainLevelRes
