---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangliheng.
--- DateTime: 5/8/2025 4:50 PM
---
--- Desc: 1.替换成LuaWebRequest 2.改完Post请求
---

local LoadingStateBase = require("Loading.LoadingState.LoadingStateBase")

---@class CheckResVersionState : LoadingStateBase
local CheckResVersionState = BaseClass("CheckResVersionState", LoadingStateBase)
--local Const = require("Loading.Const")
--local util = require "Common.Tools.cjson.util"
--local WWWForm = CS.UnityEngine.WWWForm
--local CHECK_VERSION_ENDPOINT = "/gameservice/getlsu3dversion.php"
--local USE_GET_METHOD_DEF = false


--local StateType = {
--    Init = 1,
--    Requesting = 2,
--    AllFailed = 3,
--    Success = 4,
--}

function CheckResVersionState:__init(startupLoading)
    LoadingStateBase:__init(startupLoading)

    --self.requestList = {}
    --self.requestHostMap = {}
    --self.reqErrorRecord = {}
    --
    --self.curState = StateType.Init
end

function CheckResVersionState:OnEnter(args)
    -- 如果是跳过更新过程的话，就直接设置加载表格状态
	-- 否则去http获取更新的文本
    --if App.IsEditor() or CS.GameEntry.Resource.SkipUpdate then
	--	Logger.Log("CheckResVersionState - SkipUpdate!!")
    --    self._startupLoading:SetState(Const.LoadingState.LoadDataTable)
    --else
	--	self:StartVersionRequestParallel()
    --    --test
    --    --self:ResolveDomainByDOH()
	--end
end

function CheckResVersionState:OnExit()
    --self:StopAllRequest()
    --self.requestHostMap = nil
    --self.requestList = nil
    --self.reqErrorRecord = nil
end

function CheckResVersionState:OnUpdate()
    --if self.curState == StateType.Requesting then
    --    if self.requestList ~= nil then
    --        for _, req in ipairs(self.requestList) do
    --            if req ~= nil then
    --                XPCALL(function() req:OnUpdate() end)
    --            end
    --
    --            if self.curState ~= StateType.Requesting then
    --                break
    --            end
    --        end
    --    end
    --end
end


--region-----------------------------CheckVersion多条线修改------------------------------

function CheckResVersionState:StartVersionRequestParallel()
    --self.curState = StateType.Requesting
    --
    --local requestParams = self:BuildRequestParams()
    --PostEventLog.Record(PostEventLog.Defines.CHECK_VERSION_START)
    --self.hostList = self._startupLoading:GetCheckVersionUrlList()
    --for _, hostCfg in ipairs(self.hostList) do
    --    if not string.IsNullOrEmpty(hostCfg.cv) then
    --        local req = self:StartRequest(hostCfg.cv, requestParams)
    --        table.insert(self.requestList, req)
    --        self.requestHostMap[req] = hostCfg
    --    end
    --end
end

function CheckResVersionState:BuildRequestParams()
    --local gm = self:GetGMFlag()
    --local uid = Setting:GetPublicString(SettingKeys.GAME_UID, "")
    --local server = Setting:GetPublicString(SettingKeys.SERVER_ZONE, "")
    --local platform = App.GetPlatformName()
    --if platform ~= "Android" and platform ~= "iOS" then
    --    platform = "Android"
    --end
    --local ret = ''
    --local zoneName = server
    --if string.IsNullOrEmpty(zoneName) or string.len(zoneName) < 3 then
    --else
    --    ret = string.SubStr(zoneName, 4)
    --end
    --
    --local params = {}
    --params.packageName = self:GetPackageName()
    --params.platform = platform
    --params.appVersion = App.GetVersion()
    --params.gm = tostring(gm)
    --params.server = tostring(server)
    --params.uid = uid
    --params.deviceId = App.GetDeviceUid()
    --params.returnJson = "1"
    --params.serverId = ret
    --
    --return params
end

function CheckResVersionState:StartRequest(url, requestParams)
    --local finalUrl = url .. CHECK_VERSION_ENDPOINT
    --local request
    --if USE_GET_METHOD_DEF then
    --    local queryString = BuildQueryString(requestParams)
    --    request = LuaWebRequest.Get(finalUrl .. "?" .. queryString)
    --    LoadingPrint("CheckResVersion (GET): " .. finalUrl .. "?" .. queryString)
    --else
    --    local form = WWWForm()
    --    for k, v in pairs(requestParams) do
    --        form:AddField(tostring(k), v)
    --    end
    --    request = LuaWebRequest.Post(finalUrl, form)
    --    LoadingPrint("CheckResVersion (POST): " .. finalUrl .. "?" .. BuildQueryString(requestParams))
    --end
    --
    --if request then
    --    local timeoutCallback = BindCallback(self, self.RequestTimeoutHandler)
    --    local failedCallback = BindCallback(self, self.RequestFailedHandler)
    --    local successCallback = BindCallback(self, self.RequestSuccessHandler)
    --    request:SetCallback(timeoutCallback, failedCallback, successCallback)
    --
    --    request:SendRequest()
    --else
    --    Logger.LogError("CheckResVersion Failed to create LuaWebRequest!")
    --end
    --
    --return request
end

function CheckResVersionState:StopAllRequest()
    --if self.requestList ~= nil then
    --    for _, req in ipairs(self.requestList) do
    --        req:DisposeRequest()
    --    end
    --
    --    self.requestList = nil
    --end
end

function CheckResVersionState:HasAliveRequest()
    --local ret = false
    --for _, req in ipairs(self.requestList) do
    --    if self.reqErrorRecord[req] == nil and string.IsNullOrEmpty(req.error) then
    --        ret = true
    --        break
    --    end
    --end
    --
    --return ret
end

function CheckResVersionState:RequestFailedHandler(req, error)
    --Logger.LogErrorFormat("CheckResVersionState:[Request Failed], err:{%s}", tostring(error))
    --self.reqErrorRecord[req] = "req_failed"
    --
    --local hasAliveRequest = self:HasAliveRequest()
    --if not hasAliveRequest then
    --    Logger.LogErrorFormat("CheckResVersion:[All Failed], state:{%s}", self:GetAllReqErrorStateString())
    --    PostEventLog.Record(PostEventLog.Defines.CHECK_VERSION_FAILED, tostring(error))
    --    AppStartupLoading:GetInstance():ForceToConnectGame(LoginErrorMessage.ERROR_CHECK_VERSION_FAILED)
    --    self.curState = StateType.AllFailed
    --end
end

function CheckResVersionState:RequestTimeoutHandler(req)
    --Logger.LogError("CheckResVersionState:[Timeout]")
    --self.reqErrorRecord[req] = "req_timeout"
    --
    --local hasAliveRequest = self:HasAliveRequest()
    --if not hasAliveRequest then
    --    Logger.LogErrorFormat("CheckResVersion:[All Failed], state:{%s}", self:GetAllReqErrorStateString())
    --    PostEventLog.Record(PostEventLog.Defines.CHECK_VERSION_TIMEOUT)
    --    AppStartupLoading:GetInstance():ForceToConnectGame(LoginErrorMessage.ERROR_CHECK_VERSION_TIMEOUT)
    --    self.curState = StateType.AllFailed
    --end
end

function CheckResVersionState:RequestSuccessHandler(req, downloadHandler)
    --if self.curState ~= StateType.Requesting then
    --    return
    --end
    --
    --local hostCfg = self.requestHostMap[req]
    --Logger.LogFormat("CheckResVersionState:[Success], url:{%s}, raw json:{%s}", hostCfg.cv, downloadHandler.text)
    --AppStartupLoading:GetInstance():SetCheckResRecvText(downloadHandler.text)
    --local tabJson = CommonUtil.JsonDecode(downloadHandler.data)
    --if not table.IsNullOrEmpty(tabJson) then
    --    PostEventLog.Record(string.format("CheckRes_Success:[%s]", hostCfg.lineName))
    --    Logger.Log(string.format("CheckRes_Success:[%s]", hostCfg.lineName))
    --
    --    self.curState = StateType.Success
    --    self:ParseResponseMsg(req, tabJson)
    --    self:StopAllRequest()
    --
    --    if hostCfg.gsl ~= nil then
    --        self._startupLoading:SetPreferGateUrl(hostCfg.gsl, hostCfg.lineName)
    --    end
    --else
    --    Logger.LogError("CheckResVersion:[Success ParseError]")
    --    self.reqErrorRecord[req] = 'parse_error'
    --    local hasAliveRequest = self:HasAliveRequest()
    --    if not hasAliveRequest then
    --        Logger.LogErrorFormat("CheckResVersion:[All Failed], state:{%s}", self:GetAllReqErrorStateString())
    --        PostEventLog.Record(PostEventLog.Defines.CHECK_VERSION_PARSE_ERROR)
    --        AppStartupLoading:GetInstance():ForceToConnectGame(LoginErrorMessage.ERROR_CHECK_VERSION_FAILED)
    --        self.curState = StateType.AllFailed
    --    end
    --end
end

function CheckResVersionState:GetAllReqErrorStateString()
    --local result = {}
    --for req, stateStr in pairs(self.reqErrorRecord) do
    --    local hostCfg = self.requestHostMap[req]
    --    if hostCfg ~= nil then
    --        table.insert(result, string.format("%s=%s", tostring(hostCfg.lineName), stateStr))
    --    end
    --end
    --
    --return table.concat(result, "|")
end

--endregion--------------------------------------------------------------------------------

function CheckResVersionState:ParseResponseMsg(req, _tabJson)
    --local _hotUpdateMsg = _tabJson["hotUpdateMsg"] or ""
    --local _updateType = _tabJson["updateType"] or ""
    --_updateType = tonumber(_updateType) or 0
    --local _downloadUrl = _tabJson["downloadurl"] or ""
    --self:SaveManifestVersion(_hotUpdateMsg)
    --
    --local str = "Google Play";
    --local btn2_dialogId = "129016"
    --if App.IS_IOS() then
    --    str = "AppStore"
    --    btn2_dialogId = "129018"
    --end
    --
    --if (_updateType == 1) then
    --    local _content = Localization:GetString(129013, str)
    --    UIUtil.ShowMessage(_content, 2, btn2_dialogId, "129017", function()
    --        if ( not string.IsNullOrEmpty(_downloadUrl)) then
    --            CS.CommonUtils.OpenURL(_downloadUrl);
    --        end
    --    end, function()
    --        self._startupLoading:SetState(Const.LoadingState.DownloadManifest)
    --    end, function()
    --        self._startupLoading:SetState(Const.LoadingState.DownloadManifest)
    --    end)
    --elseif _updateType == 2 then
    --    local _content = Localization:GetString(129013, str)
    --    UIUtil.ShowMessage(_content, 1, "110003", "", function()
    --        if ( not string.IsNullOrEmpty(_downloadUrl)) then
    --            CS.CommonUtils.OpenURL(_downloadUrl);
    --        end
    --    end, function()
    --
    --    end, function()
    --        if ( not string.IsNullOrEmpty(_downloadUrl)) then
    --            CS.CommonUtils.OpenURL(_downloadUrl);
    --        end
    --    end)
    --else
    --    self._startupLoading:SetState(Const.LoadingState.DownloadManifest)
    --end
end

function CheckResVersionState:SaveManifestVersion(data)
    --if (string.IsNullOrEmpty(data)) then
    --    return
    --end
    --local _tabHotUpdate = string.string2array_s(data, ';')
    --if (table.count(_tabHotUpdate) <= 0) then
    --    return
    --end
    --for _, item in pairs(_tabHotUpdate) do
    --    if (string.IsNullOrEmpty(item)) then
    --        goto continue
    --    end
    --    local _tabData = string.string2array_s(item, ',')
    --    if (table.count(_tabData) >= 4) then
    --        local _name = _tabData[1]
    --        local _version = _tabData[2]
    --        local _size = _tabData[3]
    --        local _crc = _tabData[4]
    --        local _content = string.format("%s,%s,%s", _version, _size, _crc)
    --        local _versionFile = string.lower(_name) .. ".version"
    --        _versionFile = CS.GameEntry.Resource:GetTempDownloadPath(_versionFile);
    --        util.file_save(_versionFile,_content)
    --        Logger.Log("**** return -> 保存文件 " .. _versionFile .. " content: " .. _content)
    --    end
    --    ::continue::
    --end
end

function CheckResVersionState:GetGMFlag()
    --if self.gm ~= nil then
    --    return self.gm
    --end
    --
    --local gm = Setting:GetPublicInt(SettingKeys.GM_FLAG)
    --if (App.IsGPTest()) then
    --    gm = 1
    --end
    --
    --self.gm = gm
    --return self.gm
end

function CheckResVersionState:GetPackageName()
    --if self.packageName ~= nil then
    --    return self.packageName
    --end
    --
    --local packageName = App.GetPackageName()
    --if (App.IsGPTest()) then
    --    packageName = string.gsub(packageName, "test", "")
    --end
    --self.packageName = packageName
    --
    --return self.packageName
end


return CheckResVersionState
