---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenshaowen.
--- DateTime: 2022/5/24 6:13 PM
---

local LoadingStateBase = require("Loading.LoadingState.LoadingStateBase")
local ConnectGameState = BaseClass("ConnectGameState", LoadingStateBase)
--local Const = require("Loading.Const")

function ConnectGameState:__init(startupLoading)
    LoadingStateBase:__init(startupLoading)
	--self.onGameConnection = BindCallback(self, self.OnGameConnection)
	--self.onConnectionError = BindCallback(self, self.OnGameConnectionError)
end

function ConnectGameState:OnEnter(args)
    --if not App.IsDebug() then
    --    XPCALL(function()
    --        CS.GameEntry.Sdk:initAppsFlyer(App.GetDeviceUid())
    --        PostEventLog.Record("initAppsFlyer")
    --    end)
    --end
    --
    --self._elapseTime = 0
    --self._timeout = 5
    --self._maxTryCount = 3
    --self._tryCount = 1
    --self._startupLoading.LoginTryCount = self._startupLoading.LoginTryCount + 1
    --
    --Logger.Log(string.format("#network# ConnectGameState:OnEnter serverUrl:%s, serverPort:%d", args[1], tonumber(args[2])))
    --
    --if not App.IsDebug() and not App.IsGPTest() then
    --    local zoneId = args[3]:gsub("%D+", "")
    --    args[2] = LuaEntry.Network:GetPortId(zoneId)
    --end
    --
    --LuaEntry.Network:SetGameServerUrl(args[1])
    --LuaEntry.Network:SetGameServerPort(args[2])
    --LuaEntry.Network:SetZoneName(args[3])
    --LuaEntry.Network:SetUid(args[4])
    --EventManager:GetInstance():AddListener(EventId.GameOnConnectOK, self.onGameConnection)
    --EventManager:GetInstance():AddListener(EventId.Net_Connect_Error, self.onConnectionError)
    --
    --LuaEntry.Network:Connect()
    --
    --AppStartupLoading:GetInstance():RequestServerStateUrl()
end

function ConnectGameState:OnExit()
    --EventManager:GetInstance():RemoveListener(EventId.GameOnConnectOK, self.onGameConnection)
    --EventManager:GetInstance():RemoveListener(EventId.Net_Connect_Error, self.onConnectionError)
end

function ConnectGameState:OnUpdate()
    --self._elapseTime = self._elapseTime + Time.deltaTime
    --if self._elapseTime > self._timeout then
    --    if self._tryCount < self._maxTryCount then
    --        if AppStartupLoading:GetInstance():CheckServerStateStop() then
    --            LuaEntry.Network:Disconnect()
    --            self._startupLoading:SetState(Const.LoadingState.LoadingError, Const.LoginErrorCode.ERROR_MAINTENANCE)
    --            return
    --        end
    --        LuaEntry.Network:Disconnect()
    --        LuaEntry.Network:Connect()
    --
    --        self._elapseTime = 0
    --        self._tryCount = self._tryCount + 1
    --        EventManager:GetInstance():Broadcast(EventId.NetworkRetry, true)
    --
    --        Logger.Log("[NET]connect game try count :", self._tryCount)
    --    else
    --        PostEventLog.Record("ConnectGameTimeOut ReachMaxAttempt")
    --        self:OnGameConnection(Const.LoginErrorCode.ERROR_TIMEOUT, "connect game server time out");
    --    end
    --end
end

function ConnectGameState:OnGameConnection(err, errorMessage)
    --if err ~= Const.LoginErrorCode.ERROR_SUCCESS then
    --    Logger.Log("connect error!")
    --    LuaEntry.Network:Disconnect()
    --    self._startupLoading:SetState(Const.LoadingState.GetServerStatus)
    --    return
    --end
    --
    --Logger.Log("Game server connected. start login")
    --EventManager:GetInstance():Broadcast(EventId.NetworkRetry, false)
    --self._startupLoading:SetState(Const.LoadingState.Login)
end

function ConnectGameState:OnGameConnectionError(err)
    --Logger.Log("Game server connected error. ", err)
    --self._startupLoading:SetState(Const.LoadingState.LoadingError, err)
end

return ConnectGameState
