---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenshaowen.
--- DateTime: 2022/5/24 6:15 PM
--- 根据当前manifest文件，去判断本地每一个资源是否符合预期，不一样的就需要去下载
--- 同时处理下载的大小和进度等

-- 这个totalSize很关键，是触发manifest复制的关键
-- 当totalSize = 0时，会有一个情况就是上次全都下载完毕，但是没有overwrite
-- 结果退出了游戏；下次进入时，发现要下载的本地都有，所以totalSize=0
-- 但是此时必须要overwrite；否则用户其实一直在用老版本进入的游戏。


local LoadingStateBase = require("Loading.LoadingState.LoadingStateBase")
--local Versions = require ("Loading.Versions")

local DownloadUpdateState = BaseClass("DownloadUpdateState", LoadingStateBase)
--local Const = require("Loading.Const")
--local Sdk = CS.GameEntry.Sdk
--local DownloadState =
--{
--    init = 0,
--    waitToInitLua = 1,
--}

function DownloadUpdateState:__init(startupLoading)
    LoadingStateBase:__init(startupLoading)

    --self.downloadVersions = nil
    --self.downloadManifestList = {}
    --self.bkgroundDownloadManifestList = {}
    --self._state = DownloadState.init
end

function DownloadUpdateState:OnEnter(args)
    --self._state = DownloadState.init
    --table.clear(self.bkgroundDownloadManifestList)
    --table.clear(self.downloadManifestList)
    --local manifests = args[1]
    --
    --Logger.Log("#bundle# DownloadUpdateState manifests 1 length:" .. table.length(manifests))
    --
    --local backgroundManifestName = string.lower(CS.GameEntry.Resource:GetBkgroundManifestName())
    --local packResManifestName = string.lower(CS.GameEntry.Resource:GetPackageResManifestName())
    --
    --for _, manifest in pairs(manifests) do
    --    local name = manifest.name
    --    if name == backgroundManifestName then
    --        table.insert(self.bkgroundDownloadManifestList, manifest)
    --    elseif name ~= packResManifestName then
    --        table.insert(self.downloadManifestList, manifest)
    --    end
    --end
    --
    --Logger.Log("#bundle# DownloadUpdateState self.downloadManifestList length:" .. table.length(self.downloadManifestList))
    --local List_String = CS.System.Collections.Generic.List(CS.VEngine.DownloadInfo)
    --local lst = List_String()
    --
    --local totalSize = CS.GameEntry.Resource:GetDownloadSize(0,self.downloadManifestList, lst)
    --if (totalSize > 0) then
    --    Logger.Log('#bundle# DownloadSize :' .. tostring(totalSize))
    --    self._startupLoading:SetBundleDownloadTotalBytes(totalSize)
    --
    --    Setting:SetPublicString("BundleDownLoadSize",tostring(totalSize))
    --
    --    EventManager:GetInstance():Broadcast(EventId.BeginDownloadUpdate)
    --    self.downloadVersions = CS.GameEntry.Resource:DownloadUpdates(lst)
    --else
    --    local size = Setting:GetPublicString("BundleDownLoadSize","")
    --    if size~=nil and size~="" then
    --        Logger.Log("Special! DownloadForceFinish")
    --        self:OnDownloadComplete(true)
    --    else
    --        self:onAllFinish(false)
    --        Logger.Log('#bundle# DownloadSize 0 new')
    --        EventManager:GetInstance():Broadcast(EventId.PreloadRes)
    --        self._startupLoading:SetState(Const.LoadingState.LoadDataTable)
    --    end
    --end
end

function DownloadUpdateState:OnExit()
    --table.clear(self.bkgroundDownloadManifestList)
    --table.clear(self.downloadManifestList)
    --if self.downloadVersions ~= nil then
    --    if not self.downloadVersions.isDone then
    --        self.downloadVersions:Stop()
    --    end
    --
    --    self.downloadVersions = nil
    --end
end

function DownloadUpdateState:OnUpdate()
    --if self._state == DownloadState.init then
    --    if self.downloadVersions == nil then
    --        return
    --    end
    --    if not self.downloadVersions.isDone then
    --        self._startupLoading:SetBundleDownloadProgress(self.downloadVersions.progress)
    --    else
    --        EventManager:GetInstance():Broadcast(EventId.EndDownloadUpdate)
    --        if (self.downloadVersions.isError) then
    --            Logger.LogError("#bundle# DownloadUpdate error " .. self.downloadVersions.error)
    --            self._startupLoading:SetState(Const.LoadingState.LoadingError, Const.LoginErrorCode.ERROR_DOWNLOAD_UPDATE)
    --        else
    --            Logger.Log("#bundle# DownloadUpdate OK!")
    --
    --            local names = CS.GameEntry.Resource:GetManifestNames();
    --            for i = 0, names.Length - 1 do
    --                local name = names[i]
    --                name = string.lower(name)
    --                local path = CS.GameEntry.Resource:GetTempDownloadPath(name);
    --                local temp = path .. ".temp";
    --                os.rename(temp, path)
    --            end
    --
    --            self:OnDownloadComplete(true)
    --        end
    --    end
    --elseif self._state == DownloadState.waitToInitLua then
    --    self:onAllFinish(true)
    --end
end


function DownloadUpdateState:GetDownloadManifest(name)
    --if (self.downloadManifestList == nil) then
    --    return nil
    --end
    --
    --for _, v in pairs(self.downloadManifestList) do
    --    if (v.name == name) then
    --        return v
    --    end
    --end
end

function DownloadUpdateState:TryCopyManifest()
    --if self.downloadManifestList ~= nil then
    --    for _, v in pairs(self.downloadManifestList) do
    --        Logger.Log("TryCopyManifest self.downloadManifestList : " .. tostring(v.name) .. "-" .. tostring(v.version))
    --        Versions.CopyTempManifestToDownLoadPath(v)
    --    end
    --end
    --
    --if self.bkgroundDownloadManifestList ~= nil then
    --    for _, v in pairs(self.bkgroundDownloadManifestList) do
    --        Logger.Log("TryCopyManifest self.bkgroundDownloadManifestList : " .. tostring(v.name) .. "-" .. tostring(v.version))
    --        Versions.CopyTempManifestToDownLoadPath(v)
    --    end
    --end
end

function DownloadUpdateState:OverrideManifest()
    --Logger.Log("DownloadUpdateState:OverrideManifest")
    --
    --if self.downloadManifestList ~= nil then
    --    for _, v in pairs(self.downloadManifestList) do
    --        Logger.Log("OverrideManifest self.downloadManifestList : " .. tostring(v.name) .. "-" .. tostring(v.version))
    --        Versions.OverrideManifest(v)
    --    end
    --end
    --
    --if self.bkgroundDownloadManifestList ~= nil then
    --    for _, v in pairs(self.bkgroundDownloadManifestList) do
    --        Logger.Log("OverrideManifest self.bkgroundDownloadManifestList : " .. tostring(v.name) .. "-" .. tostring(v.version))
    --        Versions.OverrideManifest(v)
    --    end
    --end
    --
    --return true
end

function DownloadUpdateState:OnDownloadComplete()
    --Logger.Log("onDownLoadComplete Start")
    --
    --if App.IsDebug() or App.IsGPTest() then
    --    CS.ApplicationLaunch.DumpLoadingLuaScripts()
    --    CS.GameEntry.Resource:DumpBundleDetail()
    --end
    --
    --CS.GameEntry.Sound:StopAllSounds()
    --CS.GameEntry.Resource:UnloadUnusedAssets()
    --Logger.Log("UnloadUnusedAssets")
    --XPCALL(function()
    --    Logger.Log("#zlh# #DownloadUpdateState# start ClearVersions and UnloadAllAssetBundles !")
    --    CS.ResourceManager.ClearVersions()
    --    CS.UnityEngine.AssetBundle.UnloadAllAssetBundles(false)
    --    Logger.Log("#zlh# #DownloadUpdateState# ClearVersions and UnloadAllAssetBundles finish!")
    --
    --    if App.IsDebug() or App.IsGPTest() then
    --        CS.ApplicationLaunch.DumpLoadingLuaScripts()
    --        CS.GameEntry.Resource:DumpBundleDetail()
    --    end
    --end)
    --
    --Setting:SetPublicString("BundleDownLoadSize","")
    --
    --Logger.Log("onDownLoadComplete finish")
    --self._state = DownloadState.waitToInitLua
end

function DownloadUpdateState:onAllFinish(needReload)
    --Logger.Log("onAllFinish:", tostring(needReload))
    --if needReload then
    --    XPCALL(function ()
    --        local ret = self:OverrideManifest()
    --        if ret then
    --            local gmFlag = Setting:GetPublicInt(SettingKeys.GM_FLAG, 0)
    --            if App.IsDebug() or App.IsGPTest() or gmFlag > 0 then
    --                CS.VEngine.Versions.ClearAsync()
    --            end
    --        end
    --    end)
    --else
    --    self:TryCopyManifest()
    --end
    --
    --if needReload then
    --    if self._startupLoading.UILoading ~= nil then
    --        EventManager:GetInstance():Broadcast(EventId.SU_ForceDestroyLoadingListener)
    --        self._startupLoading.UILoading.enabled = false
    --    end
    --    CS.ApplicationLaunch.Instance:ReloadGame()
    --end
end

function DownloadUpdateState:CheckDeviceStorage(bundleSize)
    --local diskSpace = -1
    --local restSpace = -1
    --local canDownload = true
    --if Sdk.GetDiskSpace then
    --    diskSpace = Sdk:GetDiskSpace()
    --end
    --if diskSpace>=0  then
    --    if diskSpace < bundleSize then
    --        canDownload = false
    --        restSpace = diskSpace
    --    end
    --end
    --return canDownload,restSpace
end

return DownloadUpdateState
