---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenshaowen.
--- DateTime: 2022/5/24 6:14 PM
--- 把从CheckResVersion拿下来的文件信息，去检测是否需要下载
--- 这部分检测在C#中处理的，通过CS.DownloadManifest.LoadAsync来创建
--- 在代码里判断了version和CRC。如果不一样的话，会去网络下载version这个文件
--- gameres这个文件还是比较大的，压缩完一般也需要几百K

local LoadingStateBase = require("Loading.LoadingState.LoadingStateBase")
local DownloadManifestState = BaseClass("DownloadManifestState", LoadingStateBase)
--local Const = require("Loading.Const")

function DownloadManifestState:__init(startupLoading)
    LoadingStateBase:__init(startupLoading)
	--self._downloadManifests = {}
end

function DownloadManifestState:OnEnter(args)
	--local names = CS.GameEntry.Resource:GetManifestNames();
	--local packRes = CS.GameEntry.Resource:GetPackageResManifestName();
	--
	--for i = 0, names.Length - 1 do
	--	local n = names[i]
	--	if (n ~= packRes) then
	--		table.insert(self._downloadManifests, CS.DownloadManifest.LoadAsync(n))
	--	end
	--end
end

function DownloadManifestState:OnExit()
	--for k,v in pairs(self._downloadManifests) do
	--	v:Dispose()
	--end
	--table.clear(self._downloadManifests)
end

function DownloadManifestState:OnUpdate()
	--if table.length(self._downloadManifests) <= 0 then
	--	return
	--end
	--
	--local allDone = true
	--local occurredError = false
	--for _, v in pairs(self._downloadManifests) do
	--	v:OnUpdate()
	--
	--	if not v.isDone then
	--		allDone = false
	--	elseif not string.IsNullOrEmpty(v.error) then
	--		Logger.LogError("DownloadManifest:", tostring(v.error))
	--		occurredError = true
	--		break
	--	end
	--end
	--
	--if occurredError then
	--	AppStartupLoading:GetInstance():ForceToConnectGame(LoginErrorMessage.ERROR_UPDATE_MANIFEST)
	--	return
	--end
	--
	--if allDone then
	--	local manifests = {}
	--	for _, v in pairs(self._downloadManifests) do
	--		if (v.manifest ~= nil) then
	--			local _name = v.manifest.name
	--			if (not string.IsNullOrEmpty(_name)) then
	--				table.insert(manifests, v.manifest)
	--			end
	--		end
	--	end
	--	self._startupLoading:SetState(Const.LoadingState.DownloadUpdate, manifests)
	--end
end

return DownloadManifestState
