---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenshaowen.
--- DateTime: 2022/5/24 6:16 PM
---

local LoadingStateBase = require("Loading.LoadingState.LoadingStateBase")
local EnterGameState = BaseClass("EnterGameState", LoadingStateBase)

--local DELAY_TIME = 0.5

function EnterGameState:__init(startupLoading)
    LoadingStateBase:__init(startupLoading)
end

function EnterGameState:OnEnter(args)
    --self.needTick = true
	--self.delayCounter = 0
end

function EnterGameState:OnExit()
end

function EnterGameState:OnUpdate()
    --if not self.needTick then
    --    return
    --end
    --
    --self.delayCounter = self.delayCounter + Time.deltaTime
    --if self.delayCounter >= DELAY_TIME then
    --    self:EnterGame()
    --    self.needTick = false
    --end
end

function EnterGameState:EnterGame()
    --Logger.Log("OnEnterGame: ")
    --
    --CS.GameEntry.GlobalData:recordGaid()
    --
    --self:OnEnterGame()
    --RenderSetting.ResetStartTime()
    --
    --CS.GameEntry.Resource:SetBkgroundDownloadThread(1)
    --CS.GameEntry.Resource:StartBkgroundDownload_Lua()
end


function EnterGameState:OnEnterGame()
    --AppStartupLoading:GetInstance():Shutdown(true)
    --TikTokUtil.TrackStart()
end

return EnterGameState
