---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Imaginaerum.
--- DateTime: 29/7/2024 上午10:18
---

local LoadingStateBase = require("Loading.LoadingState.LoadingStateBase")
---@class EuropeanUnionPrivacyState : LoadingStateBase
local EuropeanUnionPrivacyState = BaseClass("EuropeanUnionPrivacyState", LoadingStateBase)


function EuropeanUnionPrivacyState:OnEnter(args)
    --Logger.Log("EuropeanUnionPrivacyState:OnEnter")
    --
    --do
    --    PostEventLog.Record("Loading_PrivacyState_TempClose")
    --    self:DoNext()
    --    return
    --end
    --
    --if not CommonUtil.NeedShowPrivacy() then
    --    self:DoNext()
    --else
    --    UIManager:GetInstance():OpenWindow(UIWindowNames.UIPrivacy)
    --end
end

function EuropeanUnionPrivacyState:DoNext()
    --TikTokUtil.InitSdk()
    --self._startupLoading:StartConnect()
end

function EuropeanUnionPrivacyState:OnExit()
    --Logger.Log("EuropeanUnionPrivacyState:OnExit")
end


return EuropeanUnionPrivacyState
