---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenshaowen.
--- DateTime: 2022/5/24 6:17 PM
--- 当网络连接不上时，需要走这个状态，因为服务器有可能维护中，此时就应该显示维护信息UI
--- 这个状态主要是给http发送一个请求，同时获取相应的服务器状态

local LoadingStateBase = require("Loading.LoadingState.LoadingStateBase")
local GetServerStatusState = BaseClass("GetServerStatusState", LoadingStateBase)
--local Const = require("Loading.Const")
--local rapidjson = require "rapidjson"
--local UnityWebRequest = CS.UnityEngine.Networking.UnityWebRequest

function GetServerStatusState:__init(startupLoading)
    LoadingStateBase:__init(startupLoading)
end

function GetServerStatusState:OnEnter(args)
    --self._elapseTime = 0
    --self._timeout = 8
    --self._maxTryCount = 2
    --self._tryCount = 1
    --
    --self._httpRequest = AppStartupLoading:GetInstance():GetServerStatus()
end

function GetServerStatusState:OnExit()
    --self:DisposeRequest()
end

function GetServerStatusState:DisposeRequest()
    --if self._httpRequest then
    --    self._httpRequest:Abort()
    --    self._httpRequest:Dispose()
    --    self._httpRequest = nil
    --end
end

function GetServerStatusState:OnUpdate()
    --if self._httpRequest == nil then
    --    Logger.LogError("GetServerStatus http request nil!")
    --    return
    --end
    --
    --self._elapseTime = self._elapseTime + Time.deltaTime
    --
    --if self._elapseTime > self._timeout then
    --    self:DisposeRequest()
    --    self._elapseTime = 0
    --
    --    if self._tryCount < self._maxTryCount then
    --        self._httpRequest = AppStartupLoading:GetInstance():GetServerStatus()
    --        self._tryCount = self._tryCount + 1
    --
    --        EventManager:GetInstance():Broadcast(EventId.NetworkRetry, true)
    --        LoadingPrint("get server status try count:", self._tryCount)
    --    else
    --        Logger.LogError("get server status timeout")
    --        self:OnGetServerStatus(nil, Const.LoginErrorCode.ERROR_GSS_TIMEOUT)
    --    end
    --elseif self._httpRequest.isDone then
    --    if self._httpRequest.result ~= UnityWebRequest.Result.Success then
    --        Logger.LogError("get serverlist net error:" .. tostring(self._httpRequest.error))
    --        local err = tostring(self._httpRequest.error)
    --
    --        self:DisposeRequest()
    --        self:OnGetServerStatus(nil, err)
    --    else
    --        local text = self._httpRequest.downloadHandler.text
    --        self:DisposeRequest()
    --
    --        if text == nil then
    --            LoadingPrint("GetServerStatus: no data")
    --            self:OnGetServerStatus(nil, Const.LoginErrorCode.ERROR_DATA_GSS);
    --        else
    --            LoadingPrint("GetServerStatus: %s", text)
    --            local res = rapidjson.decode(text)
    --            if res then
    --                self:OnGetServerStatus(res, Const.LoginErrorCode.ERROR_SUCCESS);
    --            else
    --                self:OnGetServerStatus(nil, Const.LoginErrorCode.ERROR_JSON_GSS);
    --            end
    --        end
    --    end
    --end
end

function GetServerStatusState:OnGetServerStatus(response, err)
    --EventManager:GetInstance():Broadcast(EventId.NetworkRetry, false)
    --if err == Const.LoginErrorCode.ERROR_SUCCESS then
    --    if response and response.code ~= 0 then
    --        self._startupLoading:SetState(Const.LoadingState.LoadingError, Const.LoginErrorCode.ERROR_MAINTENANCE, response.time)
    --    else
    --        self._startupLoading:SetState(Const.LoadingState.LoadingError, Const.LoginErrorCode.STATE_ERROR_CONNECT)
    --    end
    --else
    --    self._startupLoading:SetState(Const.LoadingState.LoadingError, err)
    --end
end

return GetServerStatusState
