---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zhangliheng.
--- DateTime: 4/28/2025 4:50 PM
---
--- GetServerList重构 1.支持Get/POST Method切换 2.添加串行多线请求 3.打点GSL_FAILED_MAX来表示GSL彻底失败的情况 同时上报具体reason


local LoadingStateBase = require("Loading.LoadingState.LoadingStateBase")
--local Const = require("Loading.Const")
local GetServerListState = BaseClass("GetServerListState", LoadingStateBase)
--local GameEntry = CS.GameEntry
--local WWWForm = CS.UnityEngine.WWWForm

--local USE_GET_METHOD_DEF = false
--local SERVER_LIST_ENDPOINT = "/gameservice/getserverlist.php"
--local DEFAULT_CODE = "barrel"

function GetServerListState:OnEnter(args)
    --self._elapseTime = 0
    --self._tryCount = 1
    --self.hostName = ""
    --self.failedReasonList = {}
    --self.errorStrList = {}
    --self.hostList = AppStartupLoading:GetInstance():GetGSLUrlList()
    --self._maxTryCount = #self.hostList
    --self:SendRequest()
end

function GetServerListState:OnExit()
    --self:DisposeRequest()
end

function GetServerListState:GetCurrentHostData()
    --local index = ((self._tryCount-1) % #self.hostList) + 1
    --return self.hostList[index]
end

function GetServerListState:GetRequestUrl()
    --local hostData = self:GetCurrentHostData()
    --return hostData.gsl .. SERVER_LIST_ENDPOINT, hostData.lineName
end

function GetServerListState:BuildRequestParams()
    --local deviceID = App.GetDeviceUid()
    --if string.IsNullOrEmpty(deviceID) then
    --    deviceID = GameEntry.Device:NewDeviceID()
    --    PostEventLog.Record("NewDeviceID")
    --    print("GetServerList .. New Device ???")
    --end
    --
    --local params = {
    --    uuid = deviceID,
    --    country = App.GetFromCountry(),
    --    is3D = "1",
    --    lang = App.GetLanguageName(),
    --    simOp = tostring(GameEntry.Sdk:GetSimOperator()),
    --    platform = App.GetPlatformName(),
    --    packageName = App.GetPackageName(),
    --    code = DEFAULT_CODE,
    --}
    --
    --if App.IsGPTest() then
    --    params.simOp = ""
    --end
    --
    --if CS.AESHelper.GenerateGSLSig then
    --    local now = GameEntry.Timer:GetLocalSeconds()
    --    local timeStamp = tostring(now)
    --    params.t = timeStamp
    --    params.sig = CS.AESHelper.GenerateGSLSig(deviceID, timeStamp)
    --end
    --
    --XPCALL(function()
    --    params.zoneId = GameEntry.Device:GetTimeZoneId()
    --end)
    --
    --if App.IsDebug() or App.IsGPTest() then
    --    params.gmFlag = "0"
    --    params.loginFlag = "0"
    --else
    --    params.loginFlag = "1"
    --    params.newServer = "1"
    --
    --    local uid = Setting:GetPublicString(SettingKeys.New_GAME_UID, "")
    --    if not string.IsNullOrEmpty(uid) then
    --        params.gameuid = uid
    --        Setting:SetPublicString(SettingKeys.New_GAME_UID, "")
    --    end
    --
    --    local uidErr = Setting:GetPublicString(SettingKeys.GAME_UID_FOR_ERR_SEARCH, "")
    --    if not string.IsNullOrEmpty(uidErr) then
    --        params.gameUidForSearch = uidErr
    --        Setting:SetPublicString(SettingKeys.GAME_UID_FOR_ERR_SEARCH, "")
    --    end
    --end
    --
    --return params
end

function GetServerListState:SendRequest()
    --self:DisposeRequest()
    --
    --LoadingPrint("get server list, attempt %d", self._tryCount)
    --local hostData = self:GetCurrentHostData()
    --local url = hostData.gsl .. SERVER_LIST_ENDPOINT
    --self.hostName = hostData.lineName
    --
    --local params = self:BuildRequestParams()
    --
    --local request
    --if USE_GET_METHOD_DEF then
    --    local queryString = BuildQueryString(params)
    --    request = LuaWebRequest.Get(url .. "?" .. queryString)
    --    LoadingPrint("GetServerList (GET): " .. url .. "?" .. queryString)
    --else
    --    local form = WWWForm()
    --    for k, v in pairs(params) do
    --        form:AddField(tostring(k), v)
    --    end
    --    request = LuaWebRequest.Post(url, form)
    --    LoadingPrint("GetServerList (POST): " .. url .. "?" .. BuildQueryString(params))
    --end
    --self._httpRequest = request
    --if self._httpRequest then
    --    local timeoutCallback = BindCallback(self, self.RequestTimeoutHandler)
    --    local failedCallback = BindCallback(self, self.RequestFailedHandler)
    --    local successCallback = BindCallback(self, self.RequestSuccessHandler)
    --    self._httpRequest:SetCallback(timeoutCallback, failedCallback, successCallback)
    --
    --    self._httpRequest:SendRequest()
    --else
    --    Logger.LogError("GetServerListState Failed to create UnityWebRequest!")
    --end
end

function GetServerListState:DisposeRequest()
    --if self._httpRequest ~= nil then
    --    self._httpRequest:DisposeRequest()
    --    self._httpRequest = nil
    --end
end

function GetServerListState:RequestTimeoutHandler(req)
    --self:HandleRequestFailure(Const.LoginErrorCode.ERROR_GSL_TIMEOUT, "timeout")
end

function GetServerListState:RequestFailedHandler(req, error)
    --PostEventLog.Record("GSL_Statis", string.format("lineName:%s, reason:%s", tostring(self.hostName), tostring(error)))
    --self:HandleRequestFailure(Const.LoginErrorCode.ERROR_HTTP_GSL, tostring(error))
end

function GetServerListState:RequestSuccessHandler(req, downloadHandler)
    --self:HandleRequestSuccess(downloadHandler.text)
end

function GetServerListState:OnUpdate()
    --if self._httpRequest == nil then
    --    return
    --end
    --
    --if self._httpRequest ~= nil then
    --    XPCALL(function() self._httpRequest:OnUpdate() end)
    --end
end

function GetServerListState:HandleRequestFailure(errorCode, shortErrorMsg)
    --self:AppendFailedReason(errorCode, shortErrorMsg)
    --LoadingPrint("Get server list failed: %s", shortErrorMsg)
    --
    --if self._tryCount < self._maxTryCount then
    --    self._tryCount = self._tryCount + 1
    --    self._elapseTime = 0
    --    EventManager:GetInstance():Broadcast(EventId.NetworkRetry, true)
    --    self:SendRequest()
    --else
    --    self:DisposeRequest()
    --
    --    local uploadStr = self:GetUploadFailedStr()
    --    PostEventLog.Record("GSL_FAILED_MAX", uploadStr)
    --    Logger.Log("[GSL_FAILED_MAX] " .. uploadStr)
    --
    --    self._startupLoading:SetState(Const.LoadingState.LoadingError, errorCode, uploadStr)
    --end
end

function GetServerListState:HandleRequestSuccess(responseText)
    --LoadingPrint("Server list response: %s", responseText)
    --AppStartupLoading:GetInstance():SetGSLRecvText(responseText)
    --
    --self:DisposeRequest()
    --
    --if string.IsNullOrEmpty(responseText) then
    --    PostEventLog.Record("GSL_Statis", string.format("lineName:%s, reason:%s", tostring(self.hostName), "empty response"))
    --    self:HandleRequestFailure(Const.LoginErrorCode.ERROR_DATA_GSL, "empty response")
    --    return
    --end
    --
    --local response = CommonUtil.JsonDecode(responseText)
    --if table.IsNullOrEmpty(response) then
    --    PostEventLog.Record("GSL_Statis", string.format("lineName:%s, reason:%s", tostring(self.hostName), "invalid json:" .. tostring(responseText)))
    --    self:HandleRequestFailure(Const.LoginErrorCode.ERROR_JSON_GSL, "invalid json")
    --    return
    --end
    --
    --if not response or not response.serverList or #response.serverList == 0 then
    --    local errorCode = response and response.code ~= 0 and Const.LoginErrorCode.ERROR_SERVER_LIST or Const.LoginErrorCode.ERROR_SERVER_LIST_EMPTY
    --    PostEventLog.Record("GSL_Statis", string.format("lineName:%s, reason:%s", tostring(self.hostName), "empty server list: " .. tostring(responseText)))
    --    self:HandleRequestFailure(errorCode, "invalid or empty server list")
    --    return
    --end
    --
    --self:OnGetServerListFinalSuccess(response)
end

function GetServerListState:OnGetServerListFinalSuccess(response)
    --EventManager:GetInstance():Broadcast(EventId.NetworkRetry, false)
    --
    --local serverList = response.serverList
    --AppStartupLoading:GetInstance():SetAllServerList(serverList)
    --
    --self:AppendFailedReason('success', 'success')
    --
    --local uploadStr = self:GetUploadFailedStr()
    --PostEventLog.Record("GSL_Success", uploadStr)
    --Logger.Log("[GSL_Success]" .. uploadStr)
    --
    --if self._startupLoading.IsShowServerList then
    --    LoadingPrint("Open debug choose server UI")
    --    UIManager:GetInstance():OpenWindow(UIWindowNames.UIDebugChooseServer, function(ip, port, zone, uid)
    --        self:DebugConnectGameServer(ip, port, zone, uid)
    --    end)
    --else
    --    local serverInfo = self:GetLastLoggedServerInfo(response) or serverList[1]
    --    LoadingPrint("Auto connect to server: %s:%d", serverInfo.ip, serverInfo.port)
    --    self:DebugConnectGameServer(serverInfo.ip, serverInfo.port, serverInfo.zone, serverInfo.gameUid or "")
    --end
end

function GetServerListState:DebugConnectGameServer(ip, port, zone, uid)
    --if string.IsNullOrEmpty(ip) or port == 0 or string.IsNullOrEmpty(zone) then
    --    LoadingPrint("Invalid server info: %s:%d [%s]", ip, port, zone)
    --    return
    --end
    --
    --TikTokUtil.TrackPlayerRegistration()
    --PostEventLog.Record("LoginState", string.format("Connecting to server: %s:%d [%s] UID:[%s]", ip, port, zone, uid))
    --
    --self._startupLoading:SaveGameServerSetting(ip, port, zone, uid, "")
    --self._startupLoading:SetState(Const.LoadingState.ConnectGame, ip, port, zone, uid)
end

function GetServerListState:GetLastLoggedServerInfo(response)
    --if response.lastLoggedServer ~= 0 then
    --    for _, server in ipairs(response.serverList) do
    --        if server.id == response.lastLoggedServer then
    --            return server
    --        end
    --    end
    --end
    --return nil
end

function GetServerListState:AppendFailedReason(reasonCode, errorStr)
    --table.insert(self.failedReasonList, string.format("%s:%s", self.hostName or "", tostring(reasonCode)))
    --table.insert(self.errorStrList, string.format("%s:%s", self.hostName or "", tostring(errorStr)))
end

function GetServerListState:GetUploadFailedStr()
    --local failedReasonStr = table.concat(self.failedReasonList, "|")
    --local errListStr = table.concat(self.errorStrList, "|")
    --local uploadStr = string.format(" gsl_state_list:[%s], gls_err_list:[%s]", failedReasonStr, errListStr)
    --return uploadStr
end

return GetServerListState
