---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenshaowen.
--- DateTime: 2022/5/24 6:20 PM
---

local LoadingStateBase = require("Loading.LoadingState.LoadingStateBase")
local LoadSceneState = BaseClass("LoadSceneState", LoadingStateBase)
--local Const = require("Loading.Const")

---- 返回主城的一个引导
--local finishStartBackHomeGuideId = 10121000
--local finishStartBackHomeGuideIdB = 10000041

function LoadSceneState:__init(startupLoading)
    LoadingStateBase:__init(startupLoading)
	--self.isNewAccount = false
	--self.delayCounter = 0
end

function LoadingStateBase:__delete()

end

function LoadSceneState:OnEnter(args)
	--self.enterTimeStamp = UITimeManager:GetInstance():GetLocalTime()
	--self.tempTimeStamp = self.enterTimeStamp
	--XPCALL(function()
	--	CS.ApplicationLaunch.Instance:InitUSky()
	--	CS.QualityChangeRegistry.Instance:Init()
	--end)
	--self.state = 1
	--
	--self.guideId = finishStartBackHomeGuideId
	--if LuaEntry.Player.abTest == ABTestType.B then
	--	self.guideId = finishStartBackHomeGuideIdB
	--end
	--if self.isNewAccount then
	--	DataCenter.PreloadModelManager:Preload({UIAssetTimeLine.OpeningAnimation, UIAssetTimeLine[GuideAnimObjectType["SU_BossShowingTimeline"]]})
	--end
end

function LoadSceneState:OnExit()
	--self.isNewAccount = nil
	--local cost = UITimeManager:GetInstance():GetLocalTime() - self.enterTimeStamp
	--Logger.Log(string.format('#zlh# ******** load scene state whole cost: %s ********', cost))
end

function LoadSceneState:OnUpdate()
	--if LuaEntry.GlobalData:HasLogged() then
	--	self._startupLoading:SetState(Const.LoadingState.EnterGame)
	--	return
	--end
	--
	--if self.state == 1 then
	--	if not DataCenter.GuideManager:IsDoneThisGuide(self.guideId) then
	--		local assetPrepareComplete = DataCenter.PreloadModelManager:CheckModelComplete(UIAssetTimeLine.OpeningAnimation, UIAssetTimeLine[GuideAnimObjectType["SU_BossShowingTimeline"]])
	--		if not assetPrepareComplete then
	--		end
	--	end
	--	if CS.GameEntry.Shader:IsInitDone() and self._startupLoading:IsLoadSceneDone() then
	--		XPCALL(function()
	--			self.state = 2
	--			self:LoadScene()
	--			end,
	--			function ()
	--				self._startupLoading:SetState(Const.LoadingState.LoadingError, Const.LoginErrorCode.ERROR_LOAD_SCENE_ERR)
	--			end)
	--	end
	--end
end

function LoadSceneState:LoadScene()
	--CS.DefaultNewButtonCurve.LoadDefaultCurve("Assets/Main/Animation/UIButtonCurve/UIButtonCurveDefault.asset")
	--
	--local tmplevel = LuaEntry.Player:GetCurLevelId()
	--local levelId = 1100001
	--
	--if self.isNewAccount then
	--	PostEventLog.Record("LoadSceneState_isNewAccount:" .. tostring(self.isNewAccount))
	--else
	--	levelId = LevelId.Main
	--	PostEventLog.Record("LoadSceneState_isNewAccount:" .. tostring(self.isNewAccount))
	--end
	--
	--local param = {}
	--local levelType = GetTableData(TableName.PVELevelOld, levelId, "type")
	--levelType = tonumber(levelType)
	--
	--if levelType == SU_PveLevelType.ZombieBattle or levelType == SU_PveLevelType.CountMaster then
	--	param.pveEntrance = PveEntrance.Guide
	--else
	--	param.pveEntrance = PveEntrance.Test
	--end
	--
	--param.levelId = tonumber(levelId)
	--param.isStart = false
	--
	--self:LogCostTime('step1')
	--SetWorldInitZoom(WorldType.Normal)
	--SceneManager.ChangeToLevel(param,
	--		function()
	--			self:LogCostTime('step2')
	--
	--			self.state = 3
	--			self:DoFirstEnter()
	--			self.delayCounter = 0
	--		end)
end

function LoadSceneState:DoFirstEnter()
	--CS.GameEntry.Sdk:LogEvent(CS.UnityGameFramework.SDK.AnalyticsEvent.app_launch);
	--
	--CS.GameEntry.Sdk:DoInitGooglePay();
	--
	--ClearIfTrackingDisabled()
	--
	--if CS.SDKManager.IS_UNITY_ANDROID() and not CS.SDKManager.IS_UNITY_EDITOR() then
	--	CS.AndroidUtils.RecoverGraphicAPI()
	--end
	--
	--LuaEntry.GlobalData:SetLogged(true)
	--self._startupLoading:SetState(Const.LoadingState.EnterGame)
end


function LoadSceneState:LogCostTime(tag)
	--local now = UITimeManager:GetInstance():GetLocalTime()
	--local cost = now - self.tempTimeStamp
	--self.tempTimeStamp = now
	--Logger.Log(string.format('#zlh# ******** load scene state [%s] cost: %s ********', tag,  cost))
end


return LoadSceneState
