---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenshaowen.
--- DateTime: 2022/5/24 4:58 PM
---

---@class LoadingStateBase
local LoadingStateBase = BaseClass("LoadingStateBase")

---@param startupLoading AppStartupLoading
function LoadingStateBase:__init(startupLoading)
    self._startupLoading = startupLoading
end

function LoadingStateBase:__delete()
    self._startupLoading = nil
end

function LoadingStateBase:OnEnter(args)
    
end

function LoadingStateBase:OnExit()

end

function LoadingStateBase:OnUpdate()

end

return LoadingStateBase