---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenshaowen.
--- DateTime: 2022/5/24 6:19 PM
---

local LoadingStateBase = require("Loading.LoadingState.LoadingStateBase")
local LoadingErrorState = BaseClass("LoadingErrorState", LoadingStateBase)
--local Const = require("Loading.Const")
--local GameEntry = CS.GameEntry

function LoadingErrorState:__init(startupLoading)
    LoadingStateBase:__init(startupLoading)
end

function LoadingStateBase:__delete()

end

function LoadingErrorState:GetErrorMsg(errorCode)
    --errorCode = errorCode or ""
    --for k, v in pairs(Const.LoginErrorCode) do
    --    if tostring(k) == errorCode then
    --        return LoginErrorMessage[k] or errorCode
    --    end
    --end
    --return errorCode
end

function LoadingErrorState:GetExtraErrorMsg()
    --local simCode = tostring(CS.GameEntry.Sdk:GetSimOperator())
    --if not string.IsNullOrEmpty(simCode) and string.startswith(simCode, "460") then
    --    simCode = "1"
    --else
    --    simCode = "0"
    --end
    --local country = App.GetFromCountry()
    --if country == "VN" then
    --    country = "1"
    --elseif country == "HK" then
    --    country = "2"
    --elseif country == "CN" then
    --    country = "3"
    --else
    --    country = "0"
    --end
    --local lang = CS.GameEntry.Localization:GetLanguage()
    --if lang == 8 then
    --    lang = "1"
    --else
    --    lang = "0"
    --end
    --local final = string.format("\nC%s%s%s", simCode, country, lang)
    --return final
end

function LoadingErrorState:OnEnter(args)
    --local errorCode = args[1]
    --local uploadStr = tostring(args[2])
    --LoadingPrint("Loading error: %s", tostring(errorCode))
    --
    --local errorStr = errorCode == nil and "[NONE]" or tostring(errorCode)
    --local errorMsg = self:GetErrorMsg(errorStr)
    --PostEventLog.Record("LoadingError", errorMsg)
    --
    --if UIManager:GetInstance():IsWindowOpen(UIWindowNames.UIDisconnect) then
    --    Logger.Log("LoadingErrorState:OnEnter - in DisconnectView!")
    --    return
    --end
    --
    --pcall(function()
    --    local tabInfo = {}
    --    tabInfo["errcode"] = errorCode
    --    tabInfo["checkres"] = AppStartupLoading:GetInstance():GetCheckResRecText()
    --    tabInfo["gslrecv"] = AppStartupLoading:GetInstance():GetGSLRecvText()
    --    tabInfo["uploadStr"] = uploadStr
    --    tabInfo["zoneId"] = GameEntry.Device:GetTimeZoneId()
    --    tabInfo["serverId"] = Setting:GetPublicString(SettingKeys.SERVER_ZONE, "")
    --    local strInfo = rapidjson.encode(tabInfo)
    --    ZendeskUtil.SetTicketField(strInfo)
    --end)
    --
    --if errorCode == Const.LoginErrorCode.ERROR_NETWORK then
    --    local dialog = Localization:GetString("129063") .. self:GetExtraErrorMsg() .. "-1"
    --    UIUtil.ShowMessage(dialog, 2, 550007, 129091,
    --            OpenZendesk, ReloadAction, ReloadAction)
    --end
end

function LoadingErrorState:OnExit()

end

function LoadingErrorState:OnUpdate()

end

return LoadingErrorState
