---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenshaowen.
--- DateTime: 2022/5/24 6:18 PM
---

local LoadingStateBase = require("Loading.LoadingState.LoadingStateBase")
local LoadDataTableState = BaseClass("LoadDataTableState", LoadingStateBase)
--local GameEntry = CS.GameEntry
--local Const = require("Loading.Const")

function LoadDataTableState:__init(startupLoading)
    LoadingStateBase:__init(startupLoading)
end

function LoadDataTableState:OnEnter(args)
    --self._stateTime = 0
    --
    --GameEntry.pb:Reload();
    --
    ---- 先初始化shader,和下面的顺序不要调换
    --CS.GameEntry.Shader:Initialize()
    ---- 开始进行预加载
    --if self._startupLoading ~= nil then
    --    self._startupLoading:Preload()
    --    self._startupLoading:CreateBlurObj()
    --end
end

function LoadDataTableState:OnExit()

end

function LoadDataTableState:OnUpdate()
    --self._stateTime = self._stateTime + Time.deltaTime
    --
    --if GameEntry.Localization.IsInitDone and GameEntry.pb.IsInitDone then
    --
    --    if true then
    --
    --        self._startupLoading:SetState(Const.LoadingState.LoadScene)
    --        LuaEntry:StartGame()
    --    else
    --        if GameEntry.Localization.IsInitSuccess and GameEntry.pb.IsInitSuccess then
    --            self._startupLoading:SetState(Const.LoadingState.EuropeanUnionPrivacy)
    --        else
    --            self._startupLoading:SetState(Const.LoadingState.LoadingError, Const.LoginErrorCode.ERROR_LOAD_DATATABLE);
    --        end
    --    end
    --
    --elseif self._stateTime > 60 then
    --    self._startupLoading:SetState(Const.LoadingState.LoadingError, Const.LoginErrorCode.ERROR_LOAD_DATATABLE_TIMEOUT);
    --end
end

return LoadDataTableState
