--[[
-- [INPUT]: 依赖 Framework 的 BaseClass，构造时接收 AppStartupLoading 实例
-- [OUTPUT]: 对外提供 LoadingStateBase 类，暴露 OnEnter/OnExit/OnUpdate 生命周期空实现供子类覆写
-- [POS]: Loading 模块的加载状态基类，定义启动状态机各步骤的统一接口契约；AppStartupLoading 内联的 BaseState 与之同构
-- [PROTOCOL]: 变更时更新此头部,然后检查 CLAUDE.md
--]]

---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenshaowen.
--- DateTime: 2022/5/24 4:58 PM
---

---@class LoadingStateBase
local LoadingStateBase = BaseClass("LoadingStateBase")

---@param startupLoading AppStartupLoading
function LoadingStateBase:__init(startupLoading)
    self._startupLoading = startupLoading
end

function LoadingStateBase:__delete()
    self._startupLoading = nil
end

function LoadingStateBase:OnEnter(args)
    
end

function LoadingStateBase:OnExit()

end

function LoadingStateBase:OnUpdate()

end

return LoadingStateBase