---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenshaowen.
--- DateTime: 2022/5/24 6:20 PM
---

local LoadingStateBase = require("Loading.LoadingState.LoadingStateBase")
local LoginState = BaseClass("LoginState", LoadingStateBase)
--local Const = require("Loading.Const")

function LoginState:__init(startupLoading)
    LoadingStateBase:__init(startupLoading)
end

function LoginState:__delete()

end

function LoginState:OnEnter(args)
    --self._elapseTime = 0
    --self._timeout = 6
    --
    ---- 登录前首先要初始化游戏
    --LuaEntry:StartGame()
    --
    --PostEventLog.Record("LoginState",  string.format("[LoginState] StartLogin uid:[%s], zone:[%s]",
    --        tostring(LuaEntry.Network:GetUid()), tostring(LuaEntry.Network:GetZoneName())))
    --
    ---- 发送登录消息
    --local so = CS.Sfs2X.Entities.Data.SFSObject()
    --so:PutInt("is_portrait", IS_PORTRAIT and 1 or 0)
    --CS.LoginMessage.Instance:Send(LuaEntry.Network:GetUid(), "", LuaEntry.Network:GetZoneName(), so);
end

function LoginState:OnExit()
end

function LoginState:OnUpdate()
    --self._elapseTime = self._elapseTime + Time.deltaTime
    --if self._elapseTime > self._timeout then
    --    if self._startupLoading.LoginTryCount < self._startupLoading.LoginMaxTryCount then
    --        self._startupLoading:StartConnect()
    --    else
    --        PostEventLog.Record("LoginTimeout")
    --        self._startupLoading:SetState(Const.LoadingState.LoadingError, Const.LoginErrorCode.ERROR_LOGIN_TIMEOUT)
    --    end
    --end
end

function LoginState:OnLoginResponse(loginMessage)
    --Logger.Log("OnLoginResponse ok")
    --
    --if loginMessage["loginMessage"] ~= nil then
    --    Logger.LogError("OnLoginResponse Error!")
    --    LuaEntry.Network:OnLoginError(loginMessage)
    --else
    --    self._startupLoading:SetState(Const.LoadingState.PushInit)
    --end
end

return LoginState
