---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenshaowen.
--- DateTime: 2022/5/24 6:22 PM
---

local LoadingStateBase = require("Loading.LoadingState.LoadingStateBase")
local PermissionState = BaseClass("PermissionState", LoadingStateBase)
--local Const = require("Loading.Const")
--local SDKManager = CS.SDKManager
--local Sdk = CS.GameEntry.Sdk

function PermissionState:__init(startupLoading)
    LoadingStateBase:__init(startupLoading)
end

function PermissionState:__delete()

end

function PermissionState:OnEnter(args)
    --Logger.Log("PermissionState:OnEnter")
    --
    --if SDKManager.IS_UNITY_ANDROID() and not SDKManager.IS_UNITY_EDITOR() then
    --    Sdk:RequestSdCardPermission()
    --else
    --    self._startupLoading.PermissionRecv = true
    --end
end

function PermissionState:StartDownLoadConfigZip()
    --if self.isDownloadZip == true then
    --    return
    --end
    ---- 开始内网下载配置
    --local _zipDataTable = CS.ApplicationLaunch.Instance:GetZipDataTable()
    --if App.IsDebug() then
    --    if CS.GameEntry.Resource.SkipUpdate then
    --        Logger.Log("****config: 不使用本地 1")
    --        _zipDataTable._ConfigStatus = CS.ConfigStatus.NotUseLocal
    --    else
    --        if _zipDataTable._ConfigStatus == CS.ConfigStatus.Init then
    --            local action1 = function()
    --                self._startupLoading:SetState(Const.LoadingState.LoadingError, Const.LoginErrorCode.ERROR_DOWNLOAD_UPDATE)
    --            end
    --            local action2 = function()
    --                self._startupLoading:SetState(Const.LoadingState.LoadingError, Const.LoginErrorCode.ERROR_DOWNLOAD_UPDATE)
    --            end
    --            _zipDataTable:StartZipDownLoad(action1,action2)
    --            Logger.Log("****config: 开始下载 1")
    --        else
    --            _zipDataTable._ConfigStatus = CS.ConfigStatus.FinishUnzip
    --            Logger.Log("****config: 非第一次进入")
    --        end
    --    end
    --else
    --    Logger.Log("****config: not use zip!")
    --    _zipDataTable._ConfigStatus = CS.ConfigStatus.NotUseLocal
    --end
    --self.isDownloadZip = true
end

function PermissionState:OnExit()
    --Logger.Log("PermissionState:OnExit")
    --CS.ApplicationLaunch.Instance:GetZipDataTable():DisposeZipDownloadRequest()
    --
    ---- 获取完权限之后，立即处理一下DeviceID
    --local deviceID = App.GetDeviceUid()
    --if string.IsNullOrEmpty(deviceID) then
    --    deviceID = CS.GameEntry.Device:NewDeviceID()
    --    PostEventLog.Record("NewDeviceID")
    --    Logger.Log("PermissionState:OnExit - NewDeviceID")
    --end
end

function PermissionState:ReloadGame()
    --if (self._toReloadGame == true) then
    --    Logger.Log("PermissionState:ReloadGame")
    --    CS.GameEntry.Sound:StopAllSounds()
    --    CS.ApplicationLaunch.DumpLoadingLuaScripts()
    --    CS.GameEntry.Resource:DumpBundleDetail()
    --    CS.GameEntry.Resource:UnloadUnusedAssets()
    --
    --    if self._startupLoading.UILoading ~= nil then
    --        EventManager:GetInstance():Broadcast(EventId.SU_ForceDestroyLoadingListener)
    --        self._startupLoading.UILoading.enabled = false
    --    end
    --    CS.ApplicationLaunch.Instance:ReloadGame()
    --    self._reloadGame = true
    --
    --    return true
    --end
    --
    --return false
end

function PermissionState:OnUpdate()
    --if (self._reloadGame == true) then
    --    return
    --end
    --
    --if self:ReloadGame() then
    --    return
    --end
    --
    --if self._startupLoading.PermissionRecv then
    --    self:StartDownLoadConfigZip()
    --end
    --
    --local action = function()
    --    self._startupLoading:SetState(Const.LoadingState.LoadingError, Const.LoginErrorCode.ERROR_DOWNLOAD_UPDATE)
    --end
    --
    --local _localUnzipState = CS.ApplicationLaunch.Instance:GetZipDataTable():ExecuteUnzipDatabase(action)
    --if _localUnzipState == 1 then
    --    return
    --elseif _localUnzipState == 2 then
    --    self._toReloadGame = true
    --    return
    --end
    --
    --local _st = CS.ApplicationLaunch.Instance:GetZipDataTable()._ConfigStatus
    --if self._startupLoading.PermissionRecv and
    --        self._startupLoading.UILoading ~= nil and
    --        (_st == CS.ConfigStatus.FinishUnzip or _st == CS.ConfigStatus.NotUseLocal) and
    --        CS.GameEntry.Localization.IsInitDone  then
    --
    --    if CommonUtil.IsEUCountry() then
    --        Sdk:SendDataToNative("PM_InitAppSDK_EUCountry", "")
    --    else
    --        Sdk:SendDataToNative("PM_InitAppSDK", "")
    --    end
    --
    --    self._startupLoading:SetState(Const.LoadingState.CheckResVersion)
    --end
end

return PermissionState
