---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenshaowen.
--- DateTime: 2022/5/24 6:22 PM
---

local LoadingStateBase = require("Loading.LoadingState.LoadingStateBase")
local PushInitState = BaseClass("PushInitState", LoadingStateBase)
--local Const = require("Loading.Const")
--local Const_PushInitTimeOut = 8

function PushInitState:__init(startupLoading)
    LoadingStateBase:__init(startupLoading)
end

function LoadingStateBase:__delete()

end

function PushInitState:OnEnter()
	--self._elapseTime = 0
    --self.realtimeSinceStartup = Time.realtimeSinceStartup
	--
	--LoadingPrint('PushInitState:OnEnter!')
	--print("------------------------------------------")
end

function PushInitState:OnExit()

end

function PushInitState:DoRetry()
	--local uid = Setting:GetPublicString(SettingKeys.GAME_UID, "")
	--if string.IsNullOrEmpty(uid) then
	--	self._startupLoading:SetState(Const.LoadingState.GetServerList)
	--else
	--	self._startupLoading:StartConnect()
	--end
end

function PushInitState:OnUpdate()
    --self._elapseTime = self._elapseTime + Time.deltaTime
	--
    --if not self._startupLoading.IsPushInitReceived then
    --    if self._elapseTime > Const_PushInitTimeOut then
	--		LoadingPrint('PushInitState:OnUpdate wait TimeOut!!!')
    --        PostEventLog.Record(PostEventLog.Defines.LONG_TIME_NOT_PUSH_INIT)
	--
    --        if self._startupLoading.LoginTryCount < self._startupLoading.LoginMaxTryCount then
	--			self:DoRetry()
    --        else
    --            self._startupLoading:SetState(Const.LoadingState.LoadingError, Const.LoginErrorCode.ERROR_INIT_TIMEOUT)
    --        end
    --    end
    --else
    --    if self._startupLoading.IsNeedPassword then
    --        self._startupLoading:SetState(Const.LoadingState.AuthPin)
    --    else
    --        self:OnLoginComplete()
    --        self._startupLoading:SetState(Const.LoadingState.LoadScene)
    --    end
    --end
end

function PushInitState:OnLoginComplete()
	--LoadingPrint('PushInitState:OnLoginComplete..')
    --TikTokUtil.TrackPlayerLogin()
    --
    --CS.GameEntry.Sdk:SendDataToNative("Pay_queryPurchase", "")
    --
    --AppStartupLoading:GetInstance():ResetServerStateFlag()
	--
	--LoadingPrint('PushInitState:OnLoginComplete OK!!')
end

return PushInitState
