---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenshaowen.
--- DateTime: 2022/5/24 4:25 PM
---

---@class AppStartupLoading
local AppStartupLoading = BaseClass("AppStartupLoading", Singleton)

function AppStartupLoading:GetLoadingProgress()
    return self._currentMaxProgress
end

function AppStartupLoading:GetCurState()
    return self._currState
end

function AppStartupLoading:IsLoading()
    return self.isInLoading
end

function AppStartupLoading:__initState()
    self._stateList = {}
    self._currState = 0
end

function AppStartupLoading:__init()
    self.isInLoading = false
    self._loadingProgress = 0
    self._currentMaxProgress = 0
    self:__initState()
    self.__update_handle = nil
end

function AppStartupLoading:__delete()
    self:Shutdown()
    table.clear(self._stateList)
    self._stateList = nil
end

function AppStartupLoading:Start(isReload, showLogo)
    self.isInLoading = true
    self:EnableUpdate()
end

function AppStartupLoading:Shutdown(needDestroyUI)
    self:DisableUpdate()
    self.isInLoading = false
end

function AppStartupLoading:Stop()
    self:SetState(0)
end

function AppStartupLoading:EnableUpdate()
    self:DisableUpdate()
    self.__update_handle = function() self:Update() end
    UpdateManager:GetInstance():AddUpdate(self.__update_handle)
end

function AppStartupLoading:DisableUpdate()
    if self.__update_handle then
        UpdateManager:GetInstance():RemoveUpdate(self.__update_handle)
        self.__update_handle = nil
    end
end

function AppStartupLoading:GetState(state)
    return self._stateList[state]
end

function AppStartupLoading:GetStateName(state)
    return tostring(state)
end

function AppStartupLoading:SetState(newState, ...)
    if self._currState ~= newState then
        local oldState = self._loadingState
        if oldState ~= nil then
            oldState:OnExit()
        end
        self._currState = newState
        self._loadingState = self:GetState(self._currState)
        if self._loadingState ~= nil then
            self._loadingState:OnEnter({...})
        end
    end
end

function AppStartupLoading:Update()
    self:UpdateLoadingProgress()
    if self._loadingState ~= nil then
        self._loadingState:OnUpdate()
    end
end

function AppStartupLoading:UpdateLoadingProgress()
    self._currentMaxProgress = self._loadingProgress
end

return AppStartupLoading
